Gemfile.lock

Updated lockfile from ruby 1.9.3-p547

---

Gemfile
Gemfile.lock
app/controllers/apo_controller.rb
app/controllers/catalog_controller.rb
app/helpers/apo_helper.rb
app/views/apo/register.html.erb
spec/controllers/apo_controller_spec.rb
spec/integration/apo_spec.rb

would appreciate review from @atz (in conjunction with the related dor-services changes)

New license types argo 285

---

.travis.yml

http://docs.travis-ci.com/user/migrating-from-legacy/

Update Travis to run on faster container based infrastructure

---

Gemfile.lock
README.md

Per my recent experience with getting Argo up and going.

Update Readme to reflect setting up Argo in a development environment

---

.hound.yml
.jshintignore
.jshintrc

Per our discussion yesterday.
Uses configs - 
- Default Hound SCSS linting
- Argo defined rubocop
- Airbnb ES5 Javascript jshintrc

Adds Hound CI to our continuous integration build

---

config/environments/development.rb
config/environments/test.rb
config/settings.yml

These are just a few new settings we need to have for the bulk upload stuff to work.

Adding a few settings required for spreadsheet bulk upload.

---

.travis.yml

This should speed up our CI time significantly

run travis against latest Ruby 2.2.2

---

lib/tasks/argo.rake

be explicit why we are using v7.1.0 of hydra-jetty

---

Gemfile.lock
config/environments/dor_development.rb
config/environments/dor_production.rb
config/environments/dor_staging.rb
config/environments/dor_test.rb
config/settings.yml

Making workflow service log be written to log/ directory by default.

---

fedora_conf/data/druids
fedora_conf/data/load_order
fedora_conf/data/tm388wy6148.xml

adds an accessionWF object to the fixture data

---

.travis.yml

this speeds up subsequent Travis CI builds quite a bit. see http://docs.travis-ci.com/user/caching/

use the bundler cache on Travis

---

app/views/catalog/_show_sections/_default_datastreams.html.erb
app/views/items/close_version_ui.html.erb
config/application.rb
config/environments/development.rb
config/environments/production.rb
config/environments/staging.rb
config/environments/test.rb
config/initializers/assets.rb
config/settings.yml
spec/integration/item_displays_spec.rb

Deployed to stage successfully
Closes #152 
Fixes up specs that were succeeding for a reason unknown
Also removes Settings for `APPLICATION` which aren't needed.

Update dev, test, stage, & prod configs

---

README.md

* modify instructions to reflect changes in test env configuration and better understanding of fixture loading for different envs
* minor typographical cleanup while we're here

README updates for fixture loading, tests, and installation

---

app/models/index_queue.rb
spec/models/index_queue_spec.rb

rescue from no method error when parsing an index queue response

---

config/deploy.rb

now with explanation.
(the explanation being that public gets overwritten on deployments, and so the .htaccess file with the workgroup list is lost, and then argo doesn't get the workgroup info it needs about the user to do perm checks)

resurrect the trigger for running 'rake argo:htaccess' on restart

---

Gemfile
Gemfile.lock

Removes some leftover gem cruft from legacy conversions.

Remove cruft

---

app/assets/javascripts/status.js.coffee

Just some old comments that aren't being used.

Remove dead file

---

Gemfile
Gemfile.lock

Tested and deployed to dev successfully
Closes #197 
Closes #182 
Thanks @jkeck for talking through various causes.

update Sprockets to 3.4

---

lib/tasks/argo.rake

run rake ci as RAILS_ENV=test

---

.gitignore
config/newrelic.yml
config/settings.yml

Deployed successfully to dev. Argo now setup in @sul-devops-team New Relic group. PR's also in for configs
Closes #149 Closes #52

fix newrelic to use new config pattern

---

spec/views/_user_util_links.html.erb_spec.rb

with contexts for regular, admin, and manager users.

Add tests for header navigation links

---

config/application.rb
lib/bulk_reindexer.rb
lib/indexer.rb
lib/pid_gatherer.rb
lib/tasks/argo.rake
spec/lib/pid_gatherer_spec.rb

d14098b enables Resource Index to be used for development and test ... Useful for testing our indexing approach
8721a70 Moves pid gathering tasks to its own class. specs mainly test memoization functionality of collection methods

Breakout pid lists

---

app/assets/javascripts/report.js.coffee

Closes #258 
Tried to write a test here, but the old js + coffeescript started to be too difficult.

fixes column resizing issue when selecting columns

---

app/helpers/application_helper.rb
app/models/view_switcher.rb
app/views/catalog/_report_view_toggle.html.erb
app/views/discovery/index.html.erb
app/views/report/index.html.erb
app/views/report/workflow_grid.html.erb
config/locales/en.yml
spec/features/view_switcher_spec.rb
spec/helpers/application_helper_spec.rb
spec/models/view_switcher_spec.rb

Closes #132 
Closes #253 
Various examples in action:

View switcher

---

app/controllers/catalog_controller.rb
app/views/catalog/_show_field_list.html.erb
spec/features/item_view_metadata_spec.rb

Fix for https://github.com/sul-dlss/argo/issues/215

Show md source

---

Gemfile
Gemfile.lock
app/controllers/discovery_controller.rb
app/controllers/items_controller.rb
app/controllers/registration_controller.rb
app/controllers/report_controller.rb
app/helpers/dor_object_helper.rb
app/helpers/registration_helper.rb
app/models/discovery.rb
app/views/items/file.html.erb
app/views/report/index.html.erb
config/routes.rb
spec/controllers/items_controller_spec.rb
spec/helpers/registration_helper_spec.rb
spec/models/user_spec.rb

Want to get this merged before I get too far afield.  Note the massive (and unbreaking!) simplification in routes.

Commit within

---

app/assets/stylesheets/blacklight_hierarchy.scss

Closes #269 
Not a pretty approach, but will will need to suffice until TLC can be thrown on blacklight-hierarchy
Also not testable as far as I can tell.

use scss import rather than require

---

app/views/items/workflow_view.html.erb
spec/views/items/workflow_view.html.erb_spec.rb

fix Nil exception with @object, not @obj

---

Gemfile
Gemfile.lock

unpin addressable from 2.3.5 to allow current webmock

---

app/views/items/file.html.erb

See https://github.com/sul-dlss/argo/pull/264#discussion_r46227831 for context. An oversight on my part when merging this pr.

use link_to rails helper to generate a link

---

app/controllers/catalog_controller.rb

Fixes #292: MODS typeOfResource label on facet

---

app/views/_user_util_links.html.erb
spec/views/_user_util_links.html.erb_spec.rb

condense registration nav links to a dropdown

---

lib/tasks/argo.rake

Fix travis fold command

---

app/controllers/application_controller.rb
app/controllers/auth_controller.rb
config/routes.rb
spec/controllers/catalog_controller_spec.rb

…e should just return a 401
Closes #324

rip out old unused auth stuff, there is no webauth login route, so just return 401

---

app/controllers/items_controller.rb
app/helpers/workflow_helper.rb
spec/controllers/items_controller_spec.rb

This PR addresses #293 and #220, but doesn't fix the issues completely. This fix is for the button action to work correctly.

fix broken change status button in workflow view and some cleanup

---

app/assets/javascripts/modules/date_range_query.js
app/views/catalog/_show_date_choice.html.erb
spec/features/date_range_form_spec.rb

Closes #329 
Also resolves the Travis intermittent failures :pray:

Update date range to use form submit rather than javascript url change

---

spec/features/date_range_form_spec.rb

See data about tries/success recorded here: https://github.com/sul-dlss/argo/pull/352#issue-121720520
This approach is consistent with other's experiences:
- https://github.com/teampoltergeist/poltergeist/issues/530
- http://www.soulcutter.com/blog/2013/click-events-in-poltergeist-vs-capybara-webkit/
- http://stackoverflow.com/questions/20071160/capybara-poltergeist-click-not-working

trigger click rather than click_button

---

app/assets/stylesheets/argo/argo.sass
app/assets/stylesheets/argo/impersonate_groups.scss
app/views/_user_util_links.html.erb
app/views/auth/groups.html.erb
spec/views/_user_util_links.html.erb_spec.rb
spec/views/auth/groups.html.erb_spec.rb

update style to groups page and impersonate navbar

---

app/views/_user_util_links.html.erb

No longer valid references outdated auth pattern.

removes reference outdated auth

---

app/controllers/catalog_controller.rb

Confirmed working on dev. Closes #286
Not really sure how to test this as we don't have enough data to populate any of these facets. Suggestions?

set explicit limit for Argo facet fields

---

config/initializers/squash_exceptions.rb

successfully tested in stage. Should help alleviate some of #333

enable squash revision

---

app/helpers/registration_helper.rb

Fixes #67 . It's a data, not code, change.

add media and software to content type pulldown

---

Gemfile
Gemfile.lock
lib/tasks/rubocop.rake

This PR adds these rake tasks:
```
rake rubocop                                   # Run RuboCop
rake rubocop:auto_correct                      # Auto-correct RuboCop offenses
```

add rubocop rake task

---

README.md

minor cleanup and start Internals section

---

app/assets/javascripts/modules/datastream_edit.js
app/views/catalog/_aspect_partials/_ds.html.erb

Tagging @drh-stanford for this. Not sure where I get to this page in argo, but something along these lines should work.

move inline partial javascript to a plugin based one

---

app/assets/stylesheets/argo/document.sass

Make MODS bulk load button on APO item pages line up a little nicer.

---

app/assets/stylesheets/argo/argo.sass
app/views/report/bulk.html.erb

The commit history on the bulk_ui_layout branch got too messy. This pull request is intended to fix issue #87.

Changing the button layout on the bulk actions page.

---

Gemfile.lock

Addresses several security issues: https://groups.google.com/forum/#!topic/ruby-security-ann/aSbgDiwb24s

update to patched version of Nokogiri

---

app/controllers/items_controller.rb
spec/controllers/items_controller_spec.rb

Tries to address #85 by setting the datastream in the XML editor to the exact content. Unfortunately ActiveFedora filters this content through `Nokogiri::XML.to_s` so the newline entities disappear. However, this is our part of the fix.
This PR also does major cleanup of the `datastream_update` method and specs to handle empty and malformed arguments.

set the XML to be verbatim as posted from the client after validation

---

app/views/auth/groups.html.erb
spec/views/auth/groups.html.erb_spec.rb

adds way to back out of impersonate

---

app/views/report/bulk.html.erb
spec/features/bulk_screen_spec.rb

Re-enabling three of the buttons that were erroneously disabled.

---

Gemfile
Gemfile.lock

Add pry-doc to gemset for dev/test

---

app/controllers/catalog_controller.rb
app/helpers/application_helper.rb
app/views/catalog/_bulk_update_view_button.html.erb
config/locales/en.yml
spec/features/search_results_spec.rb
spec/features/view_switcher_spec.rb
spec/helpers/application_helper_spec.rb

Adding separate Bulk Updates button to the search results page.

---

app/views/bulk_actions/_form.html.erb
spec/views/bulk_actions/_form.html.erb_spec.rb

Have DescriptiveMetadataDownload as default bulk action

---

app/controllers/apo_controller.rb
app/controllers/application_controller.rb
app/controllers/catalog_controller.rb
app/controllers/dor/objects_controller.rb
app/controllers/dor_controller.rb
app/controllers/items_controller.rb
app/controllers/status_controller.rb

New rails, new style.
Closes #156

Filters are actions now

---

.rubocop.yml
app/controllers/apo_controller.rb
app/controllers/catalog_controller.rb
app/controllers/dor_controller.rb
app/controllers/items_controller.rb
app/controllers/registration_controller.rb
app/controllers/report_controller.rb
app/controllers/status_controller.rb
app/controllers/workflow_service_controller.rb
app/views/catalog/_ds.html.erb

revise code to appease the complaints of rubocop and/or hound.ci for
files related to changes in user permissions.
Resolved conflicts in:
app/controllers/items_controller.rb
app/controllers/registration_controller.rb

Appease the gods of code style

---

app/models/user.rb

Trying to pull this out of https://github.com/sul-dlss/argo/pull/532

Revise alias_method to alias for User#is_admin? etc.

---

app/controllers/items_controller.rb

Parsing the date this way gives us the same timezone that dor-services does.
Closes #545

Use Time.zone.parse to parse user supplied date string.

---

spec/controllers/items_controller_spec.rb

Marked a spec as pending, so this should fail to pass unit testing until it is fixed.

item controller - resource spec should be fixed

---

app/views/_user_util_links.html.erb
app/views/items/_embargo_form.html.erb

Simple PR to correct a couple of logical operators.

Fix logical operators for user permission in views

---

app/models/argo/access_controls_enforcement.rb

There is no substantial functional change in this commit, it just adopts better ruby patterns (probably easier to maintain).

revision of  app/models/argo/access_controls_enforcement.rb

---

config/routes.rb

5acb9a3151bafa6948eb84a15dccac0d413b1119

Remove routes for legacy/objects, removed in 5acb9a3

---

lib/tasks/argo.rake

With new implementations and added support on setup, these tasks are no longer used.
@atz what do you say? I'm pretty sure all of this is not used ever now. Also removes a nuke solr task.
Also makes the Blacklight 5.18 upgrade easier :smile_cat:

Remove legacy argo rake tasks.

---

app/helpers/argo_helper.rb
app/views/catalog/_show_external_links.html.erb
spec/views/catalog/_show_external_links.html.erb_spec.rb

Show the document's solr doc link

---

app/assets/stylesheets/blacklight_hierarchy.scss

Add cursor to entire hierarchical facet li to indicate it is clickable.

---

app/models/ability.rb
app/views/catalog/_ds.html.erb
spec/controllers/auth_controller_spec.rb
spec/models/ability_spec.rb

it wasn't really any harder to implement my suggestions for the cancancan branch than it was to make the comments, so i went ahead and created this PR.  hoping these suggestions are uncontroversial, but just in case, i tried to make them as separate commits that can be cherry picked or squashed as desired.
@cbeer @darrenleeweber

cancancan suggestions

---

lib/tasks/rubocop.rake

Remove rubocop rake task

---

lib/solr_pid_dumper.rb

add basic methods for dumping pids from solr by object type and writing them to files

add solr_pid_dumper.rb

---

app/jobs/modsulator_job.rb
spec/jobs/modsulator_job_spec.rb

Fix versioning of new objects to include correct arguments.

---

app/controllers/items_controller.rb
spec/controllers/items_controller_spec.rb

fix ItemsController#purge_object so that it deletes the object from solr reliably and so that it handles object creation and user auth in a way that's more consistent with other methods in the controller/application.
items_controller_spec.rb: fix #purge_object tests.  note that i added a failing test in the first commit, and that if you check out 68dff40 and run `rspec`, you'll get one failure:
```
1) ItemsController#purge_object deletes the object from fedora and solr
Failure/Error: expect(Dor::SearchService.solr).to receive(:delete_by_id).with(@pid)
(#<RSolr::Client:0x007fc46bf31308>).delete_by_id("druid:oo201oo0001")
expected: 1 time with arguments: ("druid:oo201oo0001")
received: 0 times
```
(i actually wrote the test after the fix, but `git rebase -i` was able to make me look a bit …

fix purge command to delete solr doc

---

Gemfile
Gemfile.lock

#784 set Capistrano as version 3.6.0 - so update the Gemfile.

Update Capistrano to version 3.6.

---

app/assets/javascripts/application.js
app/controllers/bulk_actions_controller.rb
app/jobs/release_object_job.rb
app/models/bulk_action.rb
app/views/bulk_actions/_form.html.erb
lib/constants.rb
spec/controllers/bulk_actions_controller_spec.rb
spec/features/bulk_release_object_spec.rb
spec/jobs/release_object_job_spec.rb
spec/models/bulk_action_spec.rb
spec/views/bulk_actions/_form.html.erb_spec.rb

Adds Release object bulk action

---

app/models/release_tag.rb
app/models/release_tags.rb
app/views/catalog/_show_releases.html.erb
fedora_conf/data/qq613vj0238.xml
spec/features/enable_buttons_spec.rb
spec/models/release_tag_spec.rb
spec/models/release_tags_spec.rb
spec/views/catalog/_show_releases.html.erb_spec.rb

Closes #809 
Some of this could also be used in simplifying #811

Update release history

---

app/helpers/registration_helper.rb

remove md source none from form

---

config/routes.rb

(as far as I can tell)
Please enter the commit message for your changes. Lines starting

removes dead routes

---

lib/tasks/argo_testing.rake
spec/controllers/catalog_controller_spec.rb

touchups to @cbeer's dependency upgrade

Update dependencies jm

---

app/models/argo/profile_queries.rb
app/presenters/profile_presenter.rb
app/views/profile/_document_list.html.erb
config/routes.rb
spec/features/profile_spec.rb
spec/models/profile_queries_spec.rb

adds rights & sw information to profile

---

app/assets/stylesheets/argo/profile.scss
app/models/argo/profile_queries.rb
app/presenters/profile_presenter.rb
app/views/profile/_document_list.html.erb
app/views/profile/_table_row_pivot.html.erb
config/routes.rb
spec/features/profile_spec.rb
spec/models/profile_queries_spec.rb

#845 needs to be merged first. Closes #837 , Closes #838 , Closes #835

Number of items & contents & discovery

---

config/routes.rb

Closes #856 
I can't find a place these are used.

remove sms, email, and unused citation routes

---

app/assets/javascripts/modules/index_queue.js
app/controllers/index_queue_controller.rb
app/models/index_queue.rb
app/views/_user_util_links.html.erb
config/routes.rb
spec/controllers/index_queue_controller_spec.rb
spec/features/indexer_backlog_spec.rb
spec/models/index_queue_spec.rb
spec/views/_user_util_links.html.erb_spec.rb

This reverts commit 7db26871c2a45159268d62c5a1cd157ad571fbce.
Fixes https://github.com/sul-dlss/dor_indexing_app/issues/59?

Add index queue mechanism

---

INDEXING.md

This PR deprecates some of the indexing documentation in favor of the Wiki on dor_indexing_app. Argo makes these reindexing calls to dor_indexing_app now. The PidGatherer functionality, however, has not be migrated. It's only needed for a from-scratch reindex, but the documentation/code is valuable to retain here.

deprecate some of the indexing documentation in favor of dor_indexing_app

---

app/views/catalog/_show_date_choice.html.erb
spec/features/date_range_form_spec.rb

Include existing query parameters in the date range form; fixes #738

---

app/models/report.rb
spec/models/report_spec.rb

Explicitly use the CatalogController's blacklight configuration for generating reports

---

app/controllers/registration_controller.rb
spec/features/item_registration_spec.rb

taking a shot at addressing https://github.com/sul-dlss/argo/pull/938/files#r101326897
addresses #940 (not sure if it's comprehensive enough to close it)

feature tests for Add goobi workflows to registration & basic item registration in general

---

app/helpers/registration_helper.rb

update content types

---

app/assets/javascripts/registration/register.js.erb
app/assets/stylesheets/argo/item_registration.scss

addresses https://github.com/sul-dlss/argo/pull/938#discussion_r102845517

hide #external_workflow_dropdown elt by default using css instead of jquery

---

app/assets/javascripts/registration/grid.js.erb
app/assets/javascripts/registration/register.js.erb
app/assets/stylesheets/argo/item_registration.scss
app/controllers/registration_controller.rb
app/helpers/registration_helper.rb
app/views/items/register.html.erb
app/views/profile/_document_list.html.erb
fedora_conf/data/ww057vk7675.xml
lib/constants.rb
spec/controllers/registration_controller_spec.rb
spec/features/item_registration_spec.rb

fixes #937 
this takes @peetucket's work from PR #938 and:
* rebases on current master
* keeps the tests i added on my PR to that PR
* does a minor fixup on peter's commit w/ @cbeer's suggestion from https://github.com/sul-dlss/argo/pull/938#discussion_r102845517
* fixes the registration test i added, since #944 broke it.

Add goobi workflows to item registration [rebase and fixup from @peetucket's branch]

---

Gemfile
Gemfile.lock
app/controllers/items_controller.rb
app/helpers/argo_helper.rb
app/views/items/_catkey_ui.html.erb
app/views/items/catkey_ui.html.erb
app/views/items/catkey_ui.js.erb
config/routes.rb
spec/controllers/items_controller_spec.rb
spec/features/collection_manage_release_spec.rb
spec/features/enable_buttons_spec.rb
spec/features/item_catkey_change_spec.rb
spec/features/item_manage_release_spec.rb
spec/helpers/argo_helper_spec.rb

fixes #947 
also refactor argo_helper to use named routes instead of url_for throughout

add a ui button to edit the catkey for records

---

README.md

Dor Indexing App is now required in development mode.

Add instructions for running Dor Indexing App.

---

app/controllers/registration_controller.rb
spec/controllers/registration_controller_spec.rb

also, fix tests accordingly.
previously, if an APO referenced a collection druid in `administrativeMetadata`'s `registration` section, but the collection didn't exist, the collection druid would still be available when registering an item under the APO, listed as "Unknown Collection".  @blalbrit agrees that this is not actually a desirable feature, so this PR gets rid of it.
turns out we have some bad data like this in stage, and in the fixture data for local development work.  but it appears we don't have any data like this in production, thankfully.  i used the following code to check for registration collection druids listed on APOs, where the collection druid doesn't actually exist in the fedora repository:
```ruby
solr_resp = Dor::SearchService.query …
```

prevent RegistrationController#collection_list from returning entries for collections that don't exist in fedora

---

app/views/items/_close_version_ui.html.erb

fixes leading and trailing white spaces. 
Fixes #792

fixes extraneous line breaks in close object dialogue

---

app/assets/javascripts/registration/grid.js.erb
app/assets/javascripts/registration/register.js.erb
app/helpers/registration_helper.rb
app/views/items/register.html.erb
lib/constants.rb
spec/features/item_registration_spec.rb

remove goobi workflow drop-down menu and auto-tagging

---

app/models/user.rb
spec/models/user_spec.rb

Update user test

---

config/deploy.rb

Otherwise there may be a few seconds of the server being up without a
.htaccess

Generate the .htaccess before restarting

---

spec/controllers/apo_controller_spec.rb
spec/factories/user.rb

Stub the ability calls rather than the user calls.

Refactor ApoController spec

---

.travis.yml
Gemfile
Gemfile.lock
README.md
spec/features/bulk_screen_spec.rb
spec/features/date_range_form_spec.rb
spec/spec_helper.rb

Phantomjs is no longer maintained

Switch from Phantomjs to chrome headless for js testing

---

app/controllers/apo_controller.rb

Add some documentation
Make some methods private
Use more ideomatic ruby method names

Refactor APO controller

---

Gemfile.lock
config/initializers/dor_config.rb
config/settings.yml

While this change should have minimal impact, I'm testing on stage before removing [WIP].

Update dor-services to 5.30.0

---

.solr_wrapper.yml
Gemfile
Gemfile.lock
README.md
config/blacklight.yml
config/settings/test.yml
lib/tasks/argo_testing.rake
solr_conf/conf/schema.xml
solr_conf/conf/solrconfig.xml

Do we need to add directions for how to create a solr collection for development, or is the single collection (how we do it in Blacklight) a paradigm that's going to work?

Move to testing on solr 6 and use solr_wrapper for Solr

---

app/jobs/release_object_job.rb
spec/jobs/release_object_job_spec.rb

Remove hardcoding of dor/ path segment

---

.solr_wrapper.yml
config/initializers/okcomputer.rb
solr_conf/conf/schema.xml
solr_conf/conf/solrconfig.xml

In anticipation of an sul-solr impending solr upgrade.

 Update .solr_wrapper.yml to use 7.4.0

---

app/jobs/set_governing_apo_job.rb
spec/jobs/set_governing_apo_job_spec.rb

APO bulk update: manage versions

---

Gemfile
Gemfile.lock

Remove deps that were just provided as a bundler workaround

---

app/search_builders/argo/profile_queries.rb
spec/search_builders/argo/profile_queries_spec.rb

Corrects adding additional facet fields for profile queries.

---

config/initializers/dor.rb
spec/forms/apo_form_spec.rb

This reverts commit b48e9f3660dc3d6a282b4a10ee13a48f71da1c33.

Revert "monkey patch for dor-services until 4.0.1 comes out"

---

app/assets/stylesheets/argo/document.sass
app/views/catalog/_contents_default.html.erb
app/views/catalog/_show_sections/_child_resource.html.erb
app/views/catalog/_show_sections/_file.html.erb
app/views/catalog/_show_sections/_resource.html.erb
spec/views/catalog/_contents_default.html.erb_spec.rb

Make use of the built in `render collection: ...`.
Add a test

Extract the resource list item into its own partial

---

app/controllers/catalog_controller.rb
app/helpers/value_helper.rb
spec/helpers/value_helper_spec.rb

Adds links for objects with collections and APOs to object detail page.

---

app/controllers/files_controller.rb
spec/controllers/files_controller_spec.rb

The expected parameter is id, not file

---

app/controllers/files_controller.rb
app/helpers/value_helper.rb
app/views/files/index.html.erb
spec/controllers/files_controller_spec.rb
spec/features/item_view_metadata_spec.rb
spec/routing/files_spec.rb
spec/views/catalog/_show_sections/_file.html.erb_spec.rb
spec/views/files/index.html.erb_spec.rb

Use correct route helper

---

app/assets/javascripts/argo.js
app/views/files/index.html.erb
spec/views/files/index.html.erb_spec.rb

Fix the styling on the modals

---

app/assets/javascripts/argo.js
app/views/catalog/facet.html.erb
spec/features/filter_facet_spec.rb

Added filtering of more facets.

---

app/helpers/value_helper.rb
spec/helpers/value_helper_spec.rb

Changes fields used to look for associated items.

---

app/services/dor_services/client.rb
spec/services/dor_services/client_spec.rb

When registering a PID, set the Accept:json header

---

.travis.yml
config/settings.yml
docker-compose.yml
spec/integration/apo_spec.rb
spec/jobs/release_object_job_spec.rb
spec/services/dor_services/client_spec.rb

And remove JDK from Travis since it is no longer needed (was for spinning up Fedora/Solr before switching to Docker)

Use dor-services-app container & docker-compose for testing 

---

app/helpers/registration_helper.rb
lib/constants.rb
spec/lib/constants_spec.rb

remove manuscript from content types

---

app/controllers/registration_controller.rb
spec/controllers/registration_controller_spec.rb

always put default workflow first in list regardless of APO

---

Gemfile
Gemfile.lock
config/initializers/dor_config.rb
config/initializers/dor_services_client.rb
config/initializers/okcomputer.rb
config/settings.yml
docker-compose.yml

Refs sul-dlss/dor-services-client#8

Use dor-services-app credentials independent of URL

---

app/assets/javascripts/argo.js
app/controllers/collections_controller.rb
app/views/collections/new.html.erb
config/routes.rb
spec/controllers/collections_controller_spec.rb
spec/features/create_collection_spec.rb

Warn if collection with duplicate title or catkey is being created.

---

app/controllers/items_controller.rb
spec/controllers/items_controller_spec.rb

rather than the deprecated create_workflow method

Use the CreateWorkflowService 

---

app/views/_user_util_links.html.erb
spec/views/_user_util_links.html.erb_spec.rb

add bulk actions/updates to top menu nav bar

---

.rubocop_todo.yml
Gemfile
Gemfile.lock
app/controllers/dor/objects_controller.rb
app/controllers/files_controller.rb
app/controllers/items_controller.rb
app/forms/apo_form.rb
app/forms/collection_form.rb
app/helpers/dor_object_helper.rb
app/jobs/modsulator_job.rb
app/jobs/release_object_job.rb
app/jobs/set_governing_apo_job.rb
spec/controllers/collections_controller_spec.rb
spec/controllers/dor/objects_controller_spec.rb
spec/controllers/files_controller_spec.rb
spec/controllers/items_controller_spec.rb
spec/features/item_view_metadata_spec.rb
spec/forms/apo_form_spec.rb
spec/forms/collection_form_spec.rb
spec/jobs/modsulator_job_spec.rb
spec/jobs/set_governing_apo_job_spec.rb

Refs sul-dlss/dor-services-client#38

Upgrade to dor-services-client 1.0.0

---

app/assets/javascripts/registration/grid.js.erb
app/views/items/register.html.erb

Increases the number of tag fields on registration page.

---

config/environments/test.rb

to avoid a rails deprecation error on test

Add sqlite3.represent_boolean_as_integer = true

---

app/controllers/workflows_controller.rb
app/presenters/workflow_presenter.rb
app/presenters/workflow_process_presenter.rb
app/views/catalog/_history_default.html.erb
app/views/workflows/_show.html.erb
app/views/workflows/show.html.erb
spec/controllers/workflows_controller_spec.rb
spec/presenters/workflow_presenter_spec.rb
spec/presenters/workflow_process_presenter_spec.rb
spec/views/workflows/_show.html.erb_spec.rb

Also:
* Extract a presenter for the workflow processes

Only display the workflow status from the most recent version

---

app/controllers/workflows_controller.rb
app/helpers/workflow_helper.rb
app/presenters/workflow_presenter.rb
app/presenters/workflow_process_presenter.rb
app/views/workflows/_show.html.erb
spec/controllers/workflows_controller_spec.rb
spec/presenters/workflow_presenter_spec.rb
spec/presenters/workflow_process_presenter_spec.rb
spec/views/workflows/_show.html.erb_spec.rb

It previously had two bugs and did not have test coverage.
* URL was wrong
* options passed to render_workflow_process_reset were of the wrong type

Move render_workflow_process_reset into the presenter

---

Gemfile
Gemfile.lock
app/controllers/workflows_controller.rb
spec/controllers/workflows_controller_spec.rb

Also changed the response for trying to activate an already activated workflow
to a 403 instead of a 500

Avoid deprecated WorkflowDs#[]

---

Gemfile.lock
app/presenters/workflow_process_presenter.rb

Add YARD documentation to WorkflowProcessPresenter

Update the dor-workflow-service

---

Gemfile
Gemfile.lock

Rails 5.2.2 is incompatible with sqlite 1.4
Refs https://github.com/rails/rails/issues/35153

Pin sqlite

---

lib/constants.rb
spec/lib/constants_spec.rb

part of https://jirasul.stanford.edu/jira/browse/DEVQUEUE-229

add 3d to content and resource type for use in bulk editing

---

app/controllers/workflows_controller.rb
spec/controllers/workflows_controller_spec.rb

Pass the proper parameters to WorkflowXmlPresenter

---

app/controllers/auth_controller.rb
app/controllers/workflows_controller.rb
config/routes.rb

Using the `traceroute` gem to audit the routes

Remove unused routes

---

app/controllers/items_controller.rb
spec/controllers/items_controller_spec.rb
spec/integration/item_displays_spec.rb

Get the descriptive metadata from dor-services-app

---

app/models/track_sheet.rb
spec/models/track_sheet_spec.rb

Switch call from load_instance to find

---

app/jobs/modsulator_job.rb
spec/jobs/modsulator_job_spec.rb

Fixes current mods upload outage.

Grab the status code from status info

---

Gemfile.lock
app/controllers/workflows_controller.rb
spec/controllers/workflows_controller_spec.rb
spec/features/workflow_service_creation_spec.rb

Avoid deprecated Dor::CreateWorkflowService

Use the workflow service client for starting workflows

---

app/jobs/release_object_job.rb
spec/jobs/release_object_job_spec.rb

The dor-services-app endpoint is deprecated

Use the workflow server to start workflow

---

app/jobs/manage_catkey_job.rb
spec/features/item_view_metadata_spec.rb
spec/jobs/manage_catkey_job_spec.rb

replace removed method in dor-services

---

.rubocop_todo.yml
app/models/application_record.rb
app/models/bulk_action.rb
app/models/user.rb

This is the expected behavior in Rails 5 and is required to upgrade to Blacklight 7

Use ApplicationRecord

---

Gemfile.lock
README.md
bin/virtual-merge

This will allow us to deprecate dor-utils and just maintain this script in Argo
Ref sul-dlss/dor-utils#66
Ref #1323
Ref #1278

Merge virtual-merge in from dor-utils

---

.rubocop.yml
.travis.yml
app/models/application_record.rb
bin/virtual-merge
spec/views/catalog/_show_sidebar.html.erb_spec.rb

These snuck into master as rubocop isn't running on travis. See #1460

Rubocop fixes

---

Gemfile
Gemfile.lock
app/controllers/items_controller.rb
app/jobs/generic_job.rb
app/jobs/manage_catkey_job.rb
app/jobs/modsulator_job.rb
spec/controllers/items_controller_spec.rb
spec/jobs/generic_job_spec.rb
spec/jobs/manage_catkey_job_spec.rb
spec/jobs/modsulator_job_spec.rb

And correct `openeable` typo now that DSC uses `openable` instead as of 2.0.0.
Refs sul-dlss/dor-services-app#322

Bump to dor-services-client 2.0.0 and dor-services 7.2.4

---

app/jobs/generic_job.rb
app/jobs/manage_catkey_job.rb
app/jobs/release_object_job.rb
app/jobs/remote_indexing_job.rb
app/jobs/set_governing_apo_job.rb

Since GenericJob depends on #groups, it should define it

Move definition of #groups to GenericJob

---

app/assets/javascripts/bulk.js
app/controllers/bulk_actions_controller.rb
app/controllers/items_controller.rb
app/jobs/manage_catkey_job.rb
app/jobs/prepare_job.rb
app/models/bulk_action.rb
app/services/bulk_action_persister.rb
app/views/bulk_actions/_form.html.erb
app/views/bulk_actions/forms/_prepare_form.html.erb
app/views/report/bulk.html.erb
config/routes.rb
spec/features/bulk_screen_spec.rb
spec/jobs/generic_job_spec.rb
spec/jobs/prepare_job_spec.rb
spec/services/bulk_action_persister_spec.rb

~~DO NOT MERGE without approval from Andrew~~   approved!
Ref #1465

Move prepare objects to a background job

---

Gemfile
Gemfile.lock
app/jobs/virtual_merge_job.rb
bin/virtual-merge
spec/jobs/virtual_merge_job_spec.rb

Add virtual merge job

---

app/assets/javascripts/bulk.js
app/controllers/items_controller.rb
app/jobs/close_version_job.rb
app/jobs/prepare_job.rb
app/models/bulk_action.rb
app/views/bulk_actions/_form.html.erb
app/views/report/bulk.html.erb
spec/features/bulk_screen_spec.rb
spec/jobs/close_version_job_spec.rb

Convert close to a async background job

---

app/models/concerns/permitted_queries.rb

As there are now > 1000. refs #1428.

Increased the number of collections returned in query

---

app/views/bulk_actions/forms/_prepare_form.html.erb

DO NOT MERGE without PO approval.
closes #1514

[Needs PO approval] Tweak to Prepare objects bulk action form.

---

app/views/bulk_actions/_form.html.erb

[Needs PO approval] Changed label for description field on new bulk action form.

---

.travis.yml
Gemfile.lock

Revert "bundle update --bundler"

---

app/assets/javascripts/application.js
app/assets/javascripts/jquery.defaultText.js
app/assets/javascripts/registration/register.js
spec/features/bulk_jobs_spec.rb

Revert "Use Jquery 3 to avoid CVE-2015-9251"

---

app/services/apply_mods_metadata.rb

fixes #1540
Could @jcoyne and/or @mjgiarlo please review?

fix modsulator bulk upload jobs

---

app/assets/javascripts/application.js
app/assets/javascripts/jquery.defaultText.js
app/assets/javascripts/jquery.persistentModal.js
app/assets/javascripts/registration/register.js
spec/features/bulk_jobs_spec.rb

The problem we saw earlier where modals were broken has been fixed.

Upgrade jquery3

---

app/assets/javascripts/bulk.js
app/views/report/workflow_grid.html.erb

change deprecated jquery ajax method callbacks

---

app/assets/javascripts/registration/grid.js
app/helpers/registration_helper.rb
app/views/items/register.html.erb

Hide Metadata Source drop-down menu in item registration; default to "Auto"

---

.jshintignore
app/assets/javascripts/application.js
app/assets/javascripts/argo.js
app/assets/javascripts/bulk.js
app/assets/javascripts/controllers/bulk_actions.es6
app/assets/javascripts/stimulus.js
app/views/bulk_actions/new.html.erb
app/views/layouts/application.html.erb
spec/features/bulk_desc_metadata_download_spec.rb
spec/features/bulk_reindex_spec.rb
spec/features/bulk_release_object_spec.rb
spec/features/bulk_set_governing_apo_spec.rb
spec/views/bulk_actions/new.html.erb_spec.rb

New bulk action should use a pulldown

---

spec/controllers/files_controller_spec.rb
spec/features/item_view_metadata_spec.rb

Added additional assurances this is working via the controller spec

Remove flappy spec

---

.jshintignore
app/assets/javascripts/application.js
app/assets/javascripts/argo.js
app/assets/javascripts/bulk.js
app/assets/javascripts/controllers/bulk_actions.es6
app/assets/javascripts/stimulus.js
app/views/bulk_actions/new.html.erb
app/views/layouts/application.html.erb
spec/features/bulk_desc_metadata_download_spec.rb
spec/features/bulk_reindex_spec.rb
spec/features/bulk_release_object_spec.rb
spec/features/bulk_set_governing_apo_spec.rb
spec/views/bulk_actions/new.html.erb_spec.rb

This reverts commit 48c9fee3eeaccdff0c7ee1edc693b8c021706615 which itself was a revert.

[Needs PO approval] New bulk action should use a pulldown -- redo

---

app/views/bulk_actions/forms/_set_governing_apo_form.html.erb

Give new governing apo dropdown proper bootstrap style

---

spec/features/bulk_jobs_spec.rb

This will make it easier to switch to webpack

Test without jquery

---

.travis.yml
Gemfile.lock

Tested this on staging environment and was successful.
Before deploy to prod:
1. Update rubygems `gem update --system` on all nodes
1. `gem install bundler`

Update the bundler to bundler 2

---

config/initializers/dor_config.rb
config/initializers/okcomputer.rb
config/settings.yml
docker-compose.yml

Catalog service is now within dor-services-app

Remove catalog url variable

---

.travis.yml

Upgrade the TravisCI distro to bionic

---

spec/features/item_view_metadata_spec.rb

Add integration test for view a datastream

---

spec/features/bulk_screen_spec.rb

Add an integration test for synchronous bulk actions

---

app/controllers/workflows_controller.rb
app/presenters/workflow_process_presenter.rb
app/views/workflows/_show.html.erb
spec/controllers/workflows_controller_spec.rb
spec/models/ability_spec.rb
spec/presenters/workflow_process_presenter_spec.rb
spec/views/workflows/_show.html.erb_spec.rb

***DO NOT MERGE*** without approval from Product Owner. 
Ref #1346
Ref #1516

[Needs PO approval] Add dropdown to set a status for an errored workflow item (design needed - blocker)

---

config/initializers/dor_services_client.rb
config/settings.yml
docker-compose.yml

When this is gone dor-services-client will revert to the default 'Authorization'

Remove token header variable

---

Dockerfile
README.md

This is what @peetucket was running into, so we thought it worth documenting.

Update base Ruby image and add a note to the README about stale images

---

app/services/apply_mods_metadata.rb

found these while hunting for something else.

fix a few typos

---

package.json

Add a license to package.json

---

config/settings.yml

~~shared_configs PRs to follow~~

remove unused DPG_URL setting

---

app/jobs/checksum_report_job.rb
spec/jobs/checksum_report_job_spec.rb

fixes #1637 
BLOCKED BY sul-dlss/preservation_catalog#1214, **which needs to be merged and deployed first**

[BLOCKED] switch checksum api call to a post

---

.github/pull_request_template.md

From the basic template in place in `dor-services-app`...

Per discussion, add basic PR template

---

spec/controllers/profile_controller_spec.rb
spec/features/indexer_backlog_spec.rb
spec/features/release_history_spec.rb
spec/helpers/dor_object_helper_spec.rb
spec/helpers/items_helper_spec.rb
spec/helpers/profile_helper_spec.rb
spec/helpers/registration_helper_spec.rb
spec/helpers/spec_helper_spec.rb
spec/helpers/workflow_helper_spec.rb
spec/models/ability_spec.rb
spec/models/concerns/apo_concern_spec.rb
spec/models/concerns/catkey_concern_spec.rb
spec/models/concerns/collection_concern_spec.rb
spec/models/concerns/druid_concern_spec.rb
spec/models/concerns/title_concern_spec.rb
spec/models/index_queue_spec.rb
spec/models/release_tag_spec.rb
spec/models/release_tags_spec.rb
spec/search_builders/argo/date_field_queries_spec.rb
spec/search_builders/argo/profile_queries_spec.rb
spec/spec_helper.rb
spec/views/_user_util_links.html.erb_spec.rb
spec/views/catalog/_show_sidebar.html.erb_spec.rb
spec/views/items/_button_link_list.html.erb_spec.rb

Disable all monkeypatching done by rspec

---

README.md

having to debug and found this useful
that is what this is

add some info on debugging when running in docker container

---

README.md

more useful information when debugging activejobs
yes

more debug info added to the readme

---

app/models/report.rb
app/search_builders/report_search_builder.rb

to speed up reports (display and downloads)
see #1671

create a new search builder for reports that leaves off faceting

---

app/search_builders/report_search_builder.rb
spec/controllers/report_controller_spec.rb

allow custom date queries to work in reports

---

app/controllers/content_types_controller.rb
app/controllers/items_controller.rb
app/jobs/manage_catkey_job.rb
app/jobs/set_governing_apo_job.rb
app/presenters/buttons_presenter.rb
app/services/state_service.rb
bin/virtual-merge
spec/controllers/content_types_controller_spec.rb
spec/controllers/items_controller_spec.rb
spec/features/collection_manage_release_spec.rb
spec/features/enable_buttons_spec.rb
spec/features/item_catkey_change_spec.rb
spec/features/item_manage_release_spec.rb
spec/features/item_source_id_change_spec.rb
spec/features/set_governing_apo_spec.rb
spec/jobs/manage_catkey_job_spec.rb
spec/jobs/set_governing_apo_job_spec.rb
spec/presenters/buttons_presenter_spec.rb
spec/services/state_service_spec.rb

This service is only used in Argo. Companion PR to sul-dlss/dor-services#669
Not needed.

Port StateService from dor-services

---

docker-compose.yml

dor-services-app is not yet compatible with postgres 12
N/a

Use postgres 11

---

app/helpers/registration_helper.rb
app/javascript/registration/register.js
app/views/items/register.html.erb

This code is not used since https://github.com/sul-dlss/argo/commit/4cc750c96481192a6b83be370c7fc547ef01a165
n/a

Remove metadata source handling from javascript

---

Gemfile
Gemfile.lock
app/controllers/workflows_controller.rb
app/views/catalog/_show_workflows.html.erb
app/views/workflows/_show.html.erb
spec/controllers/workflows_controller_spec.rb

Upgrade dor-workflow-client to 3.11.0

---

Gemfile.lock

The previous branch had an error when requesting workflow.
n/a

Upgrade dor-workflow-client to a working version

---

app/services/virtual_objects_creator.rb

To reduce network traffic to dor-services-app
n/a

virtual object creator: increase poll interval from 3 to 10 seconds

---

yarn.lock

To keep dependencies up to date
n/a

upgrade js dependencies

---

app/helpers/dor_object_helper.rb
app/views/catalog/_history_default.html.erb
app/views/catalog/_show_workflows.html.erb

So the code is easier to understand.
n/a

Simplify code by not passing variables that aren't used

---

Gemfile
Gemfile.lock
app/components/workflow_process_row.rb
config/application.rb

We were using an old version of the library.
n/a

Upgrade actionview-component

---

Gemfile.lock
spec/features/add_workflow_to_item_spec.rb
spec/features/apo_spec.rb
spec/features/item_catkey_change_spec.rb
spec/features/item_source_id_change_spec.rb

Update dor-services to get new workflow indexing

---

app/controllers/files_controller.rb
app/jobs/checksum_report_job.rb
spec/controllers/files_controller_spec.rb
spec/jobs/checksum_report_job_spec.rb

Fixes #1756
To gain additional visibility into preservation-client errors, we now log them and notify Honeybadger about them.
no

Trap unexpected preservation client errors

---

Gemfile
Gemfile.lock

To be up to date with the latest dor-services-client
n/a

Upgrade to the latest version of dor-services-client

---

.rubocop.yml
app/jobs/create_virtual_objects_job.rb

Note: this branch should be tested on stage first
another attempt to address #1728

an attempt to avoid the problem of mysql going away

---

app/jobs/create_virtual_objects_job.rb

add comment about sql reconnect

---

app/forms/apo_form.rb

Do the writing first, then run the robots
Fixes #1809 
n/a

Avoid a race condition around accession of APOs

---

app/views/catalog/_datastreams_default.html.erb
app/views/items/_button_link_list.html.erb
app/views/workflows/_show.html.erb

Use the new way to initialize view components

---

app/controllers/items_controller.rb
spec/controllers/items_controller_spec.rb

Fix read rights method

---

spec/controllers/items_controller_spec.rb

Ivars are discouraged in rspec tests.
n/a

Remove ivar from test

---

app/controllers/items_controller.rb

Explicitly saving in each method is clearer than saving in a hook
n/a
no

Remove after_action hook

---

.travis.yml
app/assets/stylesheets/argo/document.sass
app/controllers/catalog_controller.rb
app/services/techmd_service.rb
app/views/catalog/_techmd_default.html.erb
config/settings.yml
docker-compose.yml
spec/services/techmd_service_spec.rb

closes #1824
To show technical metadata from the technical-metadata-service.
No.

Show techmd

---

config/deploy/prod.rb

Reverts #1841 - apologies for the confusion and timing.

Take -a and -b out of the deploy pool

---

Gemfile
Gemfile.lock
app/controllers/tokens_controller.rb
app/javascript/argo.js
app/javascript/controllers/tokens.js
app/views/tokens/index.html.erb
config/routes.rb
config/settings.yml
spec/features/token_spec.rb

This allows the user to make deposits using the SDR-API
n/a
yes

Add a way to get SDR API tokens

---

app/services/ocr_exporter.rb
bin/export-ocr
config/initializers/inflections.rb
spec/services/ocr_exporter_spec.rb

Fixes https://github.com/sul-dlss/google-books/issues/146
n/a
no

Add a script to export OCR files for a list of barcodes

---

Gemfile
Gemfile.lock

actionview-component changed it's name to view_component
n/a
no

Switch to view-component

---

Gemfile
Gemfile.lock
app/components/application_component.rb
app/components/throbber.rb

Upgrade to view_component 2.0

---

Gemfile
Gemfile.lock
spec/controllers/catalog_controller_spec.rb
spec/features/add_workflow_to_item_spec.rb
spec/features/apo_spec.rb
spec/features/bulk_screen_spec.rb
spec/features/collection_manage_release_spec.rb
spec/features/consistent_titles_spec.rb
spec/features/enable_buttons_spec.rb
spec/features/item_catkey_change_spec.rb
spec/features/item_manage_release_spec.rb
spec/features/item_source_id_change_spec.rb
spec/features/item_view_metadata_spec.rb
spec/features/release_history_spec.rb
spec/features/set_governing_apo_spec.rb
spec/services/ocr_exporter_spec.rb

Upgrade to latest sdr-api and cocina-models

---

app/views/catalog/_report_view_toggle.html.erb

Missing quotes is not valid html
no.
no

Add missing quotes

---

app/views/versions/_close_ui.html.erb
app/views/versions/_open_ui.html.erb

This fixes invalid HTML (missing quotes)
no
no

Use rails form helper

---

app/controllers/items_controller.rb
spec/controllers/items_controller_spec.rb

Fixes #1884
To fix a bug.
No.
Yes, but not in a way that should require extra testing.

Reindex tags immediately after bulk update

---

app/components/workflow_grid_component.html.erb
app/components/workflow_grid_component.rb
app/helpers/workflow_helper.rb
app/views/report/_workflow_grid.html.erb

Refactor away from helpers and toward components
no
no

Add WorkflowGridComponent

---

README.md

Testing automated merge script
no

[HOLD] Justin test

---

package.json
yarn.lock

Upgrade javascript deps

---

app/forms/apo_form.rb
app/views/apo/_form.html.erb
spec/forms/apo_form_spec.rb

set default agreement on edit apo page

---

app/controllers/apo_controller.rb
app/controllers/collections_controller.rb
app/forms/apo_form.rb
app/forms/base_form.rb
app/forms/collection_form.rb
spec/forms/apo_form_spec.rb
spec/forms/collection_form_spec.rb

This is possible because https://github.com/sul-dlss/dor-services/pull/360 has been released
no
no

Simplify forms

---

app/controllers/catalog_controller.rb

Add access rights display field

---

Gemfile
Gemfile.lock
app/controllers/dor/objects_controller.rb
spec/controllers/dor/objects_controller_spec.rb

DSC 6.0 removes legacy registration.
no
Yes.

Do registration with the cocina endpoint

---

Gemfile
Gemfile.lock

Update to latest dor-services-client and sdr-client.

Updated to dor-services-client 6.0 and sdr-client 0.24.0

---

app/controllers/dor/objects_controller.rb
spec/controllers/dor/objects_controller_spec.rb

#1111  Why was this change made?
Handle Document type, and reading direction.
no
yes

Test what was sent to registration

---

app/models/report.rb
app/views/report/_column_selector.html.erb
app/views/report/index.html.erb
spec/models/report_spec.rb

Adding things to the blacklight config that have nothing to do with blacklight is confusing.
no
no

Extract constants from blacklight_config

---

app/javascript/style/argo.scss
app/views/report/bulk.html.erb
spec/features/bulk_screen_spec.rb
spec/features/report_view_spec.rb

This is an accessibility improvement
no
no

Make bulk_buttons buttons

---

.rubocop.yml
.rubocop_todo.yml
.travis.yml
Dockerfile
Gemfile.lock
app/controllers/dor/objects_controller.rb
app/controllers/registration_controller.rb
app/models/report.rb
app/views/items/register.html.erb
lib/constants.rb
spec/controllers/dor/objects_controller_spec.rb
spec/controllers/registration_controller_spec.rb
spec/controllers/report_controller_spec.rb
spec/features/consistent_titles_spec.rb
spec/features/item_view_metadata_spec.rb
spec/features/profile_spec.rb
spec/features/report_view_spec.rb
spec/features/search_results_spec.rb
spec/models/report_spec.rb

to roll back blacklight7 changes in master branch and in production 
nope
registered an object on stage.  JLitt is running integration test suite.

No blacklight7

---

Gemfile
Gemfile.lock
bin/webpack
bin/webpack-dev-server
package.json
yarn.lock

Keep dependencies up to date
no
no

Upgrade to webpacker 5

---

app/views/catalog/show.html.erb
spec/features/item_view_metadata_spec.rb

Properly escape ampersand in titles

---

config/settings.yml
spec/features/item_view_metadata_spec.rb
spec/support/mock_index_depth.rb

Replace example.com as a host

---

app/components/blacklight_modal_component.html.erb
app/components/blacklight_modal_component.rb
app/views/bulk_jobs/_bulk_index_table.html.erb
app/views/catalog/dc.html.erb
app/views/catalog/ds.html.erb
app/views/catalog/facet.html.erb
app/views/catalog/manage_release.html.erb
app/views/content_types/show.html.erb
app/views/files/index.html.erb
app/views/items/catkey_ui.html.erb
app/views/items/collection_ui.html.erb
app/views/items/embargo_form.html.erb
app/views/items/file.html.erb
app/views/items/purl_preview.html.erb
app/views/items/rights.html.erb
app/views/items/set_governing_apo_ui.html.erb
app/views/items/source_id_ui.html.erb
app/views/items/tags_ui.html.erb
app/views/versions/close_ui.html.erb
app/views/versions/open_ui.html.erb
app/views/workflows/history.html.erb
app/views/workflows/new.html.erb
app/views/workflows/show.html.erb
spec/components/blacklight_modal_component_spec.rb
spec/views/items/embargo_form.html.erb_spec.rb

This keeps us from having to repeat (and change) markup for the Blacklight modal.
no
no

Extract the BlacklightModalComponent

---

spec/controllers/registration_controller_spec.rb
spec/features/bulk_desc_metadata_download_spec.rb

Remove empty tests

---

yarn.lock

Upgrade jquery to 3.5.1

---

app/models/report.rb

Use the druid method on SolrDocument

---

app/controllers/bulk_actions_controller.rb

Change copy around bulk action destroy

---

app/controllers/dor/objects_controller.rb
app/javascript/registration/register.js
app/views/items/register.html.erb

Allow multiple project tags

---

app/components/external_links_component.rb
spec/components/external_links_component_spec.rb

Link to PURL without the namespace on the pid

---

app/controllers/items_controller.rb
app/javascript/packs/bulk.js

Correctly send parameters to set rights from bulk update

---

app/javascript/packs/bulk.js
app/jobs/republish_job.rb
app/models/bulk_action.rb
app/views/bulk_actions/new.html.erb
app/views/report/bulk.html.erb
spec/features/bulk_screen_spec.rb
spec/jobs/republish_job_spec.rb

Port "Republish" bulk update to bulk action

---

app/controllers/items_controller.rb
app/javascript/packs/bulk.js
app/jobs/purge_job.rb
app/models/bulk_action.rb
app/views/bulk_actions/new.html.erb
app/views/report/bulk.html.erb
spec/controllers/items_controller_spec.rb
spec/features/bulk_screen_spec.rb
spec/jobs/purge_job_spec.rb

Port "Purge" bulk update to bulk actions

---

app/presenters/milestones_presenter.rb
app/views/catalog/_show_milestones.html.erb
spec/presenters/milestones_presenter_spec.rb

closes #210
To fix display of milestones.
No
No

Fixes display of milestones.

---

app/helpers/application_helper.rb

Remove unused method

---

app/controllers/items_controller.rb
app/helpers/items_helper.rb
config/routes.rb
spec/controllers/items_controller_spec.rb

This code is no longer used
no
no

Remove dead code

---

app/javascript/packs/bulk.js
app/views/report/bulk.html.erb

This removes unnecessary code.
no
no

Remove some remaining parts of purge and republish bulk update

---

Gemfile
Gemfile.lock

Upgrade rack to fix CVE-2020-8161

---

lib/constants.rb

(re) fixes #1906 
previously done in #1912, but that PR was closed without merging
tested in -stage on 5/15/2020
none

add object to resource type list

---

app/views/uploads/new.html.erb

All input elements should have labels for accessability.
none

Add a missing label tag for a file upload field

---

app/controllers/files_controller.rb
app/views/files/index.html.erb
config/routes.rb
spec/controllers/files_controller_spec.rb
spec/features/item_view_metadata_spec.rb
spec/routing/files_spec.rb
spec/views/files/index.html.erb_spec.rb

Per Andrews request: https://github.com/sul-dlss/argo/issues/183#issuecomment-625550644
Test suite
none

Remove download from workspace

---

app/controllers/uploads_controller.rb
app/views/uploads/new.html.erb
spec/controllers/uploads_controller_spec.rb

This makes the form less confusing.
automated tests
none

Remove unnecessary form field

---

app/views/bulk_jobs/status_help.html.erb

Fixes #2075
Tested locally
none

Add close button and update text on help modal

---

app/components/external_links_component.html.erb
app/components/external_links_component.rb
app/controllers/catalog_controller.rb
app/models/solr_document.rb
app/presenters/profile_presenter.rb
app/views/catalog/_manage_release.html.erb
app/views/catalog/_show_sidebar.html.erb
spec/components/external_links_component_spec.rb
spec/views/catalog/_show_sidebar.html.erb_spec.rb

Don't draw searchworks link unless it has been released

---

app/controllers/catalog_controller.rb

This code doesn't do anything.
Test suite
n/a

Remove unnecessary controller before_action

---

Gemfile
Gemfile.lock
app/controllers/tags_controller.rb
app/javascript/modules/tags_autocomplete.js
app/javascript/packs/application.js
app/javascript/registration/grid.js
app/javascript/style/application.scss
app/javascript/style/tags-autocomplete.scss
app/views/registrations/show.html.erb
config/routes.rb
package.json
spec/controllers/tags_controller_spec.rb
yarn.lock

Fixes #165 
- manually on laptop
none

Add autocomplete of tags on the registration form

---

README.md

It was a suggestion on PR #2118
n/a
README

README testing section: added a note about docker-compose -v

---

config/settings.yml

Forgot to include this in #2121 
N/A
N/A

Remove no longer used settings

---

config/environments/production.rb
config/environments/staging.rb

Because we want staging to be like production
tested on staging
n/a

Setup staging to use sidekiq

---

app/jobs/checksum_report_job.rb
app/jobs/close_version_job.rb
app/jobs/create_virtual_objects_job.rb
app/jobs/descmetadata_download_job.rb
app/jobs/manage_catkey_job.rb
app/jobs/modsulator_job.rb
app/jobs/prepare_job.rb
app/jobs/purge_job.rb
app/jobs/release_object_job.rb
app/jobs/remote_indexing_job.rb
app/jobs/republish_job.rb
app/jobs/set_governing_apo_job.rb
app/jobs/set_tags_job.rb

This matches the recommended configuration for sidekiq
Tested in stage
n/a

Set all jobs to run in the default (sidekiq) queue

---

spec/features/item_view_metadata_spec.rb

No functional changes.
Previously `rspec ./spec/features/bulk_release_object_spec.rb[1:1] ./spec/features/item_view_metadata_spec.rb[1:2:2:1] --seed 38695` would fail because it was order dependent.
test suite
n/a

Refactor spec to prevent flapping

---

.rubocop_todo.yml
app/jobs/descmetadata_download_job.rb

This code was not reachable.
Test suite
n/a

Remove unreachable code

---

app/controllers/items_controller.rb
app/helpers/items_helper.rb
app/services/mods_validator.rb
config/routes.rb
spec/helpers/items_helper_spec.rb

and add missing test
We already have one validator, there's no reason to have 2.
Test suite
n/a

Remove unused code

---

app/helpers/xml/mods-3-6.xsd
app/helpers/xml/mods-xml.xsd
app/helpers/xml/xlink.xsd
app/services/mods_validator.rb

Fixes #2180 
testing suite
n/a

Adds xsd and local imports in mods-3-6.xsd

---

Gemfile.lock

Update webpacker to latest patch release

---

Gemfile
Gemfile.lock

See https://github.com/honeybadger-io/honeybadger-ruby/issues/369
Deployed to staging

Use a fixed version of honeybadger

---

Gemfile
Gemfile.lock

The previous branch no longer exists.

use the released version of honeybadger

---

app/controllers/items_controller.rb
spec/requests/set_rights_spec.rb

This syntax is less confusing. Added indexing which was missing before.

Use a simpler way of updating a cocina-model

---

app/jobs/register_druids_job.rb
spec/jobs/register_druids_job_spec.rb

Bulk reg report

---

app/controllers/items_controller.rb

The method that abstracts this implementation already exists, so use it.

Use the reindex method

---

app/controllers/items_controller.rb
spec/controllers/items_controller_spec.rb

There is no save necessary as the operation happens in dor-services-app

---

docker-compose.yml

Remove a duplicate config in docker-compose.yml

---

.circleci/config.yml
docker-compose.yml
spec/controllers/dor/objects_controller_spec.rb
spec/forms/apo_form_spec.rb
spec/forms/collection_form_spec.rb
spec/jobs/release_object_job_spec.rb
spec/rails_helper.rb
spec/services/techmd_service_spec.rb

This should result in faster build times and aligns with hydra_etd
test suite
circle.yml

Run circle without docker-compose

---

app/controllers/items_controller.rb

Remove callbacks for non-existant methods

---

app/javascript/modules/item_collection.js

fix error handling for collections

---

Gemfile
Gemfile.lock

To avoid https://github.com/projectblacklight/blacklight/issues/2346

Pin blacklight to 7.10.0

---

app/controllers/catalog_controller.rb

For https://github.com/sul-dlss/dor_indexing_app/pull/442

Update facet field for data quality

---

Gemfile
Gemfile.lock
spec/views/catalog/show.html.erb_spec.rb

Stub Blacklight::SearchState with a plausible Blacklight::Configuration instance

---

config/initializers/okcomputer.rb

In addition to the okcomputer db schema check, we want to check for data loss. This is adapted from similar approaches in sul-pub and prescat
Deployed to stage, and it works as expected.
DevOpsDocs edits forthcoming.

Spot check argo db for data

---

app/controllers/catalog_controller.rb
app/javascript/packs/application.js
config/webpack/environment.js
package.json
yarn.lock

closes #2292
To restore results navigation.
Locally.
Webpack

Restore results navigation.

---

app/controllers/items_controller.rb
app/models/nil_model.rb
spec/requests/show_rights_spec.rb

Add missing methods to the NilModel

---

Gemfile.lock

d'oh - because i forgot to generate the Gemfile.lock for PR #2327

update for new cocina-models

---

app/components/workflow_table_process_component.rb

So we can upgrade blacklight sometime in the future.

Avoid using deprecated method add_facet_params

---

app/controllers/items_controller.rb
spec/controllers/items_controller_spec.rb
spec/features/item_source_id_change_spec.rb
spec/requests/set_source_id_spec.rb

Update source_id using cocina api

---

app/controllers/collections_controller.rb
app/views/collections/new.html.erb
spec/controllers/collections_controller_spec.rb
spec/features/create_collection_spec.rb
spec/views/collections/new.html.erb_spec.rb

Remove unnecessary load from Fedora

---

Gemfile.lock

To fix https://github.com/sul-dlss/argo/issues/2359
Tested on stage: https://argo-stage.stanford.edu/catalog?utf8=%E2%9C%93&search_field=text&q=hp126jp7513+druid%3Ajz108tp8790+

Update to blacklight 7.14.1

---

app/controllers/datastreams_controller.rb
app/models/ability.rb
app/views/datastreams/edit.html.erb
app/views/datastreams/show.html.erb
spec/requests/edit_datastream_spec.rb

This one call site was missed in #2265
Fixes #2366

Authorize access using the cocina data model

---

Gemfile
Gemfile.lock

Update cocina-models to 0.44.0

---

spec/features/item_registration_spec.rb

See 9f0d39f2dfb5bd6d6db8d4c4f27f79215028f317
This fixes the feature spec

Revert part of 9f0d39f2dfb5bd6d6db8d4c4f27f79215028f317

---

.rubocop.yml
app/components/workflow_table_process_component.rb
app/controllers/dor/objects_controller.rb
app/controllers/items_controller.rb
app/jobs/modsulator_job.rb
app/models/report.rb
app/services/registration_service.rb
config/initializers/okcomputer.rb
spec/controllers/items_controller_spec.rb
spec/features/item_registration_spec.rb
spec/requests/item_files_download_spec.rb
spec/requests/set_rights_spec.rb
spec/requests/show_rights_spec.rb

Update rubocop rules

---

.circleci/config.yml

Test on ruby 2.7.2

---

app/controllers/uploads_controller.rb
app/views/uploads/new.html.erb
spec/controllers/uploads_controller_spec.rb
spec/views/uploads/new.html.erb_spec.rb

Remove Dor.find from UploadsController

---

app/controllers/items_controller.rb
app/helpers/value_helper.rb
app/views/items/_collection_ui.html.erb
app/views/items/_collection_ui_line_item.html.erb
spec/features/apo_displays_spec.rb
spec/helpers/value_helper_spec.rb
spec/views/items/_collection_ui.html.erb_spec.rb

Decouple collection membership form from Fedora 3

---

app/controllers/catalog_controller.rb

Because we don't need this code.

Remove unused @response ivar

---

app/controllers/catalog_controller.rb
app/views/catalog/_datastreams_default.html.erb
spec/controllers/catalog_controller_spec.rb

Move code out of views

---

app/controllers/bulk_jobs_controller.rb
app/views/bulk_jobs/index.html.erb
spec/features/bulk_jobs_spec.rb

Decouple BulkJobsController from Fedora 3

---

app/services/problematic_druid_finder.rb
spec/services/problematic_druid_finder_spec.rb

Remove dependency on Fedora 3 from ProblematicDruidFinder

---

app/controllers/catalog_controller.rb
app/models/ability.rb
spec/controllers/catalog_controller_spec.rb
spec/models/ability_spec.rb

Decouple CatalogController authorization from Fedora 3

---

app/views/catalog/_history_default.html.erb

Decouple link generation from Fedora

---

app/components/workflow_process_row.html.erb
app/components/workflow_process_row.rb
app/controllers/application_controller.rb
app/controllers/workflows_controller.rb
app/presenters/workflow_presenter.rb
app/views/workflows/_show.html.erb
spec/components/workflow_process_row_spec.rb
spec/controllers/workflows_controller_spec.rb
spec/features/add_workflow_to_item_spec.rb
spec/presenters/workflow_presenter_spec.rb
spec/views/workflows/_show.html.erb_spec.rb

Decouple workflows controller from Fedora 3

---

Gemfile
Gemfile.lock
app/forms/dro_rights_form.rb
spec/requests/item_files_download_spec.rb
spec/requests/set_rights_spec.rb
spec/requests/show_rights_spec.rb

To test changes before they go to prod.
Will be tested in QA/stage.
None

Bump underlying cocina model that uses publish attr

---

app/controllers/catalog_controller.rb
app/models/ability.rb
spec/controllers/catalog_controller_spec.rb
spec/models/ability_spec.rb

Fix view metadata

---

app/models/user.rb

This helps clue the reader in to what is happening in the code

Use a more expressive variable

---

Gemfile
Gemfile.lock
spec/requests/item_files_download_spec.rb
spec/requests/set_rights_spec.rb
spec/requests/show_rights_spec.rb
spec/services/ocr_exporter_spec.rb

Update tests for cocina-models-0.55

---

app/jobs/descmetadata_download_job.rb
spec/jobs/descmetadata_download_job_spec.rb

Fixes #2396
This refactors the `query_dor` method in the DescMetadataDownloadJob by replacing the call to `Dor.find` and `descMetadata` with corresponding dor-services-client calls. Note that I am not sure we still need the retry behavior that was patched in here previously, so I was inclined to make the smaller change and not remove this code. I might easily be convinced to do that, though.
CI
None

Prefer using dor-services-client over Fedora connections

---

app/models/ability.rb

Remove manage_item ability from Fedora 3 objects

---

app/jobs/modsulator_job.rb

Decouple modsulator job from Fedora 3

---

spec/controllers/content_types_controller_spec.rb

:point_up: + cruft is bad
CI
None

Remove crufty comment from specs

---

app/controllers/items_controller.rb
spec/controllers/items_controller_spec.rb
spec/features/collection_manage_release_spec.rb

Decouple ItemsController#mods from Fedora 3

---

app/controllers/items_controller.rb
app/views/items/_catkey_ui.html.erb
app/views/items/_collection_ui.html.erb
app/views/items/_embargo_form.html.erb
app/views/items/_set_governing_apo_ui.html.erb
app/views/items/_source_id_ui.html.erb
spec/controllers/items_controller_spec.rb
spec/features/apo_displays_spec.rb
spec/features/item_catkey_change_spec.rb
spec/features/item_source_id_change_spec.rb
spec/requests/set_rights_spec.rb
spec/views/items/_collection_ui.html.erb_spec.rb
spec/views/items/_embargo_form.html.erb_spec.rb
spec/views/items/_set_governing_apo_ui.html.erb_spec.rb
spec/views/items/_source_id_ui.html.erb_spec.rb

Stop using Dor::Item where not necessary

---

lib/constants.rb

Fixes a production bug
CI
None

Correct mapping of file content type

---

app/controllers/items_controller.rb
spec/controllers/items_controller_spec.rb

Decouple collection addition and removal from Fedora 3

---

app/controllers/collections_controller.rb
spec/controllers/collections_controller_spec.rb
spec/support/cocina_matchers.rb

Fixes #2496
:point_up: 
CI
:no_entry_sign:

Decouple collections controller from Fedora

---

app/controllers/items_controller.rb
app/views/items/_rights.html.erb
spec/requests/show_rights_spec.rb
spec/views/items/_rights.html.erb_spec.rb

Decouple rights from Fedora 3

---

Gemfile
Gemfile.lock
app/controllers/versions_controller.rb
app/views/versions/_close_ui.html.erb
app/views/versions/_open_ui.html.erb
spec/features/apo_displays_spec.rb
spec/views/versions/_close_ui.html.erb_spec.rb
spec/views/versions/_open_ui.html.erb_spec.rb

Decouple versionsController from Fedora 3

---

.circleci/config.yml
Gemfile
Gemfile.lock
README.md

Note: this PR also bumps Simplecov now that CodeClimate supports v0.20+
Seeing test coverage is helpful when reviewing PRs.
CI
CircleCI config.

Set up test coverage and update badges

---

Gemfile
Gemfile.lock

Updated dor-services-client and sdr-client.

---

app/controllers/catalog_controller.rb
app/presenters/milestones_presenter.rb
app/services/version_service.rb
spec/features/add_workflow_to_item_spec.rb
spec/features/apo_spec.rb
spec/features/consistent_titles_spec.rb
spec/features/enable_buttons_spec.rb
spec/features/item_catkey_change_spec.rb
spec/features/item_source_id_change_spec.rb
spec/features/item_view_metadata_spec.rb
spec/features/release_history_spec.rb
spec/presenters/milestones_presenter_spec.rb
spec/requests/set_rights_spec.rb
spec/services/version_service_spec.rb

Decouple CatalogController from Fedora 3 

---

.circleci/config.yml
docker-compose.yml
spec/features/apo_spec.rb
spec/features/collection_manage_release_spec.rb
spec/features/item_manage_release_spec.rb
spec/models/report_spec.rb

Hopefully the changes to the DSA container fixes these problems

Restore xited specs

---

app/jobs/descmetadata_download_job.rb
spec/jobs/remote_indexing_job_spec.rb

Remove ActiveFedora::ObjectNotFoundError 

---

spec/models/report_spec.rb

Remove ActiveFedora::SolrService from report_spec.rb

---

app/services/purge_service.rb
spec/services/purge_service_spec.rb

Decouple PurgeService from ActiveFedora

---

spec/controllers/report_controller_spec.rb

Refactor ActiveFedora::SolrService out of controller specs

---

.rubocop_todo.yml
spec/features/add_workflow_to_item_spec.rb
spec/features/apo_displays_spec.rb
spec/features/apo_spec.rb
spec/features/bulk_jobs_spec.rb
spec/features/bulk_screen_spec.rb
spec/features/collection_manage_release_spec.rb
spec/features/consistent_titles_spec.rb
spec/features/date_range_form_spec.rb
spec/features/enable_buttons_spec.rb
spec/features/filter_facet_spec.rb
spec/features/home_page_spec.rb
spec/features/item_catkey_change_spec.rb
spec/features/item_registration_spec.rb
spec/features/item_source_id_change_spec.rb
spec/features/item_view_metadata_spec.rb
spec/features/profile_spec.rb
spec/features/release_history_spec.rb
spec/features/report_view_spec.rb
spec/features/search_results_spec.rb
spec/features/set_governing_apo_spec.rb

Remove ActiveFedora::SolrService from feature specs

---

spec/jobs/descmetadata_download_job_spec.rb
spec/jobs/purge_job_spec.rb
spec/jobs/set_governing_apo_job_spec.rb

Decouple job specs from dor-services models"

---

spec/factories/apos.rb
spec/factories/collections.rb
spec/factories/items.rb
spec/features/set_governing_apo_spec.rb
spec/support/apo_method_sender.rb
spec/support/item_method_sender.rb

This helps work around a problem where the ur-apo gets removed from the index

Use the factories for creating test objects

---

app/controllers/items_controller.rb
spec/controllers/items_controller_spec.rb

Allow item to be added to a collection if it's not currently in one

---

app/controllers/content_types_controller.rb
spec/controllers/content_types_controller_spec.rb

Don't error when there are no files

---

app/controllers/content_types_controller.rb
spec/controllers/content_types_controller_spec.rb
spec/support/cocina_matchers.rb

When an item has no resouces allow the content type to change

---

app/controllers/apo_controller.rb
app/views/apo/edit.html.erb
spec/controllers/apo_controller_spec.rb
spec/features/apo_spec.rb

Decouple ApoController#delete_collection from Fedora 3

---

.rubocop_todo.yml
app/controllers/collections_controller.rb
app/forms/apo_form.rb
app/forms/base_form.rb
app/forms/collection_form.rb
spec/controllers/collections_controller_spec.rb
spec/features/apo_spec.rb
spec/forms/apo_form_spec.rb
spec/forms/collection_form_spec.rb

Decouple the collection form from Fedora 3

---

spec/forms/collection_form_spec.rb

Remove unnecessary mocks from tests

---

app/helpers/blacklight_config_helper.rb

Stop searching field that is not populated

---

Gemfile
Gemfile.lock

connects to sul-dlss/argo#2404 and sul-dlss/argo#2612
CI and in QA
None

Bump cocina-models to pick up collection copyright

---

app/views/shared/_user_util_links.html.erb

Check for authorization using Cocina models

---

app/components/external_links_component.rb

So we can decouple from dor-services

Transfer safeurl from dor-services

---

app/forms/apo_form.rb
spec/forms/apo_form_spec.rb

Add cc0 license option

---

app/controllers/versions_controller.rb
app/services/version_tag.rb
spec/services/version_tag_spec.rb

Fixes #2646
Fix a production outage
CI
None

Inline dor-services class that parses version tags

---

.circleci/config.yml

Test on the latest version of ruby 2.7

---

app/forms/apo_form.rb
spec/forms/apo_form_spec.rb

Edit APO: show all default collections

---

app/models/admin_policy_change_set.rb

Refactor to align the AdminPolicyChangeSet with the ItemChangeSet

---

app/controllers/items_controller.rb
app/models/collection_change_set.rb
app/models/item_change_set.rb

Refactor to allow ItemChangeSet and CollectionChangeSet to take arguments

---

app/components/workflow_update_button.html.erb
app/components/workflow_update_button.rb

Remove deprecated and unnecessary method call

---

Gemfile.lock
README.md

To add some detail around mismatched bundler versions and how I was able to resolve

update readme on how to deal with bundler version conflicts

---

app/controllers/items_controller.rb

Remove extra space

---

package.json
yarn.lock

Upgrade to stimulus 2

---

app/forms/registration_form.rb
app/javascript/registration/grid.js
app/javascript/registration/register.js
spec/controllers/dor/objects_controller_spec.rb
spec/features/item_registration_spec.rb
spec/forms/registration_form_spec.rb

Fixes #2548
New feature request by @andrewjbtw.
CI, local browser -- will be tested in QA
None

Add barcode field to item registration form

---

app/forms/apo_form.rb
app/views/apo/_form.html.erb
spec/forms/apo_form_spec.rb

Fixes #2631
New unit tests
n/a

Adds new method for determining option for default object rights

---

config/application.rb

Also drop the ActiveFedora dependency, which was not used

Return the 404 page when a record is not found

---

app/javascript/argo.js
app/javascript/packs/application.js

This finishes up some of the javascript organizing work that had never been completed.

Initialize all the javascript with a single call

---

app/views/bulk_actions/new.html.erb
app/views/catalog/_cocina_default.html.erb
app/views/catalog/facet.html.erb
app/views/tokens/index.html.erb

Avoids deprecation warnings around stimulus

---

.circleci/config.yml
docker-compose.yml
spec/features/open_and_close_a_version_spec.rb

Depends on https://github.com/sul-dlss/dor-services-app/pull/2694
Because we don't have a feature test for these things

Add a feature test for open and close version

---

spec/jobs/set_catkeys_and_barcodes_csv_job_spec.rb

This resulted from a merge and caused the build on main to break

Remove invalid access

---

.circleci/config.yml
app/controllers/agreements_controller.rb
app/forms/agreement_form.rb
app/forms/user_form.rb
app/javascript/argo.js
app/javascript/style/application.scss
app/javascript/style/errors.scss
app/services/file_generator.rb
app/services/register_agreement.rb
app/views/agreements/new.html.erb
app/views/shared/_user_util_links.html.erb
config/locales/en.yml
config/routes.rb
config/settings/test.yml
docker-compose.yml
package.json
spec/features/register_agreement_spec.rb
spec/rails_helper.rb
yarn.lock

Fixes #2357
Tested locally, added a feature test and tested on stage.

Add a mechanism for registering an agreement

---

Gemfile
Gemfile.lock
app/components/date_choice_facet_component.html.erb

Upgrade to latest version (7.18.0) of blacklight.

---

spec/features/register_agreement_spec.rb

This fixes the build after a rebase

Use  file_fixture helper for register agreement

---

README.md
db/seeds.rb

Create a seed task

---

app/controllers/uploads_controller.rb
spec/controllers/uploads_controller_spec.rb

Improves usability. Now the user knows there request was accepted.

Add a message that shows the user that processing is started

---

app/components/bulk_actions_form_component.html.erb
app/components/bulk_actions_form_component.rb
app/controllers/bulk_actions_controller.rb
app/forms/bulk_action_form.rb
app/javascript/controllers/bulk_actions.js
app/jobs/manage_embargoes_job.rb
app/models/bulk_action.rb
app/models/item_change_set.rb
app/services/item_change_set_persister.rb
app/views/bulk_actions/forms/_manage_embargo_form.erb
app/views/bulk_actions/new.html.erb
spec/jobs/manage_embargoes_job_spec.rb
spec/services/item_change_set_persister_spec.rb
spec/views/bulk_actions/new.html.erb_spec.rb

closes #2671
Support embargo management from Argo.
Unit, QA
NA

Adds manage embargo bulk action.

---

app/javascript/modules/item_collection.js

Removes multiple event bindings for add_collection Button

---

Gemfile.lock

Part of sul-dlss/dor-services-app#2851

bump cocina-models for new lane barcode validation

---

app/jobs/release_object_job.rb

Each method should only do one thing

Refactor ReleaseObjectJob

---

app/components/manage_release/collection_form_component.html.erb

closes #2798
Prevent user error.

Set default what when releasing collection.

---

.rubocop.yml

Configure the new rubocops

---

app/views/collections/new.html.erb

Without that component, the code breaks with the error:
```
Response has no matching <turbo-frame id="modal-frame"> element
```

Use the EditModalComponent for new collections

---

Gemfile.lock
app/assets/stylesheets/variables.scss
app/components/blacklight_modal_component.html.erb
app/components/edit_modal_component.html.erb
app/javascript/application.js
app/javascript/modules/blacklight-override.js
app/views/bulk_jobs/_bulk_index_table.html.erb
app/views/bulk_jobs/show.html.erb
app/views/catalog/_report_view_toggle.html.erb
app/views/registrations/show.html.erb
app/views/shared/_header_navbar.html.erb
app/views/shared/_user_util_links.html.erb
app/views/uploads/new.html.erb
config/webpack/environment.js
package.json
yarn.lock

Upgrade to Bootstrap 5

---

app/javascript/application.js
app/javascript/bulk.js
app/javascript/controllers/tokens.js

Remove unnecessary library rails-ujs

---

app/components/action_button.html.erb
app/components/action_button.rb
app/components/download_all_button_component.rb
app/components/workflow_step_status_selector.html.erb
app/views/apo/_form.html.erb
app/views/bulk_actions/index.html.erb
spec/components/download_all_button_component_spec.rb
spec/components/sidebar_controls_component_spec.rb

Use the data-turbo-method provided by @hotwired/turbo rather than ujs

---

app/components/blacklight_modal_component.html.erb
app/components/edit_modal_component.html.erb
spec/components/blacklight_modal_component_spec.rb
spec/components/edit_modal_component_spec.rb
spec/features/item_view_metadata_spec.rb

Update the close button style for bootstrap 5

---

app/assets/stylesheets/argo.scss
app/views/bulk_jobs/_bulk_index_table.html.erb
app/views/bulk_jobs/index.html.erb
app/views/bulk_jobs/status_help.html.erb
app/views/uploads/new.html.erb
spec/views/bulk_jobs/_bulk_index_table.html.erb_spec.rb
spec/views/uploads/new.html.erb_spec.rb

use bootstrap classes rather than custom styles

---

app/controllers/items_controller.rb

See https://github.com/hotwired/turbo/issues/84#issuecomment-756189909

use the correct redirect status so that it is followed by a GET

---

README.md
bin/dev

Provide required environment variables in the dev script

---

app/components/workflow_step_status_selector.html.erb
app/javascript/argo.js
app/views/agreements/new.html.erb
package.json
yarn.lock

Update agreement form with bootstrap 5 styles

---

spec/features/date_range_form_spec.rb

Easier to understand as a human what is happening.

Refactor test to click on a button rather than a css selector

---

app/javascript/controllers/registration_controller.js
app/views/registrations/show.html.erb

Use the bootstrap 5 API for manipulating the modal

---

app/views/apo/_form.html.erb
app/views/bulk_actions/forms/_manage_release_form.html.erb
app/views/collections/new.html.erb
app/views/uploads/new.html.erb

Style radio buttons with bootstrap 5 styles

---

app/javascript/controllers/button.js

Use the bootstrap 5 API for managing the modal

---

app/assets/stylesheets/document.scss
app/components/document_component.html.erb
app/components/techmd_component.html.erb
app/helpers/items_helper.rb
app/javascript/argo.js
app/presenters/argo_show_presenter.rb
app/views/catalog/_cocina_default.html.erb
app/views/catalog/_contents_default.html.erb
app/views/catalog/_datastreams_default.html.erb
app/views/catalog/_events_default.html.erb
app/views/catalog/_history_default.html.erb
app/views/catalog/_techmd_default.html.erb

Add aria- properties explaining the dynamic behavior of the headers
It's important to use semantic controls (like `<button>`) for dynamic elements.

Improve the accessability of the show page

---

app/javascript/registration/grid.js
app/javascript/registration/pathTo.js
app/javascript/registration/register.js

We never set an data-application-root, so this code isn't doing anything except adding indirection and complexity

Remove code that wasn't doing anything

---

app/javascript/controllers/apo_form_controller.js
app/javascript/controllers/collection_editor.js
app/views/collections/new.html.erb
spec/views/collections/new.html.erb_spec.rb

Remove jquery code from the new collection form

---

docker-compose.yml

Turn on logging for SURI

---

app/views/bulk_actions/_checksum_report_job.html.erb
app/views/bulk_actions/_export_tags_job.html.erb
app/views/bulk_actions/_register_druids_job.html.erb

Remove unused templates

---

app/views/bulk_jobs/_bulk_index_table.html.erb
spec/features/bulk_jobs_spec.rb

This functionality was uncovered by tests.

Test that the help link works

---

db/seeds.rb
spec/controllers/report_controller_spec.rb
spec/features/item_registration_spec.rb
spec/features/set_governing_apo_spec.rb
spec/support/reset_solr.rb

Otherwise DSA can't find the UR-apo

Reset solr when loading seeds

---

app/javascript/bulk.js

Send auth token when bulk setting tags and source_id

---

app/services/registration_csv_converter.rb
spec/jobs/register_druids_job_spec.rb

Update isMemberOf to array while parsing CSV

---

app/assets/stylesheets/variables.scss

For the new designs Astrid prepared

Change the primary color to cardinal

---

app/assets/stylesheets/show.scss
app/components/document_component.html.erb
app/components/document_title_component.html.erb
app/components/document_title_component.rb
app/components/open_close_component.html.erb
app/components/open_close_component.rb
app/components/sidebar_controls_component.html.erb
app/components/sidebar_controls_component.rb
app/javascript/controllers/index.js
app/javascript/controllers/open_close_controller.js
spec/components/open_close_component_spec.rb
spec/components/sidebar_controls_component_spec.rb
spec/features/enable_buttons_spec.rb

Open close component

---

Gemfile
Gemfile.lock

Upgrade to turbo-rails 1.0

---

app/assets/stylesheets/show.scss
app/assets/stylesheets/variables.scss
app/components/document_component.html.erb
app/components/overview_component.html.erb
app/components/overview_component.rb
app/controllers/catalog_controller.rb
app/models/solr_document.rb
spec/components/overview_component_spec.rb

Show the overview table on the show page.

Overview component

---

app/components/details_component.html.erb
app/components/details_component.rb
app/components/overview_component.html.erb
app/components/overview_component.rb
app/components/sidebar_controls_component.html.erb
app/components/sidebar_controls_component.rb
spec/components/details_component_spec.rb
spec/components/overview_component_spec.rb
spec/components/sidebar_controls_component_spec.rb
spec/features/edit_item_tags_spec.rb
spec/features/set_governing_apo_spec.rb

Move buttons to icons

---

spec/features/open_and_close_a_version_spec.rb

Ref https://github.com/sul-dlss/workflow-server-rails/pull/514

Adjust feature test for fewer accession steps

---

app/assets/stylesheets/document-component.scss
app/assets/stylesheets/sul_variables.scss
app/assets/stylesheets/variables.scss

Style the accordion to match the mockups

---

app/components/details_component.rb
app/components/overview_component.rb
app/components/show_embargo_component.rb

These more closely match the mockup

Use pencil icons rather than emojis

---

app/views/catalog/_cocina_default.html.erb

Add icons to cocina expand and collapse

---

app/components/details_component.html.erb
app/components/details_component.rb
app/components/overview_component.rb
spec/components/details_component_spec.rb
spec/components/overview_component_spec.rb

Add default values to the show page

---

app/assets/stylesheets/show.scss
app/assets/stylesheets/sul_variables.scss
app/components/document_title_component.html.erb
app/components/document_title_component.rb

Add pills to show the object type

---

app/components/external_links_component.html.erb
app/components/external_links_component.rb
app/components/sidebar_controls_component.html.erb
spec/components/external_links_component_spec.rb
spec/components/sidebar_controls_component_spec.rb

Don't show PURL or SearchWorks links for Admin Policies

---

Gemfile
Gemfile.lock
app/components/sidebar_controls_component.html.erb
app/components/sidebar_controls_component.rb
app/controllers/dor_controller.rb
app/controllers/publishes_controller.rb
config/routes.rb
spec/components/sidebar_controls_component_spec.rb
spec/controllers/dor_controller_spec.rb
spec/features/enable_buttons_spec.rb
spec/requests/publish_spec.rb
spec/requests/unpublish_spec.rb

Add unpublish function

---

app/assets/stylesheets/document-component.scss
app/components/sidebar_controls_component.html.erb
app/components/sidebar_controls_component.rb
app/helpers/argo_helper.rb
app/views/catalog/_datastreams_default.html.erb
spec/components/sidebar_controls_component_spec.rb

Move MODS upload button to the main set of controls

---

app/controllers/items_controller.rb
app/services/collection_change_set_persister.rb
spec/requests/item_update_spec.rb

Support setting copyright on collection

---

app/components/overview_component.html.erb
app/controllers/items_controller.rb
app/views/items/edit_use_statement.html.erb
config/routes.rb
spec/requests/item_update_spec.rb

Edit use and reproduction field inline

---

app/components/contents_component.html.erb
app/controllers/structures_controller.rb
app/javascript/controllers/index.js
app/javascript/controllers/structural_controller.js
app/services/structure_updater.rb
spec/fixtures/files/structure-upload.csv
spec/requests/upload_structural_csv_spec.rb
spec/services/structure_updater_spec.rb

Upload structural CSV

---

app/controllers/items_controller.rb

Update code comment related to APO access defaults

---

app/components/details_component.html.erb
app/components/overview_component.html.erb
spec/components/details_component_spec.rb
spec/components/overview_component_spec.rb

Collection display

---

spec/components/details_component_spec.rb

Add tests around Content type on the show page

---

app/components/details_component.html.erb
app/components/details_component.rb
app/models/report.rb
app/models/solr_document.rb
app/presenters/citation_presenter.rb

See https://github.com/sul-dlss/dor_indexing_app/pull/722

Use the new created date solr field

---

app/controllers/collections_controller.rb
app/controllers/items_controller.rb
config/routes.rb
spec/requests/collection_update_spec.rb
spec/requests/edit_copyright_spec.rb
spec/requests/edit_license_spec.rb
spec/requests/edit_use_statement_spec.rb
spec/requests/item_update_spec.rb

Use the appropriate change set for a collection

---

app/assets/stylesheets/show.scss
app/components/details_component.rb
app/components/document_component.html.erb
app/components/document_component.rb
app/components/document_title_component.html.erb
app/components/external_links_component.html.erb
app/components/show/admin_policy_component.html.erb
app/components/show/admin_policy_component.rb
app/components/show/collection_component.html.erb
app/components/show/collection_component.rb
app/components/show/item_component.html.erb
app/components/show/item_component.rb
app/views/catalog/_show_thumbnail.html.erb
spec/components/details_component_spec.rb
spec/components/show/admin_policy_component_spec.rb
spec/components/show/collection_component_spec.rb
spec/components/show/item_component_spec.rb
spec/features/item_view_metadata_spec.rb
spec/features/release_history_spec.rb
spec/requests/set_rights_spec.rb

Don't reserve a spot for thumbnails for APO or Collections

---

app/views/workflow_service/lock.html.erb
spec/features/open_and_close_a_version_spec.rb

Ref https://projects.invisionapp.com/share/ZR1072MLCMEW#/screens/444887297

Update title for unlock icon

---

Gemfile
Gemfile.lock
app/services/apply_mods_metadata.rb
spec/services/apply_mods_metadata_spec.rb

Use the new mods update DSA endpoint for saving MODS

---

app/services/structure_serializer.rb
app/services/structure_updater.rb
spec/services/structure_serializer_spec.rb
spec/services/structure_updater_spec.rb

Use short resource names for the csv

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/argo.scss
app/assets/stylesheets/bulk-actions.scss

This helps provide context for where these styles apply in the application

Extract bulk styles from argo.scss

---

app/components/show/admin_policy_component.html.erb
app/components/show/apo/default_object_rights_component.html.erb
app/components/show/apo/default_object_rights_component.rb
spec/components/show/apo/default_object_rights_component_spec.rb

Create a component to display Admin policy defaults

---

app/components/show/catkey_component.rb
app/components/show/details_component.html.erb
app/models/collection_change_set.rb
app/models/concerns/catkey.rb
app/models/item_change_set.rb
app/services/collection_change_set_persister.rb
app/services/item_change_set_persister.rb
app/views/catkeys/_edit.html.erb
spec/components/show/details_component_spec.rb
spec/features/item_catkey_change_spec.rb

Allow editing and display of multiple catkeys

---

app/components/show/collection/details_component.html.erb
app/components/show/collection/details_component.rb
app/components/show/collection/overview_component.html.erb
app/components/show/collection/overview_component.rb
app/components/show/collection_component.html.erb
spec/components/show/collection/details_component_spec.rb
spec/components/show/collection/overview_component_spec.rb

This removes a whole bunch of conditional logic

Extract the overview and details components for collections

---

app/components/show/admin_policy_component.html.erb
app/components/show/apo/details_component.html.erb
app/components/show/apo/details_component.rb
app/components/show/apo/overview_component.html.erb
app/components/show/apo/overview_component.rb
spec/components/show/apo/details_component_spec.rb
spec/components/show/apo/overview_component_spec.rb

Reduce the number of conditionals and make the layout for admin policies simpler.

Extract the overview and details components for admin policies

---

app/components/document_component.rb
app/components/show/agreement/details_component.html.erb
app/components/show/agreement/details_component.rb
app/components/show/agreement/overview_component.html.erb
app/components/show/agreement/overview_component.rb
app/components/show/agreement_component.html.erb
app/components/show/agreement_component.rb
app/components/show/overview_component.html.erb
spec/components/show/agreement/details_component_spec.rb
spec/components/show/agreement/overview_component_spec.rb
spec/components/show/agreement_component_spec.rb

Remove unnecessary fields from the agreement view

---

app/components/show/agreement/details_component.html.erb
app/components/show/agreement/details_component.rb
app/components/show/apo/details_component.html.erb
app/components/show/apo/details_component.rb
app/components/show/collection/details_component.html.erb
app/components/show/collection/details_component.rb
app/components/show/item/details_component.html.erb
app/components/show/item/details_component.rb
app/components/show/project_tag_component.rb
app/components/show/tags_component.html.erb
app/components/show/tags_component.rb
spec/components/show/project_tag_component_spec.rb
spec/components/show/tags_component_spec.rb

Extract components for tags

---

Gemfile.lock

[release branch] Update dependencies for cocina-models update

---

config/settings.yml

Remove unused config

---

app/jobs/create_virtual_objects_job.rb
app/services/virtual_objects_creator.rb
app/services/virtual_objects_csv_converter.rb
app/views/bulk_actions/forms/_create_virtual_objects_form.html.erb
spec/jobs/create_virtual_objects_job_spec.rb
spec/services/virtual_objects_creator_spec.rb
spec/services/virtual_objects_csv_converter_spec.rb

Connects to sul-dlss/dor-services-app#3416
To reflect public API changes in DSA and avoid breaking virtual object creation.
CI. Will be tested via integration test too.
None

Use the new virtual object structure

---

app/controllers/datastreams_controller.rb

Fix bug and test broken by https://github.com/sul-dlss/argo/commit/3be8ef295c680c53d458cfec2fc9f68384e58d95

fix the build

---

app/models/collection_change_set.rb
spec/components/show/collection/overview_component_spec.rb
spec/models/collection_change_set_spec.rb

Set up missing properties on CollectionChangeSet

---

app/controllers/items_controller.rb
app/helpers/items_helper.rb
app/models/item_change_set.rb
app/services/item_change_set_persister.rb

Allow the license to be cleared out

---

app/components/document_title_component.html.erb
app/views/catalog/show.html.erb

Pass the cocina model to the ability check

---

spec/features/item_view_metadata_spec.rb

This test duplicates what happens in the test immediately preceding.

Remove a duplicate test

---

spec/features/register_agreement_spec.rb

Remove unused let blocks from agreement spec

---

app/components/show/apo/details_component.html.erb
app/components/show/apo/details_component.rb
app/controllers/apo_controller.rb
app/views/apo/_count_collections.html.erb
app/views/apo/_count_items.html.erb
config/routes.rb
spec/requests/apo_count_spec.rb

[HOLD] Display the count of collections and items on the apo show page

---

app/assets/stylesheets/show.scss
app/assets/stylesheets/variables.scss
app/components/show/admin_policy_component.html.erb
app/components/show/apo/grant_component.html.erb
app/components/show/apo/grant_component.rb
app/components/show/apo/roles_component.html.erb
app/components/show/apo/roles_component.rb
spec/components/show/apo/grant_component_spec.rb
spec/components/show/apo/roles_component_spec.rb

Fixes #3099
Tested on stage by Andrew.

Display APO roles

---

app/components/show/collection/details_component.html.erb
app/components/show/collection/details_component.rb
app/controllers/collections_controller.rb
app/views/collections/_count.html.erb
config/routes.rb
spec/requests/collection_count_spec.rb
spec/support/item_method_sender.rb

Display a count of the collection members

---

app/components/contents/file_component.html.erb
app/components/contents/file_component.rb
app/components/contents/resource_component.html.erb
spec/components/contents/file_component_spec.rb

Fixes #3169
CI and tested in stage

Display file role/use in contents section of show page

---

Gemfile
Gemfile.lock
app/services/modsulator_client.rb

Hold this until new Argo UI has been deployed to prod

Upgrade to faraday 2

---

.rubocop.yml
spec/controllers/auth_controller_spec.rb
spec/controllers/catalog_controller_spec.rb
spec/controllers/files_controller_spec.rb
spec/controllers/registrations_controller_spec.rb
spec/controllers/workflow_service_controller_spec.rb
spec/helpers/profile_helper_spec.rb
spec/jobs/descmetadata_download_job_spec.rb
spec/models/dor_object_workflow_status_spec.rb

Add new cops and auto-correct
Existing tests

add new cops

---

app/components/bulk_actions_form_component.html.erb
app/components/bulk_actions_form_component.rb
app/controllers/bulk_actions_controller.rb
app/controllers/workflows_controller.rb
app/forms/bulk_action_form.rb
app/javascript/bulk.js
app/jobs/add_workflow_job.rb
app/models/bulk_action.rb
app/services/bulk_action_persister.rb
app/views/bulk_actions/forms/_add_workflow_form.html.erb
app/views/report/bulk.html.erb
spec/features/bulk_screen_spec.rb
spec/jobs/add_workflow_job_spec.rb

Fixes #2034
Tested by Andrew on stage.

Move start workflow to an asynchonous bulk action

---

app/components/bulk_actions_form_component.rb
app/controllers/items_controller.rb
app/javascript/bulk.js
app/jobs/refresh_mods_job.rb
app/models/bulk_action.rb
app/views/report/bulk.html.erb
spec/controllers/items_controller_spec.rb
spec/features/bulk_screen_spec.rb
spec/jobs/refresh_mods_job_spec.rb

Move refresh MODS to a asynchronous bulk action

---

app/components/bulk_actions_form_component.html.erb
app/components/bulk_actions_form_component.rb
app/jobs/export_structural_job.rb
app/models/bulk_action.rb
app/services/structure_serializer.rb
app/views/bulk_actions/_export_structural_job.html.erb
config/settings.yml
spec/jobs/export_structural_job_spec.rb

Bulk export of structural metadata as CSV

---

app/components/bulk_actions_form_component.html.erb
app/components/bulk_actions_form_component.rb
app/javascript/bulk.js
app/jobs/apply_apo_defaults_job.rb
app/models/bulk_action.rb
app/views/report/bulk.html.erb
spec/features/bulk_screen_spec.rb
spec/jobs/apply_apo_defaults_job_spec.rb

Migrate Apply APO defaults to a bulk action

---

app/components/bulk_actions_form_component.html.erb
app/components/bulk_actions_form_component.rb
app/controllers/bulk_actions_controller.rb
app/controllers/items_controller.rb
app/forms/bulk_action_form.rb
app/javascript/bulk.js
app/javascript/controllers/bulk_actions.js
app/jobs/generic_job.rb
app/jobs/set_source_ids_csv_job.rb
app/models/bulk_action.rb
app/models/collection_change_set.rb
app/models/item_change_set.rb
app/services/version_service.rb
app/views/bulk_actions/forms/_set_source_ids_csv_form.html.erb
app/views/report/bulk.html.erb
spec/features/bulk_screen_spec.rb
spec/jobs/set_source_ids_csv_job_spec.rb

Fixes #2029
To be tested on stage by Andrew.

Port setting source_id to a bulk action

---

app/controllers/items_controller.rb
app/javascript/bulk.js
app/views/report/bulk.html.erb
config/routes.rb
spec/controllers/items_controller_spec.rb

Remove bulk tags

---

.circleci/config.yml

To prevent deprecation warning on circle-ci

Upgrade circleci convenience images for pg and redis

---

Gemfile
Gemfile.lock

Update jsbundling-rails to 1.0.2

---

app/components/bulk_actions_form_component.rb
spec/views/bulk_actions/new.html.erb_spec.rb

Fixes #3235
Because it was requested in #3235.
CI

Update labels and order of actions in bulk actions form

---

app/components/bulk_actions_form_component.html.erb

This should have been part of #3235 but we did not catch it until tested in QA.
CI & QA

Make release the active bulk action tab when page first loads

---

spec/requests/workflows_spec.rb

Controller specs are deprecated. Request specs are better because they test more of the stack.

Migrate controller spec to request spec

---

app/controllers/items_controller.rb
config/routes.rb
spec/controllers/items_controller_spec.rb

Remove unused method ItemsController#mods

---

spec/requests/registration_spec.rb

Controller specs are deprecated.

Move registration tests to request tests

---

spec/requests/create_collections_spec.rb

Collection specs are deprecated

Move CollectionsController spec to a request spec

---

spec/requests/files_spec.rb

Migrate FilesControllerSpec to a request spec

---

spec/requests/manage_collection_membership_spec.rb

Collection specs are deprecated

Convert collection controller spec to a request spec

---

config/application.rb

Use the latest application defaults.

Flip application defaults to 7.0

---

.circleci/config.yml

Test on Ruby 3.1

---

app/components/techmd_component.html.erb

I believe this was copypasta that lead to an error in the javascript console.
Fixes #3287

Remove unnecessary stimulus controller directive

---

README.md

Update README re: preferred Ruby version

---

.rubocop.yml

Add new rubocop cops

---

package.json
yarn.lock

Upgrade to stimulus 3.0

---

Dockerfile

To be consistent with the prod environment.

Update the ruby version in the docker file

---

app/components/contents_component.html.erb
app/controllers/content_types_controller.rb
app/controllers/files_controller.rb
app/controllers/items_controller.rb
app/jobs/export_structural_job.rb
app/jobs/set_content_type_job.rb
app/services/ocr_exporter.rb
app/services/structure_updater.rb

Handle nil structurals.

---

.rubocop_todo.yml
app/models/user_log.rb

Rubocop CaseLikeIf autocorrect

---

app/components/bulk_actions_form_component.rb
app/views/bulk_actions/_druids.html.erb
app/views/bulk_actions/index.html.erb
spec/components/bulk_actions_form_component_spec.rb

how the populate button on bulk actions only when a search is present

---

app/views/shared/_user_util_links.html.erb
spec/features/bulk_desc_metadata_download_spec.rb

Fixes #3315 - rename bulk edit to bulk action
Once merged, please proceed directly to sul-dlss/infrastructure-integration-test#384 without passing go or collecting $200
Existing tests

rename bulk edit to bulk action

---

app/jobs/release_object_job.rb

Update documentation about ReleaseObjectJob

---

app/jobs/descriptive_metadata_export_job.rb
app/services/description_export.rb
spec/jobs/descriptive_metadata_export_job_spec.rb
spec/services/description_export_spec.rb

See https://github.com/sul-dlss/argo/pull/3339#issuecomment-1080830535

Add source_id column to the descriptive export

---

app/jobs/descriptive_metadata_export_job.rb
spec/jobs/descriptive_metadata_export_job_spec.rb

Sort the columns of the descriptive CSV export

---

app/jobs/add_workflow_job.rb
app/jobs/apply_apo_defaults_job.rb
app/jobs/close_version_job.rb
app/jobs/export_structural_job.rb
app/jobs/generic_job.rb
app/jobs/manage_embargoes_job.rb
app/jobs/prepare_job.rb
app/jobs/purge_job.rb
app/jobs/refresh_mods_job.rb
app/jobs/release_object_job.rb
app/jobs/set_collection_job.rb
app/jobs/set_content_type_job.rb
app/jobs/set_governing_apo_job.rb
app/jobs/set_rights_job.rb
spec/jobs/apply_apo_defaults_job_spec.rb
spec/jobs/export_structural_job_spec.rb
spec/jobs/prepare_job_spec.rb
spec/jobs/refresh_mods_job_spec.rb
spec/jobs/release_object_job_spec.rb
spec/jobs/set_collection_job_spec.rb
spec/jobs/set_content_type_job_spec.rb
spec/jobs/set_governing_apo_job_spec.rb
spec/jobs/set_rights_job_spec.rb

Refactor jobs to have a common pattern for jobs that load from cocina

---

app/assets/stylesheets/show.scss
app/components/show/controls_component.html.erb
app/components/show/controls_component.rb
app/controllers/descriptives_controller.rb
app/controllers/metadata_controller.rb
app/jobs/descriptive_metadata_export_job.rb
config/routes.rb
spec/components/show/controls_component_spec.rb
spec/requests/download_descriptive_csv_spec.rb

Download descriptive CSV from the show page

---

app/components/show/catkey_component.rb
app/controllers/catkeys_controller.rb
app/forms/catkey_form.rb
app/jobs/set_catkeys_and_barcodes_csv_job.rb
app/jobs/set_catkeys_and_barcodes_job.rb
app/models/collection_change_set.rb
app/models/item_change_set.rb
app/services/catkey.rb
app/services/collection_change_set_persister.rb
app/services/item_change_set_persister.rb
app/views/bulk_actions/catkey_and_barcode_csv_jobs/_new.html.erb
spec/components/show/collection/details_component_spec.rb
spec/components/show/item/details_component_spec.rb
spec/jobs/set_catkeys_and_barcodes_csv_job_spec.rb
spec/jobs/set_catkeys_and_barcodes_job_spec.rb
spec/requests/set_catkey_spec.rb
spec/services/item_change_set_persister_spec.rb

Allow setting multiple catkeys via the CSV bulk jobs

---

app/components/show/controls_component.html.erb
app/controllers/serials_controller.rb
app/forms/serials_form.rb
app/views/serials/_form.html.erb
app/views/serials/edit.html.erb
config/locales/en.yml
config/routes.rb
spec/components/show/controls_component_spec.rb
spec/forms/serials_form_spec.rb
spec/requests/serials_spec.rb

This incomplete implementation seems to be causing round-tripping errors.
Fixes #3014
Using the test suite.

Add a form for writing serials

---

app/controllers/bulk_jobs_controller.rb

So we don't repeat code
test suite

use the Druid#with_namespace method

---

app/components/show/admin_policy_component.html.erb
app/components/show/admin_policy_component.rb
app/components/show/agreement_component.html.erb
app/components/show/collection_component.html.erb
app/components/show/collection_component.rb
app/components/show/item_component.html.erb
app/controllers/catalog_controller.rb
app/controllers/events_controller.rb
app/views/catalog/_events_default.html.erb
app/views/events/show.html.erb
config/routes.rb
spec/requests/events_spec.rb

Load events lazily

---

app/forms/serials_form.rb
spec/features/update_serials_metadata_spec.rb
spec/forms/serials_form_spec.rb
spec/rails_helper.rb
spec/requests/serials_spec.rb

Fixes #3368
The prior mapping was causing a roundtrip validation error in DSA
Added an integration test.

Fix mapping for sort_field

---

app/jobs/set_catkeys_and_barcodes_job.rb
app/views/bulk_actions/catkey_and_barcode_jobs/_new.html.erb
spec/jobs/set_catkeys_and_barcodes_job_spec.rb

Allow the bulk form to set multiple catkeys

---

app/services/item_change_set_persister.rb
spec/requests/item_update_spec.rb

Don't clear out collections if they haven't changed

---

spec/requests/set_content_types_spec.rb

This code isn't needed.
Unit tests

Remove unused block from test

---

app/controllers/application_controller.rb
app/controllers/content_types_controller.rb
app/controllers/structures_controller.rb
app/views/content_types/_content_type.html.erb
spec/requests/set_content_types_spec.rb
spec/views/content_types/_content_type.html.erb_spec.rb

So that we handle this state consistently.

[refactor] Use the existing methods for ensuring an item is modifiable

---

app/services/structure_updater.rb
spec/services/structure_updater_spec.rb

Ensure the resource type provided in the CSV is valid

---

app/components/workflow_step_status_selector.rb
app/controllers/catalog_controller.rb
spec/features/item_catkey_change_spec.rb
spec/features/item_source_id_change_spec.rb
spec/views/catalog/_home_text.html.erb_spec.rb

For consistency and readability.
n/a

Autocorrect rubocop Layout/LineEndStringConcatenationIndentation

---

app/views/bulk_actions/index.html.erb
spec/requests/bulk_action_spec.rb

Don't pass the page parameter through to creating a new bulk action

---

app/controllers/content_types_controller.rb
spec/requests/set_content_types_spec.rb

Prevent an update when new resource type isn't selected

---

app/services/structure_updater.rb

Avoid a DOS using a malicious upload.
Test suite.

Avoid public_send as using it with untrusted input could lead to a DOS

---

lib/cocina/models/factories.rb
spec/jobs/set_catkeys_and_barcodes_job_spec.rb
spec/jobs/set_collection_job_spec.rb
spec/jobs/set_source_ids_csv_job_spec.rb

Use factories in more specs

---

spec/views/content_types/_content_type.html.erb_spec.rb
spec/views/datastreams/show.html.erb_spec.rb
spec/views/items/_set_governing_apo_ui.html.erb_spec.rb
spec/views/items/_source_id_ui.html.erb_spec.rb

Use factories in view specs

---

app/components/edit/item/access_rights_component.html.erb
app/components/edit/item/access_rights_component.rb
app/controllers/embargos_controller.rb
app/forms/embargo_form.rb
app/views/embargos/_form.html.erb
config/locales/en.yml
spec/requests/embargo_spec.rb

Update the embargo form to use the multipart access rights

---

app/controllers/content_types_controller.rb
app/forms/content_type_form.rb
app/javascript/controllers/content_type_controller.js
app/javascript/controllers/index.js
app/views/content_types/_content_type.html.erb
spec/requests/set_content_types_spec.rb
spec/views/content_types/_content_type.html.erb_spec.rb

Fixes https://github.com/sul-dlss/argo/issues/3211
Automated test suite

Update content type menu to handle reading order for images

---

app/services/license_and_rights_statements_setter.rb

This avoids repeated unnecessary API calls

Memoize object loaded from DSA

---

spec/jobs/set_catkeys_and_barcodes_job_spec.rb

[refactor] Rename test variable to be clearer about its raison d'être

---

app/components/show/controls_component.html.erb
spec/components/show/controls_component_spec.rb

Resolves #3364. 
Unit tests updated with new language and pass. Screenshot:

Changing CSV to Cocina spreadsheet

---

lib/tasks/argo.rake

To fix the new rake tasks so they don't block others from running.

move require statements to individual rake tasks that need them

---

app/components/bulk_actions_form_component.rb
app/controllers/bulk_actions/descriptive_metadata_import_jobs_controller.rb
app/controllers/descriptives_controller.rb
app/jobs/descriptive_metadata_import_job.rb
app/jobs/generic_job.rb
app/models/bulk_action.rb
app/services/description_import.rb
app/views/bulk_actions/descriptive_metadata_import_jobs/_new.html.erb
app/views/bulk_actions/descriptive_metadata_import_jobs/new.html.erb
app/views/bulk_actions/descriptive_metadata_import_jobs/new.turbo_stream.erb
config/routes.rb
spec/factories/bulk_action.rb
spec/jobs/descriptive_metadata_import_job_spec.rb
spec/jobs/generic_job_spec.rb
spec/requests/bulk_actions/descriptive_metadata_import_jobs_spec.rb
spec/services/description_import_spec.rb

Add a bulk job for descriptive metadata import

---

lib/cocina/models/factories.rb
spec/components/show/apo/default_object_rights_component_spec.rb
spec/components/show/apo/overview_component_spec.rb
spec/components/show/apo/roles_component_spec.rb
spec/features/apo_displays_spec.rb
spec/features/item_registration_spec.rb
spec/forms/apo_form_spec.rb
spec/models/ability_spec.rb
spec/requests/create_collections_spec.rb
spec/requests/remove_apo_collection_spec.rb
spec/requests/update_an_existing_admin_policy_spec.rb
spec/services/admin_policy_persister_spec.rb
spec/services/license_and_rights_statements_setter_spec.rb

Add an admin policy factory

---

spec/factories/apos.rb
spec/factories/collections.rb
spec/factories/items.rb
spec/features/apo_spec.rb
spec/features/edit_item_tags_spec.rb
spec/features/item_catkey_change_spec.rb
spec/features/item_manage_release_spec.rb
spec/features/item_source_id_change_spec.rb
spec/features/open_and_close_a_version_spec.rb
spec/features/set_governing_apo_spec.rb
spec/features/update_serials_metadata_spec.rb
spec/requests/apo_count_spec.rb
spec/requests/collection_count_spec.rb
spec/requests/view_cocina_model_spec.rb

This helps differentiate them from those that are only in-memory factories

[refactor] Rename factories that persist to DSA

---

app/components/edit/item/access_rights_component.html.erb
app/forms/apo_form.rb
app/forms/embargo_form.rb
app/forms/has_view_access.rb
app/forms/has_view_access_with_cdl.rb
app/models/item_change_set.rb
app/services/admin_policy_persister.rb
app/services/item_change_set_persister.rb
app/views/apo/_form.html.erb
spec/features/apo_spec.rb
spec/forms/apo_form_spec.rb
spec/requests/update_an_existing_admin_policy_spec.rb
spec/services/admin_policy_persister_spec.rb

Add new access rights component to the APO form

---

app/components/contents/resource_component.rb
app/components/contents/structural_component.html.erb
app/components/contents/structural_component.rb
spec/components/contents/resource_component_spec.rb

Fixes #3402
locally with a 607 page book.

Add pagination to the structure

---

app/models/ability.rb

These are not "groups" they are "roles"

[refactor] Rename constants for easier comprehension

---

app/controllers/items_controller.rb
app/jobs/refresh_mods_job.rb
app/models/ability.rb
app/models/user.rb
app/services/license_and_rights_statements_setter.rb
spec/models/ability_spec.rb
spec/requests/close_version_spec.rb
spec/requests/open_version_spec.rb

Ref https://github.com/sul-dlss/cocina-models/pull/394

Remove unused roles

---

app/services/structure_updater.rb
spec/services/structure_updater_spec.rb

closes #3451
Valid cocina wasn't being created.
Unit

Fix structure upload.

---

app/forms/embargo_form.rb
app/forms/has_view_access.rb
app/jobs/generic_job.rb
app/jobs/manage_embargoes_job.rb
app/views/bulk_actions/manage_embargo_jobs/_new.html.erb
spec/jobs/manage_embargoes_job_spec.rb

(view,download,location)
Fixes #3216
Test suite

Update the bulk embargo job to use the cocina access terms 

---

app/controllers/descriptives_controller.rb
app/controllers/structures_controller.rb
app/services/cocina_validator.rb
spec/fixtures/files/structure-upload.csv
spec/requests/upload_structural_csv_spec.rb

Handle validation errors when updating structural

---

Gemfile.lock
app/jobs/manage_embargoes_job.rb

This breaks the process up into a series of steps, each of which may fail. We need to handle a failure at any of these steps.
This removes an unsightly multi-line lambda.
Test suite

Refactor to use Result#bind

---

app/controllers/bulk_actions/descriptive_metadata_import_jobs_controller.rb
app/services/description_import.rb
app/services/description_validator.rb
spec/features/upload_descriptive_metadata_spec.rb
spec/services/description_validator_spec.rb

Fixes #3443  and fixes #3442 and fixes #3438 and fixes #3439 (additional validation for headers and rows in descriptive metadata CSV)
Added new tests

Additional validation for the descriptive metadata CSV

---

app/controllers/catkeys_controller.rb
app/controllers/content_types_controller.rb
app/controllers/descriptives_controller.rb
app/controllers/embargos_controller.rb
app/controllers/serials_controller.rb
app/controllers/structures_controller.rb
spec/requests/set_catkey_spec.rb
spec/requests/set_content_types_spec.rb

Load using cancancan

---

app/jobs/descriptive_metadata_import_job.rb
spec/jobs/descriptive_metadata_import_job_spec.rb

Closes #3478 
This adds a pattern for filtering which jobs and error combinations will alert to honeybadger. 

Rescue validation error in DescriptiveMetadataImportJob to avoid alerting honeybadger

---

app/controllers/apo_controller.rb
app/controllers/bulk_jobs_controller.rb

For consistency across the app.

Use cancancan controller methods more broadly

---

app/views/content_types/_content_type.html.erb

Update help text to point at structural CSV update

---

.rubocop.yml
.rubocop_todo.yml
app/components/show/apo/details_component.html.erb
app/components/show/apo/details_component.rb
app/controllers/agreements_controller.rb
config/routes.rb
spec/components/show/apo/details_component_spec.rb
spec/factories/items.rb
spec/features/apo_displays_spec.rb
spec/features/apo_spec.rb

Show agreement title on admin policy show page

---

app/controllers/bulk_jobs_controller.rb
spec/features/bulk_jobs_spec.rb

Fixes #3532
Added tests such that we actually try the authorization logic.

Fix load_resource for the BulkJobsController for the index action

---

app/javascript/controllers/registration_controller.js

This functionality was not working because it had not been upgraded for Bootstrap 5

Display the progress modal

---

Gemfile
Gemfile.lock
app/models/ability.rb
spec/requests/create_new_item_spec.rb

Optimistic locking.

---

app/assets/stylesheets/icons.scss
app/assets/stylesheets/registration.scss
app/assets/stylesheets/registration/registration.scss
app/javascript/controllers/registration_controller.js
app/javascript/registration/grid.js
app/views/registrations/show.html.erb
spec/features/item_registration_spec.rb

This removes the multiple select and the lock button per the designs.
Ref #3514
locally, test suite, on stage by Andrew

Update registration grid actions styles

---

app/views/registrations/show.html.erb

As specified in the design.
Ref #3514
locally, integration tests.

Add a header to the registration page

---

app/services/registration_service.rb

Remove exception handling for an error that can't be thrown

---

Gemfile.lock
app/controllers/datastreams_controller.rb
app/controllers/dor/objects_controller.rb
app/controllers/items_controller.rb
app/jobs/register_druids_job.rb
app/services/registration_csv_converter.rb
app/services/registration_service.rb
spec/features/item_view_spec.rb
spec/jobs/register_druids_job_spec.rb
spec/jobs/release_object_job_spec.rb
spec/requests/create_new_item_spec.rb
spec/requests/edit_datastream_spec.rb
spec/requests/item_update_spec.rb
spec/requests/update_datastream_spec.rb
spec/requests/upload_structural_csv_spec.rb

Parse errors from DSA

---

app/jobs/descriptive_metadata_import_job.rb
app/services/cocina_validator.rb
spec/requests/upload_structural_csv_spec.rb

Show full error messages from the API response

---

app/controllers/bulk_actions/governing_apo_jobs_controller.rb
app/controllers/items_controller.rb
app/controllers/registrations_controller.rb
app/helpers/registration_helper.rb
app/services/admin_policy_options.rb
app/views/bulk_actions/governing_apo_jobs/_new.html.erb
app/views/items/_set_governing_apo_ui.html.erb
app/views/registrations/show.html.erb
spec/features/bulk_set_governing_apo_spec.rb
spec/helpers/registration_helper_spec.rb
spec/services/admin_policy_options_spec.rb
spec/views/items/_set_governing_apo_ui.html.erb_spec.rb

This way, if there is a failure in querying solr, we fail early and not in the view where it is hard to diagnose.
Test suite

[refactor] Move query logic out of the views and into the controller

---

.rubocop.yml
app/controllers/application_controller.rb
config/initializers/devise.rb
spec/support/templates_tracker.rb

Keep up to date with rubocop changes.

Add the new rubocop rules

---

app/controllers/apo_controller.rb
app/controllers/registrations_controller.rb
app/javascript/registration/grid.js
app/services/collection_name_service.rb
app/views/apo/registration_options.html.erb
app/views/registrations/show.html.erb
config/routes.rb
spec/requests/registration_spec.rb

This sets the stage to implement the new rights menu for the registration page.

[refactor] Use a turbo frame to implement the apo registration options 

---

app/views/apo/registration_options.html.erb

This fixes the integration test `create_apo_spec.rb`
Integration test

Select the default rights when changing APO

---

app/jobs/set_catkeys_and_barcodes_job.rb

Trying to debug a problem in this ticket: #3591, and want to see the stacktrace.
Existing tests

send an HB alert for failed catkey/barcode job

---

app/services/description_validator.rb
spec/services/description_validator_spec.rb

A typo in the code was causing valid sheets to report "Title column not found"
Fixes #3593

Fix typo in header validation

---

spec/features/apo_spec.rb

An attempt to fix a flaky Argo spec
The tests!

attempt to fix flaky apo spec

---

spec/features/apo_spec.rb

Increase the capybara wait time for an element rendered by a turbo-frame

---

app/services/description_validator.rb
spec/services/description_validator_spec.rb

Depends on https://github.com/sul-dlss/cocina-models/pull/417
The beginnings of fixing #3441.   Needs to be fixed to walk the cocina model structure recursively and check types.  See the ticket.
Added a test.

Descriptive metadata CSV header cocina path validation

---

app/components/edit/item/access_rights_component.html.erb

Switch controlled digital lending to a dropdown

---

app/components/show/external_links_component.html.erb
app/components/show/external_links_component.rb
config/settings.yml
config/settings/development.yml
config/settings/test.yml

Remove the Fedora UI button

---

spec/features/apo_spec.rb

It was using an awkward syntax to achieve the same goal

Move method expectations to the instance double

---

app/javascript/controllers/index.js
app/javascript/controllers/tag_validation_controller.js
app/javascript/registration/grid.js
app/javascript/registration/register.js
app/views/registrations/show.html.erb

This makes the code for managing the registration page simpler.

[refactor] Move tag validation to a Stimulus controller

---

app/controllers/dor/objects_controller.rb
app/forms/registration_form.rb
app/javascript/registration/register.js
app/views/registrations/show.html.erb
spec/features/item_registration_spec.rb
spec/forms/registration_form_spec.rb

Reduces complexity of the javascript.

Process tags on the back end 

---

spec/features/add_workflow_to_item_spec.rb
spec/features/collection_manage_release_spec.rb
spec/features/enable_buttons_spec.rb
spec/features/item_catkey_change_spec.rb
spec/features/item_manage_release_spec.rb
spec/features/item_source_id_change_spec.rb
spec/features/item_view_spec.rb

Remove unnecessary stubbing

---

config/settings.yml

Cleanup unused config

---

app/jobs/generic_job.rb
spec/jobs/descriptive_metadata_import_job_spec.rb

closes sul-dlss/dor-services-app#3619
Avoid unnecessary job retries.
Unit

Handle csv jobs missing druid column without repeating.

---

spec/features/apo_spec.rb

To prevent this flaky test from annoying us.
Tests

adjust agreement to just check href target

---

app/views/versions/_open_ui.html.erb

require user enter description in field when opening object

---

app/forms/serials_form.rb
spec/forms/serials_form_spec.rb

closes #3601
Parallel titles are title too.
Unit

Allow serials form to handle parallel titles.

---

app/components/bulk_actions_form_component.rb
app/controllers/bulk_actions/tracking_sheet_report_jobs_controller.rb
app/jobs/tracking_sheet_report_job.rb
app/models/bulk_action.rb
app/views/bulk_actions/_tracking_sheet_report_job.html.erb
app/views/bulk_actions/tracking_sheet_report_jobs/_new.html.erb
app/views/bulk_actions/tracking_sheet_report_jobs/new.html.erb
app/views/bulk_actions/tracking_sheet_report_jobs/new.turbo_stream.erb
config/routes.rb
config/settings.yml
spec/jobs/tracking_sheet_report_job_spec.rb

Fixes #3416 
Updated unit test

Add Generate Tracking sheets bulk action

---

spec/features/apo_spec.rb

Because it's better than scarifying a chicken.

comment out flaky test expectation

---

app/controllers/bulk_actions/register_druid_jobs_controller.rb
app/services/registration_csv_converter.rb
app/views/bulk_actions/register_druid_jobs/_new.html.erb
spec/jobs/register_druids_job_spec.rb

Closes #3526 
Requires review/testing by @andrewjbtw 
New field list displayed:
Updated unit test.

[HOLD] Use cocina properties in bulk action -> register druids

---

app/assets/stylesheets/show.scss
app/views/catalog/show.html.erb

closes #3657
It used to be there.

Add back to search on show page.

---

app/components/spinner.html.erb
app/components/spinner.rb
app/components/techmd_component.html.erb
app/views/catalog/_cocina_default.html.erb
app/views/catalog/_events_default.html.erb

closes #3664
So user isn't left wondering.
Local

Adds spinner for lazy loading.

---

spec/factories/collections.rb

Now that DSA uses database contstraints, it is better at catching duplicates
CI

Ensure collections are using unique sourceIds

---

.circleci/config.yml
docker-compose.yml
spec/rails_helper.rb

Remove fedora from the docker environment

---

app/views/bulk_actions/open_version_jobs/_new.html.erb

closes #3667
Because it is required.

Require description for open version bulk job.

---

.rubocop.yml

Add new cop style.   No existing violations
Existing test suite

add new cop style

---

app/services/modsulator_client.rb

refs #3680
Avoid timeouts.
Stage

Increase modsulator timeout to 45 minutes.

---

app/javascript/controllers/registration_controller.js

closes #3649
Lock was causing problem for users.

Removed editing a cell warning for registration form.

---

Gemfile
Gemfile.lock

The previous branch no longer exists.

Switch to the Blacklight 7.x release branch

---

Gemfile
Gemfile.lock

Update to blacklight 7.25.2 to fix #3697
Existing tests

use latest blacklight

---

Gemfile
Gemfile.lock
app/assets/config/manifest.js

Install propshaft

---

config/initializers/blacklight.rb

Now that we use zeitwerk, we don't need this
test suite

Remove unnecessary configuration file

---

app/forms/catkey_form.rb
spec/requests/set_catkey_spec.rb

Follow on from previous catkey editing work in #3681
* add a new validation to ensure we do not end up with duplicate catkeys.
* refactor validation into separate smaller methods to make rubocop happy.
* remove `id` param from mocked test data (no longer needed)
Added a new test

do not allow duplicate catkeys

---

Gemfile
Gemfile.lock
app/controllers/items_controller.rb
app/jobs/purge_job.rb
app/services/purge_service.rb
spec/jobs/purge_job_spec.rb
spec/services/purge_service_spec.rb

Pass the username to dor-services-app when doing a purge

---

app/models/item_change_set.rb
app/services/item_change_set_persister.rb
spec/requests/item_update_spec.rb

Otherwise combining dark access with published files can trigger a validation error.
Fixes #3709
Tested on stage and added a request test.

Update access and file access simultaneously

---

solr_conf/conf/solrconfig.xml

We do not use these fields in our collection.
Test suite

Remove unused fields from solrconfig.xml

---

docker-compose.yml

We haven't used TravisCI for a long time.
local

Remove obsolete comment about TravisCI

---

config/settings/development.yml
config/settings/test.yml
docker-compose.yml
solr_conf/solr.xml

Now that we don't have contention with Fedora 3 for that port.
locally

Run Solr on it's default port (8983)

---

app/controllers/apo_controller.rb

Handle problematic data in stage without throwing an error.
See https://app.honeybadger.io/projects/49894/faults/85702827
Stage

Remove problematic collections when returning registration options.

---

app/controllers/catalog_controller.rb

Every object had the same facet value here
CI

Remove unnecessary facet Object source

---

app/controllers/catalog_controller.rb
app/models/solr_document.rb
config/locales/blacklight.en.yml

Part of sul-dlss/dor_indexing_app#846
Fixes #3721

Add facet configuration for released to searchworks/earthworks

---

app/controllers/catalog_controller.rb
app/presenters/profile_presenter.rb
app/views/profile/_document_list.html.erb
spec/features/profile_spec.rb

Remove the 'Released To' facet

---

Gemfile
Gemfile.lock

Fixes #3598
via https://github.com/sul-dlss/mods_display/issues/107
Tested on stage on https://argo-stage.stanford.edu/view/druid:bb181jh4180

Optimistically version mods_display

---

app/controllers/registrations_controller.rb
app/forms/csv_registration_form.rb
app/javascript/controllers/index.js
app/javascript/controllers/registration_tabs_controller.js
app/jobs/register_druids_job.rb
app/services/csv_upload_validator.rb
app/services/registration_csv_converter.rb
app/views/registrations/_item_row.html.erb
app/views/registrations/show.html.erb
config/routes.rb
spec/features/item_registration_csv_spec.rb
spec/fixtures/files/item_registration.csv
spec/jobs/register_druids_job_spec.rb
spec/requests/bulk_actions/import_structural_job_spec.rb
spec/services/csv_upload_validator_spec.rb
spec/services/registration_csv_converter_spec.rb

Rebase after PR #3653 is merged;  This has already been vetted by Andrew as part of vetting PR #3653, so it is ready to be merged once #3653 is merged.
CSV are easier than forms.

Registration form csv

---

app/controllers/registrations_controller.rb
app/forms/registration_form.rb
app/javascript/controllers/registration_controller.js
app/views/registrations/_item_row.html.erb
config/routes.rb
spec/features/item_registration_spec.rb
spec/requests/registration_catkey_spec.rb

Validates catkey on registration page.

---

.rubocop.yml
app/controllers/uploads_controller.rb
spec/jobs/checksum_report_job_spec.rb
spec/jobs/modsulator_job_spec.rb
spec/jobs/set_collection_job_spec.rb
spec/jobs/tracking_sheet_report_job_spec.rb
spec/requests/create_new_item_spec.rb
spec/services/admin_policy_options_spec.rb

Add new cops and let it auto-correct
Existing tests

add new cops and auto-correct

---

app/javascript/modules/project_autocomplete.js
app/javascript/modules/tags_autocomplete.js

We don't want to ship debug code to the users.

Comment out unnecessary debug

---

app/jobs/descriptive_metadata_export_job.rb
spec/jobs/descriptive_metadata_export_job_spec.rb

closes #3790
Tolerate user errors
Unit

Allow DescriptiveMetadataExportJob to handle missing druids.

---

app/jobs/descriptive_metadata_import_job.rb

This looks like copypasta that was completely off.
reading the code

Fix documentation

---

app/models/track_sheet.rb

Remove the druid prefix from tracksheet barcode

---

.circleci/config.yml

Update ruby orb to 1.4.1

---

app/views/registrations/create_status.html.erb

Add more columns to the registration output

---

app/javascript/controllers/access_rights_controller.js

Fixes #3810 
https://user-images.githubusercontent.com/2294288/180321629-9044e2b6-8a26-476a-8a86-2f1df3a36e33.mp4

Fix disable world download when Stanford view is selected

---

app/views/catalog/_show_workflows.html.erb

This will make it possible to easily test if a workflow is done from an integration test.  Will be useful the GIS integration test being written (https://github.com/sul-dlss/infrastructure-integration-test/issues/16)
Localhost

add ids to workflow detail elements to facilitate testing

---

app/controllers/catalog_controller.rb
spec/features/filter_facet_spec.rb
spec/features/home_page_spec.rb
spec/search_builders/search_builder_spec.rb

Stop differentiating between Hydrus and non-Hydrus collections

---

.rubocop_todo.yml
app/models/permitted_queries.rb
spec/models/permitted_queries_spec.rb

Exclude inactive collections from the list to transfer to

---

.rubocop.yml
config/application.rb
spec/features/date_range_form_spec.rb
spec/models/workflow_status_spec.rb
spec/services/structure_updater_spec.rb

add new rubocops and concomittant tweaks

---

app/assets/stylesheets/show.scss
app/components/show/item/structure/directory_component.html.erb
app/components/show/item/structure/directory_component.rb
app/components/show/item/structure/file_component.html.erb
app/components/show/item/structure/file_component.rb
app/components/show/item/structure/file_hierarchy_component.html.erb
app/components/show/item/structure/file_hierarchy_component.rb
app/components/show/item_component.html.erb
app/controllers/structures_controller.rb
app/services/file_hierarchy_service.rb
app/views/structures/hierarchy.html.erb
config/routes.rb
spec/features/item_view_spec.rb
spec/requests/file_hierarchy_spec.rb
spec/services/file_hierarchy_service_spec.rb

closes #3881
Hierarchy!
Local, unit

Adds file hierarchy display.

---

spec/support/selenium_webdriver.rb

Prevent deprecation on Capybara::Selenium::Driver

---

app/models/report.rb
spec/models/report_spec.rb

closes #3950
Include fields in report.
QA, unit

Fix to report to show date fields.

---

config/settings.yml

closes #3946
Unblock many tickets.
Note that I deviated from the requirements in the ticket:
* Followed the conventions for feature flags from dor-services-app. 
* Used a boolean because it is less error prone.
* Did not add to shared_configs, as this can be done when rolling out feature to each environment.

Adds folio feature flag.

---

app/jobs/set_source_ids_csv_job.rb

fix copy pasta in comment that showed up in a search on "catkeys" 

set_source_ids_csv_job: correct the comments

---

config/settings/development.yml
config/settings/test.yml
spec/features/item_catalog_record_id_change_spec.rb
spec/features/item_registration_spec.rb
spec/features/update_serials_metadata_spec.rb
spec/forms/serials_form_spec.rb
spec/jobs/refresh_mods_job_spec.rb
spec/jobs/set_catalog_record_ids_and_barcodes_csv_job_spec.rb
spec/jobs/set_catalog_record_ids_and_barcodes_job_spec.rb
spec/models/track_sheet_spec.rb
spec/requests/refresh_metadata_spec.rb
spec/requests/registration_catalog_record_id_spec.rb
spec/requests/set_catalog_record_id_spec.rb
spec/services/item_change_set_persister_spec.rb

This helps us begin testing "Folio mode."

Flip on Folio feature for test and development

---

app/controllers/structures_controller.rb
spec/requests/upload_structural_csv_spec.rb
spec/services/structure_updater_spec.rb

Set encoding when uploading structural CSV.

---

spec/services/descriptions_grouper_spec.rb

The test was incomprehensible.

Pretty and reduce JSON in DescriptionsGroup spec.

---

app/views/apo/_form.html.erb

Fixes #3992 
Looks like this now:
Localhost

increase label size to improve readability

---

app/views/apo/_form.html.erb

Follow on from #3995, ref #3992
Made both label in this DIV consistent for alignment (the important label change is the first one)
Localhost

bootstrap cols add to 12

---

app/views/apo/_form.html.erb

closes #3991
Allow for pasting hijinks.
QA

Validate catalog links when registering APO.

---

app/controllers/metadata_controller.rb
app/jobs/descmetadata_download_job.rb
app/services/dublin_core/mods2dc.xslt
app/services/dublin_core_service.rb
app/services/mods/access_conditions.rb
app/services/mods/license.rb
app/services/mods/solr_service.rb
app/services/mods/virtual_object.rb
app/services/mods_service.rb
config/licenses.yml
spec/fixtures/ex2_related_dc.xml
spec/jobs/descmetadata_download_job_spec.rb
spec/requests/view_full_dublin_core_spec.rb
spec/requests/view_mods_descriptive_metadata_spec.rb
spec/services/dublin_core_service_spec.rb
spec/services/mods_service_spec.rb
spec/support/fixtures.rb

Move MODS and DC generation locally.

---

app/jobs/republish_job.rb
spec/jobs/republish_job_spec.rb

Prevent APOs and agreements from being republished

---

bin/dev

A dev convenience that we already tend to have in other codebases.
Local
No

Auto-install foreman in bin/dev if missing

---

app/components/bulk_actions_form_component.rb

Fixes #4030 
Requires the flag introduced in #4085 
CI

Disable manage release on cutover flag

---

app/controllers/registrations_controller.rb
app/jobs/refresh_mods_job.rb
spec/features/update_serials_metadata_spec.rb

clarify comments;  avoid false matches on Symphony specific language
comments only
no

adding comments pertaining to folio cutover

---

app/components/bulk_actions_form_component.rb

Minor update to the menu text per @andrewjbtw request.
⚡ ⚠ Please ensure this change does not introduce accessibility violations (at the WCAG A or AA conformance levels); if it does, include a rationale. See the [Infrastructure accessibility guide](https://github.com/sul-dlss/DeveloperPlaybook/blob/main/best-practices/infra-accessibility.md) for more …

Update manage release menu text during folio cutover for clarity

---

Gemfile.lock

update puma gem

---

app/models/repository.rb

Remove unnecessary separate method in repository.

---

.circleci/config.yml

Add rerun failed test support for circle.

---

.rubocop/custom.yml
app/components/show/controls_component.rb
config/settings.yml
spec/components/show/controls_component_spec.rb
spec/features/bulk_desc_metadata_download_spec.rb
spec/features/bulk_release_object_spec.rb
spec/features/collection_manage_release_spec.rb
spec/features/create_collection_spec.rb
spec/features/item_manage_release_spec.rb
spec/services/csv_upload_validator_spec.rb

~~HOLD until close of biz, west coast, on Fri August 18, 2024~~
folio cutover
Andrew exercised the code in stage.
Nope.

settings.yml: set ils_cutover_in_progress to true

---

Gemfile

The Gemfile was super disorganized:
- We had groups of gems for test and development that were in more than one place.   
- We had comments for gems where it was unclear which gem the comments referred to.
CI
No.

Gemfile reorganized (but unchanged functionally)

---

app/views/registrations/show.html.erb

Fixes #4102
@andrewjbtw what do you think of this language?
Localhost

update maximum number of registered rows instructions

---

spec/components/show/controls_component_spec.rb
spec/features/bulk_release_object_spec.rb
spec/features/collection_manage_release_spec.rb
spec/features/create_collection_spec.rb
spec/features/item_manage_release_spec.rb
spec/services/csv_upload_validator_spec.rb

To make it easier to do #4124 when we get the green light for folio
specs
no new ones.

make turning on folio features easier

---

app/components/bulk_actions_form_component.rb
app/components/show/controls_component.rb
app/services/csv_upload_validator.rb
config/settings.yml
spec/features/bulk_release_object_spec.rb
spec/features/collection_manage_release_spec.rb
spec/features/create_collection_spec.rb
spec/features/item_manage_release_spec.rb
spec/services/csv_upload_validator_spec.rb

**HOLD for Andrew to confirm in qa and/or stage**
Fixes #4124 
no new ones.

Turn features back on now that folio is ready

---

.circleci/config.yml

Update to latest browser-tools orb.
Checking to see if it fixes current circleCI woes.
CI

use latest browser-tools orb

---

.rubocop_todo.yml
app/components/bulk_actions_form_component.rb
app/controllers/bulk_actions/export_cocina_json_jobs_controller.rb
app/jobs/export_cocina_json_job.rb
app/models/bulk_action.rb
app/views/bulk_actions/_export_cocina_json_job.html.erb
app/views/bulk_actions/export_cocina_json_jobs/_new.html.erb
app/views/bulk_actions/export_cocina_json_jobs/new.html.erb
app/views/bulk_actions/export_cocina_json_jobs/new.turbo_stream.erb
config/routes.rb
config/settings.yml
spec/jobs/export_cocina_json_job_spec.rb
spec/requests/show_list_bulk_actions_spec.rb

Resolves #3847. Download Cocina JSON
Unit, tested on QA. Checking with @andrewjbtw about whether he would like to test that. 
No

Export full Cocina json

---

Gemfile
Gemfile.lock
app/controllers/files_controller.rb
spec/requests/item_files_download_spec.rb

refs #4133
Unit, @andrewjbtw test object in stage

Fixes download all.

---

app/controllers/report_controller.rb
app/models/report.rb

Add comments to report model and controller

---

app/javascript/controllers/object_reporter.js
app/models/report.rb

Link to druids and purls in reports view

---

app/models/report.rb
spec/models/report_spec.rb

Add new fields to report view

---

Gemfile
Gemfile.lock
app/components/contents/structural_component.html.erb
app/components/contents/structural_component.rb
app/components/contents_component.html.erb
app/components/contents_component.rb
app/controllers/catalog_controller.rb
app/controllers/workflow_service_controller.rb
app/models/repository.rb
spec/features/add_workflow_to_item_spec.rb
spec/features/collection_manage_release_spec.rb
spec/features/enable_buttons_spec.rb
spec/features/item_catalog_record_id_change_spec.rb
spec/features/item_manage_release_spec.rb
spec/features/item_registration_spec.rb
spec/features/item_source_id_change_spec.rb
spec/features/item_view_spec.rb
spec/requests/workflow_service_spec.rb

Use GraphQL endpoint for retrieving lite cocina objects

---

app/controllers/concerns/date_facet_configurations.rb
app/models/solr_document.rb
spec/models/solr_document_spec.rb

Fixes #4185 - remove last submitted and last ingested facets
- Localhost
- CI
- QA

remove last submitted and last ingested facets

---

app/controllers/apo_controller.rb
app/models/permitted_queries.rb
app/services/admin_policy_options.rb
spec/services/admin_policy_options_spec.rb

Sort collection and APOs lists case-insensitively by title

---

db/seeds.rb

We encountered this error when resetting Argo in QA. We should probably not try to reset Solr, etc. in prod-like envs?

Skip DB seeding in production env

---

app/models/ability.rb
spec/models/ability_spec.rb

closes #4195
Fix permissions problems for some users.

Add lite cocina models to cancan ability.

---

README.md

Fix reset instructions

---

README.md

Adds solr config into to README

---

app/views/layouts/blacklight/base.html.erb
config/settings.yml

Adds google analytics

---

app/javascript/controllers/object_reporter.js
app/views/report/_document_list.html.erb

closes #4226
Per ticket.
Stage, prod

Switch to direct report download.

---

solr_conf/conf/schema.xml
solr_conf/conf/solrconfig.xml

~~Draft until I shake out problems in qa~~
for solr in container to match sul-dlss/sul-solr-configs/pull/279
locally and deployed to qa

update solr config files to match production

---

.circleci/config.yml
docker/Dockerfile-solr

Build solr image in circleci

---

app/services/structure_serializer.rb
app/services/structure_updater.rb
spec/components/contents/file_component_spec.rb
spec/services/structure_serializer_spec.rb
spec/services/structure_updater_spec.rb

Tested by Andrew in stage and confirmed working as intended.
Fixes #4258

Add file language to upload/download spreadsheets

---

README.md

Add yarn install to tldr

---

app/services/catalog_record_id.rb
spec/services/catalog_record_id_spec.rb

closes #4289
Keeping symphony links is causing mayhem in access systems.
Unit

Remove symphony links.

---

Gemfile
Gemfile.lock

Upgrade view component.

---

solr_conf/conf/solrconfig.xml

To align the solr in this repo with the configurations in our Solr Cloud.
It wasn't, but the sul-solr-config changes were tested in prod.

update solrconfig.xml to match sul-solr-configs

---

config/settings.yml

Remove unused settings.

---

Gemfile
Gemfile.lock
config/initializers/rack_profiler.rb
config/initializers/ruby_prof.rb
config/settings.yml
config/settings/development.yml

Remove profiling tools.

---

Gemfile
Gemfile.lock

Upgrade workflow client to 7.0

---

app/services/csv_upload_validator.rb
app/services/registration_csv_converter.rb
spec/services/csv_upload_validator_spec.rb
spec/services/registration_csv_converter_spec.rb

Fixes #4316
Wrote a test and it failed without the fix, and passes with the fix.
Also, deployed to stage and Andrew exercised it and signed off.

csv registration ignores blank lines at end

---

.rubocop.yml
spec/jobs/descmetadata_download_job_spec.rb
spec/jobs/modsulator_job_spec.rb

Multiple choice:
a. it seems a good time to bring argo up to date with cops.
b. it's daunting to add large numbers of cops at once; this was a nice small list
c. conforming to standards reduces cognitive load
d. every week is an unscheduled week when your retirement looms
e. OCD
f. _________________
CI

add new rubocops and make corrections as needed

---

app/helpers/blacklight_config_helper.rb

Preparing to add information about integration testing and it seemed prudent to first add info about the module itself.
CI

blacklight_config_helper gets comments

---

README.md
app/controllers/registrations_controller.rb
app/javascript/controllers/registration_item_row_controller.js
app/javascript/controllers/registration_tabs_controller.js
app/views/registrations/show.html.erb
spec/factories/apos.rb
spec/features/item_registration_csv_spec.rb

Fixes #4323
- Prefer "docker compose" to docker-compose to be more modern
- Fix bug that wipes out existing form values with invalid CSV uploads
TODO

Fix bug that wipes out existing form values with invalid CSV uploads

---

app/controllers/catalog_controller.rb
app/controllers/descriptives_controller.rb
app/helpers/apo_helper.rb
app/helpers/blacklight_config_helper.rb
app/models/permitted_queries.rb
app/models/solr_document.rb
app/services/collection_name_service.rb
app/services/mods/virtual_object.rb
app/views/bulk_jobs/index.html.erb
solr_conf/conf/schema.xml
solr_conf/conf/solrconfig.xml
spec/features/item_view_spec.rb
spec/features/report_view_spec.rb
spec/features/search_results_spec.rb
spec/models/permitted_queries_spec.rb
spec/models/report_spec.rb
spec/models/track_sheet_spec.rb
spec/requests/bulk_actions/governing_apo_job_spec.rb
spec/requests/registration_spec.rb
spec/services/admin_policy_options_spec.rb
spec/services/mods_service_spec.rb
spec/support/reset_solr.rb

~~Hold for PO review~~   Andrew has signed off on this as of 2024-03-08
To improve relevancy rankings in search results.  This uses the new Solr title fields.
part of sul-dlss/dor_indexing_app/issues/1075
integration tests, Andrew.

Solr title field chgs

---

app/models/permitted_queries.rb
app/services/admin_policy_options.rb
spec/services/admin_policy_options_spec.rb

closes #4351
Correct sorting in dropdown.
Stage, Andrew

Fix sorting of collection and APO lists.

---

app/presenters/milestones_presenter.rb
spec/presenters/milestones_presenter_spec.rb

Fixes https://github.com/sul-dlss/argo/pull/4366

Stop displaying version tag on item view page

---

app/controllers/versions_controller.rb
app/views/versions/_close_ui.html.erb
app/views/versions/_open_ui.html.erb
spec/features/open_and_close_a_version_spec.rb
spec/requests/close_version_spec.rb
spec/requests/open_version_spec.rb
spec/views/versions/_close_ui.html.erb_spec.rb
spec/views/versions/_open_ui.html.erb_spec.rb

Fixes https://github.com/sul-dlss/argo/issues/4363
Fixes https://github.com/sul-dlss/argo/issues/4364

Remove the version significance selector from open/close

---

app/controllers/bulk_actions/open_version_jobs_controller.rb
app/jobs/open_version_job.rb
app/views/bulk_actions/open_version_jobs/_new.html.erb
spec/jobs/open_version_job_spec.rb

Fixes https://github.com/sul-dlss/argo/issues/4365

Remove Change Type from Open New Object Versions bulk action form

---

app/jobs/release_object_job.rb
spec/jobs/release_object_job_spec.rb

Fixes #4350 
Updated unit tests

Use the ReleaseTags API in ReleaseObjectJob

---

app/controllers/catalog_controller.rb
app/views/catalog/_history_default.html.erb
spec/features/add_workflow_to_item_spec.rb
spec/features/collection_manage_release_spec.rb
spec/features/enable_buttons_spec.rb
spec/features/item_catalog_record_id_change_spec.rb
spec/features/item_manage_release_spec.rb
spec/features/item_source_id_change_spec.rb
spec/features/item_view_spec.rb

Use dor-services-app API to retrieve release tags for show page

---

Gemfile
Gemfile.lock
app/controllers/versions_controller.rb
app/jobs/close_version_job.rb
app/jobs/descriptive_metadata_import_job.rb
app/jobs/generic_job.rb
app/jobs/open_version_job.rb
app/services/apply_mods_metadata.rb
app/services/version_service.rb
spec/jobs/descriptive_metadata_import_job_spec.rb
spec/jobs/open_version_job_spec.rb
spec/services/apply_mods_metadata_spec.rb
spec/services/version_service_spec.rb

First step in normalizing versioning in Argo.
Unit

Enhance version service

---

app/components/download_all_button_component.rb
app/controllers/files_controller.rb
app/services/state_service.rb
app/services/workflow_service.rb
spec/components/download_all_button_component_spec.rb
spec/features/enable_buttons_spec.rb
spec/features/item_catalog_record_id_change_spec.rb
spec/features/item_manage_release_spec.rb
spec/features/item_source_id_change_spec.rb
spec/features/set_governing_apo_spec.rb
spec/services/state_service_spec.rb
spec/services/workflow_service_spec.rb

The workflow service should answer workflow questions.

[REFACTOR] Move accessioned? from state service to workflow service

---

app/controllers/workflow_service_controller.rb
app/services/state_service.rb
spec/features/enable_buttons_spec.rb
spec/requests/workflow_service_spec.rb
spec/services/state_service_spec.rb

It's already handled by the WorkflowService.
Unit

[REFACTOR] Move published

---

spec/features/indexing_identifiers_spec.rb
spec/features/indexing_tag_facets_spec.rb
spec/features/indexing_tags_spec.rb
spec/features/indexing_titles_spec.rb

closes #4380
These tests are consistently flaky and block Argo work.

Skip flaky tests on CI.

---

app/forms/collection_form.rb

closes #4385
Normalize versioning.
QA, Andrew.

Changes collection form to close version.

---

app/services/state_service.rb
spec/features/open_and_close_a_version_spec.rb
spec/services/state_service_spec.rb

closes #4394
Versioning normalization
Unit, Andrew, integration tests

Changes state service to use version service.

---

app/services/apply_mods_metadata.rb
spec/services/apply_mods_metadata_spec.rb

Resolves #4403.
Unit. And passes integration tests for bulk_metadata_update. Andrew did some testing, but there is an HB error to investigate: https://app.honeybadger.io/projects/50568/faults/106837203 and which should be resolved with https://github.com/sul-dlss/dor-services-app/pull/4863.

Use VersionService in ApplyModsMetadata

---

app/components/manage_release/form_component.html.erb
app/forms/apo_form.rb
app/models/concerns/apo_concern.rb
app/models/report.rb
app/models/solr_document.rb
app/models/track_sheet.rb
app/presenters/citation_presenter.rb
app/views/apo/_form.html.erb
app/views/bulk_jobs/index.html.erb
spec/forms/apo_form_spec.rb
spec/jobs/tracking_sheet_report_job_spec.rb
spec/models/solr_document_spec.rb
spec/models/track_sheet_spec.rb
spec/requests/manage_release_spec.rb

Fix tracking-sheets to use string based title field

---

app/models/track_sheet.rb

I suspect this code isn't called. Let's do an experiment to see.

Add an experiment for dead code

---

app/controllers/catalog_controller.rb
app/models/solr_document.rb
config/locales/blacklight.en.yml

Fixes #4415.
Unit and deployed to stage. Andrew tested and approved.

[HOLD] Add Released to PURL Sitemap facet

---

.circleci/config.yml
docker-compose.yml

Fix docker-compose.

---

app/controllers/files_controller.rb
app/helpers/items_helper.rb
config/routes.rb
spec/helpers/items_helper_spec.rb
spec/requests/files_spec.rb
spec/routing/files_spec.rb
spec/views/files/index.html.erb_spec.rb

Fix stacks and preservation links to filenames with hierarchy

---

app/models/track_sheet.rb

Experiment to find dead code found it wasn't dead: https://app.honeybadger.io/projects/49894/faults/107765668

Remove notification

---

.rubocop.yml

make the yellow go away for another week.

Add new rubocops

---

Dockerfile

This fixes the build and testing related to openapi.

Upate dockerfile to debian base for openapi support

---

app/views/workflows/_show.html.erb
spec/requests/workflows_spec.rb

closes #4456 
Viewing on Argo QA.

update context workflow to display as table

---

Gemfile.lock

A quick dependency update to pick up the latest dor-services-client

Update dor-services-client and other gems

---

app/services/structure_serializer.rb
app/services/structure_updater.rb
spec/services/structure_serializer_spec.rb
spec/services/structure_updater_spec.rb

Fixes #4473 - add new OCR cocina attributes to structural CSV download and upload
~~HOLD for test on QA~~
CI and argo QA

add sdrGeneratedText and correctedForAccessibility to structural csv

---

config/settings.yml

OCR isn't ready for production yet.

No OCR in prod

---

.circleci/config.yml
.rubocop.yml
README.md

Keep pace with Ruby upgrades
CI

Bump Ruby version to 3.3.1

---

Gemfile
Gemfile.lock
app/components/document_title_component.html.erb
app/components/version_milestones_component.html.erb
app/components/version_milestones_component.rb
app/controllers/catalog_controller.rb
app/helpers/items_helper.rb
app/presenters/argo_show_presenter.rb
app/presenters/milestones_presenter.rb
app/views/catalog/_show_milestones.html.erb
config/routes.rb
spec/components/document_title_component_spec.rb
spec/components/version_milestones_component_spec.rb
spec/features/version_view_spec.rb
spec/presenters/milestones_presenter_spec.rb

closes #4491
Support additional work on version detail page.
Unit, QA

Stub out initial user version detail page.

---

app/controllers/catalog_controller.rb
app/presenters/milestones_presenter.rb
spec/presenters/milestones_presenter_spec.rb

Move some initialization from CatalogController to MilestonesPresenter.

---

app/controllers/catalog_controller.rb
app/controllers/cocina_objects_controller.rb
app/controllers/events_controller.rb
app/controllers/structures_controller.rb
app/controllers/technicals_controller.rb
app/models/repository.rb
spec/requests/cocina_objects_spec.rb
spec/requests/events_spec.rb
spec/requests/file_hierarchy_spec.rb
spec/requests/structure_spec.rb
spec/requests/technicals_spec.rb

Display user version cocina in cocina model collapse.

---

app/components/contents_component.html.erb
app/components/contents_component.rb
spec/components/contents_component_spec.rb

Hide upload and download structural CSV when user version.

---

app/components/contents_component.html.erb
app/components/download_all_button_component.html.erb
app/components/download_all_button_component.rb
app/controllers/files_controller.rb
config/routes.rb
spec/components/download_all_button_component_spec.rb
spec/requests/item_files_download_spec.rb

Support downloading all files for user versions.

---

app/components/show/admin_policy_component.html.erb
app/components/show/agreement_component.html.erb
app/components/show/collection_component.html.erb
app/components/show/external_links_component.rb
app/components/show/item_component.html.erb
app/controllers/user_versions_controller.rb
config/application.rb
config/routes.rb
spec/components/show/external_links_component_spec.rb
spec/requests/view_cocina_model_for_user_version_spec.rb

Show cocina for version from cocina models button.

---

app/components/contents_component.html.erb
app/components/contents_component.rb
app/controllers/structures_controller.rb
config/routes.rb
spec/components/contents_component_spec.rb
spec/requests/structure_spec.rb

Update structural display for user_versions

---

app/components/version_milestones_component.html.erb
spec/components/version_milestones_component_spec.rb

Remove collapsible lifecycle events in item UI

---

app/components/document_title_component.html.erb
app/components/document_title_component.rb
app/controllers/catalog_controller.rb
app/helpers/items_helper.rb
app/presenters/argo_show_presenter.rb
app/presenters/milestones_presenter.rb
spec/components/document_title_component_spec.rb
spec/features/version_view_spec.rb
spec/presenters/milestones_presenter_spec.rb

Show user version banner.

---

app/forms/registration_form.rb
spec/features/item_registration_spec.rb

Resolves #4488 to provide info about the item which was unable to be registered. 
Unit and deploy to stage; selected integration tests. 
@andrewjbtw this can be available to test on stage if you'd like to do so. This PR displays an error with the HRID but does not highlight the section of the form involved. That could be ticketed as a future step--it was seeming complicated since it's not a form validation error.

[HOLD] Show IDs in registration error

---

Gemfile
Gemfile.lock

Updated dor services client

---

app/assets/stylesheets/show.scss
app/components/show/item/thumbnail_component.html.erb

Update file thumbnail.

---

app/assets/stylesheets/document-component.scss
app/assets/stylesheets/variables.scss

Stop using sass variables for accordion styles

---

app/assets/stylesheets/icons.scss

It would be nice to not need sass.

Set icon color without sass

---

app/assets/stylesheets/show.scss
app/components/show/external_links_component.rb

Style external links using the component library

---

app/javascript/controllers/tag_validation_controller.js

Rename method to be accurate about what it is doing

---

app/assets/stylesheets/variables.scss

Remove unused colors

---

app/views/layouts/blacklight/base.html.erb

Update bootstrap icons to latest version

---

app/components/bulk_actions_form_component.html.erb
app/views/bulk_actions/_common_fields.html.erb

Moves back button on new bulk action page.

---

Gemfile
Gemfile.lock

Green is a nicer color than red.

Upgrade dor-services-client.

---

app/components/constraint_component.rb
app/components/constraint_layout_component.html.erb
app/components/constraint_layout_component.rb
app/views/catalog/_constraints.html.erb

Use component library selected item for selected filters.

---

app/components/workflow_table_process_component.rb

Reset link should be blue

---

app/jobs/descriptive_metadata_export_job.rb
spec/jobs/descriptive_metadata_export_job_spec.rb

Log an error when APO included in descriptive MD export bulk action

---

app/javascript/controllers/bulk_upload_jobs_controller.js
app/views/bulk_actions/index.html.erb

Make Delete buttons blue instead of red

---

app/assets/stylesheets/show.css

style the open close button

---

app/components/show/external_links_component.rb
app/presenters/argo_show_presenter.rb
spec/components/show/external_links_component_spec.rb

PURLs are versioned when on older user version

---

app/components/contents/file_component.html.erb
app/components/contents/file_component.rb
app/components/contents/preservation_link_component.html.erb
app/components/contents/preservation_link_component.rb
app/components/contents/resource_component.html.erb
app/components/contents/resource_component.rb
app/components/contents/stacks_link_component.html.erb
app/components/contents/stacks_link_component.rb
app/components/contents/structural_component.html.erb
app/components/contents/structural_component.rb
app/controllers/files_controller.rb
app/controllers/structures_controller.rb
app/helpers/items_helper.rb
app/views/files/index.html.erb
app/views/structures/show.html.erb
config/settings.yml
spec/components/contents/file_component_spec.rb
spec/components/contents/preservation_link_component_spec.rb
spec/components/contents/resource_component_spec.rb
spec/components/contents/stacks_link_component_spec.rb
spec/views/files/index.html.erb_spec.rb

closes #4522
Allow users to get files for previous versions.
Unit, Andrew

Make file links specific to version.

---

app/components/contents/preservation_link_component.rb
app/controllers/files_controller.rb
app/views/files/index.html.erb
spec/components/contents/preservation_link_component_spec.rb

@lwrubel pointed out a logic error that prompted a refactoring.
Unit

Refactor file controller index.

---

app/components/document_title_component.rb

I hit merge before pushing a tweak in response to a suggestion. 
Unit

version banner tweak

---

Gemfile.lock
yarn.lock

Upgrade blacklight-hierarchy to 6.4.0

---

app/jobs/descriptive_metadata_import_job.rb
spec/jobs/descriptive_metadata_import_job_spec.rb

Fixes #4623 
@andrewjbtw has tested in stage

Do not close version 1 objects on bulk updates

---

app/jobs/republish_job.rb
spec/jobs/republish_job_spec.rb

closes #4638
Per @andrewjbtw, see ticket.
Unit

Changes publishing to use low queue.

---

app/components/contents/file_component.rb
app/components/contents_component.rb
app/components/download_all_button_component.rb
app/components/show/controls_component.rb
app/components/show/external_links_component.rb
app/components/version_milestones_component.rb
app/controllers/user_versions_controller.rb
app/views/versions/_close_ui.html.erb
app/views/versions/_open_ui.html.erb
app/views/workflow_service/lock.html.erb
app/views/workflow_service/unlock.html.erb
config/routes.rb
spec/components/contents/file_component_spec.rb
spec/components/download_all_button_component_spec.rb
spec/components/show/controls_component_spec.rb
spec/components/show/external_links_component_spec.rb
spec/components/version_milestones_component_spec.rb
spec/features/apo_displays_spec.rb
spec/features/user_version_view_spec.rb
spec/requests/close_version_spec.rb
spec/requests/download_descriptive_csv_spec.rb
spec/requests/item_files_download_spec.rb
spec/requests/open_version_spec.rb
spec/requests/structure_spec.rb
spec/requests/view_cocina_model_for_user_version_spec.rb
spec/requests/view_mods_descriptive_metadata_spec.rb

closes #4636
Per @andrewjbtw 
unit, QA

Rename versions and user_versions routes

---

app/components/top_navbar_component.html.erb

Aligns with https://github.com/sul-dlss/component-library/pull/34

Reduce header vertical margin slightly

---

app/views/layouts/blacklight/base.html.erb
app/views/shared/_footer.html.erb

Update component library

---

.circleci/config.yml
compose.yaml

Change env var for DSA (for local dev & CI)

---

Gemfile.lock
app/controllers/bulk_actions/descriptive_metadata_import_jobs_controller.rb
app/controllers/bulk_actions/validate_cocina_descriptive_jobs_controller.rb
app/controllers/descriptives_controller.rb
app/services/csv_upload_normalizer.rb
spec/fixtures/files/catalog_record_id_and_barcode_extra_columns.csv
spec/fixtures/files/catalog_record_id_and_barcode_preamble.csv
spec/services/csv_upload_normalizer_spec.rb

Account for normal user practices.
Unit, Andrew

Additional normalization of descriptive CSV uploads.

---

app/components/top_navbar_component.html.erb

Updating the mobile menu to match component library
Locally

move mobile menu under title, switch order

---

app/views/report/_document_list.html.erb

Escape search params JSON in report view

---

app/components/top_navbar_component.html.erb

Fix color contrast issues in top nav area

---

.circleci/config.yml

Bump orb versions in CI config

---

app/controllers/catalog_controller.rb

closes #4705
To make the sorting more determinate.
Andrew

[HOLD] Add secondary sort to relevance.

---

.circleci/config.yml
.codecov.yml
Gemfile
README.md
spec/spec_helper.rb

CodeClimate has gotten flaky.
CI

Switch from CodeClimate to CodeCov for test coverage

---

.circleci/config.yml
Gemfile
Gemfile.lock
spec/support/capybara.rb

To gather more information when system tests fail.
CI

Take screenshots when system specs fail

---

app/services/description_validator.rb
spec/services/description_validator_spec.rb

Fixes #4711.
Andrew tested and confirmed the problem is not occurring anymore.

Provide descriptive invalid header error

---

.codecov.yml
app/controllers/application_controller.rb
app/jobs/set_catalog_record_ids_and_barcodes_csv_job.rb
app/jobs/set_catalog_record_ids_and_barcodes_job.rb
app/jobs/tracking_sheet_report_job.rb
app/models/track_sheet.rb

Remove misleading usage of `protected` keyword

---

app/components/show/controls_component.html.erb
spec/components/show/controls_component_spec.rb

Disable serials link when item is not open.

---

Dockerfile
Gemfile
Gemfile.lock
compose.yaml
db/migrate/20160318203331_increase_delayed_job_column.rb
docker/entrypoint.sh

Finish the migration away from MySQL/MariaDB
CI, ran container & checked localhost locally

Switch containerland over to Postgres and drop MySQL from the deps

---

app/controllers/serials_controller.rb
app/forms/serials_form.rb
app/views/serials/_edit.html.erb
app/views/serials/_form.html.erb
app/views/serials/edit.html.erb
spec/forms/serials_form_spec.rb
spec/requests/serials_spec.rb

Validate that part label is present if sort key is present in serials form

---

README.md
app/controllers/bulk_actions/catalog_record_id_and_barcode_csv_jobs_controller.rb
app/jobs/generic_job.rb
app/jobs/set_catalog_record_ids_and_barcodes_csv_job.rb
app/models/item_change_set.rb
app/services/catalog_record_id.rb
app/services/item_change_set_persister.rb
app/views/bulk_actions/catalog_record_id_and_barcode_csv_jobs/_new.html.erb
spec/jobs/set_catalog_record_ids_and_barcodes_csv_job_spec.rb

HOLD this PR until:
Fixes #4747
Includes:
- **Remove manual foreman installation from README**
- **Add part label and sort key to catalog links CSV job**

 Add part label and sort key to catalog links CSV job

---

app/components/bulk_actions_form_component.rb
spec/system/bulk_content_type_spec.rb
spec/system/bulk_desc_metadata_download_spec.rb

On hold till Tuesday, 5/13.
Fixes #4749
These changes make the organization and function of the bulk actions easier to make sense of for our users.

Re-order and rename bulk actions

---

app/forms/serials_form.rb
app/jobs/set_catalog_record_ids_and_barcodes_csv_job.rb
spec/forms/serials_form_spec.rb

Strip whitespace in serials forms or catalog links uploads

---

app/services/description_import.rb
spec/services/description_import_spec.rb

Allow form.structuredValue in descriptive import

---

app/jobs/descriptive_metadata_export_job.rb
spec/jobs/descriptive_metadata_export_job_spec.rb

Do not retry download desc MD job if missing or malformed druid

---

Gemfile
Gemfile.lock
app/components/workflow_process_row.rb
app/components/workflow_step_status_selector.rb
app/components/workflow_update_button.rb
app/models/workflow_status.rb
spec/components/workflow_process_row_spec.rb
spec/components/workflow_step_status_selector_spec.rb
spec/components/workflow_update_button_spec.rb
spec/models/workflow_status_spec.rb
spec/presenters/workflow_presenter_spec.rb
spec/requests/files_spec.rb
spec/requests/purge_object_spec.rb
spec/requests/update_an_existing_admin_policy_spec.rb
spec/requests/workflows_spec.rb
spec/services/apply_mods_metadata_spec.rb
spec/system/apo_displays_spec.rb
spec/system/bulk_jobs_spec.rb
spec/system/item_catalog_record_id_change_spec.rb
spec/system/item_source_id_change_spec.rb
spec/views/workflows/_show.html.erb_spec.rb

Remove dor-workflow-client.

---

.circleci/config.yml
README.md
compose.yaml

Workflow server is deprecated.
Local, circle

Remove workflow container from compse and circle.

---

app/controllers/agreements_controller.rb
app/forms/agreement_form.rb
app/forms/application_form.rb
app/services/register_agreement.rb

refs #4848
We don't like Reform.
Unit

Replace agreement form with active model form.
