sul-dlss/argo

.circleci/config.yml

Shaves about a minute of the build time because the caches actually work

Update to the latest ruby orb

---

app/forms/apo_form.rb
spec/forms/apo_form_spec.rb

fixes #2601
This allows us to decouple from Fedora 3

Decouple from the license services that are part of dor-services

---

app/helpers/blacklight_config_helper.rb

So that non-cocina compliant objects can still be found when you search their identifier.
Fixes #2614

Search the id field

---

app/controllers/registrations_controller.rb
app/helpers/apo_helper.rb
app/helpers/registration_helper.rb
app/models/track_sheet.rb
app/models/user.rb
app/services/search_service.rb
lib/tasks/argo.rake
spec/controllers/registrations_controller_spec.rb
spec/helpers/registration_helper_spec.rb
spec/models/track_sheet_spec.rb
spec/models/user_spec.rb

So we can decouple from dor-services
Fixes #2600

Import the Dor::SearchService from dor-services

---

app/views/apo/_form.html.erb

The only elements in HTML that are void elements are:
area, base, br, col, command, embed, hr, img, input, keygen, link, meta, param, source, track, wbr
A non-void element must have a closing tag.
http://www.w3.org/TR/html-markup/syntax.html#syntax-elements

Insert a missing closing tag

---

app/controllers/content_types_controller.rb
app/helpers/registration_helper.rb
app/views/content_types/_content_type.html.erb
lib/constants.rb
spec/controllers/content_types_controller_spec.rb
spec/features/item_registration_spec.rb
spec/helpers/registration_helper_spec.rb
spec/support/cocina_matchers.rb

~~NOTE: If would best to review, merge and deploy sul-dlss/dor-services-app#2605 first, though if done out of order, this would just result in a `<bookData>` node being left behind in contentMetada if you switched from a book type to a non book type.~~ <-- merged
Fixes #2534 - allow book type content type updates to set reading direction like they do at registration
Note: with this PR the reading direction will be set/removed correctly in the cocina model, but it does not get removed from contentMetadata if you change from a book type to a non-book type.  As noted above, this problem is fixed in sul-dlss/dor-services-app#2605, in the part of the code that translates the cocina model data back into contentMetadata.
Updated tests and verified on argo-qa

allow book reading direction to be set with content type updates

---

docker-compose.yml

* Bump dependencies and fix `Dockerfile` regarding mimemagic
* Without these changes, I could not bring up the `web` container
* Make DSA container create the UR-APO and add a role to the web container
* This role grants the logged in user (via `ROLES` env var) permission to use any created APOs when registering items.
Both of these changes are included to make it easier to create fixture data.
CI, locally
docker-compose

Reduce drag when working locally in development

---

app/controllers/datastreams_controller.rb
app/presenters/workflow_xml_presenter.rb
app/services/pretty_xml.rb
app/views/workflows/_history.html.erb

This previously was a monkey-patch on Nokogiri::XML.  This helps us decouple from dor-services

Import xml prettify from dor-services

---

config/routes.rb

To avoid a deprecation warning

Remove Sidekiq session_secret it is obsolete

---

.circleci/config.yml
.rubocop.yml
Gemfile
Gemfile.lock
app/controllers/apo_controller.rb
app/forms/apo_form.rb
app/helpers/apo_helper.rb
app/javascript/modules/apo_form.js
app/javascript/modules/permission_grant.js
app/models/admin_policy_change_set.rb
app/services/admin_policy_change_set_persister.rb
app/views/apo/_form.html.erb
app/views/apo/edit.html.erb
app/views/apo/new.html.erb
docker-compose.yml
lib/constants.rb
spec/controllers/apo_controller_spec.rb
spec/factories/collections.rb
spec/features/apo_displays_spec.rb
spec/features/apo_spec.rb
spec/forms/apo_form_spec.rb
spec/requests/create_new_admin_policy_spec.rb
spec/requests/update_an_existing_admin_policy_spec.rb
spec/services/admin_policy_change_set_persister_spec.rb
spec/support/collection_method_sender.rb

*NOTE* this requires the `update_descriptive` feature flag to be set to "true" in dor-services-app.
Hold for testing on stage with @andrewjbtw 
Fixes #2420
Fixes #2622
Fixes #2621
Fixes #2379 
Fixes #2628
Fixes #2630
Ref #2418

Decouple APO form from Fedora 3

---

app/forms/collection_form.rb
spec/forms/collection_form_spec.rb

Previously there would be an error if the collection title or catkey were both left blank

Provide validations for the CollectionForm

---

app/controllers/collections_controller.rb
spec/controllers/collections_controller_spec.rb

Fixes: https://app.honeybadger.io/projects/49894/faults/78684696

Remove escaped space from solr query

---

.circleci/config.yml
spec/factories/apos.rb
spec/factories/items.rb

of the AdminPolicy
See https://github.com/sul-dlss/dor-services-app/pull/2616
Decoupling from fedora 3 and dor-services gem

Update factories to leverage dor-services-app bootstrapping

---

app/components/blacklight_modal_component.rb
app/views/bulk_jobs/_bulk_index_table.html.erb
app/views/bulk_jobs/status_help.html.erb
app/views/catalog/facet.html.erb
app/views/content_types/show.html.erb
app/views/datastreams/edit.html.erb
app/views/datastreams/show.html.erb
app/views/files/index.html.erb
app/views/items/catkey_ui.html.erb
app/views/items/collection_ui.html.erb
app/views/items/embargo_form.html.erb
app/views/items/file.html.erb
app/views/items/rights.html.erb
app/views/items/set_governing_apo_ui.html.erb
app/views/items/source_id_ui.html.erb
app/views/manage_releases/show.html.erb
app/views/metadata/descriptive.html.erb
app/views/metadata/full_dc.html.erb
app/views/tags/edit.html.erb
app/views/versions/close_ui.html.erb
app/views/versions/open_ui.html.erb
app/views/workflows/history.html.erb
app/views/workflows/new.html.erb
app/views/workflows/show.html.erb
spec/components/blacklight_modal_component_spec.rb

Avoids some of these warnings:
```
Use slots (https://viewcomponent.org/guide/slots.html) instead. (called from _app_views_catalog__search_sidebar_html_erb___1760964059338821852_371500 at /home/circleci/project/app/views/catalog/_search_sidebar.html.erb:1)
DEPRECATION WARNING:  is deprecated and will be removed in ViewComponent v3.0.0.
```

Use slots instead of deprecated content areas

---

spec/controllers/report_controller_spec.rb
spec/factories/apos.rb
spec/factories/collections.rb
spec/factories/items.rb
spec/features/item_registration_spec.rb
spec/features/set_governing_apo_spec.rb
spec/support/reset_solr.rb

This also bootstraps the UR-APO, so that it's never missing.  dor-services-app depends on it finding the APO in solr.

Create a test support method for clearing out solr

---

Gemfile
Gemfile.lock

Drop unused responders dependency

---

.rubocop.yml
app/controllers/collections_controller.rb
app/forms/access_form.rb
app/services/cocina_access.rb
app/services/cocina_dro_access.rb
spec/presenters/buttons_presenter_spec.rb
spec/views/files/index.html.erb_spec.rb

now that dor-services gem is no longer used directly
ran grep to find leftovers from the dor-services gem removal (this was the dor-services cruft i found yesterday and mentioned at standup this morning)
```
argo % git grep 'Dor::' | grep -v 'Dor::Services::Client' | grep -v 'Dor::Workflow'                   main
app/controllers/collections_controller.rb:    # The following two steps mimic the behavior of `Dor::AdministrativeMetadataDS#add_default_collection`
app/controllers/dor/objects_controller.rb:class Dor::ObjectsController < ApplicationController
app/forms/access_form.rb:  # @option params [String] :rights the rights representation from the form (must be one of the keys in Dor::RightsMetadataDS::RIGHTS_TYPE_CODES, or 'default')
app/services/cocina_access.rb:  # @param [String] the …
```

clarify comments and remove unused let vars

---

.circleci/config.yml

Speedier CI means less waiting
CI
CI

Speed up CI build by doing more in parallel

---

README.md

This makes it easier to begin registering items and using the Argo UI. Thanks to @jcoyne for the tips.
I tested the steps locally.
README

Document quick fixture creation in README

---

app/forms/apo_form.rb
spec/forms/apo_form_spec.rb

quick touchup to make sort for default collection list case insensitive, per discussion with @andrewjbtw on slack this morning (re: #2659).
unit tests and local dev instance.  happy to test on -stage or -qa also, if that's desired.
n/a

Edit APO: sort default collections case insensitively

---

app/controllers/catalog_controller.rb

fixes #2645 - remove pids_only param when linking back to search results from a bulk action
Localhost browser and qa

remove pids_only param from search context when returning to search view

---

app/components/external_links_component.html.erb
app/components/external_links_component.rb
app/controllers/items_controller.rb
config/routes.rb
spec/components/external_links_component_spec.rb
spec/requests/view_cocina_model_spec.rb

closes #2618
Make it easier to view full JSON for cocina object.
Unit, qa
NA

Adds display of full JSON for cocina.

---

app/components/external_links_component.rb
app/controllers/items_controller.rb
config/routes.rb
spec/components/external_links_component_spec.rb
spec/requests/view_cocina_model_spec.rb

This is the idiomatic way to show the data for an object in a Rails app

Use the show action for the cocina model

---

app/controllers/items_controller.rb
app/models/item_change_set.rb
app/services/item_change_set_persister.rb
spec/controllers/items_controller_spec.rb
spec/services/item_change_set_persister_spec.rb

The update API is now mature enough where we can replace and retire the embargo update API.

Refactor: Set an embargo using the update API

---

config/initializers/cookies_serializer.rb

The hybrid serializer will upgrade any existing marshal cookies to JSON cookies

Upgrade cookies to use JSON serialization

---

Gemfile
Gemfile.lock
app/javascript/argo.js
app/javascript/blacklight_hierarchy.js
app/javascript/packs/application.js
package.json
yarn.lock

This went missing in the Blacklight 7 upgrade.
Before
After

Restore missing remove icon on the tags facet

---

app/controllers/content_types_controller.rb
spec/controllers/content_types_controller_spec.rb
spec/support/cocina_matchers.rb

Don't set hasMemberOrder for non-book types.

---

app/models/ability.rb
spec/models/ability_spec.rb

Fixes #2688
In #2486, we lost the ability to authorize a user to view metadata (i.e., hit the show page) of a (Cocina) APO. This PR restores that and only that ability, and adds tests showing no additional abilities have been conferred to such users.
CI, local browser testing, and @andrewjbtw may want to test in a deployed env (verifying that now)
None

Allow users with an APO role to view the APO

---

app/controllers/catalog_controller.rb
app/controllers/versions_controller.rb
app/views/versions/_close_ui.html.erb

HOLD - Pending approval by @andrewjbtw 
Fixes #2298 - do not allow a user to close an object (in the UI) if the cocina is invalid.  See the UI screenshot below in the comments.
**Important note**: this does not prevent closing via a bulk action.
Existing tests and verified on QA too
Find objects that are in this state for testing:
QA: https://argo-qa.stanford.edu/catalog?f[data_quality_ssim][]=Cocina+conversion+failed
Stage:  https://argo-stage.stanford.edu/catalog?f[data_quality_ssim][]=Cocina+conversion+failed
Prod: https://argo.stanford.edu/catalog?f[data_quality_ssim][]=Cocina+conversion+failed
To see in action, try this object:
https://argo-qa-a.stanford.edu/view/druid:bg954kx8787
* Open the `identityMetadata` and remove the sourceId element (if it exists) to make it invalid.
* Add …

prevent closing a version when invalid cocina

---

spec/lib/argo/indexer_spec.rb

`./spec/lib/argo/indexer_spec.rb` has some picky tests that expect the rest client to be called a specific number of times (based on retries).  for whatever reason, CI doesn't always pass with a complaint like this:
```
Failure/Error: expect(RestClient).to receive(:post).exactly(3).and_raise(RestClient::Exception.new(double))
(RestClient).post(*(any args))
expected: 3 times with any arguments
received: 5 times with any arguments
```
This just attemps to make this test less flaky by not testing for the exact number of calls.  Since our course of action for now seems to be ignore and try the test again, I think this a valid tradeoff for having a consistently passing test suite.

make indexer test less picky

---

app/javascript/argo.js
app/javascript/controllers/index.js
app/javascript/packs/application.js

The stimulus application was being initialized in Argo.initialize, which is called on every page load.  This is not ideal, especially when using turbo or turbolinks.  This also gives better organization by separating the stimulus from the non-stimulus part of the application

Split the stimulus controllers into their own file

---

spec/features/bulk_release_object_spec.rb

Look for the job to be completed rather than 'Processing', because the job may be completed by the time the page renders

Fix a flappy spec

---

app/javascript/packs/bulk.js
app/views/report/bulk.html.erb

Because these elements had two class attributes the latter one was being ignored, so nothing matched that selector.  Furthermore, these nodes weren't disabled, so undisabling did nothing

Remove useless code

---

Gemfile
Gemfile.lock
app/components/lazy_tag_facet_component.html.erb
app/components/lazy_tag_facet_component.rb
app/controllers/apo_controller.rb
app/controllers/catalog_controller.rb
app/javascript/argo.js
app/javascript/packs/application.js
app/javascript/packs/bulk.js
app/javascript/spreadsheet.js
app/views/catalog/_lazy_tag_facet.html.erb
app/views/layouts/blacklight/base.html.erb
app/views/registrations/show.html.erb
app/views/report/_document_list.html.erb
app/views/report/bulk.html.erb
config/routes.rb
package.json
spec/requests/create_new_admin_policy_spec.rb
spec/support/selenium_webdriver.rb
yarn.lock

This depends on #2643
The gif does not display the beach-ball cursor correctly:

Lazy load the tags facet 

---

app/components/contents/file_component.rb
spec/components/contents/file_component_spec.rb

Fixes infrastructure-integration-test#240
The integration tests depend on the publish attribute being shown correctly based on the actual file attributes and not on the access for the whole object.  We have that attribute in cocina now, so can use it.
On -qa
Existing tests

show the publish attribute for a file correctly

---

app/components/contents/external_file_component.html.erb
app/components/contents/external_file_component.rb

It's a ruby internal and bad stuff can happen if you do this

Don't redefine object_id

---

spec/lib/argo/indexer_spec.rb

Follow on from #2695, an attempt to make the indexer spec that depends on retries less prone to flakiness
The test suite

make indexing spec less flaky - part two

---

app/controllers/items_controller.rb
spec/controllers/items_controller_spec.rb
spec/features/item_catkey_change_spec.rb
spec/features/item_source_id_change_spec.rb
spec/requests/set_governing_apo_spec.rb

This was caused because turbo expects form responses to be redirect or render a template
This is also a better UI than was there before because it now shows the error on the page in an alert dialog rather than just showing plaintext.

Fix errors that were not showing when an object is not open

---

lib/constants.rb

We no longer use this constant.

Remove unused constant

---

app/components/manage_release/collection_form_component.html.erb
app/components/manage_release/collection_form_component.rb
app/components/manage_release/form_component.html.erb
app/components/manage_release/form_component.rb
app/components/manage_release/item_form_component.html.erb
app/components/manage_release/item_form_component.rb
app/views/bulk_actions/forms/_manage_release_form.html.erb
app/views/manage_releases/_item_manage_release_bulk_action_form.html.erb
app/views/manage_releases/show.html.erb
spec/components/manage_release/collection_form_component_spec.rb
spec/components/manage_release/form_component_spec.rb
spec/components/manage_release/item_form_component_spec.rb

This fixes a regression introduced in https://github.com/sul-dlss/argo/commit/9ec63b6fae8df19413c55f12881f3bb659ed9c96 where an erb was rendered both from within and without a component and the component way doesn't support capture blocks
Ref https://github.com/sul-dlss/argo/pull/2693#issuecomment-828043108

Ensure release options display on the manage release form

---

app/controllers/items_controller.rb
app/jobs/set_catkeys_and_barcodes_job.rb
app/jobs/set_governing_apo_job.rb
app/models/collection_change_set.rb
app/models/item_change_set.rb
app/services/collection_change_set_persister.rb
app/services/item_change_set_persister.rb
app/services/license_and_rights_statements_setter.rb
spec/jobs/set_catkeys_and_barcodes_csv_job_spec.rb
spec/jobs/set_catkeys_and_barcodes_job_spec.rb
spec/services/collection_change_set_persister_spec.rb
spec/services/item_change_set_persister_spec.rb

This allows us to use a standard pattern rather than inventing our own.  This is more maintainable as we have less code to maintain and it is a library we are using in other projects such as h2.  Now fewer classes need to be aware of Persisters.

Refactor change sets to use reform-rails

---

app/forms/access_form.rb
app/services/cocina_access.rb
app/services/cocina_dro_access.rb

A few changes to inline comments to reflect where the constants used are from (not in dor-services gem anymore).

adjust comments to remove references to dor-services

---

.rubocop.yml
spec/jobs/set_catkeys_and_barcodes_job_spec.rb

Tests were removed in https://github.com/sul-dlss/argo/pull/2693/files#diff-9a7dc28d99cfc95d006d7f19b549215a08e149e9a9a050c1f05f4b6bd1019896L89-L91
Unit
NA

Restores tests to set_catkeys_and_barcodes_job_spec.

---

spec/features/register_agreement_spec.rb

This test often takes a while and having a larger timeout helps

Increase the wait time for the register agreement spec

---

.rubocop_todo.yml
app/components/sidebar_controls_component.rb
app/controllers/application_controller.rb
app/controllers/catkeys_controller.rb
app/controllers/items_controller.rb
app/forms/application_change_set.rb
app/models/collection_change_set.rb
app/models/item_change_set.rb
app/services/collection_change_set_persister.rb
app/views/catkeys/_edit.html.erb
app/views/catkeys/edit.html.erb
config/initializers/new_framework_defaults_6_1.rb
config/routes.rb
spec/components/sidebar_controls_component_spec.rb
spec/features/item_catkey_change_spec.rb
spec/requests/set_catkey_spec.rb

Previously there was a null pointer exception when the identification metatata was not present. This was seen happening on collections that don't yet have a catkey.
Refactored catkey management out of ItemsController which had too many responsibilities.
Fixes #2626

Ensure the manage catkey function works for collections

---

app/controllers/content_types_controller.rb
app/javascript/packs/bulk.js
app/views/content_types/_content_type.html.erb
app/views/report/bulk.html.erb
spec/controllers/content_types_controller_spec.rb
spec/views/content_types/_content_type.html.erb_spec.rb

fixes #2694
See this comment for context: https://github.com/sul-dlss/argo/issues/2694#issuecomment-824458429

Stop using the 'Old content type' filter when updating type

---

app/javascript/controllers/nested_form_controller.js
app/views/tags/_edit.html.erb

Fixes #2729
This provides users immediate feedback that clicking the button worked as expected and suggest to them that the page transition should happen momentarily. It also prevents double-submits. Note that I attempted to add test coverage to the edit_tags feature spec, but I cannot inspect the button element after clicking the button because the selenium driver says the reference is stale. Does not seem worth the time to futz with Capybara to test such a tiny change.
CI
None

Disable save button after submitting edit tags form

---

app/views/bulk_actions/index.html.erb

See https://developer.mozilla.org/en-US/docs/Web/API/HTMLAnchorElement/download
Fixes #2731

Add download attribute to download links

---

app/views/bulk_actions/_checksum_report_job.html.erb
app/views/bulk_actions/_descmetadata_download_job.html.erb
app/views/bulk_actions/_export_tags_job.html.erb
app/views/bulk_actions/_register_druids_job.html.erb

Follow on from #2734 and #2731

correctly set download links for bulk action reports

---

app/components/external_links_component.html.erb
app/components/external_links_component.rb
app/models/solr_document.rb
spec/components/external_links_component_spec.rb

This no longer makes sense when we move dor-services out of the stack

Stop relying on the dor_services_version_ssim field

---

app/jobs/generic_job.rb
app/jobs/release_object_job.rb
spec/features/collection_manage_release_spec.rb
spec/features/item_manage_release_spec.rb
spec/jobs/release_object_job_spec.rb

This is now available via the cocina api.
Fixes #2740

Stop using the deprecated release_tags api

---

Gemfile
Gemfile.lock
spec/controllers/dor/objects_controller_spec.rb

Update cocina-models to 0.61.0

---

app/controllers/items_controller.rb
app/models/collection_change_set.rb
app/services/collection_change_set_persister.rb
spec/requests/set_governing_apo_spec.rb
spec/services/collection_change_set_persister_spec.rb
spec/services/item_change_set_persister_spec.rb
spec/support/cocina_matchers.rb

closes #2764
Allow a user to update APO for collection. Existing code was treating a Cocina collection like a DRO.
Unit
NA

Allows updating APO for collection.

---

app/components/manage_release/collection_form_component.html.erb
spec/components/manage_release/collection_form_component_spec.rb

in the collections release form.
This aligns this form with the item release form and, since this value is required, it prevents the submission of invalid values.
Fixes #2785

Check the released option by default

---

app/controllers/catalog_controller.rb

Andrew was having problems with the Bulk Action page.  Traced to a large solr query being sent over GET.
See discussion in slack: https://stanfordlib.slack.com/archives/C09M7P91R/p1628200332093000
Existing tests

allow large solr queries to work by using post instead of get

---

app/helpers/registration_helper.rb
spec/helpers/registration_helper_spec.rb

Fixes #2794 
Following a suggestion from Andrew in the ticket, filtering out all of the workgroups ending in /administrator when constructing the permissions query for the APO list to send to Solr.
Andrew has verified this works correctly on stage and doesn't seem to have any unintended side-effects.  The query change is only for building the list of APOs available for the drop down.
Updated an existing test.

filter out workgroups ending with /administrator when constructing query

---

app/models/user_log.rb
app/views/bulk_jobs/show.html.erb
config/locales/en.yml

Logging isn't working correctly with invalid druids to the modsulator after #2791 because I missed a few things.
On stage

fix logging issues with modsulator invalid druid

---

app/controllers/items_controller.rb
app/views/items/_collection_ui.html.erb
spec/controllers/items_controller_spec.rb

Fixes #2800 - though to be honest it's unclear how you can hit this point, because it's unclear why you'd get to the "remove a collection" endpoint for an object without any collections.  See the details on the ticket.
Added a new test

no exception if an object has no collections

---

config/initializers/okcomputer.rb
spec/features/status_spec.rb

To address these from okcomputer status/all:
```
dor_services_url: FAILED Error: '404 Not Found' (0.094s) (OPTIONAL)
modsulator_url: FAILED Error: '404 Not Found' (0.060s) (OPTIONAL)
normalizer_url: FAILED Error: '404 Not Found' (0.121s) (OPTIONAL)
stacks_file_url: FAILED Error: '404 Not Found' (0.077s) (OPTIONAL)
stacks_thumbnail_url: FAILED Error: '404 Not Found' (0.070s) (OPTIONAL)
workflow_url: FAILED Error: '404 Not Found' (0.067s) (OPTIONAL)
```
deployed to stage, and everything passed except stacks-host, which I didn't touch:
https://argo-stage-a.stanford.edu/status/all/
```
Default Collection
bulk_metadata_dir: PASSED Directory '/workspace/bulk/' is writable (as expected). (0.009s)
bulk_metadata_tmp_dir: PASSED Directory '/workspace/bulk/tmp/' is writable (as expected). (0.010s) …
```

okcomputer: promote or delete optional checks

---

Gemfile
Gemfile.lock
package.json
yarn.lock

So the next dependency updates doesn't inadvertently upgrade to Bootstrap 5.

Upgrade to Blacklight 7.20.1

---

Gemfile
Gemfile.lock
package.json
yarn.lock

Keep up to date. This is the same version that h2 uses.

Update to the latest version of turbo-rails

---

app/views/catalog/show.html.erb
app/views/datastreams/edit.html.erb

Fixes #2832
This is the best I could do for #2832. 🤷🏻‍♂️ 
Note that this commit does not fix the missing republish flash notice. @jcoyne and I think this is unrelated and probably bears more work to hotwire-ify how Argo handles flash.
QA env
None.

Prevent turbo from caching the catalog show page

---

Gemfile
Gemfile.lock

The 7.1.1 version was yanked.  See the story here: https://github.com/hotwired/turbo-rails/commit/31e19cb4b781d186bc31edaa4035b2e13a19fc3c

Update turbo-rails to a released version

---

app/models/concerns/csv_concern.rb
app/models/report.rb
spec/models/report_spec.rb

This will make it possible to upgrade blacklight to 8.x

Avoid deprecated instance variable from Blacklight

---

package.json
yarn.lock

It no longer causes a problem with Blacklight.activate()

Update blacklight-frontend to latest

---

app/assets/stylesheets/variables.scss

Bootstrap 5 by default underlines all links, this makes it look like BS 4.

Don't underline links

---

app/javascript/controllers/tokens.js

csrfParm is an appropriate form field name, not a header

Use the correct header for retrieving a token

---

app/components/lazy_tag_facet_component.html.erb

Bootstrap 5 removes pointer events from disabled inputs, so this overrides this.  This also upgrades the class for alignment to BS5

Turn on pointer events for the tag facet

---

app/assets/stylesheets/workflow_grid.scss
app/components/workflow_table_process_component.rb
app/controllers/report_controller.rb
app/views/report/reset.js.erb
spec/components/workflow_table_process_component_spec.rb
spec/controllers/report_controller_spec.rb

This fixes a problem created when we removed rails-ujs.  This method of rendering remote js is deprecated in rails, so I replaced it with a simple redirect + flash message

Stop rendering remote js.

---

Gemfile.lock
package.json
yarn.lock

This allows hierarchical facets (tags) to expand/contract when using Bootstrap 5.

Upgrade blacklight hierarchy

---

app/components/workflow_step_status_selector.html.erb

Turbo only handles confirmation on the form itself. Fixes #2889

Move confirmation to the form from the button

---

app/javascript/modules/permission_add.js

Update APO registration form to use bootstrap 5 form layout

---

app/components/external_links_component.rb
spec/components/external_links_component_spec.rb

It's `SearchWorks` not `Searchworks`.  
I did NOT change the tag, as that would require data remediation and it's likely not worth it.   In fact, this change may not be worth it.
unit tests, etc

fix SearchWorks link label (capital W)

---

app/controllers/collections_controller.rb
app/javascript/argo.js
app/javascript/controllers/collection_editor.js
app/views/collections/new.html.erb
spec/controllers/collections_controller_spec.rb
spec/search_builders/argo/date_field_queries_spec.rb

This was depending on a solr field that we don't have in the index.  This change also future proofs against moving away from Fedora 3 since we don't use the fedora object model solr field

Restore functionality for collection checking

---

app/javascript/argo.js

These are imported in the app/javascript/modulesapo_form.js, and there's no reason to import them again.

Remove unnecessary imports

---

app/components/document_component.html.erb
app/components/document_component.rb
app/controllers/catalog_controller.rb

This makes it clearer where the content is coming from and makes it easier to migrate to BL 8, as some of the templates we were using no longer exist

Create a document component for the first page

---

app/components/document_component.html.erb

```
DEPRECATION WARNING: render_document_heading is deprecated and will be removed from a future release (Removed without replacement).
```

Avoid a deprecation warning in blacklight

---

app/views/bulk_actions/_checksum_report_job.html.erb
app/views/bulk_actions/_export_tags_job.html.erb
app/views/bulk_actions/_register_druids_job.html.erb

This reverts commit 171a4d882d5fe0e4fa1c3510fd04f1f1765d45f4.
Integration tests were failing.

Revert "Remove unused templates"

---

app/helpers/value_helper.rb
spec/helpers/value_helper_spec.rb

Destructure arguments correctly for ruby 3.0

---

app/services/registration_csv_converter.rb

Fixes #2944 
The bulk registration job had its own code for setting the access hash that did not match the registration form. This causes a validation failure by not including the required controlledDigitalLending related values when required.
A future refactor may rename/update the CocinaDroAccess method for clarity.

Replace registration job access selection with CocinaDroAccess

---

app/controllers/registrations_controller.rb

Otherwise a missing collection can result in a 500 error.

Notify when there are missing collections

---

app/helpers/argo_helper.rb

All others (like registration) should remain container-fluid. 
This was caused by a regression in https://github.com/sul-dlss/argo/commit/50914bfe579b5212e9a0a92a3aaa1ff0c2db2a0a#diff-f7572e813105da402ff889a50f513c883352daa760f926b589f93cf93dc75eefR12

Only the catalog controller show page should have a container class

---

app/components/open_close_component.rb
app/javascript/controllers/open_close_controller.js

This fixes a regression introduced when the open_close_controller was created

The open/close widget opens a modal

---

Gemfile
Gemfile.lock

We are no longer on this ancient version of mysql2

Upgrade to the latest mysql2 gem

---

Dockerfile

App now runs ruby 3.0.3 so Dockerfile should be in sync.
Built web container locally and ran tests.

Update Dockerfile base image to ruby 3

---

app/assets/stylesheets/show.scss
app/components/external_links_component.html.erb
app/components/external_links_component.rb

This corresponds to Astrid's designs https://projects.invisionapp.com/share/ZR1072MLCMEW#/screens/445123823

Show an inactive SearchWorks button when the item is not released

---

app/assets/stylesheets/show.scss
app/components/external_links_component.html.erb
app/components/external_links_component.rb

Resize and reorder the lin
ks to align with the mockup

Remove FoXML export from the external links

---

app/javascript/controllers/json_renderer.js
app/views/catalog/_cocina_default.html.erb

Fixes #2618 (again)
The previous impl allowed users to expand and collapse individual nodes, and as a user, I expect to see widgets for collapse-all and expand-all. So I added it. Note that I chatted with @andrewjbtw and he wants the "View Cocina in New Window" button to remain even with this in place as a means for easy copy/paste of large cocina structures.
Locally. Clicked the buttons and watched the JS console.
None

Expand and collapse cocina in place

---

app/components/show_embargo_component.html.erb
app/components/show_embargo_component.rb
app/components/sidebar_controls_component.html.erb
app/components/sidebar_controls_component.rb
spec/components/show_embargo_component_spec.rb
spec/components/sidebar_controls_component_spec.rb

Per the design mockups.
Ref #2960

move manage embargo from a button to a link in the embargo component

---

app/assets/stylesheets/show.scss
app/components/open_close_component.rb

Update lock icons to use something easier to distinguish

---

app/assets/stylesheets/show.scss

Make the pill longer

---

app/components/contents_component.html.erb
app/controllers/structures_controller.rb
app/services/structure_serializer.rb
config/routes.rb
spec/requests/download_structural_csv_spec.rb
spec/services/structure_serializer_spec.rb

Download the structural metadata as a CSV

---

app/components/details_component.html.erb
app/components/details_component.rb

The created_date field comes from the originInfo in MODS.  Most records don't have this set.
Fixes #2965

Switch to using registered_date

---

app/components/overview_component.html.erb
spec/components/overview_component_spec.rb

Don't show fields not applicable to an admin policy on the overview

---

app/components/details_component.html.erb
app/models/solr_document.rb
spec/components/details_component_spec.rb
spec/models/solr_document_spec.rb

Localize the created date on the details component

---

app/services/structure_serializer.rb
spec/services/structure_serializer_spec.rb

The code can encounter a nil pointer error if we don't account for items that may have no Filesets.

Handle exporting an empty structure

---

app/components/details_component.rb
app/controllers/catalog_controller.rb
app/helpers/value_helper.rb

Now we are using our components to drive this display and we are not relying on Blacklight for this

Remove unused config

---

app/components/contents/file_component.html.erb
app/components/contents/file_component.rb
app/components/contents/resource_component.html.erb
spec/components/contents/file_component_spec.rb

Display the file level access

---

app/controllers/items_controller.rb
spec/requests/apply_apo_defaults_spec.rb

Connects to #3019
To make it clearer to the user which bulk update operations failed and which succeeded.
🤷🏻‍♂️ 
None

Surface errors from applying APO default access in the UI

---

app/controllers/items_controller.rb
spec/requests/apply_apo_defaults_spec.rb

Connects to #3019
Backported from `main` to `release`

Surface errors from applying APO default access in the UI 

---

Gemfile.lock
app/components/show/admin_policy_component.html.erb
app/components/show/collection_component.html.erb
app/components/show/item_component.html.erb
app/components/show/workflow_error_component.html.erb
app/components/show/workflow_error_component.rb
app/controllers/catalog_controller.rb
app/models/solr_document.rb
app/views/layouts/blacklight/base.html.erb
spec/helpers/value_helper_spec.rb

Fixes #3027 - show workflow errors in alert dialog box on item/collection/apo pages below buttons and above details, all other alerts/errors/notices are last as is in same location as before
Localhost browser, existing tests

show workflow errors on item page

---

docker-compose.yml

The default pager (`less`) is not available in the docker container which will throw errors if you do this: ` docker compose run workflow rails c` to get to the rails console and then have a lot of output.  This disables the less pager for the workflow container.
localhost

allow paging to work when using rails console in docker

---

app/controllers/items_controller.rb
app/views/items/error.html.erb
app/views/layouts/catalog_result.html.erb
spec/requests/item_update_spec.rb

Errors were not being displayed.

Add error handling for turbo-frames

---

app/components/manage_release/collection_form_component.html.erb
app/views/bulk_actions/forms/_manage_release_form.html.erb
app/views/catkeys/_edit.html.erb
app/views/items/_source_id_ui.html.erb
spec/views/items/_source_id_ui.html.erb_spec.rb

See https://getbootstrap.com/docs/4.5/components/forms/#help-text

help-block in bootstrap 3 becomes form-text in bootstrap 4/5

---

app/components/contents_component.html.erb
app/components/contents_component.rb
app/components/show/item_component.html.erb
app/components/show/item_component.rb
app/controllers/structures_controller.rb
spec/components/contents_component_spec.rb
spec/controllers/structures_controller_spec.rb

Fixes #3062 - hide upload csv button if object is locked (does not allow modifications)
- Updated component test
- New structure controller test

hide upload CSV button if the object is locked

---

spec/features/bulk_reindex_spec.rb

This test seems to fail 30% of the builds.

Try to fix flaky feature spec

---

tmp/.gitignore

If you try to `docker-compose up -d` without a `tmp/pids` argo_web_1
will exit with:
```
/usr/local/bundle/gems/puma-5.6.1/lib/puma/launcher.rb:248:in `write': No such file or directory @ rb_sysopen - tmp/pids/server.pid (Errno::ENOENT)
```
This commit keeps `tmp/pids/` by adding `tmp/pids/.gitkeep`. The `tmp/.gitignore` was modified
to allow this but still ignore everything else.
Testing locally with `docker compose up -d`
None.

Keep tmp/pids in git for Argo to start

---

README.md

So I/we no longer need to read the docker-compose when trying to find the shortest way to spin up all containers but the web one.
It's a README change.
README

Update named containers to start up all needed services

---

app/components/show/item/thumbnail_component.html.erb
app/components/show/item/thumbnail_component.rb
app/components/show/item_component.html.erb
app/presenters/citation_presenter.rb
spec/components/show/item/thumbnail_component_spec.rb

Use the citation as the thumbnail label

---

app/components/contents/external_file_component.html.erb
app/components/contents/external_file_component.rb
spec/components/contents/external_file_component_spec.rb

Cocina now only has the druid for the structural members, so we can only display those. This change removes the "resource" portion and only displays an "item" link.
I viewed the contentMetadata for [druid:bf746ns6287](https://argo-stage.stanford.edu/view/druid:bf746ns6287) in my dev environment and the changes worked.
I also ran:
bundle exec rspec spec/components/contents/external_file_component_spec.rb
@andrewjbtw tested in QA as well.
The full suite of tests unfortunately do not run reliably in my dev environment.
Closes #3088

Remove resource part of item link

---

config/settings.yml
config/settings/test.yml

Don't try to connect to staging from a development machine.

Enable registering an agreement in the local development environment

---

app/controllers/agreements_controller.rb

Provide a proper turbo response for the agreement form

---

app/components/show/controls_component.html.erb

Move embargo to the end as it's only used by items. This makes the positions more stable between collections and items.
Fixes #3119

Reorder controls

---

app/views/versions/_close_ui.html.erb

Let the browser ensure that a description has been provided when closing a version.
Using my dev environment I tested closing version before and after the change, with and without a description.

Require description when closing a version

---

app/components/show/apo/default_object_rights_component.html.erb
app/components/show/apo/default_object_rights_component.rb

So we can release Argo while we continue working on #3121.
Default object rights will be added back when we can display the expected value.
Localhost

remove default object rights from display

---

app/components/show/apo/default_object_rights_component.html.erb
app/components/show/apo/default_object_rights_component.rb
app/models/solr_document.rb
spec/components/show/apo/default_object_rights_component_spec.rb

Fixes #3121 - show the default access rights for APOs in a consistent way to that shown for items (by showing what is in the newly indexed solr documents for APOs)
See https://github.com/sul-dlss/dor_indexing_app/pull/754 for new indexing work this depends on
~~Note: HOLD until the new indexing code above is deployed, and APOs re-indexed for this to show correctly (note: it should not break if Argo is deployed before this occurs, but the display of default object rights will be blank until then).~~
Localhost browser

add back default access rights display for APOs

---

app/components/show/item/thumbnail_component.html.erb

Fixes #3125 - improve contrast of placeholder.
Dark grey fill to very light grey fill (to set of from page just a bit), and a solid black border.
Example:
Localhost browser

improve contrast of placeholder image

---

app/assets/stylesheets/show.scss
app/assets/stylesheets/sul_variables.scss
app/components/document_title_component.html.erb
app/components/document_title_component.rb
app/controllers/catalog_controller.rb
app/models/solr_document.rb
spec/components/document_title_component_spec.rb
spec/models/solr_document_spec.rb

Improve the virtual object experience for users by:
1. Adding a facet to find all virtual objects; and
2. Rendering a pill on the show page to let users know they're looking at a virtual object
Yes, there's only one virtual object in QA. Happy to take suggestions for how to label these better. @andrewjbtw. Both the collapsible heading *and* the link could both say `Virtual Objects` for instance? 🤷🏻‍♂️ 
CI, QA
None

Spiff up virtual object UI experience

---

app/components/show/agreement/details_component.html.erb
app/components/show/agreement/details_component.rb
app/components/show/controls_component.html.erb
app/components/show/controls_component.rb

Closes #3112 -- there was cruft in the Agreement page.
Note "Manage release" button is gone, and "Released to" is no longer in Details table.
As JCoyne points out, it is difficult to test for the absence of something.  These changes only affect the Argo display on the Agreeement change, and proof is in what the eye beholds?  (Per images above)

Agreement page tweaks

---

.circleci/config.yml

Consistency, clarity, conciseness.
Includes:
* Use modern invocations (*e.g.*, `bin/rails`)
* Remove copypasta (`mkdir -p` is from the ETD build)
* Use the ruby CI orb to invoke Rubocop
CI

Update CI: use modern commands and remove copypasta

---

app/components/show/access_rights_component.html.erb
app/models/solr_document.rb
spec/features/item_view_metadata_spec.rb

fixes #3146
i wasn't sure if there was a better or more idiomatic way to do this, happy to change if so.
in search results (desired display behavior for reference):
on show page before fix:
on show page after fix:
n/a

object show: list all indexed rights for objects with complex rights combinations

---

app/controllers/datastreams_controller.rb
app/controllers/metadata_controller.rb
app/views/metadata/full_dc.html.erb
app/views/metadata/full_dc_xml.html.erb
config/routes.rb
spec/requests/view_full_dublin_core_spec.rb

Because it's not a datastream and will continue to be a feature after the DatastreamController is removed

Move DC XML view to the MetadataController

---

app/assets/stylesheets/argo.scss
app/views/bulk_jobs/index.html.erb

Fix style for bulk upload

---

app/components/action_button.rb
app/components/show/controls_component.html.erb
app/components/show/controls_component.rb
app/controllers/items_controller.rb
spec/components/show/controls_component_spec.rb
spec/requests/apply_apo_defaults_spec.rb

Fixes #3041 - Add an Apply APO Defaults button that is shown for items and collections
~~HOLD Pending testing on QA~~
~~Note: Testing currently blocked by https://github.com/sul-dlss/dor-services-app/issues/3648 and https://github.com/sul-dlss/argo/issues/3185~~
Localhost browser, and updated component and request specs
Integration tests passed on QA

add apply APO defaults button for items and collections

---

app/components/show/admin_policy_component.html.erb
app/components/show/agreement_component.html.erb
app/components/show/collection_component.html.erb
app/components/show/controls_component.rb
app/components/show/item_component.html.erb
app/components/show_embargo_component.rb
spec/components/show/controls_component_spec.rb
spec/components/show_embargo_component_spec.rb

Fixes #3132 - disallow setting or editing an embargo when an object is in a state where it cannot be modified (i.e. version needs to be opened)
Localhost and updated tests 

disallow setting or editing embargo for locked objects

---

app/components/show/apo/overview_component.html.erb
app/components/show/apo/overview_component.rb
spec/components/show/apo/overview_component_spec.rb

Fixes #3100 to display APO registration workflow(s) in the Overview component. 
Added specs. Deployed to QA and confirmed that one, multiple, or 'None' workflows appear. To be reviewed by @andrewjbtw. 

Show registration workflows on APO page

---

app/jobs/set_governing_apo_job.rb
spec/jobs/set_governing_apo_job_spec.rb

Previously it would raise an exception if a version wasn't already open.
Fixes #3164

Open a new version when setting APO in bulk

---

app/components/bulk_actions_form_component.html.erb
app/components/bulk_actions_form_component.rb
app/controllers/bulk_actions_controller.rb
app/controllers/content_types_controller.rb
app/forms/bulk_action_form.rb
app/javascript/bulk.js
app/jobs/set_content_type_job.rb
app/models/bulk_action.rb
app/services/bulk_action_persister.rb
app/views/bulk_actions/forms/_set_content_type_form.html.erb
app/views/report/bulk.html.erb
spec/controllers/content_types_controller_spec.rb
spec/features/bulk_screen_spec.rb
spec/jobs/set_content_type_job_spec.rb

Fixes #2031: Moves set content type bulk action to a bulk job. 
Needs review by @andrewjbtw. Note question in the issue (#2031) about how I moved the label for current resource type to a place different than it is in the design. 
The tests I added seem rather long, so I'd welcome ideas on how to improve them if anyone agrees and has ideas. 

Set content type bulk action

---

app/components/bulk_actions_form_component.html.erb
app/components/bulk_actions_form_component.rb
app/controllers/bulk_actions_controller.rb
app/helpers/application_helper.rb
app/views/bulk_actions/index.html.erb
app/views/bulk_actions/new.html.erb
app/views/catalog/_bulk_action_button.html.erb
app/views/catalog/_bulk_update_view_button.html.erb
app/views/report/bulk.html.erb
spec/components/bulk_actions_form_component_spec.rb
spec/controllers/bulk_actions_controller_spec.rb
spec/features/bulk_desc_metadata_download_spec.rb
spec/features/bulk_screen_spec.rb
spec/features/report_view_spec.rb
spec/views/bulk_actions/new.html.erb_spec.rb

Another attempt to fix #2792 
This does a few things:
- for bulk actions, it uses the search parameters in the query to determine if a previous search is available to get druids from (the same mechanism currently used for bulk update) instead of using the blacklight search history from cookie storage
- if no search parameters are available, it hides the "Populate with previous search" button on the New Bulk Action page
- if no search parameters are available, it hides the "Get druids from search " button on the Bulk Update page
- it stops showing the previous search from history in small text next to that button (as it is no longer relevant)
The net result is that unless you use the "Bulk Update" or "Bulk Action" buttons above the search results, you will not get those "get druid list" …

bulk actions: use search params instead of search history to get druids

---

app/components/bulk_actions_form_component.html.erb

This fixes a problem in the stimulus where it was raising 'oldTab is null'

Add the tab for refreshing metadata

---

app/components/bulk_actions_form_component.html.erb
app/components/bulk_actions_form_component.rb
app/controllers/bulk_actions_controller.rb
app/controllers/items_controller.rb
app/forms/bulk_action_form.rb
app/javascript/bulk.js
app/jobs/set_rights_job.rb
app/models/bulk_action.rb
app/services/bulk_action_persister.rb
app/views/bulk_actions/forms/_set_rights_form.html.erb
app/views/report/bulk.html.erb
spec/features/bulk_screen_spec.rb
spec/jobs/set_rights_job_spec.rb
spec/requests/set_rights_spec.rb

Argo users would like to be able to update object rights as an asynchronous Bulk Action similar to how they do with synchronous Bulk Updates.
Closes #2030
I tested in my dev environment and on QA. See below for the more thorough testing that @andrewjbtw did. And some initial problems that were fixed.

Rights bulk action

---

package.json
yarn.lock

turbo-rails handles all the same functionality

Rails-ujs is no longer necessary

---

spec/requests/workflow_service_spec.rb

Controller specs are deprecated. Request specs exercise more of the stack

Migrate WorkflowServiceController spec to a request spec

---

spec/controllers/items_controller_spec.rb
spec/requests/purge_object_spec.rb

Controller tests are deprecated

Move purge object test to a request test

---

spec/requests/reindex_spec.rb

Move spec for reindexing to a request spec

---

spec/requests/manage_descriptive_metadata_jobs_spec.rb

Move BulkJobsController spec to a request spec

---

spec/requests/upload_modsulator_spreadsheet_spec.rb

Convert UploadController spec to a request spec

---

spec/controllers/report_controller_spec.rb
spec/requests/display_workflow_grid_spec.rb

Controlller tests are deprecated

Move workflow grid test to a request spec

---

spec/requests/set_content_types_spec.rb

Port change content type test to be a request spec

---

spec/requests/bulk_action_spec.rb

Convert BulkActionsController test to a request spec

---

Gemfile
Gemfile.lock
spec/requests/bulk_action_spec.rb
spec/requests/display_workflow_grid_spec.rb
spec/requests/files_spec.rb
spec/requests/manage_descriptive_metadata_jobs_spec.rb
spec/requests/workflow_service_spec.rb
spec/requests/workflows_spec.rb

This dependency is no longer needed.

Remove rails-controller-testing

---

app/controllers/dor/objects_controller.rb

The latter will be the unparsed header in Rails 7.1, which is not what we want

Use Request#media_type rather than Request#content_type

---

.rubocop.yml
app/controllers/items_controller.rb
app/models/nil_model.rb
app/presenters/cocina_hash_presenter.rb
app/services/deep_compact_blank.rb
app/views/catalog/_cocina_default.html.erb
spec/presenters/cocina_hash_presenter_spec.rb
spec/services/deep_compact_blank_spec.rb

Fixes #3178
This commit hides empty descriptive elements in Cocina JSON when displayed, both on the catalog show page and in the items show view.
This is accomplished by wrapping the Cocina::Models instance with a presenter object that collaborates with a new service class that knows how to deeply remove blank values from enumerables (hashes and arrays). We lean on the Rails built-in method, `#compact_blank`, to do the heavy lifting.
CI + will be tested in QA

Hide empty descriptive elements in displayed Cocina JSON

---

README.md

This gets the JS deps with yarn, and builds the javascript.

Document call to rake test:prepare

---

app/controllers/items_controller.rb
spec/requests/edit_license_spec.rb

When pressing cancel on the license editor (similar to #3294 but for license rather than copyright) for a collection.
Fixes #3293

Use a collection changeset for a collection

---

Gemfile
Gemfile.lock

An open issue in view_component is causing a number of test failures. Until resolved, pin to the latest working version (2.50.0)
https://github.com/github/view_component/issues/1315

Pin view_component to 2.50.0 until bug in 2.51.0 is resolved

---

app/jobs/set_collection_job.rb

This method doesn't do anything with the third argument. There's no need to loop over it

Fix call to Ability#can?

---

app/jobs/export_structural_job.rb
spec/jobs/export_structural_job_spec.rb

This is a small change to strip the "druid:" prefix from druids in the structural metadata bulk action export. The existing test has been updated to parse the CSV and make sure the druids are correct.
Adjusted unit test to look at druid column. Ran a report with 7 items on QA.
Closes #3292

Strip druid: prefix in structural metadata CSV

---

app/components/contents/file_component.html.erb
app/components/contents/file_component.rb
app/components/contents/resource_component.html.erb
app/components/contents/resource_component.rb
spec/components/contents/file_component_spec.rb
spec/components/contents/resource_component_spec.rb

Resolves #2925. Image height and width display for image files in the Content resources section.
Added and ran unit tests, deployed to QA. 
When the fileset has a type of image, the Height and Width columns display:
When the image files do not have presentation metadata, the columns appear but values are blank. 
When the fileset is not for an image, the columns do not appear.
⚡ ⚠ If this change updates the Argo UI, run all integration tests that use Argo and create a PR on the integration test repo to fix anything …

Display image props

---

Gemfile.lock

To stay up-to-date with sdr-client releases.
CI + was successfully integration tested in stage

Bump sdr-client to 0.74.0

---

app/controllers/concerns/creates_bulk_actions.rb
app/views/bulk_actions/_druids.html.erb

Now that we use query string parameters to define the previous search used for the "populate druids" button in Bulk Actions (see #3222), the previous search is lost once you submit a bulk action job.  This simply passes the existing search params on through the form submission used to create a new bulk action and then onto the redirect to create a new job.  This allows the search request to be preserved if you then create a new bulk action immediately and want to apply them to the same list of druids.
Localhost browser.

pass search params through the bulk action create form

---

Gemfile
Gemfile.lock

No need to pin the dependency to patch-level now that the bug is fixed.
CI

Unpin ViewComponent now that the bug introduced in 2.51.0 has been fixed

---

app/services/description_export.rb
spec/jobs/descriptive_metadata_export_job_spec.rb
spec/services/description_export_spec.rb

See https://github.com/sul-dlss/argo/pull/3339#issuecomment-1080833153

Ordinal keys should begin at 1 rather than zero

---

app/controllers/catalog_controller.rb

Cocina enforces that these have values now.  Query facets are expensive, so removing unneeded queries should speed up search results.

Remove query facets that are no longer possible

---

app/components/show/agreement_component.html.erb
app/components/show/agreement_component.rb
app/components/show/item_component.html.erb
app/components/show/item_component.rb
app/components/techmd_component.html.erb
app/components/techmd_component.rb
app/controllers/catalog_controller.rb
app/controllers/technicals_controller.rb
app/helpers/items_helper.rb
app/presenters/argo_show_presenter.rb
app/views/technicals/show.html.erb
config/application.rb
config/routes.rb
spec/components/techmd_component_spec.rb
spec/requests/technicals_spec.rb

Fixes #3756
Avoid having a call to the technical metadata service block rendering of the show page.
locally

Load technical metadata lazily

---

lib/cocina/models/factories.rb
spec/components/show/item/overview_component_spec.rb
spec/features/item_source_id_change_spec.rb
spec/jobs/add_workflow_job_spec.rb
spec/jobs/apply_apo_defaults_job_spec.rb
spec/jobs/close_version_job_spec.rb
spec/jobs/descriptive_metadata_export_job_spec.rb
spec/jobs/manage_embargoes_job_spec.rb
spec/jobs/prepare_job_spec.rb
spec/jobs/purge_job_spec.rb
spec/jobs/refresh_mods_job_spec.rb
spec/rails_helper.rb
spec/requests/serials_spec.rb

Per discussion on #3323 it was agreed to first make factories for cocina models. This is a minimal implementation of a factory that is useful in a test.

Create a factory for a cocina object

---

config/deploy/prod.rb

@andrewjbtw says we can unhold this after some descriptive metadata changes drop. Not until then.
CI

Remove temporary PO prompt from production deploys

---

README.md
bin/server
lib/tasks/argo.rake

- Restructure the README to be clearer on how to do local development.
- Add a script to start the bin/rails server with appropriate env variables.
- Add rake tasks for seeding solr for local development and for creating items.
Localhost

add rake tasks for seed data and update readme

---

app/services/structure_updater.rb
spec/services/structure_updater_spec.rb

Fixes #3400 - validate uploaded structural metadata in CSV to ensure the user does not change an existing file's preserve value from no to yes
Added new test

ensure uploaded csv does not change preserve from no to yes

---

Dockerfile
Procfile.dev
bin/dev
docker-compose.yml

This PR modifies the docker-compose web service to use bin/dev as an entrypoint. This means that JS and CSS assets will get compiled automatically when the files change. Hopefully it should make getting set up to develop Argo a little bit easier.
Local development environment.
The docker configuration isn't used outside of development.

[SPIKE] bin/dev and docker

---

app/forms/apo_form.rb
app/services/admin_policy_persister.rb
spec/services/admin_policy_persister_spec.rb

We no longer have an AdminPolicyChangeSet, so the name was a bit confusing.

[refactor] Rename AdminPolicyChangeSetPersister to AdminPolicyPersister

---

app/controllers/descriptives_controller.rb
app/jobs/descriptive_metadata_import_job.rb
app/services/description_import.rb
spec/jobs/descriptive_metadata_import_job_spec.rb
spec/services/description_import_spec.rb

Instead of merging the upload with the existing metadata, generate a whole new descriptive metadata for each upload.  This is how it should work per @arcadiafalcone 

Don't try to set nil values on CSV imports

---

docker-compose.yml

If you start the containers with `docker compose up` and then stop them
with ctrl-c or a `docker compose stop` the tmp/pids/server.pid in the
working directory (shared with the docker container) is not deleted.
This means when you try to start it back up again you get an error about
the server already running.
I suspect there's a better way to do this, but this small change will remove the
server.pid before starting up `rails server`.
Starting and stopping my local Argo Docker development environment.
⚡ ⚠ If this …

Remove pid file when starting up rails dev server

---

app/services/structure_serializer.rb
app/services/structure_updater.rb
spec/fixtures/files/bulk_upload_structural.csv
spec/fixtures/files/structure-upload.csv
spec/services/structure_serializer_spec.rb
spec/services/structure_updater_spec.rb

Fixes #3327 - add a new `rights_location` column to structural spreadsheet and rename `rights_access` column to `rights_view`
Note: I also added an additional validation to ensure the new `rights_location` column has a value if either `rights_view` or `rights_download` contains a value of `location-based`.  
Question: is there an easy way to verify the location specified is an allowed value in the enum here: https://github.com/sul-dlss/cocina-models/blob/main/openapi.yml#L318-L324 
Updated existing tests to show location can be set, and to account for new column and renamed column, and added a new test for location validation.

add rights_location, rename rights_access, add validation for location

---

app/controllers/descriptives_controller.rb
app/controllers/structures_controller.rb

We were mostly using the load_and_authorize_resource, so use that consistently across all controllers
```
$ git grep load_and_authorize_cocina |wc -l
5
$ git grep load_and_authorize_resource |wc -l
10
```
test suite

[refactor] use load_and_authorize_resource consistently

---

app/models/bulk_action.rb

Reverts this [change](https://github.com/sul-dlss/argo/commit/9956d8e530ec1cb9739dcad1498c7dcf3c933d74#diff-53119f6275d5138e0ab2020201cb5b59268a159737c296991d49d3e0c98da2efR6) in https://github.com/sul-dlss/argo/commit/9956d8e530ec1cb9739dcad1498c7dcf3c933d74
While this change probably didn't effect production, it caused bulk actions to return 422 errors during local development. This reverts that change so that local dev and testing of bulk jobs can continue. 
⚡ ⚠ If this change updates the Argo UI, run all …

Revert change that caused 422s in development

---

spec/features/bulk_jobs_spec.rb

This avoids a warning message like:
```
[2022-04-12 14:45:34.970] ERROR -- #<InstanceDouble(Dor::Services::Client::Object) (anonymous)> received unexpected message :metadata with (no args): nil
```

Stub call to metadata

---

app/controllers/concerns/creates_bulk_actions.rb

closes #3413 
long druid lists were causing response handling upstream from argo to throw a 500 error... because of the possibly enormous redirect `Location` header?
e.g. the apache error logs (`argo_error_ssl.log`) would report `Premature end of script headers: bulk_actions, referer` when the user received a 500 in this case (despite the app logs showing a successful 303 response to the `POST`).  note that HTTP 303 responses should have a location.  perhaps the location header in the 303 was not parseable by apache once a certain size was exceeded?
this only occurred with long druid lists.  thanks to @tallenaz yesterday for talking through where we might insert some debug logging, and @edsu today for suggesting a look at the 303 response the user gets when there's a long-ish druid list …

bulk action creation: remove bulk action form values from params passed along location URL in redirect when bulk action is created.

---

Capfile
Gemfile
Gemfile.lock

closes #3180
So that Argo can be put in maintenance mode.
QA

Adds maintenance page.

---

app/controllers/descriptives_controller.rb
app/views/descriptives/_form.html.erb
spec/features/upload_descriptive_metadata_spec.rb

and catch validation errors
Fixes #3475

Close the modal when the upload is successful

---

app/jobs/generic_job.rb

The failure lambda already prints the line number

Avoid having duplicate line numbers in the error message

---

app/controllers/descriptives_controller.rb
app/jobs/descriptive_metadata_export_job.rb
app/services/description_headers.rb
spec/jobs/descriptive_metadata_export_job_spec.rb
spec/requests/download_descriptive_csv_spec.rb
spec/services/description_headers_spec.rb

Download descriptive spreadsheet header re-ordering

---

app/services/description_import.rb
spec/services/description_import_spec.rb

Closes #3470 
This addresses the issue where if a descriptive metadata upload spreadsheet as a record with blank values in `contributor1.*` for instance, but does have values in `contributor3.*` that creates parameters with nil values such as:
```
{
:purl=>"https://purl.stanford.edu/jr825qh8124",
:title=>[{:value=>"foo bar 2"}],
:contributor=>[
nil,
nil,
{:name=>[
nil,
nil, 
{:parallelValue=>[
nil,
nil, 
{:structuredValue=>[
{:value=>"Parallel 1 part 1", :type=>"name"},
{:value=>"1800-1900", :type=>"life dates"}
]},
{:structuredValue=>[
{:value=>"Parallel 2 part 1", :type=>"name"},
{:value=>"marchioness", :type=>"term of address"}]}]}]}]
}
```
This recursively removes the nils from the parameters resulting in:
```
{
:purl=>"https://purl.stanford.edu/jr825qh8124",
:title=>[{:value=>"foo …
```

Remove nil values from arrays when uploading descriptive metadata

---

app/components/show/controls_component.html.erb
spec/components/show/controls_component_spec.rb

"Manage serials" should not be an option in "Manage description" pulldown except for items with ckeys
collection objects with ckeys now show this:
Fixes #3460

don't show 'Manage serials' option for non-item objects

---

app/controllers/descriptives_controller.rb
app/controllers/structures_controller.rb
app/jobs/descriptive_metadata_import_job.rb
app/services/cocina_validator.rb
app/services/description_import.rb
spec/requests/upload_descriptive_csv_spec.rb
spec/requests/upload_structural_csv_spec.rb

Extracted a method for validate_and_save.  This is often something we do at the same time.  This helps us always handle the necessary exceptions while simplifying the controllers.
Errors were not being handled properly, leading to an exception.
Test suite

Handle errors on saving to dor-services-app

---

spec/jobs/descriptive_metadata_import_job_spec.rb
spec/jobs/set_rights_job_spec.rb
spec/services/license_and_rights_statements_setter_spec.rb

Prepare for forthcoming cocina models validation.

Fixes tests to that purl matches external identifier.

---

lib/tasks/argo.rake

So the rake task to create items matches the new factory name
Tested in localhost

fix rake task to create items

---

app/jobs/prepare_job.rb

When performing an Open New Object Versions bulk action a failure to open an item should be logged and then the bulk action should continue to the next druid rather than stopping.
Fixes #3505
Tested with two items in my dev environment, the first of which was not openable and the second which was. I confirmed that the bulk action downloadable log file reflected that the first failed to open and the second succeeded.
⚡ ⚠ If this change updates the Argo UI, run all integration tests that use Argo and create a PR on the …

Continue after failure to open

---

app/javascript/controllers/registration_controller.js

The registration form hasn't been displaying errors properly since the bootstrap 5 upgrade
locally

Upgrade registration form modal to bootstrap 5

---

app/assets/stylesheets/registration/registration.scss
app/views/registrations/show.html.erb

Ref #3514
Makes the top of the registration form look like the design in #3514 prior to adding new widgets

Restyle registration for to use bootstrap styles

---

app/jobs/descriptive_metadata_import_job.rb
spec/jobs/descriptive_metadata_import_job_spec.rb

closes #3522
Per requirements, aligns with replayable spreadsheet/modsulator.
Unit

Desc metadata import job additions

---

app/jobs/set_catkeys_and_barcodes_job.rb
spec/jobs/set_catkeys_and_barcodes_csv_job_spec.rb
spec/jobs/set_catkeys_and_barcodes_job_spec.rb

So that the version is correctly handled when a new version is opened. Previously, the cocina object was not mutated with the new version.
Unit

Fix version handling in SetCatkeysAndBarcodesJob.

---

Gemfile
Gemfile.lock
app/jobs/generic_job.rb
app/services/version_service.rb
spec/jobs/descriptive_metadata_import_job_spec.rb
spec/jobs/generic_job_spec.rb
spec/jobs/set_license_and_rights_statements_job_spec.rb

The cocina model returned from version open has the new version and etag. This allows correct optimistic lock handling.

Uses cocina model return from version open.

---

app/models/track_sheet.rb
spec/models/track_sheet_spec.rb

Fixes #3547: use the same field we use to show object titles in Argo in the tracking sheets (instead of the solr field having the Fedora label).
See for the Solr field name we are indexing to: https://github.com/sul-dlss/dor_indexing_app/blob/main/app/indexers/descriptive_metadata_indexer.rb#L19
and the method used to generate (using `Cocina::Models::Builders::TitleBuilder`):
https://github.com/sul-dlss/dor_indexing_app/blob/main/app/indexers/descriptive_metadata_indexer.rb#L54
And the field name defined in Argo that we will now use in the tracking sheet to get this title: https://github.com/sul-dlss/argo/blob/main/app/models/solr_document.rb#L24
It was not tested.

use object title from solr instead of label from solr

---

app/services/description_validator.rb
spec/services/description_validator_spec.rb

Fixes #3444 - validates cell values in spreadsheet for 0s and spreadsheet errors.
Added new tests

Validate cell values for csv desc metadata spreadsheets

---

app/components/bulk_actions_form_component.rb
app/controllers/bulk_actions/validate_cocina_descriptive_jobs_controller.rb
app/jobs/validate_cocina_descriptive_job.rb
app/models/bulk_action.rb
app/views/bulk_actions/validate_cocina_descriptive_jobs/_new.html.erb
app/views/bulk_actions/validate_cocina_descriptive_jobs/new.html.erb
app/views/bulk_actions/validate_cocina_descriptive_jobs/new.turbo_stream.erb
config/routes.rb
spec/jobs/validate_cocina_descriptive_job_spec.rb

Closes #3373 
Adds a bulk action that takes a csv/spreadsheet equivalent to the descriptive metadata upload job without committing changes to the cocina objects.
New unit test.

[HOLD] Add a bulk action for Validating descriptive metadata uploads

---

app/controllers/datastreams_controller.rb
app/controllers/items_controller.rb

The cookie can hold up to 4k of data, so use more of that space
Fixes #3523

Don't truncate error messages so short

---

app/presenters/cocina_hash_presenter.rb
app/views/catalog/_cocina_default.html.erb
lib/cocina/models/factories.rb
spec/presenters/cocina_hash_presenter_spec.rb

Fixes #3583
This commit adds a new option to the `CocinaHashPresenter` that allows it to render a Cocina structure without metadata, and in this case it means without the lock, created timestamp, and modified timestamp. This new option is then used on the catalog show page. As part of this work, convert the CocinaHashPresenter spec to use factories instead of hand-crafted Cocina model instances and add a flag to the factories to retain past test behavior.
CI

Render Cocina on show page without metadata

---

app/assets/stylesheets/bootstrap-overrides.scss
app/assets/stylesheets/variables.scss

On HOLD until Andrew takes a look in QA and approves.
Fixes #3577
This commit changes the appearance of all primary buttons (including outline-primary buttons) such that if they are disabled, whether via CSS class (for link-y buttons) or pseudoclass (for button-y buttons), they are greyed out, making it clear to users that they are not able to be pushed.
CI

[HOLD] Style disabled primary buttons as greyed out

---

app/components/contents/file_component.rb
spec/components/contents/file_component_spec.rb

Resolves #3574. Shows location value rather than "Location-based" in structural View and Download columns.
Specs and integration tests. 

Display location for location-based access.

---

README.md
config/initializers/byebug.rb

To make it easier and clearer to debug the application locally.
If other folks want to enable pry or other debuggers, feel free to use/repurpose this pattern.
Ran it locally

Allow developers to spin up a remote debugger in development env

---

app/jobs/set_catkeys_and_barcodes_job.rb
spec/jobs/set_catkeys_and_barcodes_job_spec.rb

Fixes #3591 - removing catkeys via bulk action was not working (we need to send an empty array and not nil)
- Tested job on stage
- New test to confirm we send a blank array and not nil when no catkey(s) are provided for a druid

fix catkey setting bulk action

---

app/javascript/controllers/expandable_snippets.js
app/javascript/controllers/index.js
app/views/events/show.html.erb
spec/features/item_view_spec.rb

~~HOLD until @andrewjbtw can take a look in QA~~
Fixes #3575
This commit makes the show page tidier by showing only a peek into each event in the events list. This allows users to determine which events they want to see in detail.
CI + QA

Show truncated events on show page with option to expand

---

app/services/description_validator.rb
spec/features/apo_spec.rb
spec/services/description_validator_spec.rb

closes #3600
Allow parallel titles, which are valid for descriptive spreadsheets.
Unit

Recognize parallel titles as valid titles.

---

spec/features/apo_spec.rb

Turbo links pull in the link name, which can sometimes be flappy.  This sleeps instead of waits.  1 second passed locally and failed in CI.  Trying for 3 seconds.
Existing tests

another attempt to fix flappy spec

---

Gemfile
Gemfile.lock
app/views/metadata/_descriptive.html.erb
app/views/metadata/descriptive.html.erb

Previously the title was in the header.
Fixes #3615
Fixes #635

Display the mods title in the body of the modal

---

app/components/show/admin_policy_component.html.erb
app/components/show/agreement_component.html.erb
app/components/show/collection_component.html.erb
app/components/show/item_component.html.erb
app/controllers/cocina_objects_controller.rb
app/views/catalog/_cocina_default.html.erb
app/views/cocina_objects/show.html.erb
config/routes.rb
spec/requests/cocina_objects_spec.rb

Fixes #3626
This commit removes the burden of loading the full Cocina data structure from the show page, doing so lazily, only if the user interacts with the Cocina dropdown. This allows the show page to render more quickly. The approach taken in this commit follows similar work on lazy-loading events and technical metadata.
CI + QA

Lazy-load cocina object JSON on show page

---

Gemfile
Gemfile.lock
app/controllers/descriptives_controller.rb
app/views/descriptives/_form.html.erb
spec/features/upload_descriptive_metadata_spec.rb

Closes #3620 by allowing `.xlsx` file extensions in the file open dialog and then uses `CsvUploadNormalizer` to parse either a CSV or Excel sheet into csv data.

Allow excel files to be uploaded for description update

---

app/assets/stylesheets/show.scss

Closes #3328 
This updates the resource file table to truncate filenames. A bit of positional adjustment was required as well. This may truncate the filenames too much, which may require some additional design.

Adjust css for the resource file table to truncate filenames

---

spec/features/apo_spec.rb

Previous flaky test fix was potentially looking for nil text, which was sometimes not the case when turbo actually filled it in?  Just speculation.  This version again passes locally and in the CI branch consistently.
Tests

adjust test syntax for flaky test

---

app/services/description_import.rb
spec/services/description_import_spec.rb

closes #3651
Users are creative.
Unit

Allows descriptive spreadsheet columns to be out of orders.

---

app/javascript/registration/register.js
spec/features/item_registration_spec.rb

Fixes #3650 - tags were not making it the object because the params being sent by javascript was "tag" and the params expected by the server were "tags" (started with changes made in https://github.com/sul-dlss/argo/pull/3637 )...I normalized to "tags" , which makes more sense.
Localhost browser.  Updated integration tests to catch this in the future: https://github.com/sul-dlss/infrastructure-integration-test/pull/426

fix bug where tags were not making it during registration

---

spec/presenters/date_presenter_spec.rb

Closes #3665 and should fix the broken builds related to this small coverage drop.
New test.

Add a test for date_presenter to improve coverage

---

app/services/structure_updater.rb
spec/services/structure_updater_spec.rb

Closes #3576 
With an initial (single) fileset:
The exported data will look like:
```
resource_label,resource_type,sequence,filename,file_label,publish,shelve,preserve,rights_view,rights_download,rights_location,mimetype,role
Page 1,file,1,Health_Wellbeing_Panel_audio_GMT20220304-220000_Recording.mp4,Health_Wellbeing_Panel_audio_GMT20220304-220000_Recording.mp4,yes,no,yes,dark,none,,video/mp4,
Page 2,file,1,Health_Wellbeing_unedited_transcript_GMT20220304-220000_Recording.transcript.pdf,Health_Wellbeing_unedited_transcript_GMT20220304-220000_Recording.transcript.pdf,yes,no,yes,dark,none,,application/pdf,
Page 3,file,1,Health_Wellbeing_unedited_transcript_GMT20220304-220000_Recording.transcript.vtt,Health_Wellbeing_unedited_transcript_GMT20220304-220000_Recording.transcript.vtt,yes,no,yes,d …
```

Add filesets to an object through structural metadata csv upload

---

app/views/tags/_row.html.erb

When working on https://github.com/sul-dlss/argo/pull/3681 (catkey editing), I noted that the design for removing catkey rows shows a trash icon, yet the icon for removing tags on a very similar modal form is currently a button.  This makes the tag editing form look like the design for catkeys: https://github.com/sul-dlss/argo/issues/3358#issuecomment-1116329820
**Current:**
**Updated:**
⚡ ⚠ If this change updates the Argo UI, run all integration tests that use Argo and create a PR on the integration test repo to fix …

change icon on tag form to trash icon

---

app/controllers/apo_controller.rb
app/services/register_agreement.rb
spec/factories/apos.rb
spec/factories/collections.rb
spec/factories/items.rb
spec/features/item_registration_spec.rb

DSA no longer does synchronous indexing, so we need to add one when creating an APO or an agreement.  Also adjusted factories to do the indexing since we have no asynch workers in the tests.  Also stoped expecting a process tag to be created
Test suite

Add synchronous indexing when necessary

---

app/forms/registration_form.rb

closes #3694
Descriptive metadata isn't being refreshed upon registration.

Set refresh to true for catkey when registering.

---

app/forms/serials_form.rb
spec/forms/serials_form_spec.rb

closes #3687
Less work for user.

Set catkey to no refresh when updating with serial form.

---

.gitignore
app/jobs/descriptive_metadata_import_job.rb
app/models/repository.rb
spec/jobs/descriptive_metadata_import_job_spec.rb

Fixes #3524 - close objects after running bulk desc metadata import job.  Also delete a tmp db file that was inadvertently added by #3534 and update gitignore to prevent from happening again.
Note: this will only close objects for which an update actually occurred.  It also assumes that any object updated is currently open, which now must be true (as we will open before applying update, if not already open). 
~~HOLD because:~~
~~Andrew tested and approved on May 13, but after rebasing from main I noticed one test started failing (likely due to this change: https://github.com/sul-dlss/argo/commit/686655e43c2f5149354fdcb56aece5638308e59c)~~
~~I think what is happening in that test is that the validation is failing, but the object is still getting closed, and so the final result is …

close objects after bulk desc metadata import job

---

Gemfile
Gemfile.lock

Temporarily pin blacklight to a known working PR https://github.com/projectblacklight/blacklight/pull/2718 to fix #3697 
Once the blacklight PR https://github.com/projectblacklight/blacklight/pull/2718 is merged, we can unpin.
Localhost, test suite

pin blacklight to a known working branch

---

app/controllers/report_controller.rb
spec/requests/reset_workflow_steps_spec.rb

Another attempt to deal with #3697
Guard against setting a workflow step back to waiting that is no longer in an error state.
Existing tests

do not update workflow back to waiting if not in error

---

docker-compose.yml

Without this, you are unable to access newly registered items without manually triggering the indexing.
Tested locally.  I can access the newly registered items.

Add docker compse configuration for indexing workers

---

app/controllers/catkeys_controller.rb
app/forms/catkey_form.rb
app/services/catkey.rb
app/views/catkeys/_edit.html.erb
app/views/catkeys/_row.html.erb
app/views/catkeys/edit.html.erb
lib/constants.rb
spec/features/item_catkey_change_spec.rb
spec/features/update_serials_metadata_spec.rb
spec/requests/set_catkey_spec.rb

Fixes #3358 - update catkey editing form so it allows for adding/removing catkeys and setting of refresh/no refresh.  Design in the ticket: https://github.com/sul-dlss/argo/issues/3358#issuecomment-1116329820
As implemented:
Also: validate that there is no more than a single catkey set to refresh and that any entered catkey values are valid..
~~HOLD for PO testing~~
- Localhost browser
- Updated existing tests for new UI
- Added many more tests for all of the scenarios (deleting, updating, setting refresh)

adjust catkey form to use multiple rows

---

app/components/show/controls_component.html.erb
spec/components/show/controls_component_spec.rb

Fixes #3706 - do not allow upload of cocina desc metadata spreadsheet for locked objects
Updated existing test

do not allow cocina spreadsheet upload for locked objects

---

app/controllers/bulk_actions/content_type_jobs_controller.rb
spec/features/bulk_content_type_spec.rb

closes #3726
It was being ignored.
Andrew on stage.

Pass viewing direction to content type job.

---

app/helpers/apo_helper.rb

hardcode list of workflow options per issue #3741

---

Dockerfile
docker/entrypoint.sh

This is a small docker file change to add an entrypoint script that will remove an existing `tmp/pids/server.pid` on startup because when running with foreman it is not removed on shutdown. When attached (watching the docker output) and ending with `ctrl-c` it remains, as well as when detached and running either `docker compose stop` or `docker compose down`. The result is that subsequent starts of the web application currently require manually removing the `server.pid` file to avoid the web container stopping with the `pid file already exists` error. 
⚡ ⚠ If this change has cross service impact (including writing to shared file systems or interacting with other SDR APIs), ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] …

Remove existing server.pid on startup when using docker

---

app/jobs/descriptive_metadata_import_job.rb
spec/jobs/descriptive_metadata_import_job_spec.rb

Fixes #3740 - do not close objects that are registered (they do not need to be closed and it will not work)
Todo: 
- test on QA/stage
Added a new test, but should validate with Andrew on QA/stage

do not close objects when updating desc metadata if they are registered but not accessioned

---

app/forms/registration_form.rb
app/javascript/controllers/registration_controller.js
app/views/registrations/_item_row.html.erb
spec/features/item_registration_spec.rb

~~[HOLD - for PO review, but also so PR #3751 can go through first]~~
closes #3748 
Registration page validates barcode against allowed barcodes per cocina.
po review

Validate barcode on registration page

---

app/forms/content_type_form.rb

Fixes #3761 - add webarchive-binary content type to menus
Single config file affects both the bulk action and the item detail form (yay).
**Item detail page:**
**Bulk action:**
Localhost browser, Existing tests

add webarchive-binary content type to menu

---

Gemfile
Gemfile.lock
app/controllers/registrations_controller.rb
spec/requests/registration_source_id_spec.rb

DSA is the canonical source of uniqueness.
Unit

Switch to using DSA to check if source id is unique.

---

app/jobs/register_druids_job.rb
app/views/registrations/create_status.html.erb
spec/jobs/register_druids_job_spec.rb

closes #3770
Users don't like the druid prefix.

Remove druid prefix after registering.

---

app/controllers/structures_controller.rb
app/jobs/export_structural_job.rb
app/services/structure_serializer.rb
spec/services/structure_serializer_spec.rb
spec/services/structure_updater_spec.rb

Fixes #3758 - include the druid column for all structural metadata exports (even single objects).
This adds the druid column to the core export class, and then removes it from the bulk action job (since it will come automatically from the single object now).
~~HOLD to validate on QA/stage with real data~~ validated on qa, works fine
Updated/existing tests/localhost.  Verified on qa with actual data.
Note: existing spec for bulk action job is unchanged but passes, showing that it still works as expected (i.e. includes the druid column)

add druid column to all exported structural metadata

---

app/jobs/set_catkeys_and_barcodes_csv_job.rb
app/jobs/set_catkeys_and_barcodes_job.rb
app/models/item_change_set.rb
app/services/catkey.rb
app/services/item_change_set_persister.rb
app/views/bulk_actions/catkey_and_barcode_csv_jobs/_new.html.erb
spec/jobs/set_catkeys_and_barcodes_csv_job_spec.rb
spec/jobs/set_catkeys_and_barcodes_job_spec.rb
spec/services/item_change_set_persister_spec.rb

closes #3735
Need to support setting refresh.
Unit, QA

Support refresh in set catkeys CSV bulk action.

---

app/services/registration_csv_converter.rb

This just adds a couple of the missing types for the csv registration so it matches the pulldown menu and alphabetizes the array.

Add missing types for csv registration

---

app/services/registration_csv_converter.rb
spec/services/registration_csv_converter_spec.rb

Closes #3807 
Since bulk registration still passes the content type in through the CSV, a few of the types were missing that have been added recently (geo and webarchives).

Add missing types when passed in through csv

---

app/components/workflow_update_button.html.erb
spec/components/workflow_update_button_spec.rb

More IDs added to DOM element (workflow step reset button) to facilitate integration testing (follow on from #3814)
Updated test and localhost

add ids to workflow reset buttons to facilitate testing

---

app/services/registration_csv_converter.rb
spec/services/registration_csv_converter_spec.rb

Registering items with a csv for access of citation-only was failing.  
Fixes #3818
I deployed it to stage and checked a csv that was failing before I deployed this fix.  It works now.

registration fix for access citation-only with csv

---

app/services/description_validator.rb
spec/services/description_validator_spec.rb

To avoid throwing HB errors for empty header cells for DescriptionValidator.  Instead, report it as invalid header:
Fixes #3822

description_validator: empty header is invalid

---

config/initializers/okcomputer.rb
config/settings.yml
spec/features/status_spec.rb

Argo no longer has a dependency on stacks
CI

Stop checking for stacks

---

config/deploy.rb

This fix made it possible to deploy the argo app to a newly built VM.

deploy.rb: capistrano first deploy works without sprockets

---

app/services/admin_policy_options.rb
spec/services/admin_policy_options_spec.rb

closes #3856
Remove APOs that we don't want user to select.
Unit

Filter inactive APOs from APO lists.

---

public/404.html

This template can be rendered at any URL, so the image path has to be relative to the root

fix path to image

---

Gemfile
Gemfile.lock

preservation-client version 5.0 removes primary_moab_location, which is never used here, thus perfectly safe here.

preservation-client is now version 5.0

---

app/jobs/descriptive_metadata_import_job.rb
spec/jobs/descriptive_metadata_import_job_spec.rb

Fixes #3865 - validate each row of the spreadsheet explicitly first when running a desc metadata import job, before we apply the desc metadata update...this will catch any validation errors and provide the same nice error message as the validate only job does.
Localhost and QA

add validation before attempting desc metadata update to get better error messages

---

app/controllers/files_controller.rb

Reverts sul-dlss/argo#3899
We have a hypothesis that this patch was working around a bug present in net-protocol 0.2.0: https://github.com/ruby/net-protocol/pull/14

Revert "Uncorrupted downloads from pres."

---

app/controllers/collections_controller.rb
app/services/collection_change_set_persister.rb
app/views/items/_edit_collection_rights.html.erb

Fixes #3901 
There is a small difference between argo and cocina proper where we refer to "view_access" that needs to be sent as "view" for the Cocina::Models::CollectionAccess value
This also fixes a small template error that displayed HTML instead of the cancel button.
Before:
After:

Correctly set collection rights when editing

---

app/controllers/tokens_controller.rb
app/models/ability.rb
app/models/null_user.rb
app/models/user.rb
spec/features/token_spec.rb
spec/models/ability_spec.rb
spec/models/user_spec.rb
spec/views/auth/groups.html.erb_spec.rb

Connects to sul-dlss/sdr-client#250
This commit limits the number of Argo users that are authorized to generate sdr-api tokens. The workgroup that is now used contains the Infra devs, JCoyne, Andrew, and Tony C, and the group is managed by Andrew.
CI + tested in QA with Andrew

Authorize SDR API token endpoint using new workgroup

---

app/controllers/registrations_controller.rb
app/forms/agreement_form.rb
config/settings.yml

Fixes #3894 - use the same regex to verify source_ids in both the agreement and the item registration forms ... and put it into the settings so we do not get out of sync again.
This was fixed for the item reg form in https://github.com/sul-dlss/argo/pull/3754/files ... this takes that regex and moves it to settings, and then uses it for agreements validation
Localhost

use the same regex to verify source_ids across the app

---

app/views/bulk_jobs/index.html.erb

Currently it's drawing into a buffer that is never displayed on the page.  This template draws the page like https://argo.stanford.edu/apos/druid:dd051ys2703/bulk_jobs where there is no sidebar. Without this change, we can not upgrade to Blacklight 8, because this unused code will use a different interface.

Don't draw a sidebar on a page that doesn't display a sidebar

---

Gemfile
Gemfile.lock
yarn.lock

This makes it possible to upgrade to blacklight 8.x
CI

Update to blacklight-hierarchy 6.1.x

---

Gemfile
Gemfile.lock

none of the pres client changes are to methods used by argo, based on a grep for pres client invocations
(this is just meant to allow automated dependency updates to keep pres client updated)
unit tests

bump preservation-client to 6.x

---

app/models/solr_document.rb

This is a prerequisite to changing any of the Argo display to include Folio identifiers:  in order to start using `folio_instance_hrid` in Argo, we need to do the blacklight configuration.  It has NO changes to Argo displays.
- unit tests
- ran a number of integration tests
- deployed to qa and eyeballed various views of a record with folio_instance_hrid_ssim populated in index
⚡ ⚠ If this change updates the Argo UI, run all integration tests that use Argo and create a PR on the integration test repo to fix anything …

Blacklight's SolrDocument gets folio hrid

---

app/components/show/controls_component.rb
app/models/solr_document.rb
spec/models/solr_document_spec.rb

`catkey_id_ssim` method never has catkey prefix.  https://github.com/sul-dlss/dor_indexing_app/blob/main/app/indexers/identity_metadata_indexer.rb - note how it is added to `prefixed_identifiers` which is used for other fields, `identifier_ssim` and `identifier_tesim`
- unit tests, on stage (I looked at show page, at search results, at republished public_xml ...)
- many integration tests
- had Andrew check Argo
- checked Solr field contents with Solr admin tools to ensure no "catkey:" present in the `catkey_id_ssim` values for prod Argo index.
⚡ ⚠ If this change has cross service impact (including writing to shared file systems or interacting with other SDR APIs), ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test in [stage|qa] …

remove unnec SolrDocument.catkey_id method

---

app/controllers/profile_controller.rb
app/presenters/profile_presenter.rb
app/search_builders/argo/profile_queries.rb
app/views/profile/_document_list.html.erb
spec/features/profile_spec.rb
spec/search_builders/argo/profile_queries_spec.rb

Closes #3964 
unit tests, deployed to QA

profile view of search results no longer includes Catkey stats

---

app/controllers/application_controller.rb
app/controllers/catalog_controller.rb
config/settings.yml
config/settings/development.yml
config/settings/test.yml

Fixes #3977
This commit adds a new facet field to the Blacklight catalog if and only if the multi-valued metadata sources feature flag is on. It also flips this flag on in dev & test, and allows the user to flip it on for a given request by adding `?multivalued=true` as a query param in the URL.
It's not clear that there are any specs that could be extended to cover the two small changes to `app/controllers/` and I'm not sure it's worth the effort to write new specs for this when we'll be extensively testing this via the browser given we're dealing with Blacklight internals.

Add `metadata_source_ssim` facet field behind feature flag

---

app/forms/collection_form.rb
app/views/collections/new.html.erb

I missed these in the giant spike PR and they cause a bug/HB alert in QA, thanks to testing from Arcadia. This fixes the issue.
CI and will be tested in QA

Remove hard-coded symphony values

---

app/views/registrations/show.html.erb

This was found in QA testing. Since it is a single string in a single view that is affected, I did not think it was unit test-worthy.
CI + QA

Fix non-standard capitalization of Folio Instance HRID

---

app/jobs/set_catalog_record_ids_and_barcodes_job.rb
spec/jobs/set_catalog_record_ids_and_barcodes_job_spec.rb

closes #3966
Collections are objects too.
Unit, stage

Handle collections in SetCatalogRecordIdsAndBarcodesJob.

---

app/controllers/application_controller.rb
app/controllers/catalog_controller.rb
config/settings.yml
config/settings/development.yml
config/settings/test.yml

~~This is **ON HOLD** until reindexing has been done in all environments.~~
Fixes #3980
This commit removes a metadata source facet field that is no longer needed after the Folio migration is complete. It also removes the feature flag that would now be dead code.
CI

Remove facet for single-valued metadata source field

---

app/forms/catalog_record_id_form.rb
spec/requests/set_catalog_record_id_spec.rb

closes #3985
Support editing catalog record ids.
Unit, QA

Fix catkey editing.

---

app/services/notes_grouper.rb
spec/services/descriptions_grouper_spec.rb

Resolves #3978. 
Unit and deploy to stage.
Updated spreadsheet with export from [Andrew's sample tag](https://argo-stage.stanford.edu/catalog?f%5Bproject_tag_ssim%5D%5B%5D=note+field+numbering+issue):
[t3978-cocina-desc-export-notes.csv](https://github.com/sul-dlss/argo/files/11296310/t3978-cocina-desc-export-notes.csv)

Order notes with no labels and types together, with no leading empty cells

---

app/controllers/descriptives_controller.rb
spec/requests/upload_descriptive_csv_spec.rb

closes #4014
So that users are not befuddled by malformed descriptive CSV.

Handle malformed CSV for descriptive upload.

---

app/helpers/apo_helper.rb
config/settings.yml

It has been deprecated and has not been in use for 3+ years.

Remove gisDiscoveryWF from APO options

---

app/services/registration_service.rb

Fixes #1043
This commit makes a small tweak to the Argo registration service, creating administrative tags for an object before creating its workflow. This should *ensure* the problematic behavior of getting too far in a workflow (the `goobiWF` in particular) before administrative tags are created since the tag creation in DSA is synchronous.

Create administrative tags before workflow

---

Gemfile
Gemfile.lock
app/forms/tags_form.rb

Keep pace with reform-rails now that the bug we found was patched.
CI

Stop pinning reform-rails to pick up patch in 0.2.5

---

app/controllers/application_controller.rb

This turns out not to work as we expected. Mutating a `Settings` value changes **global** state, so when the `folio=true` query param is added to a request, the setting is tweaked not only for that request but flips the setting across the entire site.🤦🏻‍ Andrew does not use this feature anyway. Once I hear from Arcadia, that will unblock this PR.
CI + QA

Remove controller code to flip Folio flag on based on a param

---

app/jobs/set_catalog_record_ids_and_barcodes_job.rb
app/models/item_change_set.rb
spec/jobs/set_catalog_record_ids_and_barcodes_csv_job_spec.rb

Fixes #4034 - validate that catalog record IDs (either catkey or folio_instance_hrid) and/or barcodes are valid before attempting to version/save an object.  This stops opening the object and adding a message, only to have the save fail because it was invalid.
Note: even though the ticket describes the problem as updates from a CSV file, the same thing would happen for the bulk job that allows you paste in druids, barcodes and catalog record IDs.  This will fix both jobs (as they both use the same underlying update code, just different code for getting the input data loaded).
~~[HOLD] to test on QA or stage first~~
Added specs.  Tested on QA with both CSV file and pasted values (i.e. both related jobs)

Add validation for catalog record IDs/barcodes before saving in bulk action

---

.rubocop.yml
Gemfile
Gemfile.lock

Fixes #4067
This commit updates the standard gems and uses the new pattern for requiring standardrb plugins in the `require` section of the rubocop configuration.
CI
No

Update standard gems and require standard-custom

---

app/services/description_import.rb
spec/services/description_import_spec.rb

~~HOLD for PO approval (Andrew)~~
Fixes #4071
Fixes #4072
Contributors with roles but not name are basically invalid and require complex remediation (error when publishing).  
Form data without a value (e.g. it just has source or type, but no value) also require complex remediation (prevents indexing)
I've created sul-dlss/cocina-models/issues/610 for cocina validation of contributors
Andrew reviewed it in stage;  also specs.
⚡ ⚠ If this change updates the Argo UI, run all integration tests that use Argo and create a …

csv upload: do not import contributor roles without names or form source or type without a form value

---

app/components/bulk_actions_form_component.rb
config/settings.yml

closes #4032 
Avoid problems during cutover.
Local

Disable refresh mods bulk action during cutover.

---

app/views/collections/new.html.erb
spec/features/create_collection_spec.rb

Fixes #4079  By removing the option to create a collection from a Folio hrid when the in cutover flag is set.
Before:
After:
⚡ ⚠ Please ensure this change does not introduce accessibility violations (at the WCAG A or AA conformance levels); if it does, include a rationale. See the [Infrastructure accessibility …

Disable create collection from folio during cutover

---

app/components/show/controls_component.html.erb
app/components/show/controls_component.rb
spec/components/show/controls_component_spec.rb

Fixes #4031
This commit disables the metadata refresh button on the show page when the ILS cutover flag is flipped on. Not specified in the issue, I also included a small change to the "Refresh" label to make it clear to users *why* metadata refresh is not enabled. I pondered whether we should also include similar prevention code in the ItemsController, but since this operation is a POST, I figured it was very unlikely one of our users was going to bypass the UI controls and try to hack in a metadata refresh. Check me on this.
CI
No

Disable metadata refresh on show page during ILS cutover

---

.rubocop/custom.yml
spec/components/document_title_component_spec.rb
spec/components/workflow_table_process_component_spec.rb
spec/features/enable_buttons_spec.rb
spec/helpers/value_helper_spec.rb
spec/models/bulk_action_spec.rb

Enables new cops and implements the new `receive_messages` rspec operation over `receive().and_return()`
⚡ ⚠ Please ensure this change does not introduce accessibility violations (at the WCAG A or AA conformance levels); if it does, include a rationale. See the [Infrastructure accessibility guide](https://github.com/sul-dlss/DeveloperPlaybook/blob/main/best- …

Enable new cops and update specs

---

app/components/bulk_actions_form_component.rb
config/settings.yml

Fixes #4097
This commit changes what was done in #4086 to disable releases to SearchWorks not *during* the cutover, but immediately *prior* to the cutover.
CI
No.

Disable SearchWorks release bulk action in the immediate pre-cutover period

---

app/components/show/controls_component.rb
config/settings.yml
spec/components/show/controls_component_spec.rb
spec/features/bulk_desc_metadata_download_spec.rb
spec/features/bulk_release_object_spec.rb
spec/features/collection_manage_release_spec.rb
spec/features/item_manage_release_spec.rb

set `disable_release_prior_to_ils_cutover` to true

Update settings.yml for FOLIO cutover

---

.rubocop/custom.yml
app/components/bulk_actions_form_component.rb
spec/features/bulk_desc_metadata_download_spec.rb

Fixes #4106 by simply removing the menu item
There is an issue where the form still contains a non-disabled options form/druids/etc if you switch back to the disabled options. So during the FOLIO cutover we want the options to simply be unavailable.
⚡ ⚠ Please ensure this change does not introduce accessibility violations (at the WCAG A or AA conformance …

Disable select bulk actions during folio cutover

---

app/assets/stylesheets/document.scss

Fixes #4066 - ensure error message and note colors do not have their colors overridden
Localhost

override styles for error and note text

---

app/controllers/registrations_controller.rb

Fixes #4103 - make CSV registration template have the same columns in the same order as the registration form (even though the order of the columns doesn't really matter when registering, we want to be consistent)
Todo: 
Localhost

update csv registration template to match form

---

app/views/registrations/create_status.html.erb

Related to #4104 (though not a fix for it) -- just adds a header to the registration output to make it clear that barcode and folio instance HRID may be blank.  As you can see elsewhere in the code, the barcode and catkey/instance HRID are already in the output (just blank sometimes). 
Copying and pasting the data into Excel or google sheets preserves the blank columns.
~~HOLD pending review by Andrew~~
Localhost

Add header to registration report

---

app/jobs/register_druids_job.rb
spec/jobs/register_druids_job_spec.rb

Fixes #4104 - the output of the registration bulk job should include the same columns that are shown on the webpage you get when registering objects
Todo: 
Localhost and CI

add columns to registration job report output

---

app/components/show/item/details_component.html.erb
app/components/show/item/details_component.rb
app/controllers/catalog_controller.rb
app/models/solr_document.rb
spec/components/show/item/details_component_spec.rb

Fix for #4096 (but also need https://github.com/sul-dlss/dor_indexing_app/pull/986 first to ensure these fields gets indexed).
- Adds a new "Indentifiers" facet that will show you any objects with a DOI or with contributors have ORCIDs.  Also added items with a barcode or folio_instance_hrid to this facet since they are already in solr anyway.  I know there is a separate "metadata source" facet that sort of duplicates this, but perhaps this is useful here too?
- Adds the DOI and ORCIDs to the show page (if they exist in the object).  Not in the ticket, but potentially useful and already in solr with the indexing work.
**New facet:**
**Additions to detail page** (note, the fields only show when in the record, else the table is as current):
Todo:
Localhost and stage

Add orcid and doi facets (and to detail page)

---

.circleci/config.yml

Experiment to see if we need chrome and/or browser-tools installed for CI

no need to install chrome or browser-tools

---

Gemfile
Gemfile.lock
app/jobs/checksum_report_job.rb
spec/jobs/checksum_report_job_spec.rb

closes #1997
To allow checksum report job to handle large numbers of druids.
Unit, QA, Andrew
⚡ ⚠ Please ensure this change does not introduce accessibility violations (at the WCAG A or AA conformance levels); if it does, include a rationale. See the [Infrastructure accessibility guide](https://github.com/sul-dlss/DeveloperPlaybook/blob/main/best-practices/i …

Change checksum report job to make multiple calls to pres cat.

---

.github/pull_request_template.md

We discussed making the PR template more useful and less noisy for code authors and reviewers today, and this PR amends the template so the team can review how close these changes are to what they had in mind.
N/A

Make the PR template less spammy

---

app/components/contents_component.html.erb
app/components/download_all_button_component.rb
app/controllers/files_controller.rb
app/services/state_service.rb
spec/components/download_all_button_component_spec.rb
spec/features/enable_buttons_spec.rb
spec/features/item_catalog_record_id_change_spec.rb
spec/features/item_manage_release_spec.rb
spec/features/item_source_id_change_spec.rb
spec/features/set_governing_apo_spec.rb
spec/requests/files_spec.rb
spec/requests/item_files_download_spec.rb
spec/services/state_service_spec.rb

Fixes #4141 - download all files fails when an object is opened for versioning (it looks in preservation for the newly bumped version which doesn't exist yet, instead of the last version in preservation).  This fixes it by using the last preserved version.  
This also removes the "Download all files" link unless there is an accessioned version.  This is because you can only download files once they are in preservation (this is current behavior too).  Currently, the link shows for an v1 object that has never been accessioned, but gives you a blank ZIP file.  This change removes the link (because we now have to ask for the previous version and we may as well just not show the link in this case).
HOLD to verify with Andrew

[HOLD] use the previously accessioned version when downloading all files

---

app/components/show/catalog_record_id_component.html.erb
app/controllers/catalog_record_ids_controller.rb
app/views/catalog_record_ids/_edit.html.erb

closes #4094
No longer necessary. To the best I can tell, these were vestigial anyways.
Unit
⚡ ⚠ Please ensure this change does not introduce accessibility violations (at the WCAG A or AA conformance levels); if it does, include a rationale. See the [Infrastructure accessibility guide](https://github.com/sul-dlss/DeveloperPlaybook/blob/main/best-practices/in …

Remove folio params.

---

app/views/layouts/blacklight/base.html.erb

The field with the id "search_field" is a hidden field. In blacklight it's a select box, so the default links don't work in Argo.
Fixes #4159

Fix skip link for search

---

app/controllers/catalog_controller.rb

keep "No MODS typeOfResource" and "No SW Resource Type", drop all the rest.
closes https://github.com/sul-dlss/dor_indexing_app/issues/998
CI, display of seed data on laptop dev env:

argo empty fields facet changed to only show two values

---

app/models/report.rb

Change which report fields are shown by default

---

app/services/description_import.rb

Per Andrew, to account for user data that has large number of contributors.
Unit, Andrew

Adjust padding in description import to allow > 999 contributors.

---

app/assets/stylesheets/argo.scss
app/views/catalog/_home_text.html.erb
app/views/shared/_header_navbar.html.erb

Fixes #4160
This commit includes a small number of accessibility-related changes to the homepage / landing page, including:
* Override `_header_navbar`, and remove custom `.navbar-logo` override, to replace how the Argo logo is handled. We do this to continue using the Argo logo in the upper-lefthand corner of the page, but there are two improvements:
* There is no longer an occluded string in the UI, "Argo", that scanners like Siteimprove complain about not being visible
* The Argo logo now has alt text
* Bump `Welcome to Argo` header (an `<h1>`) up a level so it is closer to the `<main>` element. The intervening `.getting-started` div was not referenced or used anywhere in Argo or Blacklight, so there is no impact on the look & feel.
It is unclear to me how to further make progress on …

Improve accessibility of landing page

---

app/models/report.rb

Fixes #4204 - rename column in report view
Localhost

rename report column

---

app/views/files/index.html.erb
spec/views/files/index.html.erb_spec.rb

Fixes #4208 - do not offer download link when file is not available for download
Stage
Updated spec

do not offer download link if file not available for download

---

app/views/catalog/_home_text.html.erb
app/views/layouts/blacklight.html.erb
spec/views/catalog/_home_text.html.erb_spec.rb

Fixes #4161 
This overrides the default blacklight layout to move the sidebar higher in the dom than content to improve the screenreader experience.
Note: I will put up a separate blacklight PR to address this upstream, at which time we can remove this override.

Move the sidebar above the content in the dom

---

app/forms/csv_registration_form.rb
spec/features/item_registration_csv_spec.rb

Fix setting download to none in csv registration form.

---

app/controllers/catalog_controller.rb
solr_conf/conf/solrconfig.xml

Closes #4224
It is difficult to test Solr configuration changes unless you can view results for the same Solr index side by side (with and without the changes).
This will allow us to tweak relevancy by testing proposed changes against the Argo production index.
CI

allow testing of Solr argument changes against real indexes

---

app/javascript/controllers/copy_controller.js
app/javascript/controllers/index.js
app/views/catalog/facet.html.erb

Fixes #4234 - add a copy/paste icon to the facet model to allow users to grab the facet list values onto their clipboard.  Note: copy/paste icon only shows on the modal window (for when you click "more >>").  We can adapt later if we need to shows this for all facets on the main argo page.
~~HOLD for testing on stage~~
Localhost and stage

add copy/paste icon to facet modal

---

app/models/report.rb

refs #4245
Speedier reports
stage, prod

Increase solr page size for csv download.

---

.circleci/config.yml
docker-compose.yml

Solr 9 is out.  Our prod Solr cloud is at Solr 8.11.2.    This is an upgrade from Solr 7.
local tests
circleci

upgrade to solr 8.11 as in prod

---

Gemfile.lock

This commit bumps DSC to 13.1.1 to pick up a patch that surfaces more exception context when connections to DSA fail.
CI

Bump dor-services-client to 13.1.1

---

app/controllers/catalog_controller.rb

This is the result of some experimentation after issue #4224 - how to use a param in the argo url to test new solr fields/other discovery improvements.
This PR updates the "query fields" for the qttest Solr requestHandler to reflect where we are going at this moment - wiriing in new author and catch all fields.
Originally, I was hoping that we would add "qt=qttest" AND "qf=field1 field2" into the argo url.  But that turned out to be less great than expected, because I think the lazy loading facet queries revert to the qf params in blacklight_config_helper.   (There is definitely a second query to Solr which reverts to the params in blacklight_config_helper .)
However, the qt=qttest param in the Argo url still allows us to see how certain differences in the request handler arguments can …

when argo url has qt=qttest, use more realistic "where we are going" qf parameter.

---

app/controllers/catalog_controller.rb
app/helpers/blacklight_config_helper.rb
solr_conf/conf/schema.xml
solr_conf/conf/solrconfig.xml

~~HOLD for integration tests to pass on stage.~~
Part of sul-dlss/dor_indexing_app#1032
As part of the Argo Discovery Improvements, various needs have arisen:
- improve search results for queries on authors, source ids, and in general (catch all field) with qf changes in blacklight_config_helper
- sync Solr config files with updates in  sul-dlss/sul-solr-configs/pull/280
Andrew vetted the blacklight_config_helper changes when I set him up with the same configuration for `qt=qttest` in the url;  he vetted the improvements for author searching and for source id searching.
I diffed solrconfig.xml against the ones in sul-solr-configs/pull/281 and they are the same in all the right ways
- ci tests
- see sul-dlss/sul-solr-configs/pull/280 for how the Solr config changes were tested
TODO:

discovery improvement work; sync solr configs with sul-solr-config

---

app/controllers/catalog_controller.rb
app/helpers/blacklight_config_helper.rb
app/models/report.rb
app/models/solr_document.rb
app/models/track_sheet.rb
solr_conf/conf/solrconfig.xml
spec/features/item_view_spec.rb
spec/features/search_results_spec.rb
spec/models/report_spec.rb
spec/models/track_sheet_spec.rb
spec/requests/report_spec.rb

~~Hold until Friday Nov 3~~
Closes #4194
To allow source id fragments to be searchable.

use new source_id fields for search and elsewhere

---

app/components/lazy_nonproject_tag_facet_component.html.erb
app/components/lazy_nonproject_tag_facet_component.rb
app/components/lazy_project_tag_facet_component.html.erb
app/components/lazy_project_tag_facet_component.rb
app/components/lazy_tag_facet_component.html.erb
app/controllers/catalog_controller.rb
app/helpers/blacklight_config_helper.rb
app/views/catalog/_lazy_nonproject_tag_facet.html.erb
app/views/catalog/_lazy_project_tag_facet.html.erb
config/routes.rb
spec/components/workflow_table_process_component_spec.rb

~~Hold until Friday Nov 3~~
HOLD until:
- Part of #4187 - add a project tag facet at the top, showing hierarchy...modeled after the similar tag facet
- Also switches field used for tag facet to no longer include project tags.
Localhost and stage/qa
HOLD for PO review - ✅ as of 10/5, ✅ as of 11/1

add project tag facet with hierarchy

---

app/controllers/catalog_controller.rb

Tying up loose ends for sul-dlss/dor_indexing_app/issues/841
hydrus_apo_title_ssim is NOT populated in Argo prod index, so we can remove a little cruft.
Triple checked this facet isn't showing in Argo prod ... and it's not because it is empty.  Whee!

no more Hydrus Admin Policy facet - Solr field is no longer used

---

app/helpers/blacklight_config_helper.rb

May address problem reported in #4273.

blacklight_config_helper.rb - fix typo for non project tags

---

app/controllers/catalog_controller.rb

Increase the limit for project and tag results.

---

app/forms/apo_form.rb
app/views/apo/_form.html.erb
spec/features/apo_spec.rb
spec/forms/apo_form_spec.rb

Fixes #4275 
CI
me on stage
Andrew on stage

APO form prefers title over label for default collections

---

solr_conf/conf/schema.xml

To match sul-dlss/sul-solr-configs/pull/283
adding a couple of dynamic field types in preparation for searchable tags.
It's harmless.  CI is good enough.

solr schema gets stored text_unstemmed dynamic fields

---

config/initializers/folio_client.rb
config/settings.yml

Allows us to use two versions of FOLIO auth until we're upgraded to Poppy in late March. 
Deployed to QA and integration tests.

Add folio_client legacy_auth setting

---

app/controllers/catalog_controller.rb
app/helpers/blacklight_config_helper.rb
solr_conf/conf/solrconfig.xml

HOLD for prod index to have new field fully populated.
part of #4265 
on stage and qa,  with all the objects reindexed

searches use searchable tag field

---

spec/features/home_page_spec.rb
spec/jobs/tracking_sheet_report_job_spec.rb
spec/models/track_sheet_spec.rb
spec/search_builders/argo/date_field_queries_spec.rb

Andrew would like us to get away from using object label for anything as it's vestigial from Fedora days.   This PR does some of that.
Part of #4262
CI.  There is one code change, which will increase recall when searching for an existing collection.

use object label less

---

spec/requests/workflows_spec.rb

an offshoot of sul-dlss/dor_indexing/pull/25 - this is the only other instance of Dor::Workflow::Document and it is an unused line in a spec.
https://github.com/search?q=org%3Asul-dlss%20Dor%3A%3AWorkflow%3A%3ADocument&type=code

Dor::Workflow::Document is no more

---

app/models/solr_document.rb

Note:  Andrew has signed off;  this is ready to go.
Because `sw_author_tesim` is a much worse name and field type than `author_display_ss` for a Solr field only used for display purposes.
And because the new field, author_display_ss, is now fully populated.
I carefully checked and rechecked, and only argo git repo references this Solr field (besides dor_indexer gem).  
I carefully checked and rechecked, and argo only uses this field for search result display and for citation presentation (I searched on the Solr field name, which came up with FIELD_AUTHOR in the SolrDocument, which is only used for search results and citation presentation;  I even searched on "author" as a word, which is the attribute name in SolrDocument, and didn't find any other matches.
I also deployed this branch to …

use author_display_ss for FIELD_AUTHOR in SolrDocument

---

app/controllers/catalog_controller.rb
app/helpers/blacklight_config_helper.rb
solr_conf/conf/solrconfig.xml

Part of sul-dlss/dor_indexing_app/issues/1031
Search the newly populated fields `druid_prefixed_ssi` and `druid_bare_ssi` instead of the old `objectId_tesim` which had both a poor name and a poor field type.
I deployed to qa and searches for druids still worked, with and without prefixes.

replace solr search field objectId_tesim with druid_prefixed_ssi and druid_bare_ssi

---

.gitignore

get rid of this in the `git status` output:
```
Untracked files:
(use "git add <file>..." to include in what will be committed)
public/packs-test/
public/packs/
```
i ran `git status` again, and those `Untracked files` results were gone, without causing any other issues.

.gitignore: ignore compiled js that won't be committed

---

app/services/structure_updater.rb
spec/services/structure_updater_spec.rb

fixes #4334
deployed to stage and followed updated steps to reproduce from [comment on](https://github.com/sul-dlss/argo/issues/4334#issuecomment-1974228931) #4334.
_**note**_: Code Climate must've gotten tripped up when, on a flappy spec, I re-ran only the one failed test, leading to the modified app code lines (and most of the rest of the codebase) not being reported as covered on that first successful CI run (the flappy spec was unrelated to the change in this PR).  Code Climate must've only counted the coverage from the one re-run test after the full suite run?  Then when I re-ran the whole test suite, Code Climate never updated its coverage report.  Likely because the test suite had the same outcome on the same commit hash?  But the failing test in the first commit and the passing …

structure_updater_spec.rb: file and fileset update test completely blank labels

---

app/controllers/catalog_controller.rb
app/helpers/blacklight_config_helper.rb
solr_conf/conf/solrconfig.xml

hold for testing - i think boost values may need to be higher, but easier to tell with sort by relevancy as default.
Part of #4329
This is desired for better search results ... but they do need to be ordered by relevancy, not druid!
I ran some searches in qa.  It certainly made nothing worse.

boost matches on primary author over other contributors in search results

---

app/helpers/blacklight_config_helper.rb
solr_conf/conf/solrconfig.xml
spec/factories/items.rb
spec/features/indexing_identifiers_spec.rb
spec/support/item_method_sender.rb

Related to sul-dlss/dor_indexing/pull/37
QUESTION:  will these tests slow the test suite substantially?  Not sure how to mitigate that, if so.  I'm striving to avoid creating and indexing documents for each test, since they need to be driven through the entire stack.
As discussed in Infra Dev Planning meeting on Tues 3/5/24, this PR introduces some integration tests that allow us to put arbitrary cocina objects into dor-services-app via factory_bot (see spec/factories/items.rb), index them using the Argo indexer (which calls the dor-indexing-app), and then use the Argo UI to search for the objects, ensure the search results are as expected, ditto the facets, blah blah.
I have some tests for tags and for titles in flight, too.  Separate PRs to come.
CI

add some Indexing and search behavior integration tests

---

app/controllers/apo_controller.rb
app/services/collection_title_service.rb

It's really the title for the collection;  we use "name" in speech but it's a bit weird to have the "CollectionNameService" get the data in the title field.
Or maybe I'm too close to the descriptive metadata at the moment.   It's fine if you close this PR and delete the branch if you think CollectionName makes more sense.
CI

CollectionTitleService is new name of CollectionNameService

---

spec/features/indexing_identifiers_spec.rb
spec/features/indexing_tags_spec.rb

Part of #4331
As discussed in Infra Dev Planning meeting on Tues 3/5/24, this PR introduces some integration tests that allow us to put arbitrary cocina objects into dor-services-app via factory_bot (see spec/factories/items.rb), index them using the Argo indexer (which calls the dor-indexing-app), and then use the Argo UI to search for the objects, ensure the search results are as expected, ditto the facets, blah blah.
CI

Tag indexing integration tests all the way through Argo UI

---

spec/features/indexing_tag_facets_spec.rb
spec/features/indexing_tags_spec.rb

- streamline the tag indexing searching tests a bit
- Split out the indexing tag facets tests into their own file as they are the problem children.  
NOTE: I wouldn't expect spec/features/indexing_tags_spec.rb to require javascript to display the edit modal, but it consistently failed without it.
CI

Update tag searching and facets tests

---

Gemfile
Gemfile.lock

We pinned it in #1372 for Rails 5.2.2 compatability. We can get up to date now that we're on rails 7.
Test suite

Unpin sqlite3

---

spec/features/indexing_other_spec.rb
spec/features/indexing_titles_spec.rb

Part of https://github.com/sul-dlss/argo/issues/4331
As discussed in Infra Dev Planning meeting on Tues 3/5/24, this PR introduces some integration tests that allow us to put arbitrary cocina objects into dor-services-app via factory_bot (see spec/factories/items.rb), index them using the Argo indexer (which calls the dor-indexing-app), and then use the Argo UI to search for the objects, ensure the search results are as expected, ditto the facets, blah blah.
CI

add title_indexing_integration feature spec

---

Gemfile.lock

Bump dor-services-client to 14.4.0

Bump dependencies, particularly dor-services-client

---

lib/tasks/argo.rake

This isn't used. We no longer have the VERSION file this operates on.

Remove obsolete version rake task

---

spec/requests/workflow_grid_spec.rb

This was removed from the accessionWF in the workflow-service

Update test to work without accessionWF:descriptive-metadata

---

lib/constants.rb

Add PURL sitemap as release target

---

Gemfile.lock
app/services/milestone_service.rb
spec/presenters/milestones_presenter_spec.rb

Fixes #4387. 
Unit, integration testing on stage. Lifecycle events now do not show "Described".

Do not show Described lifecycle event

---

app/services/admin_policy_persister.rb

closes #4386
Normalizing versioning.

Changes admin policy persister to close version.

---

app/jobs/descriptive_metadata_import_job.rb
app/jobs/generic_job.rb
spec/jobs/apply_apo_defaults_job_spec.rb
spec/jobs/descriptive_metadata_import_job_spec.rb
spec/jobs/generic_job_spec.rb
spec/jobs/manage_embargoes_job_spec.rb
spec/jobs/refresh_mods_job_spec.rb
spec/jobs/set_catalog_record_ids_and_barcodes_job_spec.rb
spec/jobs/set_collection_job_spec.rb
spec/jobs/set_governing_apo_job_spec.rb
spec/jobs/set_license_and_rights_statements_job_spec.rb
spec/jobs/set_source_ids_csv_job_spec.rb

closes #4391
To get rid of local versioning logic.
Unit

Refactor bulk action jobs to use version service.

---

app/components/show/controls_component.rb
spec/features/apo_spec.rb

APOs aren't special. They have to be versioned like every other object.
Unit

Require version to be open to edit APO or create collection.

---

app/controllers/items_controller.rb

VersionService.new needs keyword args.
CI

Use keyword arg for VersionService

---

app/components/show/controls_component.rb
app/controllers/collections_controller.rb
app/presenters/argo_show_presenter.rb
app/views/collections/new.html.erb
spec/requests/create_collections_spec.rb

Resolves #4410 to adjust Create Collection button.
Unit and testing on QA. Passed the `apo_creation_spec` and `collection_create_spec` integration tests. Will require PO testing.

Disable Create collection button only when APO not open and not openable

---

app/services/state_service.rb
spec/services/state_service_spec.rb

Otherwise there is no way to close an item with no files, since accessionWF can no longer be used to close an item.
Per @andrewjbtw 
Unit

Allow closing version 1

---

.circleci/config.yml
README.md
docker-compose.yml
spec/factories/apos.rb
spec/factories/collections.rb
spec/factories/items.rb

DIA is deprecated and not necessary for Argo tests.
Local, CI

Remove dor-indexing-app.

---

app/controllers/workflows_controller.rb
app/models/workflow_status.rb
app/presenters/workflow_presenter.rb
app/views/workflows/_show.html.erb
spec/requests/workflows_spec.rb
spec/views/workflows/_show.html.erb_spec.rb

Fixes #4436 - show workflow context in workflow detail view (if it's there).
Here is what it would look like if there is context:
And no context:
Localhost

show workflow context in workflow view

---

Gemfile
Gemfile.lock
app/controllers/catalog_controller.rb
app/presenters/milestones_presenter.rb
spec/features/add_workflow_to_item_spec.rb
spec/features/collection_manage_release_spec.rb
spec/features/enable_buttons_spec.rb
spec/features/item_catalog_record_id_change_spec.rb
spec/features/item_manage_release_spec.rb
spec/features/item_source_id_change_spec.rb
spec/features/item_view_spec.rb
spec/presenters/milestones_presenter_spec.rb

closes #4438
So that user versions can be tested.
Unit, QA

Display user version when present.

---

.rubocop.yml

Avoid warnings about wrong namespaces.

Fix rubocop namespace

---

app/controllers/workflows_controller.rb
spec/requests/workflows_spec.rb

closes #4450
Let the user know when a problem occurs.
Unit, local

Notifies user when workflow already exists.

---

app/helpers/apo_helper.rb
app/helpers/workflow_helper.rb
app/views/bulk_actions/add_workflow_jobs/_new.html.erb
app/views/workflows/_new.html.erb
spec/features/add_workflow_to_item_spec.rb

closes #4452
Keep users from getting in trouble.
Unit, local

Remove accessionWF and registrationWF from workflows that can be started by user

---

app/jobs/text_extraction_job.rb
app/services/text_extraction.rb
spec/jobs/text_extraction_job_spec.rb
spec/services/text_extraction_spec.rb

We need this for the same reason we need https://github.com/sul-dlss/common-accessioning/pull/1290 
If you start a text extraction workflow like ocrWF that can operate on both currently closed and currently opened versions, you need to know what the state is.  If the object is *not* opened yet, you need to start ocrWF with the next version up (since this is what it will be once opened by `ocrWF:start-ocr`).  If already opened, the current version is correct.
Argo can handle both situations ("text extraction" button in UI only works on already open objects but the job can handle either situation).  This allows for both to work.
CI

text extraction job needs to determine if object is opened or not

---

Gemfile
Gemfile.lock
app/models/report.rb

This dependency is moving out of stdlib in Ruby 3.4 so it must be managed by bundler.
CI

Add csv dependency to bundler

---

app/components/show/controls_component.rb
app/presenters/argo_show_presenter.rb
spec/components/show/controls_component_spec.rb

closes #4497
So that only appropriate buttons appear on the page.
Unit

Inactivates buttons on user versions details page.

---

app/components/show/agreement_component.html.erb
app/components/show/item_component.html.erb
app/components/techmd_component.rb
spec/components/techmd_component_spec.rb
spec/features/version_view_spec.rb

Do not display techmd on user version details page.

---

app/components/show/external_links_component.html.erb
app/components/show/external_links_component.rb
app/controllers/metadata_controller.rb
config/routes.rb
spec/components/show/external_links_component_spec.rb
spec/requests/view_mods_descriptive_metadata_spec.rb

Resolves #4495 to show user version descriptive metadata. Changes the "MODS" button to "Description". 
Unit and stage.

Change description button on item show

---

app/components/version_milestones_component.html.erb
app/components/version_milestones_component.rb
app/presenters/milestones_presenter.rb
spec/components/version_milestones_component_spec.rb

closes #4527
User version details page when latest object version isn't helpful to users.
Unit

Do not link user version when user version is current object version.

---

app/assets/stylesheets/show.scss
app/components/document_title_component.html.erb
spec/features/version_view_spec.rb

closes #4519
The user can't use the lock on a user version.
Unit, QA

Do not render lock on user version detail page.

---

.rubocop.yml
.rubocop_todo.yml
app/components/show/controls_component.html.erb
app/components/show/controls_component.rb
app/components/version_milestones_component.rb
app/controllers/catalog_controller.rb
app/controllers/user_versions_controller.rb
app/helpers/items_helper.rb
app/presenters/argo_show_presenter.rb
app/presenters/milestones_presenter.rb
app/presenters/user_versions_presenter.rb
app/views/catalog/_show_milestones.html.erb
config/routes.rb
spec/components/show/controls_component_spec.rb
spec/components/version_milestones_component_spec.rb
spec/features/version_view_spec.rb
spec/presenters/milestones_presenter_spec.rb
spec/presenters/user_versions_presenter_spec.rb

closes #4528
So that users can hide / restore user versions.
Unit, Stage

Adds Withdraw / Restore buttons.

---

Gemfile
Gemfile.lock

Avoids a bunch of deprecation warnings.

Bump version of erb_lint

---

app/assets/stylesheets/bootstrap-overrides.scss
app/assets/stylesheets/show.scss
app/assets/stylesheets/sul_variables.scss
app/assets/stylesheets/variables.scss
app/components/show/agreement/details_component.html.erb
app/components/show/agreement/overview_component.html.erb
app/components/show/apo/default_object_rights_component.html.erb
app/components/show/apo/details_component.html.erb
app/components/show/apo/overview_component.html.erb
app/components/show/apo/roles_component.html.erb
app/components/show/collection/details_component.html.erb
app/components/show/collection/overview_component.html.erb
app/components/show/item/details_component.html.erb
app/components/show/item/overview_component.html.erb

We move away from using SASS and toward the way bootstrap styles tables.

Use the bootstrap way to border tables

---

app/components/top_navbar_component.html.erb

So that the real controls display on small viewports.

Update the header for narrow viewports

---

app/assets/stylesheets/show.scss

We no longer have the .small class within .argo-show-btn-group

---

app/assets/stylesheets/bulk-actions.scss

the .tab_pane contains the .new_bulk_action, not the other way around

Remove unnecessary style

---

app/assets/stylesheets/errors.scss

Sass makes it harder to know where this css is being used. We can decouple from sass.

Explicitly write bootstrap 5 error classes rather than using sass

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/throbber.scss

No need to include an empty file.

Discard empty stylesheet partial

---

app/assets/stylesheets/show.scss

Bootstrap already sets the table background to white, we don't need to do it again

Remove unnecessary css rule

---

app/assets/stylesheets/show.scss
app/assets/stylesheets/variables.scss

Change background color of agreement & collection type pills

---

app/assets/stylesheets/argo.scss

Bootstrap already provides collapse.  border-spacing is only relevant when border-collapse is separate

Remove unecessary table style

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/registration.scss
app/javascript/controllers/registration_controller.js
app/javascript/controllers/registration_item_row_controller.js
app/javascript/controllers/tag_validation_controller.js
spec/features/item_registration_spec.rb

This avoids sass indirection that does the same thing

Use the bootstrap is-invalid class directly

---

app/components/version_milestones_component.html.erb
app/components/version_milestones_component.rb
spec/components/version_milestones_component_spec.rb

closes #4548
Per @andrewjbtw 
Unit, Andrew

Change to user version links in version history list.

---

app/assets/stylesheets/bootstrap-overrides.scss
app/assets/stylesheets/text-extraction.scss

We no longer set the header this way.  Ensure that .text-cardinal still works

Stop setting --bs-primary-rgb

---

app/assets/stylesheets/text-extraction.scss
app/javascript/controllers/text_extraction_controller.js
app/views/bulk_actions/text_extraction_jobs/_new.html.erb
spec/requests/text_extraction_spec.rb

So we don't need duplicate stylesheets.

Use components from the component-library

---

Gemfile
Gemfile.lock

This is a blocker for Rails 7.1

Upgrade to Puma 6

---

Gemfile
Gemfile.lock

Required before upgrading to Rails 7.1

Upgrade Rspec-rails

---

app/jobs/create_virtual_objects_job.rb

ActiveRecord::Base.clear_active_connections! is deprecated.

Avoid deprecation on clear_active_connections!

---

spec/features/item_source_id_change_spec.rb
spec/features/item_view_spec.rb
spec/features/update_serials_metadata_spec.rb

There are errors in the test suite like:
```
#<InstanceDouble(VersionService) (anonymous)> received unexpected message :closeable? with (no args)
```
but `spec/support/feature_errors.rb` is masking them.

Add missing method mocks

---

.rubocop.yml

Enable newly available rubocop rules

---

app/views/catalog/_constraints.html.erb

Use the ContraintLayoutComponent for query filters

---

Gemfile
Gemfile.lock

This commit is related to a lingering prod board card
CI

Unpin erblint and update it so Argo uses the latest

---

app/components/document_title_component.html.erb
app/components/document_title_component.rb
spec/components/document_title_component_spec.rb
spec/features/user_version_view_spec.rb
spec/features/version_view_spec.rb

Resolves #4608. 
Unit and deploy to QA.

Update version banner with link to latest

---

app/views/report/_document_list.html.erb

Fixes #4630.
These were the only buttons in Argo that were of style `btn-outline-secondary`. 
Local/QA deploy

Make reports buttons blue

---

app/assets/stylesheets/argo.css
app/components/top_navbar_component.html.erb

This will apply Bootstrap's .nav-link:focus-visible style which coordinates with the background

Add .nav-link to links in the header

---

app/components/version_milestones_component.rb
spec/components/version_milestones_component_spec.rb

closes #4631
So that the user is linked to the more useful user version page instead of the less useful version page.
Unit, Andrew

[HOLD] Link version to user version path when version has user version.

---

app/services/text_extraction.rb
spec/requests/text_extraction_spec.rb
spec/services/text_extraction_spec.rb

We do not need to set the `runocrWF` variable in Argo.  This is only used in the end-accession robot to decide if the ocrWF is to be created, but in Argo, we are creating the workflow on demand.  Adding the variable is incorrectly causing ocrWF to be run twice.
~~HOLD pending test on stage~~
Stage

do not need to set runOCR workflow variable

---

app/forms/registration_form.rb
spec/requests/create_new_item_spec.rb

It may be possible to submit the Argo registration form without a workflow selected, likely because the user has selected a new APO, which forces turbo to update options, but those options (which include the workflow drop down menu) are not rendered yet.  It can also happen if you have javascript turned off in your browser.  
This will trigger this HB alert: https://app.honeybadger.io/projects/49894/faults/96948859 and leaves the object in a state where it needs to have the initial workflow (most often `registrationWF`) added to it manually.
This code change will prevent registration from continuing unless there is a workflow option sent.  You will instead get this error message after trying to register (with javascript on or off, since it is done server side):
New spec
Also localhost, by …

do not allow registration without a workflow

---

app/components/show/controls_component.rb
app/services/text_extraction.rb
app/views/bulk_actions/text_extraction_jobs/_new.html.erb
app/views/bulk_actions/text_extraction_jobs/new.html.erb
app/views/text_extraction/_form.html.erb
config/settings.yml
config/settings/test.yml
spec/requests/text_extraction_spec.rb
spec/services/text_extraction_spec.rb

Fixes #4655 and fixes #4656:
1. Enable the Text Extraction button for media objects
2. Add a new feature setting that allows us to turn speechToTextWF for media on/off independently of ocrWF
3. Enable text extraction bulk job to be run on media objects
~~4. Fix some erb_lint deprecations~~ moved to #4674
**Media Object Modal when using "Text Extraction" button:**
**Bulk Action:**
Localhost and new spec

start speechToTextWF for media objects and in bulk jobs

---

app/components/application_component.rb
app/components/workflow_step_status_selector.html.erb
app/components/workflow_step_status_selector.rb
app/components/workflow_update_button.html.erb
app/components/workflow_update_button.rb
spec/components/workflow_step_status_selector_spec.rb
spec/components/workflow_update_button_spec.rb
spec/system/apo_spec.rb
spec/system/open_and_close_a_version_spec.rb

Fixes #4670 - do not show the skip/complete options for workflow steps sdr-ingest-transfer or sdr-ingest-received.  Other steps remain unchanged.
Set to complete button is also hidden for those steps if they are in waiting state.  See screenshots below for examples
Localhost and specs

do not allow sdr-ingest steps to be set to skip or complete

---

.circleci/config.yml
.rubocop.yml
Dockerfile
Gemfile
Gemfile.lock
README.md

To keep pace with Ruby versions.

Bump Ruby to 3.4.1

---

app/views/layouts/blacklight/base.html.erb
app/views/shared/_footer.html.erb

Update Stanford Libraries logos per 2025 brand identity guidelines.
CI, QA

Update Stanford Libraries logos to 2025 versions

---

app/views/layouts/blacklight/base.html.erb

This release has the updated SUL logo but none of the pagination and facet changes.
CI, QA

Use an earlier component library release

---

app/components/new_bulk_action_button_component.html.erb
app/components/new_bulk_action_button_component.rb
app/views/bulk_actions/index.html.erb
spec/requests/bulk_action_spec.rb

Resolves #4710 to strip bulk action form params from future bulk actions.
Request spec; tested by PO

Filter out bulk action form params

---

Gemfile.lock
app/controllers/workflows_controller.rb
app/presenters/workflow_presenter.rb
app/views/workflows/_show.html.erb
spec/presenters/workflow_presenter_spec.rb

I noticed the workflow name itself was not showing in the modal that shows workflow details.  I think this is an improvement.
**Current**
**Updated**
Localhost/CI

show workflow name on modal

---

lib/tasks/argo.rake
spec/factories/apos.rb
spec/factories/items.rb
spec/requests/apo_count_spec.rb

Allows you to work on localhost without hitting errors where the fixture APO is not connected to an actual agreeement.  Instead create each object as it is needed, so it can be properly wired together.
Localhost

bootstrap item/apo/agreement creation to better link together

---

app/javascript/controllers/collection_editor.js
app/views/collections/new.html.erb
spec/system/create_collection_spec.rb

Resolves #4733 to validate Folio HRIDs in new collection form on APO. 
https://github.com/user-attachments/assets/6e07020e-d48e-4e6e-8778-844cec73e183
System test and deploy to QA

Validate HRID in APO create collection form

---

app/services/purge_service.rb
spec/services/purge_service_spec.rb

The actions are handled by calling destroy on the object in DSA. See https://github.com/sul-dlss/dor-services-app/blob/main/app/services/delete_service.rb

Remove redundant purge actions.

---

app/forms/serials_form.rb
app/views/serials/_form.html.erb
spec/forms/serials_form_spec.rb
spec/requests/serials_spec.rb
spec/system/update_serials_metadata_spec.rb

Allow serials form to handle new and old digital serials structures

---

.circleci/config.yml
Gemfile
Gemfile.lock
README.md
compose.yaml
config/database.yml
db/migrate/20160318203331_increase_delayed_job_column.rb
db/schema.rb
db/seeds.rb

Connects to #4743
Includes:
* Change DB config to use Postgres for all envs
* Remove MySQL-ism from DB migration and allow db:migrate to function with Postgres underneath
* Change DB seeding so db:prepare functions like it does everywhere else
* Make web container depend on Postgres in docker compose
* Reflect above changes in README
CI

Switch default database from MySQL to Postgres

---

app/components/bulk_actions_form_component.rb
app/controllers/bulk_actions/export_catalog_links_controller.rb
app/controllers/bulk_actions/export_catalog_links_jobs_controller.rb
app/jobs/export_catalog_links_job.rb
app/models/bulk_action.rb
app/views/bulk_actions/_export_catalog_links_job.html.erb
app/views/bulk_actions/export_catalog_links_jobs/_new.html.erb
app/views/bulk_actions/export_catalog_links_jobs/new.html.erb
app/views/bulk_actions/export_catalog_links_jobs/new.turbo_stream.erb
config/routes.rb
config/settings.yml
spec/jobs/export_catalog_links_job_spec.rb

Resolves #4748 to create bulk action for exporting folio HRIDs and barcodes.
Unit. Reviewed by Andrew on stage.

Bulk action for exporting catalogLinks and barcodes

---

app/forms/serials_form.rb
spec/forms/serials_form_spec.rb
spec/requests/serials_spec.rb
spec/system/update_serials_metadata_spec.rb

Resolves #4766 for digital serials. HOLD until digital serials migrator has run on prod and then merge /deploy.
Deploy to QA

Serials form should only write to catalogLinks

---

Gemfile
Gemfile.lock

See: https://app.honeybadger.io/projects/49894/faults/122116465
This is a new exception that has been occurring in prod and other envs since the last blacklight-hierarchy bump earlier this week. Since Argo is stuck on BL7 for now and we do not know that need the bleeding edge of the hierarchy gem, pin the dependency for now and documented why it is pinned.
CI

Pin blacklight-hierarchy to 6.6.0 to avoid a new exception in 6.7.x

---

app/components/show/item/thumbnail_component.html.erb
app/components/show/item/thumbnail_component.rb
spec/components/show/item/thumbnail_component_spec.rb

See https://stanfordlib.slack.com/archives/C09M7P91R/p1755209369834039
Objects with an image that are of type file for which the image is in hierarchical folder will not show a thumbnail correctly in Argo.  This simply causes argo to not bother trying to show a thumbnail when the object type is file (which is the only one that supports hierarchy).
Specs

do not show thumbnails for file types

---

app/components/show/item/thumbnail_component.rb
spec/components/show/item/thumbnail_component_spec.rb

Follow on from https://github.com/sul-dlss/argo/pull/4828
I messed up, we need to look at the content_type, not the object_type (which is always `item`)
Stage, see https://argo-stage.stanford.edu/view/druid:mh980pm4136 (no thumbnail anymore) vs https://argo-stage.stanford.edu/view/druid:bb226qd5125 (still has a thumbnail)

should look for content_type not object_type

---

app/controllers/catalog_controller.rb

This field isn't populated by the indexer so it is never rendered. This is just cruft.

Remove data quality facet field from configuration

---

app/controllers/apo_controller.rb
spec/requests/registration_spec.rb

Follow up to the prior PR, this now gets the title based on the Cocina instead of the label (which is unreliable)

Use Cocina TitleBuilder for apo list of collections

---

app/views/report/_document_list.html.erb

closes #4244
They were wrapping in unhelpful ways.

Widen select columns modal.

---

app/controllers/items_controller.rb

Change the recommended slack channel when metadata refresh goes badly
