app/helpers/argo_helper.rb
@atz @jmartin-sul This is the hot-fix I applied to argo-prod. It should be merged and deployed the right way.
=> Rescue index_queue_depth if unable to connect to the remote source

README.md
* re-ordered a step (moved `bundle install` a bit later)
* edited language a bit
* removed some unnecessary stuff from the java heap size part
* fixed some file paths
* a bit of additional info from my notes on setting up argo
@mejackreed
=> addendum to Update Readme to reflect setting up Argo in a development environment

.gitignore, Gemfile, Gemfile.lock, README.md, config/environments/development.rb, config/environments/dor_development.rb, config/environments/dor_test.rb, config/environments/test.rb, config/initializers/config.rb, config/initializers/squash_exceptions.rb, config/settings.yml, config/settings/test.yml
This pull request updates the configuration pattern used in Argo by doing the following:
- Install and use the [config](https://github.com/railsconfig/config) gem
- Separating a configuration (not a security vulnerability) from settings which may need to be secure
- Checking in a default view of configured settings
This was done in a way that aims allow backwards compatibility and to not change any current config object accessing. New configs should be documented in `config/settings.yml` with generic value if security is needed.
Developers can add local configurations by creating `config/settings/development.local.yml` that will override only specified keys.
See follow on tickets #47 & #48 for opportunities for enhancement/refactor
Running tests locally without any additional configs …
=> Update config pattern

app/controllers/catalog_controller.rb, solr_conf/conf/solrconfig.xml
* rename the handler in solrconfig.xml (requires re-deploying configuration for the solr instance for the change to take effect)
* update CatalogController to override the default blacklight config value for document_solr_request_handler
once this code change is pulled, the solr config for the relevant instance will have to be redeployed, or the instance won't be able to view detail pages for objects, because it'll be using an undefined handler.
@atz, mind reviewing?
=> rename the default blacklight document handler from "document" to "/document"

.rspec, Gemfile.lock, spec/integration/bulk_jobs_spec.rb
This is intended to get Travis to succeed, as well as skip integration tests when running the regular rspec command.
=> Skip integration tests when running rspec command.

config/settings.yml
since those arethe same across instances, and fine being public
=> use actual values for BULK_METADATA .DIRECTORY and .XML

Gemfile.lock
new dor-services version should fix the errors when loading test fixtures, which should allow unit tests to pass.
a variety of other incidental gem updates.
=> various gem updates, including dor-services

config/deploy.rb
e.g., we'd like to be able to deploy non-develop branches to argo-dev
=> ask for which branch on deploy

.travis.yml
Having a non-working CI bit us (me) here. Note all of the failed travis builds after #89 was merged. This should at least get us back to our failing 5 specs.
https://travis-ci.org/sul-dlss/argo/builds
=> add solr config task back to travis

Gemfile, Gemfile.lock, spec/spec_helper.rb
the addition of this gem allows the user to bundle and run rspec as they normally would, without the need to already have phantomjs installed (now that we use phantomjs for testing).  if phantomjs is already available on the system, nothing is downloaded or installed.
Gemfile was modified as per:  https://github.com/colszowka/phantomjs-gem#usage-with-poltergeistcapybara
spec_helper.rb was modified as per:  https://github.com/colszowka/phantomjs-gem#manual-setup
further info on the gem:  https://github.com/colszowka/phantomjs-gem
=> add phantomjs to the Gemfile, so that installation of phantomjs is handled automatically

lib/tasks/argo.rake
That means on the second attempt, rake perceives it as having been run,
despite the fact that it failed.  The task authors are remiss for pulling
from ENV instead of accepting an actual argument, thereby disguising
from rake the variation in each execution.
=> When repo:load fails, it doesn't get reenabled.

lib/tasks/argo.rake
* print list of files being loaded (in order being loaded)
* have the error handler print the backtrace for each error it handles (instead of just the message)
=> more verbose logging in argo:repo:load

.gitignore, .travis.yml, Gemfile, Gemfile.lock, config/initializers/webmock.rb, config/settings.yml, config/settings/test.yml, config/solr.yml, lib/tasks/argo.rake
This work fixes the failing travis builds by doing the following:
- Allow fixtures to actually load, by using @drh-stanford's suggestion of [mocking wfs requests](https://github.com/sul-dlss/argo/pull/120#issuecomment-154692603)
- needed here was the need to mock both `/dor/*` and `/workflow_archive*` paths a bit differently
- `WebMock` is loaded in the `development` and `test` gem groups, but is disabled in `production` or when you set `Settings.DISABLE_WEBMOCK = true`
- 3981a436035af1296905b1988ce634060d038693 removes an unnecessary setting that is set, and puts the default one in the correct format with trailing `/`
- When `argo:repo:load` 
_Note: With these changes, I don't thing `test.local.yml` is needed for running tests._
Possible enhancements:
- remove argo solr generator, I'm …
=> add webmock to mock workflow-services & fix ci FTW

config/deploy.rb, config/deploy/stage.rb, config/environments/dor_staging.rb, lib/tasks/argo.rake
(similar changes will soon be needed for all other instances).
* _deploy.rb_: `config/environments/` in `:linked_dirs` becomes `config/settings/`, since this is now where per-instance config info lives.
* _deploy.rb_: the post-restart trigger for running the `argo:htaccess` rake task has been removed, as web code deployments don't necessarily coincide with the need for .htaccess refreshing, and the task is run regularly by a cron job anyway.
* _dor_staging.rb_: full paths to cert file and key file are now specified, since they no longer necessarily share a parent directory.  NOTE: a similar change will need to be made in dor_development.rb and dor_production.rb.
* _argo.rake_: `argo:htaccess` rake task now always includes the built-in argo workgroups, and de-dupes the workgroup list.
* …
=> various fixes to correct things preventing argo from deploying properly to stage

README.md, lib/tasks/argo.rake
* _README.md_: update "Install components" section to just use `rake argo:install` now that it works.
* _README.md_: suggest running the tests.
* _argo.rake_: move "WebMock.allow_net_connect!" call from ci task to `argo:jetty:clean` task, since that's what actually always needs it.
=> fixes for installing on laptop

app/controllers/application_controller.rb, app/views/layouts/application.html.erb, app/views/shared/_header_navbar.html.erb, spec/features/full_width_spec.rb
`application.html.erb` locally in argo wasn't even being used. 135cb05 syncs up local layout to reflect Blacklight's (with a minor data attribute added).
af136f5 allows argo to take advantage of Bootstraps fullscreen layout
=> Full screen

app/helpers/argo_helper.rb, app/models/concerns/catkey_concern.rb, app/models/concerns/druid_concern.rb, app/models/solr_document.rb, app/views/catalog/_show_external_links.html.erb, spec/models/concerns/catkey_concern_spec.rb, spec/models/concerns/druid_concern_spec.rb, spec/views/catalog/_show_external_links.html.erb_spec.rb, spec/views/items/_button_link_list.html.erb_spec.rb
This PR initially intended for #123 adds in view specs for link list and button list on show page.
Then 6dac49e drys up `argo_helper.rb` by creating mixed in `SolrDocument` concerns and use already available methods on `SolrDocument`.
In addition, bc2af9b removes legacy mdtoolkit links from sidebar, closes #124
=> Link list updates, with added specs

.gitignore
ignores the `vendor/` folder for locally deployed bundles (i.e., `bundle --path vendor`)
=> ignore locally deployed bundles

spec/features/search_results_spec.rb
i had to do this (on suggestion from @atz) to get things to run properly on my laptop.  otherwise, i get:
```
DN0a2323f8:argo suntzu$ rspec
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's 'rails' settings.
[Coveralls] Outside the CI environment, not sending data.
/Users/suntzu/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load': /Users/suntzu/rails_projects/argo/spec/features/search_results_spec.rb:23: invalid multibyte char (US-ASCII) (SyntaxError)
/Users/suntzu/rails_projects/argo/spec/features/search_results_spec.rb:23: invalid multibyte char (US-ASCII)
/Users/suntzu/rails_projects/argo/spec/features/search_results_spec.rb:23: syntax error, unexpected $end, expecting keyword_end
expect(page).to have_css 'a', …
```
=> specify encoding explicitly so that tests run without error on laptops

Gemfile, app/assets/stylesheets/argo/argo.sass, config/initializers/webmock.rb, config/settings.yml, lib/tasks/argo.rake
these fixes should be relevant to other deployments (argo-dev, argo-prod), but they were first implemented to get stage deployments working.
* _Gemfile_: remove the `:assets` group distinction, since Rails 4 no longer recognizes that group (http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-3-2-to-rails-4-0-gemfile)
* _Gemfile_: take the gems that were listed in `:assets`, and move them out into the general dependencies lists.
* _Gemfile_: since we're here, clean up the lists a little (alphebetize strays, remove commented out dupe entries).
* _config/initializers/webmock.rb_:  limit webmock inititialization to the two environments where it's relevant (instead of just excluding production).
* _settings.yml_: remove `'argo.css'` from the PRECOMPILE list.
* …
=> more fixes to allow deployment to argo-stage et al

README.md
- reference current default branch for travis and coveralls badges
- recommend installing and using Ruby 2.2.2
- outline running CI build and what rake tasks index data into which Solr core. closes #128
=> Update readme to do the following:

Gemfile.lock, app/controllers/apo_controller.rb, app/helpers/apo_helper.rb
Fixes #69
Note that there's no unit tests for a generic APO creation:
https://github.com/sul-dlss/argo/blob/develop/spec/controllers/apo_controller_spec.rb#L29
=> enables a negative selection for the UseLicense in APO registration

app/controllers/items_controller.rb, spec/controllers/items_controller_spec.rb
This fixes #72. It requires `dor-services`. It will *not* work until PR https://github.com/sul-dlss/dor-services/pull/112 is merged.
=> ensure we have new workflows datastream before we index item

config/environments/dor_development.rb
path is specified in settings, no assumption about common parent directory for key and cert.
you'll either need to update your settings (e.g. `development.local.yml`) to specify the path to the cert and key files relative to the argo app root, or you'll need to specify the full path for each.  or, you can pull changes to the private `shared_configs` version, once that PR is merged.  `dor_development.rb` and the appropriate settings file will need to be updated concurrently for things to keep working.
the relevant settings are `Settings.SSL.CERT_FILE` and `Settings.SSL.KEY_FILE`.
@atz @darrenleeweber @mejackreed @drh-stanford @tingulfsen
=> switch to new cert path style

config/environments/dor_development.rb, config/environments/dor_production.rb, config/environments/dor_staging.rb, config/environments/dor_test.rb, config/settings.yml
This addresses the naming issue in #97.
**NOTE** that merging this PR means that we will need to change the shared_configs branches and our local development configurations.
=> rename workflow configuration variables

app/assets/javascripts/modules/button_checker.js, app/controllers/workflow_service_controller.rb, app/helpers/argo_helper.rb, app/helpers/dor_object_helper.rb, app/views/items/_button_link_list.html.erb, config/routes.rb, spec/controllers/workflow_service_controller_spec.rb, spec/features/enable_buttons_spec.rb, spec/helpers/argo_helper_spec.rb, spec/views/items/_button_link_list.html.erb_spec.rb
Buttons will be shown to user, but disabled unless api responses come back as true
Addresses part of #187 
Reduces the number of blocking requests by 6 - 9 requests per show page load, depending on the page and the logic path executed.
=> Refactor render_buttons to use non-blocking ajax requests.

config/routes.rb
This route is missing its controller method. We are no longer using the MODS-specific editor (see #202)
```
curl -X POST --data ''  http://localhost:3000/items/asdf/mods
...
The action &#39;update_mods&#39; could not be found for ItemsController
...
```
=> remove dead POST route to /items/pid/mods

app/assets/stylesheets/registration.css
as per the docs for the jqgrid asset pipeline gem:  https://github.com/jhx/gem-jqgrid-jquery-rails#usage
prior to this fix, i was getting an error when deploying to stage:
```
DEBUG [33c337eb] 	rake aborted!
DEBUG [33c337eb] 	Sprockets::FileNotFound: couldn't find file './ui.jqgrid.css' under '/opt/app/lyberadmin/argo/releases/20151119040508/app/assets/stylesheets' with type 'text/css'
DEBUG [33c337eb] 	/opt/app/lyberadmin/argo/releases/20151119040508/app/assets/stylesheets/registration.css:2
```
i was once again able to deploy `jm_stage-b_testing` after rebasing it off this branch.
actually, now i'm not so sure this is the right thing to do.  is this line supposed to obviate the need for what i'm doing in this PR?
https://github.com/sul-dlss/argo/pull/213/files#diff-f859e2848b07324f808ce1 …
=> fix the way the jqgrid css gets required

Gemfile.lock
While we are at it, update Nokogiri to 1.6.3.3 to address upstream security issues
=> Update mods_display gem to latest, which addresses Ruby 2.2 warnings

fedora_conf/data/hv992ry2431.xml
This is the current version of the `[Internal System Objects]` uber-APO. You will need to reload your developer Fedora instances with it.
=> update Uber-APO with version from production

app/jobs/indexing_job.rb, config/application.rb, lib/indexer.rb
You can now setup things like this:
```ruby
IndexingJob.delay(priority: 1).perform_later(["druid:hj185vb7593"], true, true)
```
Where priorities get set. Priorities should mirror the priorities listed here https://github.com/sul-dlss/argo/issues/231#issue-117911064
=> Move to ActiveJobs

app/views/_user_util_links.html.erb
Fixes #64.
This PR adds an `all` parameter to the `/report/workflow_grid` route. If it is passed in (no value needed), then it will reset the facets (by calling `facet_tree` with no arguments).
=> adds All Workflows link in the header

app/controllers/catalog_controller.rb, app/helpers/argo_helper.rb, app/helpers/robot_helper.rb, app/helpers/value_helper.rb, app/models/argo/access_controls_enforcement.rb, app/models/concerns/apo_concern.rb, app/models/concerns/catkey_concern.rb, app/models/concerns/collection_concern.rb, app/models/concerns/title_concern.rb, app/models/report.rb, app/models/robot.rb, app/models/solr_document.rb, app/models/user.rb, fedora_conf/data/dd327qr3670.xml, fedora_conf/data/druids, fedora_conf/data/fg464dn8891.xml, fedora_conf/data/load_order, fedora_conf/data/pb873ty1662.xml, fedora_conf/data/qq613vj0238.xml, spec/helpers/argo_helper_spec.rb, spec/models/access_controls_enforcement_spec.rb, spec/models/concerns/apo_concern_spec.rb, spec/models/concerns/catkey_concern_spec.rb, spec/models/concerns/collection_concern_spec.rb, spec/models/concerns/title_concern_spec.rb, spec/models/solr_document_spec.rb
This fixes #75. 
The PR consolidates access to the `SolrDocument` APO druid value, for example, by providing a constant for `is_governed_by_ssim`, and a method `apo_id` to read the value. It does this for APO druid, APO title, Collection druid(s), and Collection title(s).
I've marked it work in progress because I need to test it with items that have collections (we currently don't have local fixtures for that).
@mejackreed I tried to address your comment in #75, but I'd like to pair up to review this PR. I have questions about when something is a `SolrDocument` vs. a simple `Hash`, for example.
=> refactor access to authoritative APO and Collection(s) druids and titles

app/controllers/report_controller.rb, app/helpers/workflow_helper.rb, config/routes.rb, spec/controllers/report_controller_spec.rb, spec/helpers/workflow_helper_spec.rb
Closes #73 
Also removes the `GET` verb from this route. This action isn't idempotent, and really shouldn't respond to `GET`
=> Lookup repo for WF reset link

app/controllers/discovery_controller.rb, app/controllers/report_controller.rb, app/models/concerns/csv_concern.rb, app/models/discovery.rb, app/models/report.rb, spec/controllers/discovery_controller_spec.rb, spec/controllers/report_controller_spec.rb, spec/models/discovery_spec.rb, spec/models/report_spec.rb
Fixes #80 
This PR uses the built-in Ruby `csv` package to generate the report downloads for Report and Discovery views, and adds tests. Note that the `ReportController` and `DiscoveryController` suffer from copy-n-paste code.
=> reimplement CSV output for report downloads

Gemfile.lock, app/controllers/apo_controller.rb, spec/controllers/apo_controller_spec.rb, spec/fixtures/apo_defaultObjectRights_clean.xml
This PR removes the data cleanup for registering the APO. This logic/tests are moved into dor-services pending https://github.com/sul-dlss/dor-services/pull/117. If that PR is approved, then I'll update the Gemfile.lock here in this PR
=> dor-services will handle blank parameters for APO definitions

Gemfile, Gemfile.lock
This PR upgrades to the latest `develop` dor-services code which brings in the faraday and net-http-persistent gems, and also upgrades web mock (which the upgrade to dor-services allows to go to 1.23.x)
To correctly use the persistent connections in development, `webmock` must be disabled -- not loaded by bundler at all. To do this, you'll need to comment out the initializer and the Gemfile.
=> upgrade dor-services and webmock

app/models/index_queue.rb, config/initializers/webmock.rb, spec/spec_helper.rb
This PR requires that all specs connect only to localhost or web mocks (via `stub_request`).
In unrelated work, I found that we were connecting to "status.example.edu" so there's a fix to the IndexQueue model and a webmock for that URL.
I've also added a comment about how webmock is used in the different environments
=> Ensure that specs only connect to localhost or webmocks

config/environments/dor_production.rb
line up the prod config with the style of the other instances, so that deployment works.
=> fix cert_file and key_file settings to not assume path is relative to argo app root

app/helpers/value_helper.rb, app/views/catalog/_show_field_list.html.erb, spec/views/catalog/_show_field_list.html.erb_spec.rb
Second attempt to resolve https://github.com/sul-dlss/argo/issues/289
With further discussion, we resolved to remove a value helper method.  This allows blacklight defaults to display the field 'originInfo_date_created_tesim'.  This PR may require view specs to ensure blacklight behavior for this field is consistent with requirements.
=> Remove Solr field helper: value_for_originInfo_date_created_tesim

app/controllers/apo_controller.rb, spec/controllers/apo_controller_spec.rb, spec/spec_helper.rb
This PR fixes #257 and includes tests for registering an APO and collection simultaneous, and does an overhaul of the APO controller spec for clarity.
Also, please note that I've removed the `:save` and `:content` stubs in `spec_helper` as they are obsolete for the current state of the test suite.
=> collection registration should only happen after APO changes

app/controllers/apo_controller.rb
This PR removes the private `reindex` method in `ApoController`. It's no longer used.
=> remove old APO reindex code

app/assets/javascripts/registration/grid.js, app/controllers/registration_controller.rb, app/helpers/registration_helper.rb, app/views/items/register.html.erb, config/routes.rb, spec/controllers/registration_controller_spec.rb, spec/helpers/registration_helper_spec.rb
This PR fixes #320. The JavaScript errors were from AJAX queries that were throwing 500 errors, and from a request timeout to an old URL. I removed that lyberapps-prod URL and deleted the MDSource pulldown (see comments). I also made the `collection_list` route more fault-tolerant when collections referenced in the APO do not exist in Solr and/or DOR. It also now truncates long collection titles. I also made the Workflow pulldown have unique values. Finally, I added spec tests for collection_list and workflow_list routes, neither of which existed prior.
=> fix JavaScript errors in Register Items modal dialog

app/models/user.rb, app/views/catalog/_home_text.html.erb, spec/features/date_range_form_spec.rb, spec/features/full_width_spec.rb, spec/features/indexer_backlog_spec.rb, spec/integration/item_displays_spec.rb, spec/models/user_spec.rb, spec/views/catalog/_home_text.html.erb_spec.rb
Previously HTTP Solr call was initiated on every homepage load. This should be able to shortcircuit some of those.
=> refactor homepage to shortcircuit HTTP Solr call

app/assets/javascripts/jquery.persistentModal.js, app/assets/javascripts/modules/datastream_edit.js, app/assets/stylesheets/argo/argo.sass, app/views/catalog/_aspect_partials/_ds.html.erb
This PR fixes #78. It uses the jQuery validation plugin and jQuery `parseXML` to verify that the XML in the data stream edit modal dialog is parseable before form submission.
=> validate whether the XML can be parsed before form submission

spec/features/workflow_service_creation_spec.rb
This PR will fix the following spec errors in development branches. You'll need to rebuild your test Solr core though:
```
Failures:
1) Item view metadata MD Source is "DOR"
Failure/Error: expect(page).to have_css 'dd', text: 'v1 Unknown Status'
expected to find css "dd" with text "v1 Unknown Status" but there were no matches. Also found "druid:hj185vb7593", "item", "image", "DOR", "Stanford University Libraries - Special Collections", "Fuller Slides", "fuller:M1090_S15_B02_F01_0126", "M1090_S15_B02_F01_0126", "fuller:M1090_S15_B02_F01_0126, uuid:ad2d8894-7eba-11e1-b714-0016034322e7", "Project : Fuller SlidesRegistered By : renzo", "v1 In accessioning", which matched the selector but not all filters.
2) Search results contains appropriate metadata fields
Failure/Error: expect(page).to …
```
=> use a different object to add workflow to

app/assets/stylesheets/argo/argo.sass, app/views/catalog/_aspect_partials/_dc.html.erb, app/views/items/purl_preview.html.erb
This PR fixes #330. See issue for screenshots. It makes the MODS and Dublin Core views use the same style for their `<dl><dt><dd>` data listings
=> Make style consistent between View MODS and Dublin Core

app/controllers/dor/objects_controller.rb, app/helpers/application_helper.rb, app/views/dor/label.html.erb, app/views/dor/objects/create.html.erb, app/views/dor/objects/destroy.html.erb, app/views/dor/objects/edit.html.erb, app/views/dor/objects/index.html.erb, app/views/dor/objects/show.html.erb, app/views/dor/objects/update.html.erb, config/routes.rb, fedora_conf/data/druids, fedora_conf/data/fy957df3135.xml, fedora_conf/data/load_order, spec/controllers/dor/objects_controller_spec.rb, spec/features/search_results_spec.rb
This PR fixes the Register Items exceptions, does some cleanup, and adds a development fixture for the `digitizationWF`. The cleanup is that we were only implementing the create (POST) to `/dor/objects` that's used by the Register Items UI, so I removed the unimplemented routes. I also moved `object_location` from ApplicationHelper to a private method inside the controller. There was also no spec file corresponding to the objects controller, so I created a stub spec.
Fixes #320
=> Fixes Register Items exception for missing method object_location

config/deploy.rb, config/environments/production.rb, config/environments/staging.rb
Closes #372 Closes #333 
- fixes an unlinked secrets.yml file
- deletes a holdover legacy rails configuration
This now enables default Rails exception page handling and works with squash.
Big thanks @eefahy for helping and @drh-stanford for finally coming up with the solution. :clap:
=> Fixing some deploy and configuration issues

app/assets/javascripts/bulk.js
This PR fixes #335 by stripping HTML from the error messages and updating the styling to bootstrap.
=> strip HTML from error messages in bulk update log

Gemfile, Gemfile.lock, app/controllers/items_controller.rb, spec/features/item_source_id_change_spec.rb, spec/features/item_view_metadata_spec.rb, spec/features/report_view_spec.rb, spec/features/search_results_spec.rb, spec/features/view_switcher_spec.rb, spec/integration/report_spec.rb, spec/spec_helper.rb
Closes #84 
Adds in DatabaseCleaner around specs for test cleaning up (specifically works now around WFS actions). If the test is a JS spec it will use `truncation` strategy, for rack based specs it will use `transaction`.
Also removes legacy custom Argo logic for version enforcing in favor of standard DorServices call. Note: this change effects all `ItemController` specs as it removes the outdated `#on_hold` method from that controller.
557abf7b6e6184c1e8951bbf44d4af77e680f188 also adds more specific expectations for for our `allow_any`'s . These greedy mocks seem to cause chaos and don't always decompose between specs.
=> Change source id

config/routes.rb, spec/routing/discovery_routing_spec.rb, spec/routing/report_routing_spec.rb
Closes #400 
The problem here is that classes that subclass `CatalogController` should provide the `facet` resource member route. Since we don't have fixtures in our dev/test data that reach the 10 limit threshold we weren't seeing this bug locally. I added the routing specs so if someone removes the route, our build will fail.
Confirmed this fix on dev.
=> add facet resource route for controllers that subclass CatalogController

app/controllers/application_controller.rb, app/controllers/items_controller.rb, spec/controllers/catalog_controller_spec.rb, spec/controllers/items_controller_spec.rb, spec/controllers/registration_controller_spec.rb
This PR fixes #401 by returning status code 404 when any controller throws out an `ActiveFedora::ObjectNotFoundError`. Previously we were returning status code 500 which causes squash to report missing objects as software bugs.
=> return 404 status code when objects are missing

lib/tasks/argo.rake
This PR upgrades our hydra-jetty instance to the tip of the `7.x-stable` branch which has Fedora 3.8.1 and Solr 4.10.2. See https://github.com/projecthydra/hydra-jetty/issues/40  Addresses #100
=> Upgrade to v7.2.0 of hydra-jetty

app/helpers/argo_helper.rb, spec/helpers/argo_helper_spec.rb
This PR fixes #402. It removes the overridden method `render_facet_value`. This method was added circa 2011 and isn't needed anymore as far as I can tell. To test, I changed the catalog controller to use very short `limit:` parameters (e.g., 2). The APO and Collection facet values are titles (which the original comment said they weren't).
=> remove broken render_facet_value helper

.gitignore, bin/.gitignore
This reverts commit 33fd2395a12df8ffc36442799503efd109d6253f.
I propose this commit gets reverted as it was committed straight to `develop` without going through a review. Furthermore, there are ways to accomplish this for locally for a developer without committing it to a project. I think these two articles should help accomplish this goal.
See:
- https://help.github.com/articles/ignoring-files/#explicit-repository-excludes
- https://help.github.com/articles/ignoring-files/#create-a-global-gitignore
=> Revert "gitignore my local development files"

app/controllers/application_controller.rb, app/controllers/dor_controller.rb, spec/controllers/dor_controller_spec.rb
Closes #434 
Closes #433 
Ports in a new Rails 5 method which gives us a redirect back with a fallback path.
This PR now handles the following cases:
- Within Argo (or another application) following a link to the reindex endpoint will return a user to `:back` or `catalog_index` (show page) (fallback case)
- An external application hitting that endpoint (no "Referer" header) will get a 200 with text body or a 404 with text body
=> enable non-referrer HTTP requests to return appropriate status and body

Gemfile.lock, spec/spec_helper.rb
This is designed to enable SimpleCov coverage reports in ./coverage on laptop development, so that the coverage data can be viewed immediately, regardless of travis/coveralls functionality.  The coveralls functionality should be preserved, according to their website docs, see https://coveralls.zendesk.com/hc/en-us/articles/201769485-Ruby-Rails
A similar example of this working is in the triannon project at:
https://github.com/sul-dlss/triannon/blob/master/spec/spec_helper.rb#L12-L29
And the coveralls reports are working, see:
https://coveralls.io/github/sul-dlss/triannon
=> Enable simplecov with coveralls

app/controllers/catalog_controller.rb
This PR fixes #371 by overriding the `facet.limit` Solr configuration for hierarchical facets. The decision to make the limit's 9999 here is that we're not able to guarantee that the Solr `facet.limit` parameter is appropriately large enough, and on our Solr cluster core it's set to 10.
=> override solr facet.limit configuration for hierarchical facets

app/controllers/items_controller.rb
This PR makes explicit whether to execute a synchronous Solr update (with a `.commit`) or an asynchronous Solr update (without a `.commit` and using the default `commitWithin` value). The default Solr behavior for commiting adds is dependant on its configuration. See https://wiki.apache.org/solr/CommitWithin for details.
In this PR, the default behavior for the `reindex` route is a synchronous index update. This mimics the previous very short `commitWithin` value (1 second) for reindexing. I've added an `asynchronous=true` flag that you can pass `reindex` to skip the commit. Same with the Item routes, it uses synchronous updates since it was using a very short `commitWithin` value.
I've also changed the status value for objects not found to `404`, and added synchronous vs asynchronous …
=> avoid commitWithin when updating index for items controller

app/models/argo/access_controls_enforcement.rb
Makes this consistent with what Blacklight calls things, and could trip up a future someone with confusing similar argument names (but totally different things) for `#apply_gated_discovery`
=> change method param name, not to confuse the future

config/initializers/indexer.rb
this LOG_FILE constant doesn't appear to be referenced anywhere in the application.  additionally, there are log file related things in the settings, so this could be confusing.  seems like the right thing to do is to remove it.
=> drop unused LOG_FILE constant

bin/dump_fedora_pids.rb
simple script that can be copied to a machine running a fedora instance, to be used to dump all the pids in the instance, since risearch is unreliable for that.  results can be used for custom indexing according to instructions in https://github.com/sul-dlss/argo/blob/develop/INDEXING.md
=> add bin/dump_fedora_pids.rb

app/controllers/items_controller.rb, app/views/items/_close_version_ui.html.erb, app/views/items/close_version_ui.js.erb, spec/views/items/_close_version_ui.html.erb_spec.rb
This PR fixes #409. The modal dialog has the type values filled in and uses the style of the other modals. I've also added tests for the presence of the Type pulldown menu.
upon a version close, you'll get a notice:
=> fix severity type pulldown in Close Version UI

app/controllers/dor_controller.rb, app/helpers/argo_helper.rb, spec/controllers/dor_controller_spec.rb, spec/helpers/argo_helper_spec.rb
This PR addresses part of #414. It changes the Republish button to use flash messages on the subsequent `/catalog` page via the standard redirect pattern.
=> change Republish button to use flash message

app/controllers/items_controller.rb, app/views/items/_file.html.erb, app/views/items/file.html.erb, app/views/items/file.js.erb, spec/controllers/items_controller_spec.rb, spec/views/items/_file.html.erb_spec.rb, spec/views/items/file.html.erb_spec.rb, spec/views/items/file.js.erb_spec.rb
This PR fixes #414 for the File modal dialog (the dialog is launched from the file links in the Content section of the show page). Screenshots are in #414. 
I've also added some tests that were absent from the previous implementation. The route is called `file` and I didn't change that. I did migrate the `list_files` call from the view to the controller -- it does SFTP calls. I switched the if statement for `has_been_accessioned?` to skip the WorkflowService call if the file is not marked 'preserve=yes' and `last_accessioned_version` also calls the WorkflowService synchronously.
=> convert Files dialog to new modal infrastructure

app/views/report/workflow_grid.html.erb
This PR partially address #267 by relocating the Robots queue hyperlink to after the view menu
=> remove link styling for robots queue

app/controllers/items_controller.rb, fedora_conf/data/hj185vb7593.xml, spec/controllers/items_controller_spec.rb
This PR partially fixes #416. It adds an after filter Solr commit for embargo update so that the redirect has the correct information in the index to display the left sidebar Embargo information. It also migrates the add_workflow action to this Solr commit after filter. I updated the specs to expect the after filter.
=> add flush_index after filter for embargo_update and add_workflow

app/views/report/workflow_grid.html.erb
=> rearrange partial order for constraint consistency

spec/controllers/items_controller_spec.rb, spec/features/bulk_screen_spec.rb
This removes the "focus" attribute from a couple of tests, which was accidentally left in.
=> Remove cruft from tests.

Gemfile, Gemfile.lock
* specify use of the latest released dor-services 5.x (starting with the now current 5.3.4)
* bundle update dor-services
=> switch to released dor-services version

Gemfile, Gemfile.lock
- Selenium-Webrick is no longer needed, as we use poltergeist
- Unicorn is not needed, we use the default Rails server Webrick
=> Remove outdated dependencies

app/helpers/argo_helper.rb, app/models/user.rb, spec/helpers/argo_helper_spec.rb, spec/models/user_spec.rb
=> Prevent crash when retrieving roles for an APO identifier that is nil.

app/controllers/dor/objects_controller.rb, spec/controllers/dor/objects_controller_spec.rb
This PR fixes #531 by using the dor-services IndexingService to synchronously update the index, without waiting for the reindexing pipeline to engage. @jmartin-sul can you please review this?
=> reindex and commit newly registered objects before returning

config/deploy/prod-a.rb, config/deploy/stage-a.rb
Adds capistrano for new load balancer ready nodes. After I rebuild `argo-stage-b` and `argo-prod-b` to use the remote mysql machine I will clean up these cap environments to deploy both `-a` and `-b` nodes at the same time.
=> cap for stage-a & prod-a

app/controllers/catalog_controller.rb, app/views/catalog/bulk_upload_form.html.erb
Pulled out of https://github.com/sul-dlss/argo/pull/532
The motivation for this is simply consistent use of `@obj` in the catalog controller.  Although other controllers may use `@object`, changing the catalog controller and all it's views to match may be a much bigger task than making the bulk action(s) and views use `@obj`.
This is ready for review and I'm guessing @tingulfsen could review this one.
=> Consistent use of @obj in catalog controller

app/views/catalog/_show_sections/_default_contents.html.erb, app/views/catalog/_show_sections/_default_contents_external_file.html.erb, spec/views/catalog/_show_sections/_default_contents_external_file.html.erb_spec.rb
This PR fixes #485. Since `catalog/_show_sections/_default_contents` is so messy and I wanted to keep the new functionality DRY, I implemented this as a partial `catalog/_show_sections/_default_contents_external_file`. I was able to add unit tests for this partial.
The above screenshot was generated using the following `contentMetadata` for a test object on my laptop
```xml
<contentMetadata type="image" objectId="rn653dy9317">
<resource type="image" sequence="106" id="rn653dy9317_106">
<label>Image 106</label>
<file mimetype="image/jp2" publish="yes" shelve="yes" format="JPEG2000" preserve="yes" size="3305991" id="M1090_S15_B01_F07_0106.jp2">
<imageData width="5102" height="3426"/>
<attr name="representation">uncropped</attr>
<checksum …
```
=> add support for externalFile data in the Contents section of the show page

app/models/user.rb, config/initializers/permissions.rb, lib/tasks/argo.rake, spec/controllers/items_controller_spec.rb, spec/controllers/registration_controller_spec.rb, spec/integration/about_page_spec.rb, spec/integration/apo_spec.rb, spec/integration/item_displays_spec.rb, spec/models/user_spec.rb
Extracted from https://github.com/sul-dlss/argo/pull/532.  This is a minimal change to the Argo permissions to remove an obscure init file and put these values in the User model, where they belong.  This was discussed in slack where a consensus agreed this was a good approach.
The file removed was `config/initializers/permissions.rb` and the values were transferred to
`app/models/user.rb`.  Apart from `lib/tasks/argo.rake`, the `User` model is the only place these values are used in the application.  All other changes are spec files that need the new `User::` namespace to use the values.
As discussed in slack and confirmed by @LynnMcRae , the `dor-*` roles are deprecated (`dor-admin`, `dor-viewer` and `dor-manager`).  Lynn confirmed that these user roles are removed from APO metadata. …
=> Consolidate Argo user groups/roles in the User model

Gemfile, Gemfile.lock, app/controllers/catalog_controller.rb, app/models/solr_document.rb, config/deploy.rb, config/routes.rb, spec/spec_helper.rb
- `solrizer` and `kaminari` are transitive dependencies and don't need to be explicitly declared
- `kgio` was introduced in https://github.com/sul-dlss/argo/commit/c18bd49d4c8e8a548d458a78fa4bf308617eb329, but wasn't removed when `dalli` was.
- `progressbar` was supporting the `reindex_all` rake task, which has since been rewritten without the progress bar.
- `unicode` was introduced when upgrading to blacklight 4 (https://github.com/sul-dlss/argo/commit/924a3a8092af917216df61b770f43a39282eb98e) but we don't seem to be using it
- `rsolr-client-cert` isn't needed with our Solr Cloud setup.
- `daemons` was added at the same time as delayed job, but seems unused (https://github.com/sul-dlss/argo/commit/a7d1a094543ed0b54887baf45e40ecf111dbe6bc)
=> Remove unused dependencies

app/controllers/auth_controller.rb, spec/controllers/auth_controller_spec.rb
Fixes a regression in the `AuthController` where a non-admin could not forget an impersonation.
=> Allow a non-admin to forget an impersonation group

Gemfile, Gemfile.lock, app/controllers/report_controller.rb, app/helpers/argo_helper.rb, app/models/concerns/object_type_concern.rb, app/models/null_user.rb, app/models/report.rb, app/models/solr_document.rb, app/views/catalog/_bulk_index_table.html.erb, app/views/catalog/_show_workflows.html.erb, spec/models/concerns/object_type_concern_spec.rb, spec/models/report_spec.rb
This PR updates Argo to the latest Blacklight 5.x branch 5.18. It does continue use of the SolrDocument mixins for convenience methods. This pulls some of that logic out of the view.
=> Updates Argo to latest 5.x version of Blacklight (5.18.0)

app/controllers/auth_controller.rb, app/models/user.rb, spec/controllers/auth_controller_spec.rb, spec/models/user_spec.rb
I'd be very interested in naming `is_webauth_admin?` something better, either now or in the future.
=> Add User#is_webauth_admin? to distinguish between original and impersonated groups

config/deploy/prod-a.rb, config/deploy/prod-b.rb, config/deploy/prod.rb, config/deploy/stage-a.rb, config/deploy/stage-b.rb
* use same number of workers as CPUs on prod (12/12)
* use half the number of workers as CPUs on stage (4/8)
=> lower default delayed_job worker count

app/controllers/items_controller.rb, spec/controllers/items_controller_spec.rb
When the action is not authorized, the after_action groups will
not do anything.  In it's current form, the action requires
authorization, but when it fails it still triggers after_actions
that run save_and_reindex needlessly.
This should fix #622
=> Add embargo_update to authorized before_action group.

config/environments/dor_development.rb, config/environments/dor_production.rb, config/environments/dor_staging.rb, config/environments/dor_test.rb
was, for example:
```
DEPRECATION WARNING: Dor::Config -- solrizer configuration is deprecated. Please use solr instead.
(called from <top (required)> at /home/travis/build/sul-dlss/argo/config/environments/dor_test.rb:1)
```
Similar edit will be required in our deployed shared_configs.
=> Silence deprecation in configuration

app/controllers/catalog_controller.rb, config/settings.yml
This is necessary in order to work when the server is load balanced. Separate pull requests have been made for the laptop, dev, staging and production configurations.
=> Use shared temporary directory when uploading spreadsheets.

app/controllers/report_controller.rb, app/models/report.rb, spec/controllers/report_controller_spec.rb, spec/models/report_spec.rb
This PR fixes #648 and #627 by adding a registration datetime to the available reporting columns, and fixing the report field `:field` parameters such that they are all symbols and downstream expects them as such. The latter fixes the download functionality.
=> add the Registration datetime to the report columns and fix download

app/helpers/argo_helper.rb, spec/features/enable_buttons_spec.rb, spec/helpers/argo_helper_spec.rb
This PR fixes #634 by changing the disabled/enabled check on the Purge button to use the processing status facet value.
=> only activate Purge button if object is in registered state

app/controllers/report_controller.rb, app/models/report.rb, spec/controllers/report_controller_spec.rb, spec/models/report_spec.rb
`Report#pids` should expect search result fields to be keyed on symbols, not strings.
looks like a minor regression as a result of:  https://github.com/sul-dlss/argo/commit/4b158da1293edccfee8d3ddb8578c1ac55f0c5f5  (a quick test where i reverted that commit fixed the issue, but i doubt reverting the commit is actually the right fix)
i assume report field configs were changed from using strings to symbols for some reason, so i'm guessing the right thing to do here is to fix the `pids` method?
this is deployed to stage, and seems to fix the problem with getting a list of druids from search results for bulk update (but it replaces the branch with the dor-services upgrade that fixes a couple indexing things, so indexing on argo-stage is back to being like argo-prod).
leaving this marked as …
=> fix bulk operations on search results

spec/features/enable_buttons_spec.rb
previously, the test gave false positive.  This was confirmed when fixing the typo made no change.   My changes actually do test something -- changing each "allow" result to return false instead of true in fact makes the test fail as expected.
@jmartin-sul @tingulfsen    this should be a nobrainer merge ...
=> fix test for enabled buttons when services return true

app/jobs/descmetadata_download_job.rb, config/locales/en.yml, spec/jobs/descmetadata_download_job_spec.rb
Closes #714 (hopefully).
This pull request adds a retry to Dor.find in case of timeout. I hope that this can mitigate some of the errors we are seeing with the descriptive metadata download function. Given the current time constraints our team is facing, I am implementing a pretty simple fix. If this does not help, some more time consuming debugging will be required.
=> Retry DOR connections when downloading descriptive metadata in bulk.

config/initializers/delayed_job.rb
30 minutes is not enough time for e.g. descriptive metadata download jobs to complete when thousands of objects are selected. Let's bump the max runtime.
=> Extend maximum runtime for Delayed Job to a much larger value.

app/controllers/items_controller.rb, spec/controllers/items_controller_spec.rb
fixed #725 by loading the object using `Dor.find` instead of `Dor::Item.find`
Bug was when you edited a datastream directly in argo, upon saving, the object would always be indexed in Solr as an item.  Now, it's actually indexed as its object type.
paired w/ @ndushay, who got us to add some `puts` statements and find an items_controller indexing bug much more quickly than if i'd kept being perplexed about why dor-indexing-app didn't seem to be getting indexing messages (but i'm still perplexed about that, and will file an investigation ticket for it).
=> apo indexing fix

app/controllers/catalog_controller.rb, app/views/catalog/_bulk_index_table.html.erb, config/settings/test.yml, spec/controllers/catalog_controller_spec.rb, spec/fixtures/bulk_upload/workspace/druid:bc682xk5613/2016_04_21_16_56_40_824/crowdsourcing_bridget_1-MODS.xml, spec/fixtures/bulk_upload/workspace/druid:bc682xk5613/2016_04_21_16_56_40_824/log.csv, spec/fixtures/bulk_upload/workspace/druid:bc682xk5613/2016_04_21_16_56_40_824/log.txt, spec/fixtures/bulk_upload/workspace/druid:bc682xk5613/2016_04_21_17_08_53_345/log.txt, spec/fixtures/bulk_upload/workspace/druid:bc682xk5613/2016_04_21_17_22_16_520/log.csv, spec/fixtures/bulk_upload/workspace/druid:bc682xk5613/2016_04_21_17_22_16_520/log.txt, spec/fixtures/bulk_upload/workspace/druid:bc682xk5613/2016_04_21_17_34_02_445/log.csv, spec/fixtures/bulk_upload/workspace/druid:bc682xk5613/2016_04_21_17_34_02_445/log.txt, spec/fixtures/bulk_upload/workspace/druid:bc682xk5613/2016_05_02_22_39_44_008/log.csv, spec/fixtures/bulk_upload/workspace/druid:bc682xk5613/2016_05_02_22_39_44_008/log.txt.moved, spec/jobs/descmetadata_download_job_spec.rb, spec/models/bulk_action_spec.rb, spec/views/catalog/_bulk_index_table.html.erb_spec.rb
* CatalogController#load_bulk_jobs: coerce sort field to string to prevent ArgumentError
* _bulk_index_table.html.erb: prevent nil String references when job['dir'] is nil
resolve #734 
resolve sul-dlss/media#45
=> prevent 500 error when a bulk job log file is missing

app/jobs/descmetadata_download_job.rb, spec/jobs/descmetadata_download_job_spec.rb
=> Save metadata in bulk downloaded zip files with the .xml extension.

app/helpers/registration_helper.rb, app/views/items/register.html.erb, spec/helpers/registration_helper_spec.rb
also, cleaned up the code and wrote tests.
deployed to stage.  appears to be working, but would be good to get someone who knows their way around item registration better to take a look.  @LynnMcRae or @blalbrit?
for the reviewers, i tried to break things into logical commits, and to do something similar to PR #760.
also, FWIW, the solr query requests now look something like this, according to the logs:
```
https://[host]/argo_stage/select?wt=ruby&q=apo_register_permissions_ssim:"sunetid:apanopte"+OR+apo_register_permissions_ssim:"workgroup:sdr:administrator-role"+OR+apo_register_permissions_ssim:"workgroup:dlss:lyberteam"+OR+apo_register_permissions_ssim:"workgroup:dlss:developers"&fq=objectType_ssim:adminPolicy&fq=!tag_ssim:"Project+:+Hydrus"&rows=99999&fl=id,tag_ssim,dc_title_tesim&star …
```
=> fix population of item registration apo select box

bin/dump_fedora_pids.rb
i tried to retrieve the full pid list on dor-test yesterday (in the course of discussing indexing w/ @eefahy).  i ran into permissions issues, and eventually figured out that file writing privileges had to be granted to the fedora mysql user (which i'd previously discovered when first writing the script, but had failed to include in the explanation).
added comments that would've been helpful in sorting out the problem yesterday.
=> dump_fedora_pids.rb: update top level documentation comments

spec/helpers/items_helper_spec.rb
@jmartin-sul   This is a better fix for the problem than #775
Closes #774
=> items_helper_spec: fix failing schema validation spec

config/newrelic.yml
previously, `Settings.NEWRELIC.ENABLED` actually only controlled whether profiling info was sent to the collector for dev instances.
`Settings.NEWRELIC.ENABLED` should control whether the agent is enabled and collecting info at all (regardless of rails env), not just whether it reports to the collector in dev.
=> fix newrelic config so that agent can be fully enabled/disabled

app/controllers/catalog_controller.rb, app/helpers/value_helper.rb
Closes #802 
Not sure if the comma separated is ok, but gives us the default blacklight (which is less code to maintain untested)
=> Fixes tag links on show page.

Capfile, Gemfile, Gemfile.lock, config/deploy.rb, config/deploy/prod-a.rb, config/deploy/prod.rb, config/deploy/stage-b.rb, config/deploy/stage.rb
* set honeybadger environment to cap deloyment "stage" (i.e. `dev`, `stage`, `prod`) instead of defaulting to the rails env
* auto-update the instance's shared_configs upon deployment
* consolidate the deployment of stage and prod to a single config/command for each instance, instead of one for each node in the load balanced environment
* minor Capfile `require` cleanup
test deployments to stage and dev with this branch were successful.
=> Deployment improvements

app/assets/stylesheets/argo/profile.scss, app/controllers/profile_controller.rb, app/helpers/application_helper.rb, app/helpers/profile_helper.rb, app/models/argo/profile_queries.rb, app/models/search_builder.rb, app/presenters/profile_presenter.rb, app/views/profile/_document_list.html.erb, app/views/profile/_search_header.html.erb, app/views/profile/_table_row.html.erb, config/routes.rb, spec/controllers/profile_controller_spec.rb, spec/features/profile_spec.rb, spec/helpers/profile_helper_spec.rb, spec/models/profile_queries_spec.rb, spec/models/search_builder_spec.rb
This PR adds the base functionality for creating our Results Profile (formerly "Collection Profile").
The idea here is that the rest of the functionality can be built off of this. Lays down the base work for #204 
Closes #836 
Partially addresses #838
=> Adds base functionality for Profiling

lib/constants.rb, spec/views/bulk_actions/_form.html.erb_spec.rb
=> update release tag capitalization to new standard

config/deploy.rb
so tasks show up in `cap -T` output
suggested by @eefahy after she tried to find a task for the eye restart but didn't see anything about when running `cap -T`
=> config/deploy.rb: descriptions for .htaccess gen and eye restart/config tasks

app/models/concerns/collection_concern.rb, spec/models/concerns/collection_concern_spec.rb
Fixes https://github.com/sul-dlss/argo/issues/879
=> SolrDocument#collection_titles should return an empty array for objects without collections

Gemfile, Gemfile.lock, app/controllers/registration_controller.rb, app/helpers/apo_helper.rb, app/helpers/registration_helper.rb, app/models/concerns/permitted_queries.rb, app/models/track_sheet.rb, fedora_conf/data/fy957df3135.xml, fedora_conf/data/tm388wy6148.xml, lib/pid_gatherer.rb, lib/tasks/argo.rake, spec/helpers/registration_helper_spec.rb
This fixes fixture data that causes `to_solr` being called on Workflow objects in dor-services 5.17 to fail.
```
Undefined namespace prefix: /oai_dc:dc/*[count(text()) = 0]
```
This PR also updates to dor-services 5.17.x where these fixtures break.
TODO:
=> Use proper MODS for descMetadata for workflow objects

app/models/concerns/permitted_queries.rb, spec/models/concerns/permitted_queries_spec.rb
=> Use RSolr-provided escaping for workgroup values

app/controllers/items_controller.rb
Upstream does:
```ruby
parts = value.split(':').map(&:strip)
raise ArgumentError, "Source ID must follow the format 'namespace:value', not '#{value}'" unless
parts.length == 2 && parts[0].present? && parts[1].present?
```
=> Use upstream logic for validating source ids

app/controllers/catalog_controller.rb, app/controllers/concerns/date_facet_configurations.rb, app/models/search_builder.rb, app/views/catalog/_search_sidebar.html.erb, spec/features/date_range_form_spec.rb, spec/features/home_page_spec.rb, spec/integration/item_displays_spec.rb, spec/models/search_builder_spec.rb
These changes significantly improve Argo home page performance (from 20+ seconds to <10s).
Limiting facets:
Full value list after clicking "More >>"
=> Improve home page performance

Gemfile, Gemfile.lock
the Gemfile edit wasn't strictly necessary for the upgrade itself (could've just done `bundle update`), but i think we do actually want this latest version of dor-services to be the minimum allowable version of dor-services, so it seemed like the right thing to do semantically.
closes #934
=> upgrade to latest dor-services to get new rights type codes

app/helpers/argo_helper.rb, spec/helpers/argo_helper_spec.rb
=> add "refresh descMetadata" blue button to detail pages for objects w/ entry in symphony (i.e. objects w/ catkey)

app/controllers/items_controller.rb, spec/controllers/items_controller_spec.rb
previously, the controller just showed a plaintext success method, as it had only been invokable from the old bulk actions page.
this updates it to keep the same behavior for bulk actions, but for single object update, it now redirects back to the object detail page with a flash message indicating success.  it also guards against invocation on objects without catkeys.
also, tests for all the aforementioned behavior.
and a bit of refactoring to have the standard `after_action` handle saving the updated object, instead of doing it explicitly in the updating controller method.
=> fix refresh descMetadata UI

app/controllers/bulk_actions_controller.rb, app/controllers/items_controller.rb, app/helpers/argo_helper.rb, app/jobs/set_governing_apo_job.rb, app/models/ability.rb, app/models/bulk_action.rb, app/views/bulk_actions/_form.html.erb, app/views/bulk_actions/forms/_set_governing_apo_form.html.erb, app/views/items/_set_governing_apo_ui.html.erb, app/views/items/set_governing_apo_ui.html.erb, app/views/items/set_governing_apo_ui.js.erb, config/routes.rb, spec/controllers/items_controller_spec.rb, spec/features/bulk_set_governing_apo_spec.rb, spec/features/collection_manage_release_spec.rb, spec/features/enable_buttons_spec.rb, spec/features/item_catkey_change_spec.rb, spec/features/item_manage_release_spec.rb, spec/features/item_source_id_change_spec.rb, spec/features/set_governing_apo_spec.rb, spec/helpers/argo_helper_spec.rb, spec/jobs/set_governing_apo_job_spec.rb, spec/models/ability_spec.rb, spec/models/bulk_action_spec.rb, spec/views/bulk_actions/_form.html.erb_spec.rb, spec/views/items/_set_governing_apo_ui.html.erb_spec.rb, spec/views/items/set_governing_apo_ui.html.erb_spec.rb, spec/views/items/set_governing_apo_ui.js.erb_spec.rb
this is getting pretty close to done, so here's a WIP PR, since it's easier to comment on that than on a branch by itself.
here's what's left to do, AFAIK at the moment:
here are some questions i have for what's done so far:
* the APO update (not including saving or reindexing) consists of the following two lines:
```ruby
@object.admin_policy_object = Dor.find(params[:new_apo_id])
@object.identityMetadata.adminPolicy = nil if @object.identityMetadata.adminPolicy # no longer supported, erase if present as a bit of remediation
```
seems like that should be broken out into a common helper method.  or maybe placed in dor-services as a helper method?  it's only two repeated lines, but it seems like it'd be good to centralize them.  then, if other things wanted to update APO, they'd be doing it …
=> Set APO (single object and bulk)

lib/tasks/argo_testing.rake
I think it makes sense for "rake argo:install" to also run the db:migrate tasks in addition to installing Jetty. Currently you have to do this step manually, and it is not documented.
=> Make rake argo:install also do rake db:migrate.

app/jobs/descmetadata_download_job.rb, app/jobs/generic_job.rb, app/jobs/release_object_job.rb, app/jobs/set_governing_apo_job.rb, app/models/bulk_action.rb, spec/jobs/descmetadata_download_job_spec.rb, spec/jobs/generic_job_spec.rb, spec/jobs/release_object_job_spec.rb, spec/jobs/set_governing_apo_job_spec.rb
* append to the log file when opening it instead of truncating it, so that log info from an unsuccessful job attempt isn't lost.
* zero out the success/failure/total druid counts before performing the job, in case this isn't the first time the job is being attempted for a bulk action, so that the job is incrementing fresh counts.
closes #972
=> logging and status count improvements for failed job situations

app/helpers/argo_helper.rb, app/views/items/_button_link_list.html.erb, spec/helpers/argo_helper_spec.rb, spec/views/items/_button_link_list.html.erb_spec.rb
* hide the "Open" and "Close" buttons when the user doesn't have permission to perform those operations (using the same cancan perm check that `ItemsController` uses to determine whether the user can actually perform the operation).
* add a `disabled` flag to the possible button configuration fields, for use instead of `check_url` when it's possible to disable a button without reaching out to another service with a network request (e.g. perm info based on the already loaded dor-services `object`).  #968
* convert instances where `check_url` is used with readily locally available info to use the `disabled` flag instead.  #969
* employ the `disabled` flag for "Refresh descMetadata" button rendering (disabled if obj doesn't allow modification).  #962
* fix check to show/hide "Edit APO" and …
=> argo helper polish

.gitignore, app/jobs/modsulator_job.rb, spec/jobs/modsulator_job_spec.rb
This PR changes the spreadsheet bulk upload to open log files in append mode. This should make it easier to debug production problems when jobs are restarted.
=> Modsulator job append

.jshintrc, INDEXING.md, app/assets/javascripts/bulk.js, app/controllers/dor_controller.rb, app/jobs/local_indexing_job.rb, app/jobs/remote_indexing_job.rb, app/models/bulk_action.rb, app/views/bulk_actions/_form.html.erb, app/views/report/bulk.html.erb, lib/bulk_reindexer.rb, spec/controllers/dor_controller_spec.rb, spec/features/bulk_reindex_spec.rb, spec/features/bulk_screen_spec.rb, spec/jobs/remote_indexing_job_spec.rb, spec/views/bulk_actions/_form.html.erb_spec.rb
there should now be a "Reindex" option when creating a new bulk action.  the "Reindex" command on the old bulk updates page should now be gone.
deployed to stage, did a quick test by reindexing all the workflows using the new bulk action, seemed to work fine.
closes #743
partially addresses #970
=> move bulk reindex from old bulk updates page to new bulk actions framework

app/controllers/catalog_controller.rb
We should wait to merge / deploy until we've fully reindexed Argo with this new field.
=> Add content_file_mimetypes_ssim as a facet field

app/controllers/registration_controller.rb, spec/controllers/registration_controller_spec.rb
RegistrationController#collection_list alpha-sorts (except for leading 'None' entry), so that collection drop-down is alpha-sorted on item registration page.  add corresponding test in registration_controller_spec.rb.
fixes #974
=> alphabetically sort the collection drop-down in the item registration page

app/controllers/items_controller.rb, spec/controllers/items_controller_spec.rb
=> When adding a new catkey, strip whitespace from beginning and end.

Gemfile, Gemfile.lock, app/jobs/descmetadata_download_job.rb
See: https://app.honeybadger.io/projects/49894/faults/37153380#notice-trace
`zip` was previously available by chance as a sub-dependency of `roo`, but `roo` recently was removed, thankfully. Tests continued to pass because `jettywrapper` also included `rubyzip`, but `jettywrapper` is intentionally not included in prod.
=> Resolve dependency error for rubyzip in prod

.travis.yml
This reverts commit b7d7075074721b8fe1288137778b253693d0bc91.
It's unclear why it was needed.
=> Revert "Show me /etc/hosts"

.solr_wrapper.yml
www.us.apache.org only hosts the last point release for the last three
minor releases.
See https://github.com/cbeer/solr_wrapper/pull/119
=> Update to the latest patch version of solr

app/controllers/registration_controller.rb
I believe this error was introduced when we moved away from rsolr-ext.
The current code is passing:
```
"facet.field":"{:fields=>[\"project_tag_ssim\"]}",
```
and Solr retuns a 400 bad request, because that's not the name of a
field.
=> Pass the name of the facet rather than a hash

spec/factories/bulk_action.rb
This avoids a deprecation warning in FactoryBot
=> Static attributes will be removed in FactoryBot 5.0

app/controllers/items_controller.rb, app/views/items/_workflow_view.html.erb
It was discussed at the patch party Nov 2018 that this feature is little used and requires a dependency on GraphViz.  By removing this feature, we can remove the graphviz dependency from dor-services.
=> Remove the diagram generation.

Gemfile, Gemfile.lock, config/boot.rb
Bootsnap precomputes load path resolution and caches ruby ISeq
and YAML parsing/compilation, reducing application boot time by
approximately 50%
=> Add bootsnap to Gemfile

app/forms/apo_form.rb
Previously it was not saving after modifying the object, so the value was never set.
Fixes #1143 
Fixes #807
=> Save after setting the collection

app/assets/stylesheets/argo/document.sass, app/views/catalog/_show_sections/_resource.html.erb
=> Update styles for content file metadata

app/helpers/value_helper.rb, app/views/items/_collection_ui.html.erb, fedora_conf/data/pb873ty1662.xml, spec/controllers/registration_controller_spec.rb, spec/helpers/value_helper_spec.rb, spec/views/items/_collection_ui.html.erb_spec.rb
add a helper for pulling the title out of metadata instead of just using the fedora label; use in edit collection modal
fixes #1006
=> Use metadata object labels instead of fedora object label in edit collection dialog

.travis.yml, README.md, app/controllers/items_controller.rb, config/settings/development.yml, config/settings/test.yml, spec/controllers/items_controller_spec.rb
Fixes #1020
In so doing:
* Stop stubbing the item pid with a bogus pid—this appears to add nothing other than a needless stub
* Use argo core for testing—this allows developers run the test suite with the given docker-compose configuration, simplifying setup
=>  Remove active workflows when object is purged

app/controllers/dor/objects_controller.rb, app/forms/apo_form.rb, app/forms/collection_form.rb, app/services/dor_services/client.rb, spec/controllers/collections_controller_spec.rb, spec/controllers/dor/objects_controller_spec.rb, spec/forms/apo_form_spec.rb, spec/forms/collection_form_spec.rb, spec/integration/apo_spec.rb, spec/services/dor_services/client_spec.rb
Do this instead of using `Dor::RegistrationService` within the `dor-services` gem, which creates a service seam and reduces the reach and impact of `dor-services`.
Note that this makes a small change to an integration spec that used to test two side-effects of `Dor::RegistrationService` that are no longer as easy to test with the new service boundary. We may want to revisit this integration spec if we want the additional assurance this test affords us, say, if dor-services-app is dockerized and added as a dependency of the dev/test environments for Argo.
Fixes #1212
=> Use dor-services-app to register new objects

app/controllers/items_controller.rb, app/views/report/bulk.html.erb, spec/controllers/items_controller_spec.rb
fixes #926 
see latest comments, where the desire is that if the user selects "None" for the collection when bulk setting the collection, it should be removed from items without setting a new one (this actually already happens, but the user gets an error message when a collection with no druid is attempted to be added each time)
=> bulk remove all collections if none is selected

app/controllers/collections_controller.rb, app/views/collections/new.html.erb
* creating a collection makes an ajax call which should not render the layout (else you get JS classes when all of the JS tries to load again)
* also hide the cancel button from an ajax call to be consistent with other modals, since you already have a close modal button and the cancel would have forced a full page reload
=> create collection modal should not render layout from an ajax call

app/controllers/items_controller.rb, spec/controllers/items_controller_spec.rb
build_datastream has a bunch of logic to see if there is a descMetadata.xml file in stacks
that is newer than the datastream and only then calls build_descMetadata_datastream which is
what actually refreshes from the catalog.  This change avoids a bunch of that complexity.
Additionally, there is no need to mess around with the datastream content, becuase
build_descMetadata_datastream takes care of that.
See https://github.com/sul-dlss/dor-services/issues/428#issuecomment-449234431
=> Refactor to avoid checking for a newer file

Gemfile, Gemfile.lock, app/controllers/items_controller.rb, app/helpers/dor_object_helper.rb, app/jobs/modsulator_job.rb, app/jobs/set_governing_apo_job.rb, spec/controllers/items_controller_spec.rb, spec/jobs/modsulator_job_spec.rb, spec/jobs/set_governing_apo_job_spec.rb
Fixes #1277
This changes the way Argo opens and closes versions, using Dor::Services::Client instead of the dor-services gem. The latter path broke recently when we moved away from embedding HTTP basic credentials in strings stored in config (preferring a more explicit approach): the REST client connection used in sul-dlss/dor-services:lib/dor/utils/sdr_client.rb@master#L77, which is created in sul-dlss/dor-services:lib/dor/rest_resource_factory.rb@master#L17 depends on this. Instead of fixing the dor-services approach, use Dor::Services::Client and the dor-services-app HTTP API to open and close versions to continue our move away from the junk drawer (dor-services) approach to the API-centric approach.
=> Use dor-services client & API to open and close versions 

app/helpers/application_helper.rb, app/views/catalog/_report_view_toggle.html.erb, app/views/catalog/_search_form.html.erb, spec/helpers/application_helper_spec.rb
fixes #637 
- refactor current methods that detect which type of results view we are rendering (no need to pass params around everywhere)
- bootstrap off of these methods to send a new search to current view, but default to standard results view (in case we search from item detail page for example)
- remove unnecessary tests for the helper methods (that now just use standard rails methods, don't need params passed and in and thus do not need to be tested in my opinion)
=> search form should send get request to correct spot based on current view

app/controllers/workflows_controller.rb
This was introduced 7 years ago here:
https://github.com/sul-dlss/argo/commit/5d671f0a3c3b0493842410495856bcb1bda03aa9#diff-956e46b33fb5307990c4e1a4b5fd86ccR125
but log analysis shows that this is no longer used.
=> Remove a special case from the workflow controller show

app/presenters/workflow_process_presenter.rb, spec/presenters/workflow_process_presenter_spec.rb
This used to exist:
https://github.com/sul-dlss/argo/blob/bbde9c406d096554d10e74122aa3019b30883890/app/helpers/workflow_helper.rb#L34
But was lost in this code refactor: https://github.com/sul-dlss/argo/commit/59a849cdc3da51bf93527f99d460a3d03a3df6bb
=> Only show buttons for allowable state transfers

Capfile, Gemfile, Gemfile.lock
It's already required by dlss-capistrano
=> Don't explicitly depend on capistrano-shared_configs

.gitignore, .travis.yml, docker-compose.yml
This is necessary because the workflow server image had been updated to require a database.  We also turn off the STOMP notifications.
=> Add a database for the workflow service to the docker build

INDEXING.md, app/controllers/dor_controller.rb, app/models/argo/exceptions.rb, lib/indexer.rb, spec/controllers/dor_controller_spec.rb, spec/jobs/remote_indexing_job_spec.rb, spec/lib/argo/indexer_spec.rb
Argo was the only consumer of that method
Ref sul-dlss/dor-services#535
=> Move reindex_pid_remotely in from dor-services

app/controllers/items_controller.rb, config/routes.rb
This was introduced https://github.com/sul-dlss/argo/commit/8e68e66c775761085496a60e6f72d7b3175f7df7
but that button has since been removed
=> Remove unused create_minimal_mods route

app/helpers/application_helper.rb, app/helpers/bulk_action_helper.rb, app/search_builders/argo/custom_search.rb, spec/helpers/application_helper_spec.rb, spec/helpers/bulk_action_helper_spec.rb
Because it is only used by the BulkActionController
=> Move search_of_pids to BulkActionHelper

app/helpers/argo_helper.rb, app/views/catalog/_show_external_links.html.erb
Otherwise the FoXML has pointers at INTERNAL_ID urls that are not resolvable
=> Link to the archived context of the FoXML

app/forms/apo_form.rb, app/forms/collection_form.rb, spec/forms/apo_form_spec.rb
This parameter was being passed to the registration service, but the registration service does not start the workflow
=> Remove useless workflow_priority parameter

spec/rails_helper.rb, spec/support/selenium_webdriver.rb
Instead of trying to define our own with custom settings. Figure the one built into capybara is probably set up right.
Trying this due to recent failures around chromedriver/webdrivers in travis. In some of my other projects, they have had no problems with the recently released new version of chrome/chromedriver. I am thinking possibly because they use :selenium_chrome_headless instead of defining custom driver configuration.
Cherry-pick from https://github.com/projectblacklight/blacklight/pull/2110
=> Use capybara :selenium_chrome_headless built-in driver definition

lib/constants.rb
This PR adds `Earthworks` as a target for release tags. Content will not be indexed to EarthWorks until this functionality is "turned on" by the access team.
=> Add Earthworks as a release tag target

app/controllers/bulk_actions_controller.rb, app/models/bulk_action.rb, app/services/bulk_action_persister.rb, spec/controllers/bulk_actions_controller_spec.rb, spec/jobs/descmetadata_download_job_spec.rb, spec/jobs/generic_job_spec.rb, spec/jobs/release_object_job_spec.rb, spec/jobs/remote_indexing_job_spec.rb, spec/jobs/set_governing_apo_job_spec.rb, spec/models/bulk_action_spec.rb, spec/services/bulk_action_persister_spec.rb
Previously BulkActions had a bunch of before_create hooks.  This conflated business logic and data model into one class.  This refactoring separates the concerns into two classes which makes testing of models and behaviors easier.
=> Extract BulkActionsPersister from BulkActions

app/controllers/registration_controller.rb
Reverts https://github.com/sul-dlss/argo/commit/931273641a97f1587bdd9df14411d0a8ed905d60#diff-c7642c50c0b5716cfc364d7e3d0b3589R36-R41
This helps remove the dependency on parsing the Fedora 3 XML.
=> Don't need to load from Fedora to find workflows

.travis.yml
Reverts part of https://github.com/sul-dlss/argo/commit/f3cfb15f1e3c177dbad1e82c61ba74ca90d3b882
=> It's no longer necessary to update rubygems

.rubocop_todo.yml, app/controllers/versions_controller.rb, app/jobs/close_version_job.rb, app/jobs/generic_job.rb, app/jobs/manage_catkey_job.rb, app/jobs/prepare_job.rb, app/jobs/virtual_merge_job.rb, app/services/apply_mods_metadata.rb, app/services/version_service.rb, spec/features/item_view_metadata_spec.rb, spec/jobs/manage_catkey_job_spec.rb, spec/jobs/prepare_job_spec.rb, spec/services/apply_mods_metadata_spec.rb, spec/services/version_service_spec.rb
This isolates versioning to a single spot in the codebase.
Done as an extension of work begun as part of #1499
=> Move all version-related functionality to a new service class

app/controllers/bulk_actions_controller.rb, app/controllers/items_controller.rb, app/controllers/versions_controller.rb, app/jobs/prepare_job.rb, app/views/bulk_actions/forms/_prepare_form.html.erb, app/views/versions/_close_ui.html.erb, app/views/versions/_open_ui.html.erb, spec/controllers/versions_controller_spec.rb, spec/jobs/prepare_job_spec.rb, spec/services/bulk_action_persister_spec.rb, spec/views/versions/_close_ui.html.erb_spec.rb, spec/views/versions/_open_ui.html.erb_spec.rb
We call this significance everywhere else. Do this for consistency, so Argo is less of a special case.
=> Rename severity to significance

app/controllers/versions_controller.rb, app/jobs/generic_job.rb, app/jobs/prepare_job.rb, app/services/apply_mods_metadata.rb, spec/controllers/versions_controller_spec.rb, spec/jobs/generic_job_spec.rb, spec/jobs/prepare_job_spec.rb, spec/services/apply_mods_metadata_spec.rb, spec/services/version_service_spec.rb
It has already been removed in dor-services-app: https://github.com/sul-dlss/dor-services-app/pull/349
=> Dump poorly named and unnecessary hash arg when opening versions

app/controllers/bulk_jobs_controller.rb, app/controllers/uploads_controller.rb, app/views/catalog/_bulk_start.html.erb, app/views/uploads/new.html.erb, config/routes.rb, spec/controllers/uploads_controller_spec.rb, spec/features/bulk_jobs_spec.rb
previously it was under the items routes.  This makes it clear that the uploads are for an APO.
=> Move the Upload route under apos

app/services/apply_mods_metadata.rb, spec/services/apply_mods_metadata_spec.rb
This resolve an ArgumentError caused by a combination of:
1. the refactoring in https://github.com/sul-dlss/argo/pull/1518;
1. eating all StandardError in `ApplyModsMetadata#apply`; and
1. insufficient test coverage, which I highlighted in https://github.com/sul-dlss/argo/pull/1518#pullrequestreview-281052275 but did not sufficient flag
And should help resolve a production outage related to bulk jobs.
Fixes #1543
=> Do not call #version_object with arguments

app/assets/javascripts/argo.js, app/assets/stylesheets/argo/argo.sass
This means less custom code in Argo that we need to support.  I think this looks nicer too.
Before:
After:
=> Use the default remove icon

Rakefile, config.ru, config/initializers/secret_token.rb, config/routes.rb
This will go away in Rails 6. See:
```
DEPRECATION WARNING: Using `Rails::Application` subclass to start the server is deprecated and will be removed in Rails 6.0. Please change `run Argo::
Application` to `run Rails.application` in config.ru. (called from <main> at bin/rails:6)
```
=> Replace deprecated Rails application entrypoint

app/jobs/generic_job.rb
`#update` on the prior line already persists the object.
=> Remove an unnecessary `#save`

app/jobs/close_version_job.rb
This is now handled by dor-services-app
See https://github.com/sul-dlss/dor-services-app/pull/352
Fixes #1562
=> Don't create a version when closing an event

.gitignore, .rubocop_todo.yml, app/controllers/items_controller.rb, spec/controllers/items_controller_spec.rb
Fixes #1545;  The vanilla rails error experience here in Argo, if dor-services-app has trouble retrieving metadata from Symphony, did not give enough information to help with debugging.  This does help and also gives the user a better experience.
Note that this is specific to refresh_metadata;  it accommodates UnexpectedResponse errors with any message from dor-services-client, and Andrew approved this "design" here:  https://github.com/sul-dlss/argo/issues/1545#issuecomment-528909307
=> Improve refresh metadata err handling

.rubocop.yml, bin/bundle
Rubocop autocorrect previously mangled this file which caused deploys to break.
See https://github.com/rubocop-hq/rubocop-rails/issues/104
=> Regenerate the bundler binstub and exclude it from rubocop

app/controllers/apo_controller.rb, config/routes.rb, spec/controllers/apo_controller_spec.rb
dor-services hasn't had Item#delete_role for many years, this code doesn't work
and isn't called from anywhere.
=> Remove unused code 'delete_role'

Gemfile, Gemfile.lock, app/controllers/items_controller.rb, app/controllers/report_controller.rb, app/controllers/workflows_controller.rb, spec/controllers/report_controller_spec.rb, spec/controllers/workflows_controller_spec.rb
This method means we no longer have to load workflow templates from Fedora.
=> Switch to the new workflow client update_status method

app/helpers/workflow_helper.rb, config/settings.yml
Because we can't get their step names from the workflow service
Fixes #1616
=> Don't draw the deactivated workflows

app/views/catalog/_show_milestones.html.erb
@andrewjbtw signed off in dlss-infrastructure channel this morning on getting rid of this particular noise in the Argo item view.
You may find it easier to review by commit - the first two commits should have NO functionality change whatsoever;  just easier to read code.
=> Remove unused lifecycles "Indexed" and "Ingested" from display

app/views/report/workflow_grid.html.erb
This fixes a regression where it was always displaying the full grid.
=> Preserve the search parameters when the workflow grid is displayed

README.md, app/jobs/descmetadata_download_job.rb, spec/jobs/descmetadata_download_job_spec.rb
*  check whether user who started the job can view metadata for each object in the job's pid list.  if the user cannot, log the event, skip exporting the metadata for that object, and continue processing the rest.
* corresponding new test for the permission check
* tighten up an existing expectation for the happy path use case (user has permission and all objects in job's pid list are successfully retrieved)
* refactoring/cleanup:
* spec:  turn all the instance vars into `let` vars, turn a local example var into a `let` var (and consolidate on the longer pid list for all the tests)
* job:  remove an unneeded setting of an instance var in the job, and instead rely on the parent class to do setup
i believe this...
closes #1491
=> DescmetadataDownloadJob:  add authorization check for each exported object, miscellaneous cleanup

docker-compose.yml
The new dor-services-app image expects a database.
N/A
=> Hook up dor-services-app to the database

spec/rails_helper.rb, spec/views/files/index.html.erb_spec.rb
CodeClimate has our coverage at 97% ... but ... but it also didn't have coverage stats for helpers. I tweaked the SimpleCov config to hopefully fix this.
I also changed a mock return value in a spec that was ignored.
N/A
=> Coverage fix

Gemfile, Gemfile.lock, app/helpers/dor_object_helper.rb, config/initializers/preservation_client.rb, config/settings.yml, spec/helpers/dor_object_helper_spec.rb
get `last_accessioned_version` from preservation rather than dor-services-app proxying for sdr-services-app.  This PR uses the new preservation-client gem to get the info from a preservation-catalog ReST endpoint.
N/A
=> use preservation-client gem to get last_accessioned_version

Gemfile, Gemfile.lock, app/controllers/workflow_service_controller.rb, app/helpers/apo_helper.rb, spec/features/workflow_service_creation_spec.rb
Instead get them directly from the workflow service. 
This will allow us to remove workflow templates from Fedora
N/A
=> Avoid looking in solr for workflow templates

app/components/action_button.html.erb, app/components/action_button.rb, app/views/items/_button_link_list.html.erb, spec/views/items/_button_link_list.html.erb_spec.rb
Keep code out of the views.
N/A
=> Extract code from views by creating an ActionButton component

spec/features/add_workflow_to_item_spec.rb
The old spec was misleading because this doesn't use the WorkflowServiceController.
N/A
=> Rename a spec for clarity

config/environments/test.rb, spec/features/add_workflow_to_item_spec.rb
previously the caching behavior was preventing this from being tested locally
Test were failing on master.  The cache behavior was preventing all the code from running locally.
N/a
=> Stub out the workflow template client

Gemfile, Gemfile.lock, app/helpers/apo_helper.rb, spec/features/add_workflow_to_item_spec.rb
The previous code was a workaround for shortcomings in dor-services-client.  Now that the shortcomings are addressed, we should use the simpler way.
n/a
=> Use the simpler interface in dor-services-client 3.10

Gemfile.lock
To fix any calls to dor_objects_helper.last_accessioned_version, which was broken, and to fix
n/a
=> preservation-client v0.2.1 fixes bug getting current_version

.rubocop.yml
This helps rubocop start up more quickly, shaving at least a few seconds off the build
n/a
=> Spend less time scanning irrelevant and potentially large directories for Ruby files that are not there

config/initializers/config.rb
this prevents connection errors between the argo service and solr (and likely other services) when spinning up the application for local development via `docker-compose up`.  after #1644, there was a mismatch between what settings names the application expected, and what settings the `docker-compose.yml` file provided in practice via env vars.  instead of connecting to the right container within the docker environment, the argo service was attempting to connect to localhost:8984.  example error before the change:
after the change, i spin up the services via `docker-compose up`, and get a working (blank) argo front page.
N/A
=> fix the names of the Config gem settings that docker-compose.yml overrides via env var (for argo and dor-services-app)

Dockerfile
This is an optimizatiton so we don't need to reinstall bunder evertime we change the Gemfile.lock
=> Install bundler before moving the Gemfile

db/schema.rb
This is the default when you run db:migrate.  it's easer to read
N/A
=> Generate schema with underscore for date separator

.dockerignore, docker-compose.yml
This prevents the errors reported on #1678
specifically this error in the javascript console:
```
Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Missing binding /app/node_modules/node-sass/vendor/linux-x64-72/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 12.x
Found bindings for the following environments:
- OS X 64-bit with Node.js 8.x
This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to download the binding for your current environment.
```
N/A
=> Fix the node_modules mount in docker

app/assets/stylesheets/argo/argo.sass, app/javascript/packs/report.js, app/models/report.rb, app/views/report/_column_selector.html.erb, app/views/report/index.html.erb, docker-compose.yml, spec/features/report_view_spec.rb
fixes #1670 
* jquery update broke our usage of column selectors built into jqgrid
* initial attempts at updating jqgrid were not successful
This replicates the functionality for downloading of reports without the use of jqgrid.  It does not allow for dynamic column selection for display on the screen, but that was deemed not important (downloading is more important).
Todo:
=> bypass jqgrid column selector and just implement in plain html checkboxes

app/controllers/bulk_actions_controller.rb, app/views/bulk_actions/index.html.erb
because notices were not actually being shown to users when bulk actions were created, and should be
n/a
=> actually show notices correctly in bulk actions

app/jobs/generic_job.rb, spec/jobs/prepare_job_spec.rb
When implementing the download report (as csv) job, I realized the current user (which is necessary for running a report) is not being set in a way that can be used.  We need the actual user model object with persisted groups in order to run the job correctly (not just the username persisted in params).
If this is merged, the download job (PR #1688) can be refactored to make use of it.
=> set the current user correctly in job context

app/search_builders/report_search_builder.rb, spec/search_builders/report_search_builder_spec.rb
reports/downloads are allowing users to see items for which they should not have permissions -- add back in the query limitations into the new SearchBuilder
we confirmed this is currently a problem and that this fix works on argo-stage
=> enforce view restrictions for reports

config/initializers/dor_services_client.rb
This was added [recently](https://github.com/sul-dlss/argo/pull/1593) when virtual-merge was a synchronous operation, requiring Argo to hold a connection to dor-services-app open for up to 8 minutes for medium-sized batches. With the [pull request to make virtual-merge asynchronous](https://github.com/sul-dlss/argo/pull/1659) close to being merged, we should remove this; it will no longer be necessary and make in fact mask connection-related issues.
No.
=> Remove Faraday config patch from initializer

Dockerfile, README.md
John and I had problems spinning up the web docker container unless we ran this step manually.
Note: Even though the Dockerfile currently installs Yarn, I had to re-do that before running the compile command, like this:
```yarn```
Not sure why.
Should we update documentation instead?
=> add webpacker compile when building web container

app/search_builders/search_builder.rb
The previous documentation didn't indicate this was a method from Blacklight that was overridden.
Yes
=> Improved method documentation

app/controllers/report_controller.rb, app/controllers/workflows_controller.rb, app/models/ability.rb, spec/controllers/report_controller_spec.rb
The previous restriction was too strict, only allowing admins.
N/A.
=>  Add access control enforcement for reset link 

app/views/report/bulk.html.erb
to fix the issue with the refresh mods button HTML ID not matching the JS code (needs to match https://github.com/sul-dlss/argo/blob/master/app/javascript/packs/bulk.js#L287)
fixes #1707 
n/a
=> fix typo in html for refresh mods button

.travis.yml
We don't need this server up to run tests.
n/a
=> Tests run without dor-services-app

app/javascript/packs/bulk.js
To fix a bug where users inadvertently purged objects when they meant to change content types.  See #1715
=> fix purge bug

lib/tasks/argo_testing.rake
so the `docker-compose run --rm web rake argo:repo:load` can work again
=> allow webmock connections when loading fixtures

.rubocop_todo.yml, app/components/action_button.html.erb, app/components/action_button.rb, app/controllers/items_controller.rb, app/javascript/packs/bulk.js, app/presenters/buttons_presenter.rb, config/routes.rb, spec/controllers/items_controller_spec.rb, spec/presenters/buttons_presenter_spec.rb
The purge action is currently a GET operation.  This is hazardous and it should be a DELETE.  Discovered after work done in #1716 
Also, fixed the problem where a purge from bulk actions was not showing the status correctly (it was silently redirecting to the home page after the purge was done and then showing the status as a 404)
Confirmed working as expected on localhost (both bulk action and single purge from item detail page) and also confirmed a GET request to the purge method no longer works.
=> change purge action from get to delete

app/controllers/workflows_controller.rb, spec/controllers/workflows_controller_spec.rb
The modal currently has a duplicated site header in it.
N/A
=> Don't use a layout when rendering the Add Workflow modal

app/views/collections/new.html.erb
This class caused the modal to have no gutter
Before:
After
n/a
=> Remove class that caused bad layout

app/jobs/create_virtual_objects_job.rb
- allow virtual object bulk actions a much longer time to complete (96 hours, not 48)
- don't retry virtual object bulk actions automatically.  This becomes messy for csv files with many parents, so require a manual retry (hopefully removing completed rows from the csv before rerunning).
@andrewjbtw just want you to be aware of this change, which should deploy on Monday.
n/a
=> virt obj jobs can run long and should not be retried

app/services/virtual_objects_creator.rb
There's enough to look at in honeybadger without having to wonder if something is an error or not.
https://app.honeybadger.io/projects/49894/faults/56341349
n/a
=> clearly indicate when honeybadger message is not an error

app/services/virtual_objects_creator.rb
Removing one superfluous notification (because same info logged three lines up), and removing an INFO-level notification which is only adding noise.
no
=> Quiet honeybadger a bit

Gemfile.lock, app/controllers/files_controller.rb, spec/controllers/files_controller_spec.rb
To get rid of `content` API endpoint in sdr-services-app.  We use preservation-client methods instead, which call equivalent methods in the preservation-catalog API.
n/a, AFAIK
=> Preserved content from pres

app/controllers/dor/objects_controller.rb, app/controllers/workflows_controller.rb, app/forms/apo_form.rb, app/forms/collection_form.rb, app/jobs/release_object_job.rb, spec/controllers/collections_controller_spec.rb, spec/controllers/dor/objects_controller_spec.rb, spec/controllers/workflows_controller_spec.rb, spec/forms/apo_form_spec.rb, spec/forms/collection_form_spec.rb, spec/jobs/release_object_job_spec.rb
Not providing a version is deprecated because it causes the workflow-server to make a request to dor-services-app to look it up
n/a
=> Provide the version when creating the workflow

app/controllers/files_controller.rb, spec/controllers/files_controller_spec.rb
fixes #1745 by encoding the filename in the headers when downloading through argo from the preservation link.
=> Encode the filename when downloading from preservation

Gemfile, Gemfile.lock
It doesn't support the version of mysql we use
n/a
=> Don't allow mysql 0.5.3

Gemfile, Gemfile.lock
Previously it was too permissive in the scoping so automatic updates broke the UI
Fixes #1750 
n/a
=> Revert blacklight-hierarchy to 2.0

app/controllers/files_controller.rb, app/helpers/dor_object_helper.rb, app/views/files/index.html.erb, spec/controllers/files_controller_spec.rb, spec/helpers/dor_object_helper_spec.rb, spec/views/files/index.html.erb_spec.rb
Previously this exception was uncaught which sent the user to the system status page.
n/a
=> Display a useful message to the user when the file is not in preservation

Gemfile, Gemfile.lock, config/initializers/preservation_client.rb, config/settings.yml
HOLD until: 
pres cat will start requiring that all API clients supply an auth token, or their requests will be rejected as Unauthorized.
Fixes #1770
connects to sul-dlss/preservation_catalog#1298
blocks sul-dlss/preservation_catalog#1306
n/a
=> pass auth token to pres-client

app/controllers/workflow_service_controller.rb, app/jobs/generic_job.rb, app/jobs/prepare_job.rb, app/models/dor_object_workflow_status.rb, app/services/apply_mods_metadata.rb, spec/controllers/workflow_service_controller_spec.rb, spec/features/apo_spec.rb, spec/features/item_view_metadata_spec.rb, spec/jobs/generic_job_spec.rb, spec/models/dor_object_workflow_status_spec.rb, spec/services/apply_mods_metadata_spec.rb
This prevents the workflow server from logging deprecation warnings.
n/a
=> Send the current_version when requsting the active lifecycle

Gemfile, Gemfile.lock
Part of #1776 - checksum report problems.   Reports with lots of checksums should no longer error due to uri too long.
n/a
=> preservation-client 3.1 fixes POST for checksums report

app/components/datastream_row.html.erb, app/components/datastream_row.rb, app/helpers/dor_object_helper.rb, app/models/solr_document.rb, app/views/catalog/_datastreams_default.html.erb
Components group methods together better than views + helpers.
n/a
=> Convert Datastream row to a component

app/models/solr_document.rb, spec/models/solr_document_spec.rb
We're deprecating the workflows datastream because it is an external datastream (proxy) and has no analog in a post-Fedora 3 vision.
Part of https://github.com/sul-dlss/dor-services-app/issues/601 
n/a
=> Remove workflows datastream from the datastreams table

Gemfile, Gemfile.lock, app/services/apply_mods_metadata.rb, spec/services/apply_mods_metadata_spec.rb
The Dor::StatusService is deprecated and will be removed
n/a
=> Use the status from the workflow service

app/controllers/workflows_controller.rb, spec/controllers/workflows_controller_spec.rb
This is trying to move us away from the all_workflows_xml method as it is deprecated
n/a
=> Use the models provided by the workflow client

app/controllers/dor/objects_controller.rb, spec/controllers/dor/objects_controller_spec.rb
If this value is set to ['descMetadata'] then the registration service creates descMetadata. Fixes #1792
n/a
=> Pass seed_datastream to the registration service

app/forms/collection_form.rb, spec/controllers/collections_controller_spec.rb, spec/forms/collection_form_spec.rb
=> Use symphony to get the collection descMetadata when providing a catkey

config/deploy/qa.rb
To be able to begin deploying Argo to QA.
Yes, [DevOpsDocs](https://github.com/sul-dlss/DevOpsDocs/pull/359)
=> Add QA environment to capistrano deployment

app/controllers/catalog_controller.rb, app/models/nil_model.rb, spec/features/item_view_metadata_spec.rb
So that you can see the item page even if the cocina model can't be generated.
n/a
=> Handle unexpected response error

app/views/catalog/_show_milestones.html.erb
It is surprising to scroll to the bottom of an object with 30+ versions and see the last entry, which one would reasonably assume to be the latest version, show up as version 9.
I didn't see an obvious place to add a test. Happy to take a suggestion, but I'm not inclined to sink a lot more time into this branch, and sorting of versions right now is doubleplusungood.
no
=> Sort versions as numbers in lifecycle display

lib/tasks/argo_testing.rake, spec/features/consistent_titles_spec.rb, spec/features/date_range_form_spec.rb, spec/features/profile_spec.rb, spec/features/search_results_spec.rb, spec/models/report_spec.rb
dor-services looks in identityMetadata to cast to the correct class.  This is different than the ActiveFedora defaults.  This is important before we move indexing to dor_indexing_app because this how it does the indexing.
n/a
=> Load fixtures using dor-services indexing

app/components/workflow_process_row.html.erb, app/views/report/workflow_grid.html.erb, spec/components/workflow_process_row_spec.rb, spec/components/workflow_step_status_selector_spec.rb, spec/components/workflow_update_button_spec.rb
This old way of calling render has been deprecated
n/a
=> Properly initialize a component

app/helpers/blacklight_config_helper.rb
refs https://github.com/sul-dlss/argo/issues/1828
So that the fields that are searched match the fields that are indexed.
No
=> Updated searched fields to match indexed fields.

Gemfile, Gemfile.lock, app/controllers/catalog_controller.rb, app/views/catalog/_cocina_default.html.erb, spec/features/add_workflow_to_item_spec.rb, spec/features/apo_spec.rb, spec/features/bulk_screen_spec.rb, spec/features/collection_manage_release_spec.rb, spec/features/consistent_titles_spec.rb, spec/features/enable_buttons_spec.rb, spec/features/item_catkey_change_spec.rb, spec/features/item_manage_release_spec.rb, spec/features/item_source_id_change_spec.rb, spec/features/item_view_metadata_spec.rb, spec/features/release_history_spec.rb, spec/features/set_governing_apo_spec.rb
@andrewjbtw would something like this be desirable?  This is the data representation we are going to be moving to as we migrate away from Fedora.  Currently we have only mapped over the things we need to run the robots, so this is incomplete, but it might be helpful in showing how we're doing the mapping.  I'm curious to get your thoughts.
As we move to a cocina based repository, argo users might want to see data as it is represented.
n/a
=> Show the cocina data model on the show page

Gemfile, Gemfile.lock
To get fresh coverage data with every PR (again).
I believe codeclimate was showing us green status for maintainability, but the code coverage has not been updated since dependency updates changed simplecov to v0.18.
Can you see how the graph is dead level after Jan 26?  That is the last week before we upgraded simplecov gem to v0.18.
Note that we won't see the effect of this PR until after it is merged b/c code climate only does its thing for master branch.
n/a
n/a
=> revert simplecov to 0.17 to get current code coverage

Gemfile, Gemfile.lock, app/controllers/catalog_controller.rb, app/views/catalog/_events_default.html.erb, spec/controllers/catalog_controller_spec.rb, spec/features/add_workflow_to_item_spec.rb, spec/features/apo_spec.rb, spec/features/bulk_screen_spec.rb, spec/features/collection_manage_release_spec.rb, spec/features/consistent_titles_spec.rb, spec/features/enable_buttons_spec.rb, spec/features/item_catkey_change_spec.rb, spec/features/item_manage_release_spec.rb, spec/features/item_source_id_change_spec.rb, spec/features/item_view_metadata_spec.rb, spec/features/release_history_spec.rb, spec/features/set_governing_apo_spec.rb
@andrewjbtw here is the event data. Should we stick it on the show page?
So we have a mechanism for using the event data.
n/a
=> Show events on the item show page

config/deploy/prod.rb
The new argo servers are prod-01 and -02, this removes the old (-a, -b) from the capistrano deployment for the new ones.
N/A
I ran a cap prod deploy against this branch and was able to view a druid on prod-01 and prod-02: https://argo-prod-01.stanford.edu/catalog?utf8=%E2%9C%93&q=vq518cf9512 https://argo-prod-02.stanford.edu/catalog?utf8=%E2%9C%93&q=vq518cf9512
=> Add new -01 and -02 prod servers, remove -a and -b

app/controllers/items_controller.rb, app/javascript/packs/bulk.js, config/routes.rb, spec/requests/apply_apo_defaults_spec.rb
This was renamed in dor-services 8.  Also added a test that would have caught this.
fixes #1839 
n/a
no
=> Use the correct method for reapplying APO defaults

config/deploy/prod.rb
This can be reverted once the old servers are removed from the lb pool.
=> We still need to deploy to -a and -b while they are in the pool

app/controllers/items_controller.rb, spec/controllers/items_controller_spec.rb
They are deprecated, because they are just extra indirection.
n/a
no
=> Deprecate the embargoable methods.

app/controllers/items_controller.rb, spec/controllers/items_controller_spec.rb
This removes one direct call to Fedora 3
n/a
yes
It was tested on stage.
=> Update the embargo by calling dor-services-app

app/views/catalog/_facet_limit.html.erb, app/views/catalog/_facet_pagination.html.erb
So to set the DOM selectors as they are required for the blacklight-frontend javascript
Fixes #1849 
=> Override facet_limit

app/controllers/catalog_controller.rb
This will help find and remediate objects that are missing this field we thought was required
Fixes #1864 
n/a
no
=> Add a query for items with no source_id

app/views/catalog/_show_milestones.html.erb
unquoted attributes are not valid.
no
no
=> Unquoted attributes are not legal html

.travis.yml, Gemfile, Gemfile.lock, app/controllers/items_controller.rb, app/forms/apo_form.rb, app/javascript/packs/bulk.js, app/models/report.rb, app/views/items/_tags_ui.html.erb, app/views/report/bulk.html.erb, docker-compose.yml, fedora_conf/data/druids, fedora_conf/data/load_order, fedora_conf/data/pb873ty1662.xml, fedora_conf/data/tj057vk7675.xml, fedora_conf/data/tj057vk7676.xml, fedora_conf/data/tj057vk7677.xml, spec/controllers/content_types_controller_spec.rb, spec/controllers/items_controller_spec.rb, spec/controllers/registration_controller_spec.rb, spec/controllers/versions_controller_spec.rb, spec/controllers/workflows_controller_spec.rb, spec/features/apo_spec.rb, spec/features/filter_facet_spec.rb, spec/features/profile_spec.rb, spec/forms/apo_form_spec.rb, spec/models/report_spec.rb, spec/models/workflow_status_spec.rb, spec/presenters/workflow_presenter_spec.rb, spec/presenters/workflow_xml_presenter_spec.rb, spec/views/items/_tags_ui.html.erb_spec.rb
Connects to sul-dlss/dor-services-app#679
Includes:
* Bump to latest dor-services-client
* Remove outdated docker-compose cruft from Travis CI configuration
* Correct old fixtures now that we have stricter APIs:
* Rename `ti057...` druids to `tj057...` since `i` is not a valid druid character
* Add descMetadata to `pb873...` object, else it no longer has its title indexed due to semi-recent changes to indexing
* Stop using invalid druids (*e.g.*, `oo201...`) in tests
To support SDR evolution goals around administrative tags.
No.
Yes. Tested locally by spinning up affected services in containers and getting the specs to pass. Also: https://github.com/sul-dlss/infrastructure-integration-test/pull/34
=> Use dor-services-app endpoint for administrative tags

app/javascript/modules/apo_form.js, app/views/apo/_form.html.erb
Even custom elements use all lowercase by default.  This enables us to use the erb linter.
no
no
=> Downcase the sharing element

app/services/modsulator_client.rb, config/initializers/okcomputer.rb, config/settings.yml, spec/features/status_spec.rb, spec/rails_helper.rb, spec/support/mock_index_depth.rb
The spec run was making several calls to remote services.
no
no
=> Activate webmock to block unstubbed calls

app/controllers/bulk_jobs_controller.rb, config/routes.rb, spec/features/bulk_jobs_spec.rb
Fixes #1882
To restore functionality that was inadvertently removed years ago but is still useful.
No.
No.
=> Restore bulk job deletion functionality

lib/tasks/argo_testing.rake
The load and index records command:
https://github.com/sul-dlss/argo/blob/master/README.md#load-and-index-records
Fails with:
```
WebMock::NetConnectNotAllowedError: Real HTTP connections are disabled. Unregistered request: POST http://dor-indexing-app:3000/dor/reindex/druid:br481xz7820 with headers {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'Content-Length'=>'0', 'Host'=>'dor-indexing-app:3000', 'User-Agent'=>'rest-client/2.1.0 (linux-gnu x86_64) ruby/2.6.5p114'}
```
Currently. This allows the command to be run properly. 
N/A
No.
=> Update the list of services allowing real http connections

Gemfile, Gemfile.lock
=> Update sass to 6.0

app/controllers/files_controller.rb, app/controllers/items_controller.rb, app/controllers/workflow_service_controller.rb, app/models/dor_object_workflow_status.rb, app/services/milestone_service.rb, app/services/state_service.rb, spec/controllers/workflow_service_controller_spec.rb, spec/models/dor_object_workflow_status_spec.rb, spec/services/state_service_spec.rb
Previously we were making deprecated calls and getting warnings in the logs
no.
no
=> Call dor-workflow-services in a non-deprecated way

app/forms/apo_form.rb, app/forms/collection_form.rb, spec/controllers/collections_controller_spec.rb, spec/features/apo_spec.rb, spec/forms/apo_form_spec.rb, spec/forms/collection_form_spec.rb
Registering APOs and Collections was not compatible with the current version of dor-services-client
no
yes, tested on stage
=> Register APOs and collections with Cocina

app/controllers/dor/objects_controller.rb, spec/controllers/dor/objects_controller_spec.rb
No-download access had been broken.
no
no
=> Handle no-download access appropriately

.rubocop.yml, .rubocop_todo.yml, spec/controllers/report_controller_spec.rb, spec/features/consistent_titles_spec.rb, spec/features/item_view_metadata_spec.rb, spec/features/profile_spec.rb, spec/features/report_view_spec.rb, spec/features/search_results_spec.rb, spec/models/report_spec.rb
This is required to fix the build, because previously fixtures had tag data, but now tags are in their own service.  I've moved the tests that depended on tag data to just depending on what we put in Solr.
no
no
=> Begin decoupling tests from global setup

app/views/files/index.html.erb, app/views/workflows/history.html.erb, app/views/workflows/new.html.erb, app/views/workflows/show.html.erb
The view was incorrect for bootstrap 4.
no
no
=> Fix the button modal for WorkflowView

app/javascript/style/argo.scss
In Bootstrap 4 the font size got bigger making the table overflow the modal.
no
no
=> Make text size for tables in modals be smaller

app/components/workflow_step_status_selector.html.erb, app/components/workflow_update_button.html.erb, app/javascript/jquery.persistentModal.js, app/javascript/modules/permission_add.js, app/javascript/modules/permission_grant.js, app/views/apo/_form.html.erb, app/views/auth/groups.html.erb, app/views/bulk_jobs/_bulk_index_table.html.erb, app/views/catalog/_facet_pagination.html.erb, app/views/catalog/_full_view_links_default.html.erb, app/views/collections/new.html.erb, app/views/files/index.html.erb, app/views/items/_tags_ui.html.erb, app/views/items/embargo_form.html.erb, app/views/tokens/index.html.erb, spec/components/workflow_update_button_spec.rb, spec/views/auth/groups.html.erb_spec.rb
btn-default doesn't exist in bootstrap 4
no
no
=> Convert btn-default to btn-secondary

app/controllers/dor/objects_controller.rb, spec/controllers/dor/objects_controller_spec.rb
Andrew found an error where registering dark objects does not work.
no
no
=> When access is dark download should be none

.travis.yml, Dockerfile
Adds ruby 2.7.1 to travis and Dockerfile
=> Update ruby to 2.7.1 in travis

app/controllers/dor/objects_controller.rb, app/controllers/registration_controller.rb, app/views/items/register.html.erb, lib/constants.rb, spec/controllers/registration_controller_spec.rb
Fixes broken functionality for Citation only registration
no
no
=> Use the correct field for citation-only for cocina registration

.rubocop.yml, Gemfile, Gemfile.lock
There's no reason to lock rubocop any longer as all the cops are now opt-in.
no
no
=> Upgrade rubocop

spec/features/apo_displays_spec.rb
It was confusing that it was testing an APO object, but the test was written to lead you to believe it was an item.
no
no
=> Rename spec to reflect that it's testing an APO not an item

config/initializers/okcomputer.rb, spec/features/status_spec.rb
It's just a host that we link to, not a service that gets called. Remove unnecessary code.
no
no
=> Robot status is not a service we depend on, so don't check it

Gemfile, Gemfile.lock, app/controllers/files_controller.rb, spec/controllers/files_controller_spec.rb
So argo doesn't run out of memory when downloading a large file from preservation.
Fixes #1774
no
Yes, tested on stage.
=> Do streaming download of files from preservation

app/helpers/blacklight_config_helper.rb
The `text` field was the destination of a `copyField` https://github.com/sul-dlss/sul-solr-configs/blob/ae4e469b67912aa08c93f7ea623b7f82ceb4c8b8/argo3_prod/schema.xml#L189
However, we no longer index anything into the source `*_t` for that copyfield.
This causes queryies with wildcards to return no results.
no
no
=> Remove a field we don't use from qf

docker-compose.yml
Adds the redis url in docker compose to dor-services-app so that queues work properly.
N/A
=> Set the proper redis path in docker-compose

app/presenters/buttons_presenter.rb, spec/features/apo_displays_spec.rb, spec/presenters/buttons_presenter_spec.rb
They aren't ever published, so they should always just be dark
no
no
=> Don't allow setting rights on admin policy objects

app/controllers/items_controller.rb, spec/controllers/items_controller_spec.rb, spec/features/set_governing_apo_spec.rb
Fixes #500 - in which we are currently returning forbidden (403) http codes when we should be returning bad_request (400). I believe the remaining 403 returns are valid forbidden responses.
N/A
=> Set proper return codes in items_controller

app/controllers/catalog_controller.rb, app/models/solr_document.rb, app/presenters/milestones_presenter.rb, app/views/catalog/_show_milestones.html.erb, spec/models/solr_document_spec.rb, spec/presenters/milestones_presenter_spec.rb
The model method `get_versions` was only used by the view and there was a lot of code in the view templates. This helps to put this in a class.
no.
no
=> Extract MilestonesPresenter from the view

app/controllers/report_controller.rb, spec/controllers/report_controller_spec.rb
Fixes #794 - without forcing the page to 1 on download, the current page param is sent and used as the initial page.
N/A
No.
=> Set the page to 1 when downloading

app/helpers/argo_helper.rb, app/models/solr_document.rb
The view scope is crowded with methods, move this into a real class where it is encapsulated.
no
no
=> Move the thumbnail url method to the SolrDocument model

app/javascript/registration/register.js, spec/controllers/dor/objects_controller_spec.rb, spec/forms/collection_form_spec.rb
This is no longer used.  This was required for the legacy registration api.
no.
no
=> Remove unused seed_datastream from the registration form

app/controllers/report_controller.rb, app/javascript/controllers/workflow_grid_controller.js
Previously if you hit back after linking from the workflow grid, you would get a partial rendered rather than a full page. I believe this is because Turbolinks was setting the XHR header.  We avoid this problem by switching to a different header for this conditional.
no
no
=> Fix the back button on workflow grid

app/controllers/dor/objects_controller.rb, app/forms/registration_form.rb, spec/forms/registration_form_spec.rb
Dor-services-app sees this as an invalid tag and raises an error.
no
no
=> When registering don't send project as empty string

app/controllers/bulk_actions_controller.rb, app/views/bulk_actions/index.html.erb
Fixes #997 
This adds a "Back to search" button to the top right of the Bulk actions list and utilizes the last search used before bulk actions so that it returns after a new bulk action is created.
N/A
No.
=> Add a "back to seach" button on bulk actions index

app/services/ocr_exporter.rb, spec/services/ocr_exporter_spec.rb
refs https://github.com/sul-dlss/google-books/issues/511
Switch from exporting by page to exporting by zip.
No
No
=> Changes ocr_exporter to work with zips.

.rubocop.yml, app/jobs/manage_catkey_job.rb, app/jobs/release_object_job.rb, app/models/view_switcher.rb, app/presenters/home_text_presenter.rb, app/services/bulk_action_persister.rb
This removes a warning when you run rubocop
no
no
=> Enable new cops for rubocop 0.82

app/components/version_milestones_component.html.erb, app/components/version_milestones_component.rb, app/views/catalog/_show_milestones.html.erb, spec/components/version_milestones_component_spec.rb
This allows us to test the milestones view. It also fixes the collapse behavior which is broken in prod:
no
no
=> Extract a VersionMilestonesComponent

.rubocop.yml, Capfile, Gemfile, Gemfile.lock, README.md, config/deploy.rb, config/eye/delayed_job_workers.eye, lib/capistrano/tasks/delayed_job.rake, lib/capistrano/tasks/yarn.rake
Fixes #768
This commit better documents how Argo uses the eye gem to manage DelayedJob-based background workers. As part of this work, also:
* Stop using the capistrano3-delayed-job gem to manage delayed_job, since it does not have knowledge of eye. Instead, define our own eye-based Capistrano tasks in lib/capistrano/tasks/delayed_job.rake.
* Move custom Argo tasks to lib/capistrano/tasks/*.rake
* Use eye to start, restart, stop, and view status of delayed_job workers
Yes.
No, it does not. I tested the tasks individually, and in the usual deployment flow (both deploy and rollback scenarios), in the QA environment and everything worked flawlessly.
=> Document usage of eye to manage background workers

app/helpers/registration_helper.rb, app/javascript/registration/register.js, app/views/items/register.html.erb, spec/controllers/dor/objects_controller_spec.rb, spec/features/item_registration_spec.rb
We don't keep workflow definitions in Fedora
manually on laptop
none
=> Remove the ability to register a workflow definition

app/views/uploads/new.html.erb
The label didn't point at an input element.
n/a
n/a
=> fix label to point at an existant element

app/controllers/items_controller.rb, app/javascript/packs/bulk.js, app/views/bulk_actions/new.html.erb, app/views/report/bulk.html.erb, config/routes.rb, spec/controllers/items_controller_spec.rb, spec/views/bulk_actions/new.html.erb_spec.rb
To revert a feature change that may not have satisfied the identified requirements. In the meantime, Argo users are having trouble doing bulk tag operations. (Reverting this PR will be part of work done in #2007.)
Tested by infrastructure-integration-tests in staging environment
None.
=> Revert #2008 until we can sort out #2007

app/controllers/bulk_jobs_controller.rb, app/views/bulk_jobs/help.html.erb, app/views/uploads/new.html.erb, config/routes.rb, spec/views/uploads/new.html.erb_spec.rb
Pressing this link raises an error because the partial is not found. I combed through the git history and found it here: https://github.com/sul-dlss/argo/blob/7868d89c7b24aa9aa9389308d1e707ecb5e68d01/app/views/catalog/_bulk_jobs_help
> This page not yet implemented.
n/a
n/a
=> Remove unimplemented help link

Gemfile, Gemfile.lock, spec/forms/apo_form_spec.rb
Fixes #2061 
Tested on stage
none
=> Upgrade dor-services to 9.4.0 so that agreements on APOs are replaceable

app/views/catalog/_show_main_content.html.erb, app/views/catalog/show.html.erb, spec/views/catalog/show.html.erb_spec.rb
This makes it easier to upgrade Blacklight, because customizations are in the expected places
Tested locally
n/a
=> Align argo layouts with the blacklight default layouts

.travis.yml, app/forms/collection_form.rb, spec/forms/apo_form_spec.rb, spec/forms/collection_form_spec.rb
NOTE:  I am first responder starting June 1, and this means Argo MUST be deployed AFTER dor-services-app.  I am aware of this.  dor-services-app updates have already been deployed to qa and stage.
part of issue sul-dlss/dor-services-app/issues/782  - collection registration takes a collection abstract, and we've been populating the mods descMetadata with that abstract in a funky way.  This approach utilizes the new ability of dor-services-app from PR sul-dlss/dor-services-app/pull/893.
Closes sul-dlss/dor-services-app/issues#782
I wrote tests and test-suite passes.
n/a
=> Coll reg fix

app/views/items/_collection_ui.html.erb
An unintended blue stripe is displayed:
Fixes #2081 
Tested locally
none
=> Properly close div tag to prevent unintended blue background

app/controllers/items_controller.rb, app/forms/access_form.rb, app/views/items/_rights.html.erb, spec/controllers/items_controller_spec.rb, spec/forms/access_form_spec.rb, spec/views/items/_rights.html.erb_spec.rb
Fixes #446 
This adds "(APO default)" to the proper rights selection in the modal for setting the rights on an item. If no APO is present, it leaves the list untouched.
Before:
After:
Unit test.
N/A
=> Add default tag to rights for set rights modal in item view

app/views/bulk_jobs/_bulk_index_table.html.erb, spec/views/bulk_jobs/_bulk_index_table.html.erb_spec.rb
fixes #2068 
This should show the status of bulk jobs correctly even if error are shown.
Still need to figure this out, maybe deploy to stage and run a couple example jobs, one with errors, one without.
None needed.
=> correctly show bulk job running status even if errors are present

app/forms/apo_form.rb, app/views/apo/_form.html.erb, spec/forms/apo_form_spec.rb
Use #agreement_object_id instead
Avoids a deprecation warning. Futureproofs the code
Test suite
n/a
=> Stop using deprecated model method #agreement

app/helpers/blacklight_config_helper.rb
These fields would never have good matches for searching.
test suite
n/a
=> Remove nonsensical query fields

.rubocop_todo.yml, app/controllers/catalog_controller.rb, app/models/solr_document.rb, app/presenters/milestones_presenter.rb, app/services/version_service.rb, spec/models/solr_document_spec.rb, spec/presenters/milestones_presenter_spec.rb, spec/services/version_service_spec.rb
So we don't have to have this in dor-indexing-app (inflating the index).  Adapted from https://github.com/sul-dlss/argo/pull/1341
Extracted from https://github.com/sul-dlss/argo/pull/1341/files so that can be closed.
=> Get verison info from the source

config/initializers/dor_config.rb, config/initializers/okcomputer.rb, config/settings.yml, docker-compose.yml, spec/features/item_view_metadata_spec.rb
To reduce confusion about suri configuration settings
test suite
shared_configs for qa, for stage, config files in app (see Files changed), and a PR for shared_configs for prod:  please merge sul-dlss/shared_configs/pull/1381 after this is merged.
=> remove all suri settings from argo (no longer used)

app/components/datastream_row.rb, app/models/solr_document.rb, app/views/catalog/_datastreams_default.html.erb, spec/models/solr_document_spec.rb
This makes the dataflow a lot easier to follow as there's no indirection via dor_indexing_app. This also allows for a smaller solr index. Fixes #2100
Tested locally on my laptop
n/a
=> Draw datastreams without depending on ds_specs_ssim

app/views/catalog/ds.html.erb, config/settings.yml, spec/views/catalog/ds.html.erb_spec.rb
Fixes #1913 
When included in the settings as editable:
When not included in the settings as editable:
Unit test
config/settings.yml updated (no need to update shared_configs)
=> Do not display the edit xml link for datastreams that should not be editable

Gemfile, Gemfile.lock
This will allow argo to get the new versions of cocina-models as they are released and thus automatically be kept in synch with dor-services-app
Test suite
n/a
=> Unpin sdr-client and update dependencies

config/initializers/session_store.rb
In the browser console on Firefox:
```
Cookie “_argo_session” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Cookies
```
This change removes that warning
locally
n/a
=> Fix the sameSite warnings about cookies

lib/tasks/argo_testing.rake
There is no `spec/integrations` folder, and there is no reference to the `integration_tests` rake task anywhere.
test suite
it was self documenting.   :-D
=> remove no-op rake task

.travis.yml, spec/helpers/items_helper_spec.rb
This change means the behavior of the ItemsHelper spec should no longer vary based on system libxml.
Unit tests. (Change should not affect the application otherwise.)
None.
=> Use the bundled Nokogiri instead of underlying libxml version

README.md
To help developers be able to consistently get tests to pass* locally.  (*all but one).
This PR is not "let's reorganize the README and improve it", but is meant as a surgical strike for "here's how to get tests running locally" which has been troubling for a number of developers.  I would ask that *this* PR be reviewed and approved if you think it accomplishes the goal, and additional README updates be ticketed separately (or just make a PR after this one is merged.)
If you want to see the updates formatted, visit https://github.com/sul-dlss/argo/tree/readme-testing
3 of us "clumped" and ran through the steps manually
README
=> README gets dedicated testing section

app/services/workflow_client_factory.rb
https://app.honeybadger.io/projects/49894/faults/62649217
There is a production bug that is very intermittent, but becoming more persistent with larger jobs. This passes the standard logger (i.e. log/production.log) instead of creating a one off.
Local unit tests.
N/A
=> Use standard rails logger for dor-workflow-client

app/views/catalog/_contents_default.html.erb
currently we have the `confirm` attribute set, but we want this to be `data-confirm`
Locally.
n/a
=> Set the correct attribute for data confirmation

app/controllers/files_controller.rb, spec/controllers/files_controller_spec.rb
To fix a bug reported by @oceanofsound and confirmed by @andrewjbtw. The bug has two angles:
1. Argo's files controller begins writing to the response stream before sending the headers, which results in the browser not interpreting the request as a download (but as an inline request, which will render the file in the browser instead of prompting for download location).
2. Once the request has nearly finished, the response stream is not properly closed (possibly because of writing to the response after streaming has begun) and a 500 error is raised.
This branch fixes both bugs by sending headers before writing to the response stream and ensuring the response stream is closed.
Note to @sul-dlss/infrastructure-team reviewers: I'm not sure how to test this in a way that is both resilient and …
=> Enable browser to download files streamed from preservation

app/javascript/packs/application.js
To avoid confusion on the use of the spreadsheet library when working on the reports (spreadsheet-like) view as this particular library is only used to read/write XSL files.
N/A
Inline comment.
=> Add a clarifying comment on the use of the spreadsheet library

app/jobs/checksum_report_job.rb, app/jobs/descmetadata_download_job.rb, app/services/bulk_action_persister.rb, spec/jobs/checksum_report_job_spec.rb, spec/jobs/descmetadata_download_job_spec.rb, spec/services/bulk_action_persister_spec.rb
No functional changes.
This is a simplification. There's no need to pass the output directory to the background job because it's a method on the BatchAction, which the background job is aware of.
Test suite
n/a
=> [Refactor] Stop passing output directory

app/controllers/bulk_actions_controller.rb, app/forms/base_form.rb, app/forms/bulk_action_form.rb, app/models/bulk_action.rb, app/services/bulk_action_persister.rb, app/views/bulk_actions/new.html.erb, spec/controllers/bulk_actions_controller_spec.rb, spec/factories/bulk_action.rb, spec/jobs/descmetadata_download_job_spec.rb, spec/models/bulk_action_spec.rb, spec/services/bulk_action_persister_spec.rb, spec/views/bulk_actions/new.html.erb_spec.rb
No functional changes
This separates responsibility for the form rendering from the model.  This means the model no longer needs to have virtual properties, and can be responsible solely for persistence.
Test suite
n/a
=> [Refactor] Create a BulkActionForm

.travis.yml
We are now deployed on ruby 2.7.1
Travis
n/a
=> Drop ruby 2.6.4 from the build

app/components/download_all_button_component.html.erb, app/components/download_all_button_component.rb, app/views/catalog/_contents_default.html.erb, spec/components/download_all_button_component_spec.rb
And prevent the accordion from collapsing.
Now looks like this:
Fixes #2134
Tested locally
n/a
=> Move the Download All button to the right

.travis.yml
Avoid pulling things we don't need.
Travis
n/a
=> Docker-compose will pull whatever it needs when you do docker-compose up

spec/controllers/report_controller_spec.rb
Reports no longer have pages.  The page is always set to `1`: https://github.com/sul-dlss/argo/blob/master/app/controllers/report_controller.rb#L53
test suite
n/a
=> Remove test of obsolete option

spec/features/apo_displays_spec.rb
These tests aren't useful and don't pertain to the encompassing feature.
test suite
n/a
=> Remove tests that have nothing to do with APO displays

app/helpers/dor_object_helper.rb
Because upstream has made accessibility improvements and the caching from https://github.com/sul-dlss/argo/commit/4a78027fa4da36002666d39aaddf8950a0264c75 is no longer required
Test suite
n/a
=> Remove override of upstream methods

app/helpers/dor_object_helper.rb, app/models/report.rb, app/presenters/date_presenter.rb
No functional changes
Helpers are modules that interface with the view context, but this was used by a model, so moving it elsewhere.
Test suite
n/a
=> Extract report date formatter from helpers

app/helpers/value_helper.rb
To avoid deprecation warnings
Test suite
n/a
=> Avoid using deprecated path_for_facet method

app/controllers/registrations_controller.rb, spec/controllers/registrations_controller_spec.rb
Replace with Logger#warn
Test suite
n/a
=> Logger#warning is not a method

app/controllers/application_controller.rb, app/controllers/bulk_actions_controller.rb, config/application.rb, spec/controllers/catalog_controller_spec.rb, spec/controllers/registrations_controller_spec.rb, spec/controllers/workflows_controller_spec.rb, spec/support/feature_errors.rb
This draws the user-friendly public/404.html.  This is the default behavior in later versions of ActiveFedora.
Test suite
n/a
=> Allow actiondispatch to handle 404 errors

.gitignore, app/forms/collection_form.rb, app/forms/registration_form.rb, app/services/cocina_access.rb, spec/forms/apo_form_spec.rb, spec/spec_helper.rb
When registering a collection from the APO page and selecting a no-download access type
Fixes #2177 
Test suite
n/a
=> Generate the correct access subschema

app/controllers/uploads_controller.rb, app/services/modsulator_client.rb, db/migrate/20200709002946_drop_table_delayed_jobs.rb, db/schema.rb
* drop supporting database table
* clean up stray references in code and comments
* a couple opportunistic touchups on `ModsulatorClient` (better constructor param comment, DRY up logging a bit)
happened to look at the schema and notice the `delayed_jobs` table, which seemed like cruft in light of the switch to sidekiq.
unit tests (i wasn't able to get the unit tests working locally just now, would like to pair on that if someone has time, but this change seemed safe and limited enough that i figured i'd throw up a PR and see if CI passed)
none
=> clean up remaining cruft from delayed_job

app/views/catalog/_datastreams_default.html.erb, config/settings.yml
It does not provide useful information and it is causing clicks to hit lyberservices boxes which we want to get rid of. Requested/approved by @andrewjbtw.
I deployed to stage and confirmed an object that used to show the workflows datastream was no longer shown. https://argo-stage.stanford.edu/view/druid:bb181jh4180 (note: this branch may NOT be on stage when you click the link).
I'm not sure how best to otherwise test this change. View specs are a mess. Tests weren't added or changed when we moved to this component-based approach so :man_shrugging:. @sul-dlss/infrastructure-team  good enough?
New configuration added locally, does not require shared_configs changes.
=> Hide the workflows datastream

app/controllers/datastreams_controller.rb, spec/requests/update_datastream_spec.rb
Fixes #2183 
Show error message on invalid XML when saving a datastream instead of of raising an exception.
Unit test updated.  Tested in browser in localhost.
=> show error message for malformed XML instead of raising an exception

config/settings.yml
Fixes #2196 
In localhost browser
Only a config change
=> restore ability to edit admin metadata

app/views/datastreams/show.html.erb
Fixes #2197.  The datastream info coming from Fedora looks like HTML and the browser is not rendering it.  Adding the `<pre>` tags is not working (it just doesn't render in the browser).  Using a disabled textarea shows the content as is without letting the user change it.
In localhost browser.
None.
=> restore datastream info shown to user

app/controllers/items_controller.rb, spec/controllers/items_controller_spec.rb, spec/requests/set_rights_spec.rb
This allows us to set to citation-only and it eliminates one place where we depend on the legacy ActiveFedora API. Fixes #2190
Tested on staging.
=> Set access using cocina data model

app/controllers/catalog_controller.rb, app/javascript/style/document.scss, app/views/catalog/_cocina_default.html.erb, app/views/catalog/_events_default.html.erb, app/views/catalog/_techmd_default.html.erb
But keep it collapsed
Allow users to begin seeing the new data model.
Tested on staging.
=> Display cocina by default

app/controllers/items_controller.rb, app/forms/collection_form.rb, app/forms/registration_form.rb, app/services/cocina_access.rb, spec/requests/set_rights_spec.rb
Just the properties that the form sets.
Fixes #2215
=> Updating access should not overwrite the entire access subschema

app/forms/bulk_action_form.rb, spec/forms/bulk_action_form_spec.rb
This was broken in the bulk registration PR that omitted the import tags use case. I do not love the spec coverage I added, but it covers the bug this is fixing and beginning to add coverage of the bulk action form which was not covered and allowed this bug to go unnoticed.
CI and local browser testing
None
=> Fix importing of tags

app/controllers/items_controller.rb, app/services/cocina_structural.rb, spec/requests/set_rights_spec.rb
Fixes #2220
See #2220.
CI
None.
=> Disable publish/shelve in content metadata when setting rights to dark

app/controllers/versions_controller.rb, spec/controllers/versions_controller_spec.rb
So we don't need to save the Fedora object directly from Argo.  Dor-services-app will handle the event creation for us
=> Pass user_name to the versions service

spec/factories/collections.rb
Get's rid of this warning:
```
Using the last argument as keyword parameters is deprecated
```
test suite
=> Avoid deprecation warning about kwargs

Gemfile.lock
=> Update openapi parser to avoid warnings about URI.escape

app/views/items/_catkey_ui.html.erb, app/views/items/_collection_ui.html.erb, app/views/items/_collection_ui_line_item.html.erb, app/views/items/_embargo_form.html.erb, app/views/items/_rights.html.erb, app/views/items/_source_id_ui.html.erb, app/views/report/bulk.html.erb, config/routes.rb, spec/features/apo_displays_spec.rb, spec/views/items/_embargo_form.html.erb_spec.rb
Route helpers are the idiomatic rails way of specifying a route.  This is easier to grep for too.
=> Use route helpers

app/helpers/xml/mods-3-7.xsd, app/services/mods_validator.rb
To support the latest MODS descriptive metadata. Requested by @arcadiafalcone and approved by @andrewjbtw 
CI.
None.
=> Upgrade MODS schema to v3.7

config/deploy/qa.rb
Sidekiq is running stale workers in QA.
Deployment.
None
=> Allow capistrano to manage sidekiq workers in QA

yarn.lock
JS dependencies hadn't been updated in a while
* CI
* will push to stage for smoke testing before prod deployment
n/a
=> update javascript dependencies

app/services/bulk_action_persister.rb, app/views/bulk_actions/forms/_manage_catkey_form.html.erb, app/views/bulk_actions/forms/_set_governing_apo_form.html.erb, app/views/bulk_actions/new.html.erb, spec/services/bulk_action_persister_spec.rb
This fixes a regression where bulk manage catkeys was broken.
Fixes #2257
=> BulkActionPersister now handles catkeys

docker-compose.yml
This was a regression in 9a4df0ab86e7995962379ce6db6cc0819bf511dd that made it impossible to run the tests locally
=> Restore url to dor-services for dor-indexing-app in docker-compose

app/controllers/catalog_controller.rb
This will display a list of items that must get fixed before we can migrate to cocina
=> Display a facet for non-conformant source Ids

Gemfile, Gemfile.lock, app/mailers/application_mailer.rb, config/initializers/blacklight.rb
A simple upgrade loaded dependencies out of order and was missing a required constant.
=> Upgrade to Blacklight 7.11

app/jobs/manage_catkey_job.rb, spec/jobs/manage_catkey_job_spec.rb
=> Don't close the object when updating the catkey in bulk

docker-compose.yml
Argo will not show an item page in the browser without a techmd URL configured -- else it tries to use localhost:3005, which is not accessible from the web container.
=> add techmd url in docker-compose

app/controllers/catalog_controller.rb
closes #2297
Blacklight was changed to disallow filtering on non-configured fields. This adds the necessary config.
Stage
NA
=> Adds additional facet field configuration.

app/views/catalog/show.html.erb, spec/views/catalog/show.html.erb_spec.rb
These are some differences between current Blacklight and Argo that @jcoyne and I discovered. This cleans them up.
Locally.
NA
=> Align with current blacklight.

Gemfile, Gemfile.lock
We hit this deprecation warning for each tag (approximately 10,500 times on the index page). So it's imperative that we avoid it for performance.
=> Update blacklight-hierarchy to 4.3.0

app/controllers/items_controller.rb, spec/controllers/items_controller_spec.rb, spec/requests/set_rights_spec.rb
=> Display an error when there is a bad cocina fetch

app/components/workflow_table_component.rb, app/components/workflow_table_process_component.rb
Put them locally in the WorkflowTableProcessComponent
So we stop seeing the deprecation methods.
=> Avoid deprecated method add_facet_params

app/components/application_component.rb, app/components/workflow_table_process_component.rb, spec/components/workflow_table_process_component_spec.rb
Put them locally in the WorkflowTableProcessComponent
So we stop seeing the deprecation methods.
=> Copy deprecated methods out of blacklight-hierarchy

app/views/bulk_jobs/index.html.erb
So we can upgrade blacklight at some time.
=> Avoid using the deprecated method show_presenter

app/views/catalog/show.html.erb, spec/views/catalog/show.html.erb_spec.rb
So we can upgrade blacklight at some time.
=> Avoid using the deprecated method document_show_html_title

solr_conf/conf/schema.xml
This will enable structured data to be indexed, without having to use delimiters as we currently do.
Test suite.
solr_conf/conf/schema.xml
=> Add a field type for structured values.

app/controllers/items_controller.rb, app/jobs/generic_job.rb, app/jobs/manage_catkey_job.rb, app/jobs/set_governing_apo_job.rb, app/services/catkey_service.rb, spec/controllers/items_controller_spec.rb, spec/features/item_catkey_change_spec.rb, spec/jobs/generic_job_spec.rb, spec/jobs/manage_catkey_job_spec.rb, spec/requests/set_catkey_spec.rb
=> Update catkey using the cocina api 

app/controllers/catalog_controller.rb, app/views/catalog/_show_thumbnail.html.erb
The thumbnail partial provided by blacklight was only suitable for the index context as it depends on the @response ivar that is deprecated in the show method
=> Create a show thumbnail partial

app/presenters/argo_show_presenter.rb
This functionality is now in blacklight
=> There is no reason to override the thumbnail presenter

app/controllers/bulk_jobs_controller.rb, app/controllers/catalog_controller.rb, app/models/solr_document.rb, app/presenters/buttons_presenter.rb, spec/features/apo_spec.rb, spec/features/bulk_jobs_spec.rb, spec/features/item_catkey_change_spec.rb, spec/features/item_source_id_change_spec.rb, spec/presenters/buttons_presenter_spec.rb, spec/requests/set_rights_spec.rb
This helps decouple Argo from Fedora 3
=> Decouple ButtonsPresenter from datastreams

app/components/date_choice_facet_component.html.erb
render_hash_as_hidden_fields is deprecated in Blacklight. This provides a way to avoid the deprecation.
=> Use Blacklight::HiddenSearchStateComponent to avoid deprecations

app/jobs/manage_catkey_job.rb, app/services/catkey_service.rb, spec/jobs/manage_catkey_job_spec.rb
closes #2358
Manage catKey bulk action was not supporting blank lines, which are used to remove catKeys.
Unit, stage
NA
=> Support removing catKeys with manage catKey bulk action.

app/controllers/apo_controller.rb, app/controllers/application_controller.rb, app/controllers/catalog_controller.rb, app/controllers/collections_controller.rb, app/controllers/content_types_controller.rb, app/controllers/datastreams_controller.rb, app/models/ability.rb, app/models/nil_model.rb, spec/requests/edit_datastream_spec.rb
Presently a problem getting the object from DSA prevents authorizing the object, even though we don't actually need the object if the user is an administrator.  This gives administrators to edit these broken objects.
fixes #2356
=> Allow administrators to edit objects even if they can't be loaded 

app/controllers/datastreams_controller.rb, spec/requests/update_datastream_spec.rb
This allows the legacy API to validate the correctness before saving and it makes Argo consistent with how common-accessioning updates metadata.
=> Direct datastream updates through the legacy API where possible

app/jobs/modsulator_job.rb, app/services/apply_mods_metadata.rb, spec/services/apply_mods_metadata_spec.rb
Currently we receive a deprecation warning in this method because we're doing authorization with ActiveFedora::Base object.  This prevents the deprecation.  This also uses the legacy metadata API to decouple from direct Fedora writes.
=> Authorize with cocina; use legacy API

app/controllers/items_controller.rb, spec/requests/set_rights_spec.rb, spec/requests/show_rights_spec.rb
So that you can purge an invalid object.
=> Allow admins to operate on items when the data is bad

app/forms/access_form.rb, app/views/report/bulk.html.erb, spec/forms/dro_rights_form_spec.rb
Fixes #2390 - bulk update for set rights to citation-only not working correctly.
Testing shows this works on stage, but I'm not sure I fully understand why we have two sets of options and why we still use `DEFAULT_RIGHTS_OPTIONS` for the APO (https://github.com/sul-dlss/argo/blob/main/app/views/apo/_form.html.erb#L84) and Collection (https://github.com/sul-dlss/argo/blob/main/app/views/collections/new.html.erb#L39).
But seeing as `REGISTRATION_RIGHTS_OPTIONS` is used for the items in all other spots in Argo right now (including in item registration), I think this bug fix change makes sense.
Unit tests and manually on stage
=> use correct options when setting rights in bulk page

app/models/track_sheet.rb
So that we don't need to support non-standard fields and it's easier to know which fields we use.
=> Use standard fields when available

app/controllers/datastreams_controller.rb, spec/requests/update_datastream_spec.rb
=> Updating descMetadata should use legacy API

Gemfile, Gemfile.lock
So that we can use some of the latest cocina-models features to decouple from Fedora 3.
=> Update to use latest cocina-models

app/controllers/registrations_controller.rb, spec/controllers/registrations_controller_spec.rb, spec/features/item_registration_spec.rb
Blocked by https://github.com/sul-dlss/cocina-models/pull/213
=> Get registration workflow from cocina

app/controllers/apo_controller.rb, app/models/ability.rb, spec/controllers/apo_controller_spec.rb, spec/models/ability_spec.rb
=> Decouple authorization of APO creation from ActiveFedora

app/jobs/set_governing_apo_job.rb, spec/jobs/set_governing_apo_job_spec.rb, spec/requests/manage_release_spec.rb
=> Decouple SetGoverningApoJob from Fedora 3

app/controllers/catalog_controller.rb, app/models/solr_document.rb
This lets us have a catalog of all the solr fields we use
=> Define the content-type field in SolrDocument

app/models/concerns/permitted_queries.rb, app/models/user.rb, spec/models/user_spec.rb
These fields do not exist in the solr index:
https://sul-solr-prod-a.stanford.edu/solr/argo3_prod/select?q=apo_role_group_manager_ssim%3A*
https://sul-solr-prod-a.stanford.edu/solr/argo3_prod/select?q=apo_role_person_manager_ssim%3A*
=> Remove unused solr filter query

README.md
This change was made to decouple from ActiveFedora.
=> Remove directions in the readme that pertain to ActiveFedora

Gemfile.lock
You can't spin up the docker web container unless the Gemfile.lock uses the latest version of bundler that the container is using.  You may need to update your laptop bundler gem to match.
i.e. if you run `bundle version` you should see `Bundler version 2.2.14`.  if not:
```
gem install --default bundler -v '2.2.14'
```
My laptop
=> bundle with latest version of bundler to match docker

app/helpers/blacklight_config_helper.rb
No documents index this field: https://sul-solr-prod-a.stanford.edu/solr/argo3_prod/select?fl=scale_ssim&q=creator_tesim%3A*
=> Remove unused solr field from qf

app/controllers/bulk_jobs_controller.rb, app/views/bulk_jobs/index.html.erb, spec/features/bulk_jobs_spec.rb
This reverts commit e086dc6f34d40ef6f42741f144e4481a6ad9d49f.
Ryan Lieu reports:
> objects now visible, but when I click on "MODS bulk loads" from an APO, I'm getting the "forbidden" page now
=> Revert "Decouple BulkJobsController from Fedora 3"

app/controllers/bulk_jobs_controller.rb, app/controllers/catalog_controller.rb, app/models/ability.rb, app/models/user.rb, app/views/bulk_jobs/index.html.erb, spec/controllers/catalog_controller_spec.rb, spec/features/bulk_jobs_spec.rb, spec/models/ability_spec.rb
Earlier we had to revert this in two places because we hadn't appropriately issued these abilities to users who were members of workgroups that had the manage role on the APO.
=> Grant view metadata ability to cocina objects

app/jobs/release_object_job.rb, app/jobs/republish_job.rb, app/presenters/buttons_presenter.rb, app/services/workflow_service.rb, config/routes.rb, spec/jobs/release_object_job_spec.rb, spec/jobs/republish_job_spec.rb
Fixes #2384 
- before allowing a bulk action that republishes or releases object (which also would result in a publish), confirm that the object has actually been published before and abort if not
- rename the publish check route used by the "Republish" blue button to match what it does
- updated tests
=> guard against republushing objects that have not been published

app/jobs/checksum_report_job.rb, app/jobs/descmetadata_download_job.rb, app/models/ability.rb, spec/jobs/descmetadata_download_job_spec.rb, spec/models/ability_spec.rb
=> Decouple view_metadata and view_content abilities from Fedora

app/controllers/items_controller.rb, app/models/ability.rb, spec/controllers/items_controller_spec.rb, spec/models/ability_spec.rb
=> Decouple manage-desc-metadata from Fedora 3

app/controllers/catalog_controller.rb
We now prevent invalid rights from being entered via the legacy api. This enables dor-indexing-app to decouple from ActiveFedora.
Fixes #2448
=> Remove rights errors facet

app/models/ability.rb
=> Stop authorizing manage_governing_apo on a Fedora 3 object

app/components/contents/resource_component.html.erb, app/components/contents/resource_component.rb
Integration tests fail, and the resource types are no longer correct after cocina-models 0.55.0>
Before
After
=> Update the display of resource types for cocina-models 0.55.0

app/forms/registration_form.rb, app/helpers/registration_helper.rb, lib/constants.rb
(part of) fixing #2427 -- adjusts available content types in argo registration, item detail page (blue button) and bulk updates to match the current correct list
Localhost browser and existing unit tests
=> adjust content types shown in registration form to match latest allowed values

app/controllers/registrations_controller.rb, spec/controllers/registrations_controller_spec.rb
We haven't seen such a case in Argo production in over a year and it appears to be bad data that was resolved:
https://app.honeybadger.io/projects/49894/faults/54082399
=> Remove unnecessary check from Argo

app/forms/apo_form.rb, app/helpers/apo_helper.rb, app/views/apo/_form.html.erb, spec/features/apo_spec.rb, spec/forms/apo_form_spec.rb
This removes properties that are unneeded. Ref https://github.com/sul-dlss/cocina-models/issues/230
=> Remove unused APO properties metadata_source and desc_metadata_format

app/controllers/apo_controller.rb, app/forms/apo_form.rb, app/views/apo/_form.html.erb, spec/features/apo_spec.rb, spec/forms/apo_form_spec.rb
Look in solr for these labels. It's faster.
Ref #2418
=> Decouple default_collection_objects on ApoForm from Fedora

app/controllers/content_types_controller.rb, app/views/content_types/_content_type.html.erb, app/views/report/bulk.html.erb, lib/constants.rb, spec/controllers/content_types_controller_spec.rb, spec/support/cocina_matchers.rb, spec/views/content_types/_content_type.html.erb_spec.rb
Fixes #2431
See subject.
As part of this work, increase the test coverage of the content types controller by testing previously untested branches, and add a new matcher that lets us sniff cocina objects and ensure they have expected content and resource types.
CI
None
=> Decouple content types controller from Fedora

app/controllers/items_controller.rb, app/jobs/purge_job.rb, app/services/purge_service.rb, app/services/workflow_service.rb, spec/controllers/items_controller_spec.rb, spec/jobs/purge_job_spec.rb, spec/services/purge_service_spec.rb
and removes duplicate code
Duplicate code is bad.
=> Decouples the ItemsController#purge method from Fedora 3

Gemfile, Gemfile.lock, app/controllers/items_controller.rb, spec/requests/apply_apo_defaults_spec.rb
This decouples from Fedora 3
Ref #2497
=> use the API to apply admin policy defaults

app/javascript/argo.js, app/javascript/controllers/json_renderer.js, app/views/catalog/_cocina_default.html.erb, package.json, yarn.lock
Fixes #2381
New feature request to help users make sense of the often verbose Cocina structure.
Use the `renderjson` library for this.
CI? Not sure whether this is worth a feature spec or not, tbh.
None.
=> Render Cocina model as collapsible JSON

.rubocop_todo.yml, Gemfile.lock, app/components/datastream_row.html.erb, app/components/datastream_row.rb, app/controllers/catalog_controller.rb, spec/controllers/catalog_controller_spec.rb, spec/features/add_workflow_to_item_spec.rb, spec/features/apo_spec.rb, spec/features/consistent_titles_spec.rb, spec/features/enable_buttons_spec.rb, spec/features/item_catkey_change_spec.rb, spec/features/item_source_id_change_spec.rb, spec/features/item_view_metadata_spec.rb, spec/features/release_history_spec.rb, spec/requests/set_rights_spec.rb
Decouples CatalogController from Fedora
Before:
After:
=> Load the datastream inventory using the API

.circleci/config.yml, docker-compose.yml
This is required when the dor-services-app container runs in production mode. Ref https://github.com/sul-dlss/dor-services-app/pull/2554
=> Provide a secret key to the dor-services-app container

app/javascript/controllers/json_renderer.js, app/views/catalog/_cocina_default.html.erb
Fixes #2531
To prevent Cocina with quotation marks and such from borking the collapsible/expandable Cocina display. The prior implementation had the complication that the JSON was stuffed in a data tag, an HTML attribute, where quotation marks caused the HTML to prematurely terminate the attribute. Instead, stuff the JSON in its own `<script>` tag to avoid that complication.
CI and stage
None
=> Emit valid Cocina JSON for rendering

app/controllers/datastreams_controller.rb, app/views/datastreams/edit.html.erb, app/views/datastreams/show.html.erb, spec/features/item_view_metadata_spec.rb, spec/requests/edit_datastream_spec.rb, spec/requests/update_datastream_spec.rb, spec/views/datastreams/show.html.erb_spec.rb
closes #2437
Less Fedora, more DOR services app.
Unit, QA
NA
=> Decouples datastream controller from Fedora.

app/controllers/registrations_controller.rb, spec/controllers/registrations_controller_spec.rb
This occurs when an APO has no collections for registration.
Fixes #2564
Fixes #2565
=> Prevent error retrieving list of collections for registration

app/helpers/blacklight_config_helper.rb
Nothing sets this: https://sul-solr-prod-a.stanford.edu/solr/argo3_prod/select?fl=id+title_tesim&q=title_tesim%3A*
=> Remove obsolete field title_tesim

app/helpers/blacklight_config_helper.rb
Scale is not a useful field to search with, it's for display
=> Remove scale from qf

spec/controllers/content_types_controller_spec.rb, spec/controllers/dor/objects_controller_spec.rb, spec/controllers/items_controller_spec.rb, spec/controllers/versions_controller_spec.rb, spec/features/item_manage_release_spec.rb, spec/features/item_view_metadata_spec.rb, spec/models/ability_spec.rb, spec/models/workflow_status_spec.rb, spec/presenters/buttons_presenter_spec.rb, spec/requests/manage_release_spec.rb, spec/requests/set_catkey_spec.rb, spec/requests/set_collection_spec.rb, spec/requests/set_governing_apo_spec.rb, spec/requests/set_source_id_spec.rb, spec/services/state_service_spec.rb, spec/views/catalog/_contents_default.html.erb_spec.rb
=> Get rid of unused ActiveFedora mocks

app/controllers/dor/objects_controller.rb, app/helpers/application_helper.rb, app/javascript/registration/grid.js, app/views/registrations/show.html.erb
It was creating links to Fedora, now create links to the show page instead
Fixes #2586
=> Decouple the registration front end from Fedora

spec/models/ability_spec.rb, spec/requests/set_governing_apo_spec.rb
These prevent removing dor-services
=> Remove unnecessary mocks

app/controllers/catalog_controller.rb, spec/features/search_results_spec.rb
This was added in https://github.com/sul-dlss/argo/commit/893a1eb1cabe58623e2320b76af68adfa6fd3a46 but we never actually indexed into that field
=> Removed a sort field that doesn't exist

spec/forms/apo_form_spec.rb
So we can remove the dor-services dependency
=> Decouple spec from using Dor::Agreement

spec/services/apply_mods_metadata_spec.rb
Helps decouple from dor-services
=> Decouple spec from Dor::DescMetadataDS
